### ISSUE TITLE
Check local playlist code for OSError and IOError handling

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1001]
As part of #1000 we noticed that we don't have proper try/except blocks around writing and deleting playlists. This should be fixed.

**Comment by tkem** [comment]
Wearing my "client-developer hat" <:-) I'd prefer if these errors were reported to the client. I hate to see `delete(playlist)` report no errors, but the playlist "magically" reappear after a `refresh`. That's exactly what happens with v0.19.5 and originally led to #937.

As for the `strerror` issue, it might make sense to wrap `OSError` etc. with a custom exception with proper encoding, but IMHO this belongs higher up in the call chain, for example in `PlaylistsController`. Any idea how Python 3 handles this, with its stricter Unicode vs. byte string rules?

**Comment by adamcik** [comment]
#667 is also relevant for handling things further up.

**Comment by adamcik** [comment]
Didn't we just refactor and cleanup a bunch of that code? Is this still relevant?

**Comment by jodal** [comment]
Yeah, probably fixed by mine and @tkem's changes in the area over the last year.

Leaving it to @tkem to close this.

**Comment by tkem** [comment]
Will take a look if that's still relevant.

**Comment by tkem** [comment]
Though I'd still rather see exceptions being passed to the client properly, AFAICS all `EnvironmentError`s are at least caught and logged properly. Anything beyond that is properly outside the scope of this issue, so closing this.
