### ISSUE TITLE
Looking up tracks with find_exact is very slow

### ISSUE THREAD

**Issue by dirkgroenen** [mopidy/mopidy#1008]
For my Mopify web client I have to retrieve track object for a list of URI's. To accomplish this I use the ```find_exact``` method with a list of uris. However, a request containing 150 uris takes about 11 seconds before it returns a result. 

Is there an other way to load those 'non-mopidy' tracks into the tracklist faster? More details about this issue can be found in [#62](https://github.com/dirkgroenen/mopidy-mopify/issues/62).

**Comment by jodal** [comment]
In our draft for the Core API v1.0, we've changed `library.lookup()` to take a list of URIs. With time, that should solve your use case.

**Comment by kingosticks** [comment]
Would it make sense (if not already planned) for the tracklist's add method
to also take a list of uris?

**Comment by dirkgroenen** [comment]
Any indication on when V1.0 is going to be released?

**Comment by jodal** [comment]
No, we don't have that. We've started to include some of the backwards compatible parts of the Core API v1.0 in the upcoming v0.20, but changing the signature of `lookup()` is quite backwards incompatible, so that will probably be left for v1.0 proper.

**Comment by jodal** [comment]
Yes, I think it makes very much sense to extend `tracklist.add()` with an `uris` keyword argument, and remove the current `uri` argument in v1.0.

**Comment by jodal** [comment]
That said, a revamp of the tracklist as a whole is deferred to v2.0, mostly to draw a line and scope down the amount of changes in v1.0 and work required to get it out.

**Comment by adamcik** [comment]
Shouldn't we be able to do a ``lookup(uris)`` that does an ``if isinstance(uris, basestring): uris = [uris]`` to get this moving earlier?

**Comment by jodal** [comment]
Assuming nobody uses `lookup()` with `uri` as a keyword argument, we should be able to change it to `uris` and add a string check for backwards compat.

**Comment by adamcik** [comment]
Or just ``lookup(uri=None, uris=None)`` and ``tracklist.add(uri=None, uris=None)`` and mark the ``uri`` case as deprecated and to be removed in 1.0 I guess.

**Comment by dirkgroenen** [comment]
Must say that adding a ```uris``` parameter to the ```lookup``` method would save a big part of the problems I'm currently en counting when adding 'external' tracks. :+1:

**Comment by tkem** [comment]
> Assuming nobody uses lookup() with uri as a keyword argument...

Since `Mopidy.js` introduced "by-position-or-by-name" calling convention, I know of at least one client that calls `lookup()` with `uri` as a keyword argument.

**Comment by dirkgroenen** [comment]
Mopify also uses ```lookup()``` with ```uri``` as keyword when opening playlists.
