### ISSUE TITLE
Use grilo for additional sources

### ISSUE THREAD

**Issue by hadess** [mopidy/mopidy#1021]
Grilo: https://wiki.gnome.org/Projects/Grilo

For use in mopidy, grilo would allow:
- YouTube and Vimeo support (for music videos)
- ability to write small Lua scripts for additional sources (such as websites)

It's accessible from Python using gobject-introspection.

**Comment by hadess** [comment]
I forgot that it also does UPnP, DAAP, Magnatune, Jamendo, Shoutcast, etc.

**Comment by adamcik** [comment]
Sounds like an interesting candidate for a future extension. Though as of yet we can't use gobject-introspection as we are still using the gstreamer 0.10 bindings which aren't compatible with pygi (#225).

**Comment by adamcik** [comment]
A quick look at https://developer.gnome.org/grilo/unstable/ch03.html#programming-with-grilo-concepts seems to indicated that we've landed on quite similar concepts so mapping it to mopidy should be fairly simple for however takes the time to implement such an extension.

**Comment by adamcik** [comment]
This would go into a extension outside of mopidy itself. And we typically have a policy of closing bugs for extension ideas like this as they are not something that we will fix in mopidy itself.

That being said, I do hope someone takes the time to create such a plugin as this sounds like it could get us support for a lot of new sources without having to write a Mopidy extension for each of them explicitly.
