### ISSUE TITLE
Develop: Local scan inserts broken image links to Cover Art Archive

### ISSUE THREAD

**Issue by tkem** [mopidy/mopidy#1023]
Since #802, if an album has a valid `musicbrainz_id`, `album.images` is set to the corresponding Cover Art Archive `front` image URL. However, no check is done if such an image actually exists in the archive. So I now end up with lots of local tracks/albums which contain broken image links.

Since the `album.images` property is going to be deprecated and replaced with `library.get_images` anyway, maybe this should be reverted?

**Comment by adamcik** [comment]
Yeah, this should probably be removed. Or changed to check if the images exist using an API request against the coverart API either at scan or `get_images()` time.

Though just removing would be a perfectly acceptable to me.

**Comment by tkem** [comment]
I'd prefer a run-time check (probably caching the result for a limited time), since the Cover Art Archive is growing and images may become available for an album that were not there at the time of `mopidy local scan`.
But I guess that's clearly beyond the scope of the local `json` library for now.
