### ISSUE TITLE
Break backend playback API to prepare for gapless playback

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#1052]
Known extensions that need fixing:

- [x] [mopdy-youtube](https://github.com/dz0ny/mopidy-youtube/blob/master/mopidy_youtube/backend.py#L184)
- [x] [mopidy-tunein](https://github.com/kingosticks/mopidy-tunein/blob/master/mopidy_tunein/actor.py#L113)
- [x] [mopidy-subsonic](https://github.com/rattboi/mopidy-subsonic/blob/master/mopidy_subsonic/actor.py#L40)
- [x] [mopidy-soundcloud](https://github.com/mopidy/mopidy-soundcloud/blob/master/mopidy_soundcloud/actor.py#L28)
- [x] [mopidy-gmusic](https://github.com/hechtus/mopidy-gmusic/blob/develop/mopidy_gmusic/playback.py#L18)
- [x] [mopidy-beets](https://github.com/mopidy/mopidy-beets/blob/master/mopidy_beets/actor.py#L32)
- [x] [mopidy-spotify](https://github.com/mopidy/mopidy-spotify/blob/develop/mopidy_spotify/playback.py#L48)

**Comment by adamcik** [comment]
The following code will break when the equivalent of https://github.com/adamcik/mopidy/commit/9fc319055c6d9d23f621cb7c100bb03b95923bd9 happens:

https://github.com/dz0ny/mopidy-youtube/blob/master/mopidy_youtube/backend.py#L184
https://github.com/kingosticks/mopidy-tunein/blob/master/mopidy_tunein/actor.py#L113
https://github.com/rattboi/mopidy-subsonic/blob/master/mopidy_subsonic/actor.py#L40
https://github.com/mopidy/mopidy-soundcloud/blob/master/mopidy_soundcloud/actor.py#L28
https://github.com/hechtus/mopidy-gmusic/blob/develop/mopidy_gmusic/playback.py#L18

**Comment by jodal** [comment]
@dz0ny @kingosticks @rattboi @hechtus Pinging you all since this will affect your extensions. The fix will be trivial, but a new release in coordination with Mopidy 1.0 will be needed.

**Comment by adamcik** [comment]
And https://github.com/mopidy/mopidy-beets/blob/master/mopidy_beets/actor.py#L32

**Comment by adamcik** [comment]
The tl;dr for migration is you should only be doing `def change_track(self, track): ...` which only needs to worry about setting the new URI. All the other things like preparing for change and the actual state change should not be handled by backends if we want to get gapless in 1.1 :-)

**Comment by adamcik** [comment]
https://github.com/mopidy/mopidy-spotify/blob/develop/mopidy_spotify/playback.py#L48

**Comment by jodal** [comment]
Breaking change landed in PR #1064.

The following extensions are up to date in their development branches:

- mopidy-spotify (1 and 2)
- mopidy-beets
- mopidy-soundcloud

The following have pending PRs updating the API:

- dz0ny/mopidy-youtube#19

**Comment by jodal** [comment]
Two more PRs to update backend playback API:

- hechtus/mopidy-gmusic#75
- rattboi/mopidy-subsonic#11

Closing this issue, as it should now be all in the hands of extension authors.

**Comment by kingosticks** [comment]
I'm done!
