### ISSUE TITLE
Change core.history.add() signature

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#1056]
Take `uri, name` instead of a track that is simply converted to a track ref.

This makes the API also work for the use case of adding stream titles to the history.

**Comment by adamcik** [comment]
Other thing regarding this, the add API should not be public. History is read only for anything outside of core.

**Comment by jodal** [comment]
As in `_add()` or just internal through documentation?

**Comment by adamcik** [comment]
As in `_add` IMO
