### ISSUE TITLE
Make core.tracklist.{eot,next,previous}_track internal

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#1059]
Prefix with `_get` to remove from other actors and docs.

**Comment by tkem** [comment]
Does this mean clients will no longer have access to `tracklist.next_track()` etc.?
Mopidy-Mobile uses these to enable/disable `prev` and `next` buttons...

**Comment by jodal** [comment]
@adamcik tkem have a point. Why do you feel they should be internal?

**Comment by adamcik** [comment]
Leave them in for this time round, but supplement them with a `has_{next,previous}_track()` which returns a boolean, or perhaps some thing which returns the `Ref` of the next of previous track? Then mark the old methods as deprecated and try and move people away.

This is also potentially part of the tracklist state we want to give bulk access to.

**Comment by tkem** [comment]
Mopidy-Mobile also uses `eot_track` as a fallback for its "Now Playing" view if there's no `current_track`. Reason for this is if there's no current track, i.e. in `stopped` state, I want to see what track gets played if I hit `play`, and not "Nothing playing" and wonder what might happen if I press *that button*.

Retrieving full tracks (or *at least* Refs) with next/previous also makes sense for clients who want to show something like "Next track: Foo by Bar".

**Comment by jodal** [comment]
I've removed "mark as internal, remove from docs" comments in the spec for 2.0 and added a suggestion about including `has_{eot,next,previous}_track` in a `core.tracklist.get_state()` response.

Ready to close this?

**Comment by adamcik** [comment]
Fair enough, we'll hold off ripping these away. Which also means this can just as well be bumped to a 1.x  release.

**Comment by jodal** [comment]
What is there to bump? Is there anything to do here?

**Comment by adamcik** [comment]
That would be the add a non-track based version of this.

**Comment by jodal** [comment]
Can we just leave that for 2.0 when the tracklist changes from tracks to Ref.tracklist items?

**Comment by adamcik** [comment]
Sure.
