### ISSUE TITLE
Nicely handle backends with search() without exact, but no find_exact()

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#1081]
Backends to update:

In mopidy org:
- [x] Mopidy-Local
- [x] Mopidy-Beets
- [x] Mopidy-Dirble
- [x] Mopidy-SoundCloud
- [x] Mopidy-Spotify 1
- [x] Mopidy-Spotify 2

Elsewhere:
- [x] Mopidy-AudioAddict
- [x] Mopidy-Banshee
- [x] Mopidy-Bassdrive
- [x] Mopidy-GMusic
- [x] Mopidy-InternetArchive
- [x] Mopidy-LeftAsRain
- [x] Mopidy-OE1
- [x] Mopidy-Podcast
- [x] Mopidy-radio-de
- [x] Mopidy-Subsonic
- [x] Mopidy-TuneIn
- [x] Mopidy-VKontakte
- [x] Mopidy-YouTube

**Comment by jodal** [comment]
Implemented in #1082.

Keeping open until PRs are made to all affected backends.

**Comment by adamcik** [comment]
Should we consider opening bugs against these projects? On a side note I was almost temped to script a quick bug filing helper that takes a template + a list of projects, but someone must have done this before?

**Comment by jodal** [comment]
nilicule/mopidy-audioaddict#5

**Comment by jodal** [comment]
felixb/mopidy-bassdrive#1

**Comment by jodal** [comment]
tamland/mopidy-banshee#2

**Comment by jodal** [comment]
naglis/mopidy-leftasrain#1

**Comment by jodal** [comment]
tischlda/mopidy-oe1#1

**Comment by jodal** [comment]
hechtus/mopidy-radio-de#13

**Comment by jodal** [comment]
sibuser/mopidy-vkontakte#13

**Comment by jodal** [comment]
That should be all. Closing this.
