### ISSUE TITLE
Update tests to stop using deprecated APIs

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1083]
TODO: add a list with things we should cleanup with respect to this after 1.0

**Comment by adamcik** [comment]
`py.test -d --tx '4*popen//python=python2.7 -W error' --boxed` has been the methodology so far. Splitting the test across jobs for speed. And using `--boxed` as warnings filters are global state that seems to keep leaking between tests.

**Comment by adamcik** [comment]
A gotcha with this has turned out to get not getting the futures while inside the ignore warnings context.

**Comment by adamcik** [comment]
The empty query case as not been handled by this yet. Rest should be done.

**Comment by adamcik** [comment]
Leaving this for now as we still have a lot of places we ignore deprecation. And we've not at all touched checking the deprecated properties usage.

**Comment by jodal** [comment]
Setting milestone to v3.0 as that is the latest we can fix this, since this blocks #1461.

**Comment by jodal** [comment]
What remains to close this issue is just:

- [ ] Update `tests/core/test_playback.py` to not use `core.tracklist.add()`'s `tracks` argument.

**Comment by jodal** [comment]
I've deferred removing the `tracks` arg to `core.tracklist.add()` to Mopidy 4.0, ref. #1855.
