### ISSUE TITLE
UTF-8 character coding bug

### ISSUE THREAD

**Issue by szuniverse** [mopidy/mopidy#1086]
Hi.

If I use the Library controller browse function with a valid URI. The response name is wrong when contains UTF-8 characters. This is the response:
Received text: 

``` json
{
  "jsonrpc": "2.0",
  "id": 20,
  "result": [
    {
      "__model__": "Ref",
      "type": "track",
      "uri": "local:track:gpw/06%20-%20Nem%20t%C3%B6rt%C3%A9nt%20semmi.mp3", 
      "name": "06 - Nem t\ufffd\ufffdrt\ufffd\ufffdnt semmi.mp3"
    }
  ]
}
```

I think the "name" key contains wrong character coding.

**Comment by adamcik** [comment]
Which local backend, json or sqlite or same result with both? Are these local files or Samba, NFS etc?

**Comment by szuniverse** [comment]
These are local files & json

**Comment by adamcik** [comment]
The URI looks good from an encoding point of view:

```
print urllib.unquote('local:track:gpw/06%20-%20Nem%20t%C3%B6rt%C3%A9nt%20semmi.mp3').decode('utf-8')
local:track:gpw/06 - Nem történt semmi.mp3
```

As for the name it turns out `\ufffd` is a `REPLACEMENT CHARACTER` in the unicode world. So this is telling us that instead of failing it replaced the characters it didn't like with this placeholder.

Could you check what `python -c 'import sys; print sys.getfilesystemencoding()'` gives you and also provide a `mopidy deps` to a pastebin?

**Comment by szuniverse** [comment]
python -c 'import sys; print sys.getfilesystemencoding()' : ANSI_X3.4-1968

mopidy deps:
Executable: /usr/local/bin/mopidy
Platform: Linux-3.18.7-v7+-armv7l-with-debian-7.8
Python: CPython 2.7.3 from /usr/lib/python2.7
Mopidy: 1.0.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 15.0 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  tornado>=2.3: 4.1 from /usr/local/lib/python2.7/dist-packages
    certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
    backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
Mopidy-Moped: 0.4.4 from /usr/local/lib/python2.7/dist-packages
  setuptools: 15.0 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19: 1.0.0 from /usr/local/lib/python2.7/dist-packages
    setuptools: 15.0 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.1 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
Mopidy-MusicBox-Webclient: 2.0.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 15.0 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19: 1.0.0 from /usr/local/lib/python2.7/dist-packages
    setuptools: 15.0 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.1 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
Mopidy-Mopify: 1.3.2 from /usr/local/lib/python2.7/dist-packages
  setuptools: 15.0 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19: 1.0.0 from /usr/local/lib/python2.7/dist-packages
    setuptools: 15.0 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.1 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  ConfigObj: 5.0.6 from /usr/local/lib/python2.7/dist-packages
    six: 1.9.0 from /usr/local/lib/python2.7/dist-packages
Mopidy-Youtube: 2.0.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 15.0 from /usr/local/lib/python2.7/dist-packages
  requests>=2.2.1: 2.6.0 from /usr/local/lib/python2.7/dist-packages
  pafy>=0.3.35: 0.3.72 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.0: 1.0.0 from /usr/local/lib/python2.7/dist-packages
    setuptools: 15.0 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.1 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
Mopidy-Spotify: 1.3.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 15.0 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.0: 1.0.0 from /usr/local/lib/python2.7/dist-packages
    setuptools: 15.0 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.1 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  pyspotify<1.999,>=1.9: 1.11 from /usr/lib/pymodules/python2.7
GStreamer: 0.10.36.0 from /usr/lib/python2.7/dist-packages/gst-0.10/gst
  Detailed information: 
    Python wrapper: gst-python 0.10.22.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lame
        mad
        mp3parse
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec

**Comment by jodal** [comment]
IMHO, this is expected behavior and not a bug.

- You're locale is set to something not-UTF-8. That is, something like `C` or `en_US`, not `en_US.UTF-8`.
- The file has a UTF-8 filename.
- Mopidy tries to decode the filename using your locale-defined encoding, got through `sys.getfilesystemencoding()`, which fails to understand the UTF-8 chars, since it expects something else, and replaces the unknown bytes with the Unicode replacement char (`\ufffd`)

The proper solution is probably for you to change your system locale to a locale supporting UTF-8. On for example Debian/Ubuntu systems you can run `sudo dpkg-reconfigure locales` to change this.

**Comment by laclaro** [comment]
Sorry to revive this, but I could not find anything more recent that hits the issue.

jodal, your last comment seems plausible. However, my system locale IS set to de_DE.utf-8 and I am still getting presented the utf8-replacement char. What's wrong?
