### ISSUE TITLE
Q: Why is  mopidy.core.PlaybackController.change_track() method deprecated?

### ISSUE THREAD

**Issue by szuniverse** [mopidy/mopidy#1087]
In the v1.0.0 (2015-03-25) changelog:

> Core playback controller
> Removed: Remove several internal parts that were leaking into the public API and was never intended to be used externally. (Fixes: #1070, PR: #1076)
> mopidy.core.PlaybackController.change_track() is now internal.

My simply question is why?  I am working on a native mobile app and I use it very heavily. Its a very cool feature if the user can modify the tracklist order. So I need this method, Is it possible to put it back external?

thanks in advance.

**Comment by jodal** [comment]
I'll let @adamcik answer that :-)

**Comment by szuniverse** [comment]
Ohh sorry. My bad... Please close this question I red the changelog wrong.. Big sry.. :)

**Comment by jodal** [comment]
No problem :-)
