### ISSUE TITLE
Metadata attributes on local files

### ISSUE THREAD

**Issue by morgoth** [mopidy/mopidy#1093]
Is it possible to somehow read metadata stored in local files and use them to populate fields like Artist, Album, etc?
Currently returned track has only name, url and type.

**Comment by kingosticks** [comment]
That's a track ref. You would normally use the uri to `lookup` the full track object.

**Comment by morgoth** [comment]
This is little inconvenient, as in example Gmusic backend returns all this info on currentTrack request.
Additionally when searching through local backend, there are only tracks returned, as no search is made against Artist and Album.
Also browsing through local backend displays only track names, so again this is different than in example in Gmusic.

**Comment by kingosticks** [comment]
What exactly are you trying to do here? Are you talking about issues with the json local library? If so, take a look at the sql based one instead.

**Comment by morgoth** [comment]
I would like to have unified UI for gmusic, local and other backends and be able to search by artist, album and track in the same way.
I'll take a look at sqlite extension.

**Comment by jodal** [comment]
We recently changed the contribution guidelines to make it clear that GitHub Issues is for bugs and well-defined feature requests only, ref. https://docs.mopidy.com/en/latest/contributing/#issue-guidelines

I don't want to kill your discussion. I just want to make the issue tracker a useful development tool by removing as many non-actionable issues as possible.

Can you please continue the discussion at https://discuss.mopidy.com? Feel free to post another comment here with the link to your continued discussion.

**Comment by morgoth** [comment]
I created one at https://discuss.mopidy.com/t/no-metadata-in-tracks-from-local-backend/654
