### ISSUE TITLE
Q: What am I doing wrong? The new Backend-M3U doesn't work for me.

### ISSUE THREAD

**Issue by szuniverse** [mopidy/mopidy#1098]
Hi.

I created an m3u file which contains only this one line:

```
/home/pi/01_track.mp3
```

When I started mopidy I get this message(s):
```
Loaded 1 M3U playlists from /home/pi/.local/share/mopidy/m3u
```

So mopidy recognize my m3u playlist but when I would like to play this track I post this json:

```json
{"method":"core.tracklist.add","jsonrpc":"2.0","id":111,"params":{"uri":"file:///home/pi/01_track.mp3"}}
```

I get the track uri from playlist object, and the response is:

``` json
{"id":111,"jsonrpc":"2.0","result":[]}
```

What am I doing wrong? Should I do something more to use the m3u playlist? Any guess?

Another way how I tested my m3u playlist:
I tested with a webclient, I able to add the track to the tracklist via this webclient but when I would like to play this song the server log said:

```
WARNING  Track is not playable: file:///home/pi/01_track.mp3
```

*Edited:* Formatting. -jodal

**Comment by jodal** [comment]
Please post questions to the forum, and keep the issues for bugs/feature requests only. This is a rather [new policy](https://docs.mopidy.com/en/latest/contributing/), so we're not very good at enforcing it yet and you shouldn't feel bad to have missed it.

I moved your question to https://discuss.mopidy.com/t/what-am-i-doing-wrong-the-new-backend-m3u-doesnt-work-for-me/652.

**Comment by szuniverse** [comment]
okey, sorry. I will keep in mind in the future.
