### ISSUE TITLE
Centos 7.0 : impossible ton install correctly from sources

### ISSUE THREAD

**Issue by TheTrueElektro** [mopidy/mopidy#1102]
Hello,

I try to install Modipy on a Centos 7.O for a day but impossible..

I've tried to install from the sources, and my install is in "usr/lib64/python2.7/site-package/modipy , files are there but the commmand "modipy" in terminal return : -bash: modipy: command not found

Config files are good edited i think.. and it's impossible to acess from a web platform because it can't start. In the installation guide it says to install Gstreamer, but no one of the packages are existing ( for: emerge -av gst-python gst-plugins-bad:0.10 gst-plugins-good:0.10 \
    gst-plugins-ugly:0.10 gst-plugins-meta:0.10 )

So I installed it my way : "sudo yum install gstreamer-plugins-bad gstreamer-plugins-ugly gstreamer-ffmpeg"

modipy continue to block me :( 
I don't know what to do now :c 
thanks for any help ++

**Comment by kingosticks** [comment]
It's 'mopidy'.

**Comment by adamcik** [comment]
Please post questions to the forum, and keep the issues for bugs/feature requests only. This is a rather new policy, so we're not very good at enforcing it yet and you shouldn't feel bad to have missed it.
