### ISSUE TITLE
audio/output alsasink device stopped working

### ISSUE THREAD

**Issue by mrvanes** [mopidy/mopidy#1103]
I just upgraded mopidy to 1.0.0 using Ubuntu packages and my softvol audio configuration stopped working:

[audio]
mixer = alsamixer
output = alsasink device=dmixer_mpd

[alsamixer]
control = mpd

dmixer_mpd is an alsa softvol device, with separate volume control.
This used to work like a charm before 1.0.0.

If I remove the "output = alsasink" line I have sound again, but can't change volume using the mpd control.

gst-launch audiotestsrc ! audioconvert ! audioresample ! alsasink device=dmixer_mpd still works like a charm.

Ok, after some testing I changed the output line to
output = audioresample ! alsasink device=dmixer_mpd

And this solves the problem.

**Comment by adamcik** [comment]
This is a bit strange. By default I think GStreamer should already be putting audioresample elements before the sinks we attach. However, it could be that it is getting confused as we have started doing some internal prep work for multiple outputs.

So my hunch would be that the re-sampling gets done before the tee-ing and then our alternate branch confuses the re-sample so it doesn't do it right for your sink. If this is the case each branch will need it's own `audioconvert ! audioresample` pair just to be on the safe side.

**Comment by adamcik** [comment]
Since I'm in a bug cleaning mood I'm going to go ahead an close this. If it is still an issue when testing against develop please let us know.
