### ISSUE TITLE
Playing music on wifi speaker

### ISSUE THREAD

**Issue by afritzler** [mopidy/mopidy#1106]
Is there a way to play music via mopidy on a wifi speaker? I'm running mopidy on a raspberry pi and would like to play the audio on my wireless phillips speaker. Help if very much appreciated.

**Comment by kingosticks** [comment]
Please post questions to the forum, and keep the issues for bugs/feature requests only. This is a rather [new policy](https://docs.mopidy.com/en/latest/contributing/), so we're not very good at enforcing it yet and you shouldn't feel bad to have missed it.

If you do post on the forum (discuss.mopidy.com) then you'll need to include more information on your speaker as this is currently too vague. There may even already be useful information on the forum so take a look.
