### ISSUE TITLE
Get verbose parameter from extension

### ISSUE THREAD

**Issue by dirkgroenen** [mopidy/mopidy#1109]
I would like to return the non-minified version when a user started Mopidy with the verbose parameter. Is it possible to read Mopidy's parameters in the extension class?

**Comment by adamcik** [comment]
Do you mean serving the non-minified mopidy.js given some setting and/or configured verbosity?

**Comment by dirkgroenen** [comment]
Nope, I'm planning to serve a non-minified version of mopidy-mopify (forgot to mention) when an user starts mopidy in verbose mode. 

But I just googled a bit better and it turned out that I can easily grab the parameters using ```optparse```. This should do the trick for as far as I can see.

**Comment by adamcik** [comment]
Going to go ahead and close this, if other extension have a use case for access to the flags please reopen so we can reconsider if we need to expose this.
