### ISSUE TITLE
Use faster json if available?

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1112]
https://medium.com/@jyotiska/json-vs-simplejson-vs-ujson-a115a63a9e26 reminded me that this might be worth trying.

**Comment by jodal** [comment]
I use ujson on embedded devices at work. I don't think it's worth it unless you really need the performance gain. Error handling/reporting with ujson is worse.

**Comment by adamcik** [comment]
Ok, in that case well just drop it unless we find any good reasons to do this for Raspis or something.

**Comment by kingosticks** [comment]
Oh of the comments on hacker news reported ujson as having significantly
higher memory usage. So it might not be that great for the (original)
raspi.

**Comment by adamcik** [comment]
I saw that as well, and given the original that is a much bigger concern than speed of course.
