### ISSUE TITLE
Playlist and browse result with same URI breaks MPD frontend

### ISSUE THREAD

**Issue by trygveaa** [mopidy/mopidy#1120]
If you have a playlist with a URI, and one of the results returned from library.browse has the same URI, listing of playlists in the MPD frontend may return a playlist with / in it, which breaks MPD clients.

In Spotify, I have the playlist spotify:user:spotify:playlist:4hOKQuZbraPDIfaGbM3lKI (Top 100 tracks currently on Spotify). When I list the playlists or browse "/" in the MPD frontend, that URI and name is inserted into the uri_map.

This playlist is also returned by the mopidy-spotify-tunigo extension under "/Spotify Browse/Top Lists/Top 100 tracks currently on Spotify". When browsing "/Spotify Browse/Top Lists", the URI is inserted into the uri_map with that path, overwriting the previous entry for the URI.

If I then list the playlists or browse / again, the URI won't be inserted into the uri_map again, since it already exists there. Instead the name will be looked up with the uri_map, however this will return the path from browsing "/Spotify Browse/..." instead of the playlist name.

**Comment by jodal** [comment]
Thanks for good bug report :-)

**Comment by jodal** [comment]
Fixed by PR #1142
