### ISSUE TITLE
Adding a new Android Application to the documentation

### ISSUE THREAD

**Issue by piroxxi** [mopidy/mopidy#1129]
Hi there,

I recently published a new android application in the google play store (https://play.google.com/store/apps/details?id=fr.piroxxi.mopidy.wombatclient). I created this application to simply run my Spotify playlists, as I couldn't find an Android application that was doing that nicely. It's pretty simple to use but does the job pretty well. Is there any chances you could add it to your list of application on this page of your documentation ?
-> https://docs.mopidy.com/en/latest/clients/mpd/#android-clients

Do you have a policy on what you put on this page and what you don't ? Will you have to test it first ?

I have only tested it with a Mopidy server plugged to Spotify running on a Raspberry PI (for the server part), and on a couple of devices (for the application part), but hopefully it should work on more configurations (devices and servers, as it's mpd compliant). I will start to work on more functionalities, including the ability to search a song on spotify and so on...

Thanks for the time you will spend answering this message :)

Raphaël POITTEVIN

PS : if you're interested in the code of the application, it's in a GitHub repository here : https://github.com/piroxxi/MopidyWombatClient

**Comment by adamcik** [comment]
https://docs.mopidy.com/en/latest/extensiondev/#anatomy-of-an-extension has a paragraph about this which mainly applies for Mopidy extensions. But for this case adding it to https://docs.mopidy.com/en/latest/ext/web/#other-web-clients or a similar "Other mobile clients" would make sense. Feel free to send a PR for the documentation changes to include something like this.

An other quick tip is that https://groups.google.com/forum/?fromgroups=#!forum/mopidy is our Announce lists, where we let through emails about new clients extensions etc.

**Comment by adamcik** [comment]
Closing this bug, but feel free to send quick PR adding a mention :-)

**Comment by piroxxi** [comment]
Hi Thomas,

Thank you for your reply ! :)

Cheers,
Raphaël
