### ISSUE TITLE
Use tlid in favour of tltracks in core APIs

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1131]
We should add a `tlid` argument to `playback.play`, `tracklist.index`, `tracklist.eot_track` `tracklist.next_track`, `tracklist.prev_track` to reduce the data passed around. As part of this I would also go straight to marking the `tl_track` variants as deprecated.

Thanks to @kingosticks for bringing this up :-)

**Comment by adamcik** [comment]
And yes this is just a stopgap for further core API improvements in this area.

**Comment by adamcik** [comment]
I'm also wondering if there was ever any real need for `eot_track`, `next_track` and `previous_track` to have public arguments. I think they could be / should have been argument less and we should have had an internal `_eot_track` version that gets called by the public API with a `get_current_tl_track()`

Other thing to consider is if calling with `tlid` should give a `tlid` as the return value?

**Comment by adamcik** [comment]
Oh, and add a `get_current_tlid`?

**Comment by adamcik** [comment]
#310 also comes to mind in the sense that we could have single call that gets all of the state https://github.com/tkem/mopidy-mobile/blob/46bca6d2/www/js/playback.js#L76-80 fetches.

Other thing I realized is that adding more args to the existing `*_track(tl_track)` calls is a bad idea. We want new `*_tlid()` calls so that we can have a more sane return type, and implicitly use the current tl_track instead of having to provide one.

@tkem you might have some input on this based on what you want/need this for in mopidy-mobile?

**Comment by tkem** [comment]
@adamcik: Still need to figure this out for myself (MoMo is work in progress), but using `tlid` instead of full-blown tracks sounds good to me for a start.

**Comment by adamcik** [comment]
Thing we have the existing APIs converted now, so closing this and we can reconsider on an ongoing basis if we "need" any of the other helpers going forward.
