### ISSUE TITLE
Possible 1.x core improvements

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1137]
Notes and ideas from working on #1136 - 1 and 3 I'm fairly sure we want to fix, rest are nice to haves that we can probably ignore.

1. Support `playback.play(tlid=...)` - should simplify some MPD code paths if we can let the caller know if the the `tlid` exists via a return value.
2. `playback.get_current_tlid()` mostly for completeness, as I think I found that MPD `seekid` was the only place we "need" it.
3. `tracklist.move()` that supports `start=None` or `end=None` for open slices - would remove a bunch of MPD code, would also check if this applies to any of the other similar methods.
4. `tracklist.get_tlid(index)` this would allow us to not do `slice(pos, pos + 1)` in `play(index)` for the MPD code, alternative would be `play(index)` but I'm not sold on that.
5. `tracklist.get_tl_track(tlid)` not 100% sure about this, but I seemed to run into places where I needed this, but if "everything" takes `tlid` this is a non-issue.

**Comment by tkem** [comment]
+1 for `get_current_tlid()`, since that's quite useful for clients that want to highlight the current track in a tracklist view, but don't want to re-fetch full track information. BTW, I always wondered why `get_current_track` is in `playback`, while `next`, `previous` and `eot` are in `tracklist`. Seems a little asymmetric to me, but I guess you can argue both ways.

**Comment by adamcik** [comment]
Reasoning was mostly with who "owns" knowledge about what and minimizing crossing between parts. Which makes testing much nicer. And was perfectly fine back when only had MPD as the frontend. But a lot of my changes recently have gone a bit across these borders for the sake of convenience and giving people a more sane API.

Note that you can also just do `index()` without a track or tlid to get the currently playing track. But a `get_current_tlid()` would be more robust against any changes in the tracklist.

**Comment by tkem** [comment]
Hey, didn't know about `index` acting this way without parameters; AFAICS this isn't documented anywhere, so I'm wondering if this is "officially" supported. However, this isn't really an issue, but a method that only returns the `tlid` for the current track would really be helpful.

**Comment by adamcik** [comment]
This will be new in 1.1, and you are correct, it didn't work that way before.

**Comment by tkem** [comment]
Ah, now I see it in the `develop` docs. Nice!

**Comment by adamcik** [comment]
I think most the important ones are in. Going ahead and closing this and we can always revisit as we evolve the API.
