### ISSUE TITLE
Mopidy occasionally failing to move to next track (Spotify)

### ISSUE THREAD

**Issue by mattb18** [mopidy/mopidy#1141]
When starting a Spotify playlist through Mopidy it will occasionally fail to move onto the next track. The same track will appear to start again and no audio will play. This could happen after 5 hours or maybe 30minutes, there seems to be no pattern. I'm using Mopify to control the playlists. 

Here is the -vvv debugging when the music stops playing. (I'm able to replicate this by skipping tracks until it happens) 

http://pastebin.com/RFuRy0GL

Thank you.

**Comment by adamcik** [comment]
Thanks for the report, haven't had a chance to dig into this but we haven't forgotten about the bug :-)

**Comment by adamcik** [comment]
https://github.com/mopidy/mopidy-spotify/issues/2 comes to mind, but not sure if it is related.

**Comment by mattb18** [comment]
It could be a related issue, however the track doesn't appear to be playing the entire way through. It loops the first 10 seconds or so on the position bar. If I refresh the page nothing is playing (as if I have just started the service). Some additional information: I'm running Raspbian on a Raspberry Pi 2. Thanks!

**Comment by dirkgroenen** [comment]
I can confirm this issue when Consume mode is enabled. Sometimes Mopidy stopts playing, but when you look at the player it did load the next track. It only doesn't start it so you have to hit the play button.

This happens randomly on different devices and I still can't find any pattern in it (besides the enabled  consume mode).

**Comment by mattb18** [comment]
Thanks for the additional info! What is Consume mode and can it be disabled?

**Comment by dirkgroenen** [comment]
Assuming you are using Mopify you can't disable it. At the moment I'm working on a advanced queue manager which will be integrated in the next release of Mopify. The queue manager will make it able to disable consume mode which will hopefully solve the problem for now.

Of course, the best solution would be to get it fixed in mopidy/mopidy-spotify.

**Comment by mattb18** [comment]
OK great, thank you for your help! I look forward to it's release.

**Comment by adamcik** [comment]
Is this still reproducible on Mopidy 2.0?

**Comment by mattb18** [comment]
I Have not seen this issue for a very long time so I'm presuming that it has been resolved.

**Comment by jodal** [comment]
Ok, thanks. Please open a new issue if you experience this with Mopidy 2.0 or newer.
