### ISSUE TITLE
MP3 Sound disturbed after update on 1.0.1

### ISSUE THREAD

**Issue by sterni1971** [mopidy/mopidy#1147]
Hello!

I run a raspberry with hifiberry digi and 
raspbian7, after update from mobidy 1.0.0-3  to 1.0.1 (via apt) the sound
of all mp3 file was disturbed. FLAC was ok. I downgraded to 1.0.0-3 everything was ok again.

The config:

[audio]
mixer = none
mixer_volume = 
#output = autoaudiosink
output = alsasink buffer-time=200000 latency-time=10000
visualizer = 

[softwaremixer]
enabled = true

**Comment by adamcik** [comment]
Could you try increasing the value in https://github.com/mopidy/mopidy/blob/develop/mopidy/audio/actor.py#L172 to say 10, 20, 50, 100 and report back if this helps. I suspect we might have picket a too small value for that buffer.

**Comment by sterni1971** [comment]
Hi!

that solved the problem I started with 100 down to 10 and it worked all the time. In the
1.0.1 release it is btw. Line 167.

Thanks for the great software and your help.

**Comment by adamcik** [comment]
Value was set low to minimize the time it takes from a softvolume change to it applying to the audio being played. The larger this buffer the longer it takes, but make it to small and this happens...

So we need to retune this for a 1.0.2 release.

**Comment by sterni1971** [comment]
I've tested as I said the values from 10 upwards and they seem for mp3 okay, but OGG vorbis
seems to be different. Here I had to increase it from 20 because of distortion. For me with 30
everything is fine. 
FLAC - 5 
MP3 - 10
OGG - 30

**Comment by adamcik** [comment]
https://discuss.mopidy.com/t/mopidy-not-playing-anything-since-last-apt-get-upgrade/704/5

**Comment by simsasaile** [comment]
Hi, 

I had to increase the number in `queue.set_property` to 150. With 100 I had still really bad sound after I updated mopidy yesterday.

**Comment by adamcik** [comment]
https://github.com/mopidy/mopidy/commit/7938ef48eddb55bd0865bd0df48b5b9d99cc338a is in for a 1.0.4 release, essentially setting the value to 1000ms. As it seems no matter what I pick it breaks on some system. So we are reverting to GStreamer defaults to finally get this stable for 1.0.x

**Comment by jodal** [comment]
1.0.4 has been released. The fix is in the develop branch too.
