### ISSUE TITLE
Make frontend/backend actor startup robust

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1148]
https://github.com/mopidy/mopidy-soundcloud/pull/52 reminded me that we still let "bad" extensions crash us at startup. I seem to remember this being deliberate at the time, but I think we should change stance and start catching `Exception` and not re-raise so the rest of Mopidy continues to work.

**Comment by adamcik** [comment]
So some more state on this. Our current policy has been to fail fast, however given the number of extensions and nature of some of their bugs this doesn't feel reasonable anymore. A typical example of this is some extension doing a login in `on_start` and some external service failing, now unless the extension handles it's exceptions correctly we just crashed mopidy irrespective of all the other extension being in working state.

New policy will be that we all interaction with extension startup be handled in the following way

```
try:
    ...
except Exception:
    logger.exception('Extensions %s failed, please file a bug against them '
                     'with this traceback if it continues.', ext_name)`
```

Currently there are quite a few places extensions can fail, even when excluding the extra cases of `local` and `http` which will as need to be brushed up with respect to this change. I recommend we start refactoring the startup to actually be testable as we make these changes.

There is also corner case with actors dying during `on_start` that we need to handle.

An other side effect of this is that validate env might not make sense to keep around any more.

And my final note to self, for the current test branch I have locally I've forgotten to do this for mixers, not sure if we should postpone them as I'm also suggesting to postpone `local` and `http` for now.

**Comment by kingosticks** [comment]
Whatever replaced validate env should also play well with reloading
extension config (following a sighup).

**Comment by jodal** [comment]
FWIW, mixers are ~equal to frontends and backends, so it should be easy to give them the same treatment right away.

**Comment by adamcik** [comment]
@kingosticks good point. For now this is mostly just about increasing the resilience of what we have now. Any changes like possibly removing or replacing validate env, and supporting extensions coming and going, being restarted etc will of course need to wait.

**Comment by adamcik** [comment]
Think this should be mostly solved.
