### ISSUE TITLE
How to upgrade SpotifyBackend

### ISSUE THREAD

**Issue by brunorey** [mopidy/mopidy#1155]
When running mopidy, I get the following errors:

    WARNING [10612:MpdSession-14] mopidy.core.playlists: SpotifyBackend does not implement playlists.as_list(). Please upgrade it.
    WARNING [10612:Core-10] mopidy.core.library: SpotifyBackend does not implement library.search() with "exact" support. Please upgrade it.

Needless to say, Spotify becomes useless and I can only browse local music. How should I proceed in order to upgrade spotifybackend?

Running Ubuntu, using mopidy 1.0.0 installed via apt-get from the repos at http://apt.mopidy.com/. dpkg output is as follows:

    mpd@mpd-server:~$ dpkg -l | egrep 'mopidy|spotify'
    ii  libspotify-dev                                        12.1.51-1                                           i386         Library for using the Spotify music streaming service
    ii  libspotify12                                          12.1.51-1                                           i386         Library for using the Spotify music streaming service
    ii  mopidy                                                1.0.0-3                                             all          music server with support for MPD/HTTP clients
    ii  mopidy-alsamixer                                      1.0.3-1                                             all          Mopidy extension for extension for ALSA volume control
    ii  mopidy-soundcloud                                     2.0.0-1                                             all          Mopidy extension for playing music from SoundCloud
    ii  mopidy-spotify                                        1.3.0-0mopidy2                                      all          Mopidy extension for playing music from Spotify
    ii  mopidy-spotify-tunigo                                 0.2.1-0mopidy1                                      all          Mopidy extension for providing the browse feature of Spotify
    ii  python-spotify                                        1.11-0mopidy1                                       i386         Python bindings for libspotify
    ii  python-tunigo                                         0.1.3-0mopidy1                                      all          Python API for the browse feature of Spotify (Python 2)

**Comment by adamcik** [comment]
You probably have a pip installed version hidding the APT installed one. You can check with `mopidy deps` and then just `sudo pip remove mopidy-spotify` if that is the case.

Also please use http://discuss.mopidy.com for this type of support requests as this isn't a bug in Mopidy :-)
