### ISSUE TITLE
Capability for extentions to modify playback and playlist

### ISSUE THREAD

**Issue by addisonamiri** [mopidy/mopidy#1158]
This would make a lot more sense if you've played the video game Jet Set Radio or Jet Set Radio Future but I was looking to write a extension to sort of automate transitions between songs that go beyond basic crossfading. This would include fading to and from white noise or playing audio clips in between songs. There are two parts of the extension that I couldn't figure out how to implement after reading the API documentation.

The first would to let the extension play tracks between songs preferably without adding them to the current playlist. The extension could use a user defined a playlist of audio clips to splice between every 2 or 3 songs but polluting the current playlist with a bunch of 3 second clips seems less than ideal. The second would be sound effects for song transitions. For this, the extension would take over the output stream and emulate record stops and starts or audio glitches between individual tracks.

There are a couple ways I saw in the code and documentation to implement this but both had their downsides. I could create an output extension but metadata and timestamps would get out of sync quite quickly. I could also hack some of this functionality into playback.py's ```_change_track``` but that only gets me half the way there and it'd be hard to merge functionality that only a very small set of people would use.

If something to achieve either of these is already implemented I'd appreciate some pointers to docs or just code and I'll add the documentation myself. If not I'd appreciate someone familiar with the project helping me put together a todo list of things to implement in the code. That being said, any other help is always appreciated as well.

**Comment by adamcik** [comment]
Transitions is quite an undertaking in itself. At least when trying to do it within the GStreamer playbin and without breaking gapless which we are close to adding support for. Essentially I suspect you would need to either use gnonlin and/or replace the playbin with something more custom. So for me transitions is just way out of scope so far.

Having an alternate track sneak in between might be possible, but it's not something we really have hooks for. And as you say yourself this is probably a bit a a niche use case. Also it would wreak havoc with the "current track" code (which gapless is also messing heavily with as is).

For and idea of where we are headed see the branch I published at:
https://github.com/mopidy/mopidy/compare/develop...adamcik:feature/implement-gapless

Finally, have you considered http://savonet.sourceforge.net/ - I'm not all that familiar with it, but I suspect it might be more suited for solving at least parts of this.

**Comment by addisonamiri** [comment]
That's a bummer to hear. I was hoping it'd be something simpler. I'll take a look at the code after you merge the gapless playback and see what I can do from there. Thanks anyway though.
