### ISSUE TITLE
Does working on a virtual server?

### ISSUE THREAD

**Issue by halid** [mopidy/mopidy#1159]
hi all,

i'm newbie of mopidy. sorry for mostly(maybe) fixed problems. i install to debian virtual server. But show this errors via mopidy.log file.

[24110:MainThread] mopidy.audio.gst: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.

trick: i use the virtual server via KVM and debian 7.x server(not gui or X11)

thx.

**Comment by adamcik** [comment]
Hi,

We recently changed the contribution guidelines to make it clear that GitHub Issues is for bugs and well-defined feature requests only, ref. https://docs.mopidy.com/en/latest/contributing/#issue-guidelines

I would recommend continuing the discussion at https://discuss.mopidy.com Feel free to post another comment here with the link to your continued discussion. Added bonus is that more people than just the Mopidy developers follow along there so you should get better help than we can provide here.

As for the actual question, my guess would be related to audio groups and permission for using the device.

Good luck figuring this out :-)

**Comment by adamcik** [comment]
https://discuss.mopidy.com/t/does-working-on-a-virtual-server/711/1
