### ISSUE TITLE
ncmpcpp segfaults on clearing playlist due to mopidy's playlist status

### ISSUE THREAD

**Issue by dchanters** [mopidy/mopidy#1172]
Hi,

I am able to repeatedly make ncmpcpp segfault when clearing a playlist when mopidy is in use.  If I use ncmpcpp to clear the playlist whilst it's playing a song, or has a song paused then ncmpcpp segfaults.  A discussion about this (via the ncmpcpp author), including steps to reproduce is here:

http://bugs.musicpd.org/view.php?id=4363

Note that I made a mistake---ncmpcpp has to either be playing a song, or paused, to trigger the problem.

The author suggests that the reason is mopidy is sending the wrong information.  A quick chat on IRC with a mopidy dev suggests this is a known issue.

Thanks for all your great work!

**Comment by adamcik** [comment]
Can't seem to reproduce this, but I have an ancient ncmpcpp version. Could you or some else that can reproduce provide the mopidy logs for this (https://docs.mopidy.com/en/latest/troubleshooting/#debug-logging)?

**Comment by jodal** [comment]
The ncmpcpp bug was updated 10 days ago with "should be fixed", but I'm not able to comment on it. Has anything been changed in ncmpcpp? Can this still be reproduced with recent ncmpcpp versions?

**Comment by alp9ne** [comment]
This appears to have been fixed in the latest release of ncmpcpp, which is currently newer than the package in Arch community.

**Comment by jodal** [comment]
Ok, then I assume this is fixed in ncmpcpp until someone says otherwise.
