### ISSUE TITLE
No 'title' tag support for list function of MPD client.

### ISSUE THREAD

**Issue by mark-me** [mopidy/mopidy#1181]
An error occurs when running 

    mpc list title

All other list options seem to be doing just fine.

**Comment by kingosticks** [comment]
Presumably we only support the types listed at https://docs.mopidy.com/en/latest/api/core/#mopidy.core.LibraryController.get_distinct
> artist, albumartist, album, composer, performer, date or genre.

Is this just historical or is there more to it?

**Comment by adamcik** [comment]
This was probably just an oversight either in the switch to `get_distinct` or in the old code. Only thing I'm a bit unsure about is how backends will handle a new distinct type. We should probably document that unknown distinct types should be ignored so we at least have a policy that allows for fixes like this.

**Comment by jodal** [comment]
Fixed with the merge of #1183.
