### ISSUE TITLE
Not working after plugin installation

### ISSUE THREAD

**Issue by ArthurJam** [mopidy/mopidy#1182]
Hello,

After a plugin installation, mopidy is not longer running.
I try to uninstall all (apt source for mopidy and some plugins by pip), and reinstall just the package mopidy, but it's still not working. i have an error at launch.

```
pi@raspberrypi ~ $ which mopidy
/usr/bin/mopidy
```

```
pi@raspberrypi ~ $ mopidy
Traceback (most recent call last):
  File "/usr/bin/mopidy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: certifi
```

Thanks.

**Comment by jodal** [comment]
We recently changed the contribution guidelines to make it clear that GitHub Issues is for bugs and well-defined feature requests only, ref. https://docs.mopidy.com/en/latest/contributing/#issue-guidelines

I don't want to kill your discussion. I just want to make the issue tracker a useful development tool by removing as many non-actionable issues as possible.

Can you please continue the discussion at https://discuss.mopidy.com? Feel free to post another comment here with the link to your continued discussion.

For the forum post, please include the output of `mopidy deps` too.
