### ISSUE TITLE
GStreamer error, jack server is not running or cannot be started

### ISSUE THREAD

**Issue by RanadeepPolavarapu** [mopidy/mopidy#1189]
How do I resolve this error? I can't use any of the web extensions to play music. I believe this is because I am missing some plugin.

	Cannot connect to server socket err = No such file or directory
	Cannot connect to server request channel
	jack server is not running or cannot be started
	ERROR    GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.

**Comment by kingosticks** [comment]
Take a look at step 4 of https://docs.mopidy.com/en/latest/installation/raspberrypi/#appendix-a-fixing-audio-quality-issues

If you are still having an issue then please post any follow up at discuss.mopidy.com as this issue tracker is really just for confirmed bugs and well  defined feature requests.
