### ISSUE TITLE
Playback of local files stops/pauses if mopify/spotify fails to connec

### ISSUE THREAD

**Issue by mangodan2003** [mopidy/mopidy#1194]
Whilst local media was playing it kept getting paused.

Running mopidy from command line with debug revealed this was happening everytime spotify / mopify returned a connection failed error. 

INFO     Starting Mopidy 0.19.5
INFO     Loading config from: builtin defaults, /etc/xdg/mopidy/mopidy.conf, /home/dan/.config/mopidy/mopidy.conf, command line options
INFO     Enabled extensions: mopify, spotify, mpd, http, stream, local-sqlite, softwaremixer, moped, local
INFO     Disabled extensions: none
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Mixing using GStreamer software mixing
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: SpotifyBackend, LocalBackend, StreamBackend
INFO     Mopidy uses SPOTIFY(R) CORE
INFO     Audio output set to "alsasink device=hw:imx6wandboardsg"
INFO     Connected to Spotify
INFO     Loaded 18 local playlists from /mnt/blueberry/music/mpd/playlists
INFO     Loaded 9473 local tracks using sqlite
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     MPD server running at [::ffff:10.11.12.124]:6600
INFO     HTTP server running at [::ffff:10.11.12.124]:6680
ERROR    Spotify connection error: Cannot connect to Spotify
ERROR    Spotify connection error: Cannot connect to Spotify
ERROR    Spotify connection error: Cannot connect to Spotify

**Comment by kingosticks** [comment]
This will be fixed in the upcoming v2.0 release of mopidy-spotify. See https://github.com/mopidy/mopidy-spotify/issues/1

Also, when reporting issues in the future you really should be running the latest released version. v0.19.5 is pretty old now and there have been many fixes (albeit not for this particular issue).
