### ISSUE TITLE
feature request: protect HTTP Frontend by Password and HTTP AUTH

### ISSUE THREAD

**Issue by Mebus** [mopidy/mopidy#1196]
Please add a feature that makes it possible to protect the web fronted by HTTP password authentication!

Mebus

**Comment by dbrgn** [comment]
If you want HTTP password authentication, you could simply run your favorite web frontend behind something like Nginx and enable TLS + basic auth?

**Comment by Mebus** [comment]
I tried this, but the problem was that the webinterface urls still contained the port number which was different from port 80. Solution for this?

**Comment by kingosticks** [comment]
We have a working nginx config in a PR in the pimusicbox repo. Perhaps you
could start from that.

**Comment by dbrgn** [comment]
> I tried this, but the problem was that the webinterface urls still contained the port number which was different from port 80. Solution for this?

Just guessing: Probably some proxy header missing :)

**Comment by adamcik** [comment]
Don't think we are going to add this any time soon, if you need anything more than our basic app server put a proxy / real webserver in front.
