### ISSUE TITLE
feature request: Store volume level

### ISSUE THREAD

**Issue by szuniverse** [mopidy/mopidy#1197]
Hi

I use the latest mopidy server.
My amplifier volume is almost 5/10 so if the mopidy volume is 100% it is very loud. If I set the volume to 50% on mopidy its good but If I shutdown the server and start it the volume is 100% again.
In this case it would be great if the mopidy store the volume level and set it on the next startup.

**Comment by kingosticks** [comment]
Does this not allow you to do this?
https://docs.mopidy.com/en/latest/config/#confval-audio/mixer_volume

**Comment by szuniverse** [comment]
Yes It works fine but I think it would be better if it stores the last used value. 
It would be more comfortable if I choose somehow 
- I want an initial value (this is what you wrote: https://docs.mopidy.com/en/latest/config/#confval-audio/mixer_volume) OR
- I want the last used volume value (feature request)

**Comment by adamcik** [comment]
https://github.com/mopidy/mopidy/issues/310 would be for the last stored value, moving this over there.

**Comment by dublok** [comment]
@szuniverse Do you use the alsamixer? If you to let mixer_volume empty, the volume is stored/restored by alsa.

Working for me (raspberry + hifiberry amp+) mopidy.conf:
```
[audio]
mixer = alsamixer
mixer_volume = 
output = alsasink
```
