### ISSUE TITLE
Feature request: Set mopidy settings via HTTP JSON-RPC API

### ISSUE THREAD

**Issue by szuniverse** [mopidy/mopidy#1203]
Hi

Do you plan in the future to set the mopidy server settings via HTTP JSON-RPC API like mopidy core functions websocket? 
https://docs.mopidy.com/en/latest/api/http/

for example: 
It would be nice to set the mopidy-spotify username/password via HTTP JSON-RPC API, and some setting options.

**Comment by jodal** [comment]
I know this has been discussed previously and not ruled out... Seems like it is covered by #367 and/or #502.
