### ISSUE TITLE
Local files and spotify tracks in one playlist?

### ISSUE THREAD

**Issue by d00d13** [mopidy/mopidy#1210]
As I understand there  is no any web client that can mix local tracks and spotify tracks in one playlist. Tried mopidy, moped and musicbox

That is the only thing that is missing in this awesome product. 
Please consider to add this.
Thanks

**Comment by adamcik** [comment]
The M3U playlist backend can already support URIs from any backend. So don't think there is much more we can do to fix this in mopidy itself. The fact that most of the mopidy web clients don't support editing playlists is a different problem outside the scope of mopidy itself (other than the longer term goal of making the APIs easier to use).

Have you tried mopidy-mobile, this is currently the only web interface I know that supports playlists. And though it's focused on mobile I find it works quite well on desktops.

The other part of this is the MPD interface missing it, where we have an open PR which hopefully adds this long requested feature.
