### ISSUE TITLE
MPD: Stream Name/Title are reversed compared to mpd 0.19

### ISSUE THREAD

**Issue by fatg3erman** [mopidy/mopidy#1212]
Compare these two outputs:

Mopidy:

    currentsong
    file: http://xstream1.somafm.com:3000
    Time: 0
    Artist: 
    Title: Groove Salad [SomaFM]
    Album: 
    Name: Org Lounge - Oslo
    Track: 0
    Pos: 0
    Id: 11
    Genre: Techno Ambient
    OK

MPD:

    OK MPD 0.19.0
    currentsong
    file: http://xstream1.somafm.com:3000
    Title: Org Lounge - Oslo
    Name: Groove Salad [SomaFM]
    Pos: 0
    Id: 2
    OK

I know the empty fields have their own issue raised, but this is about the 'Title' and 'Name' fields being 'reversed'. MPD uses 'Name' to present the radio station's ID as returned in its Metadata, and changes 'Title' whenever the track metadata changes. Mopidy appears to do the reverse.

I had a quick look in the code but I have a feeling this is something that goes a lot deeper than just switching the output around in the mpd frontend.

**Comment by adamcik** [comment]
This is a rather new feature, so it could be as simple as me getting things mixed around when I added it. #944 for the original bug, which shows it the same way around as you found. I.e. we should swap them back.

This would be a candidate for a 1.0.x. so if you make a PR please use that as the base branch.

**Comment by fatg3erman** [comment]
If you have a minute to help out a confused person...

   This would be a candidate for a 1.0.x. so if you make a PR please use that as the base branch.

Git confuses the life out of me. I've done one PR so far by following your Docs to the letter.

How do I use 1.0.x as the base branch? And can I do this while I simultaneously have an open PR on the develop branch? How will I know which version of the code I'm editing?

Sorry to ask dumb questions, but even the online git tutorials have confused me more (I only have experience with branching in Perforce, which could not be more different)

**Comment by jodal** [comment]
I don't know where to start to explain that through an async medium like issue comments are. If you just submit your PR, based on v1.0.x or develop, I'll make sure the fix ends up in both 1.0.x and 1.1.

**Comment by fatg3erman** [comment]
Yeah fair enough :)

**Comment by fatg3erman** [comment]
So I've been looking at the code for this and I'm not sure I'm following how this was supposed to provide the Name field.

in core/actor.py there is

    def tags_changed(self, tags):
        if not self.audio or 'title' not in tags:
            return

        tags = self.audio.get_current_tags().get()
        if not tags:
            return

        # TODO: this limits us to only streams that set organization, this is
        # a hack to make sure we don't emit stream title changes for plain
        # tracks. We need a better way to decide if something is a stream.
        if 'title' in tags and tags['title'] and 'organization' in tags:
            title = tags['title'][0]
            self.playback._stream_title = title
            CoreListener.send('stream_title_changed', title=title)

This 'title' refers to the stream title - i.e what radio stations generally send in a string of the form 'Artist - Track'.

mpd/translator.py currently outputs this as the 'Name' field

    def track_to_mpd_format(track, position=None, stream_title=None):

   ...

        if stream_title:
            result.append(('Name', stream_title))

But this is what should be in the 'Title' field (overriding the value of track.name), so that's a simple fix.

However I can't see anywhere in the code where the value of the Station Name (for the Name) field is extracted from the stream or any way it could be passed to mpd. So I'm thinking I must have missed something obvious or failed to follow the code.

**Comment by fatg3erman** [comment]
Oh wait, yes I'm being dumb. The data for the 'Title' field is what is in track.name, so they just need to be swapped.

**Comment by fatg3erman** [comment]
I've submiited a PR to fix this. I'm afraid it's based on the develop branch because I tried to do things on 1.0.x but git spat out error messages and I couldn't decipher them.
