### ISSUE TITLE
No items in library

### ISSUE THREAD

**Issue by Moult** [mopidy/mopidy#1216]
Recently installed mopidy. Music sources are from local and gmusic extension. Client is ncmpcpp.

Upon starting ncmpcpp, if I go to the browse tab, I can see "[Local media]" (and "[Google music]") where if I enter it I can see a list of my tracks.

However if I go to the "Media Library" tab, there are no items.

```
$ grep -ir "fail" mopidy.log

  Fetching passwords from your keyring failed. Any passwords stored in the keyring will not be available. (org.freedesktop.secrets service not running)
  Loading config from /etc/xdg/mopidy/mopidy.conf failed; it does not exist
  Zeroconf service _mpd._tcp at [localhost.local]:6600: Avahi service not running; publish failed.
  Zeroconf service _http._tcp at [localhost.local]:6680: Avahi service not running; publish failed.
  Zeroconf service _mopidy-http._tcp at [localhost.local]:6680: Avahi service not running; publish failed.
```

**Comment by jodal** [comment]
We recently changed the contribution guidelines to make it clear that GitHub Issues is for bugs and well-defined feature requests only, ref. https://docs.mopidy.com/en/latest/contributing/#issue-guidelines

I don't want to kill your discussion. I just want to make the issue tracker a useful development tool by removing as many non-actionable issues as possible.

Can you please continue the discussion at https://discuss.mopidy.com? Feel free to post another comment here with the link to your continued discussion.

**Comment by Moult** [comment]
No problem :)

For those interested, here is the link: https://discuss.mopidy.com/t/no-items-in-library/806
