### ISSUE TITLE
[Arch Linux] Wrong owner of /var/lib/mopidy/*

### ISSUE THREAD

**Issue by chookies** [mopidy/mopidy#1220]
I installed mopidy 1.0.7 via de community repo on Arch Linux. Starting it with the `mopidy` command went fine, but the systemd service fails with the following error

```
● mopidy.service - Mopidy music server
   Loaded: loaded (/usr/lib/systemd/system/mopidy.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2015-07-13 10:53:51 CEST; 10min ago
  Process: 28005 ExecStart=/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf (code=exited, status=1/FAILURE)
 Main PID: 28005 (code=exited, status=1/FAILURE)

Jul 13 10:53:51 technolinux mopidy[28005]: File "/usr/lib/python2.7/os.py", line 150, in makedirs
Jul 13 10:53:51 technolinux mopidy[28005]: makedirs(head, mode)
Jul 13 10:53:51 technolinux mopidy[28005]: File "/usr/lib/python2.7/os.py", line 150, in makedirs
Jul 13 10:53:51 technolinux mopidy[28005]: makedirs(head, mode)
Jul 13 10:53:51 technolinux mopidy[28005]: File "/usr/lib/python2.7/os.py", line 157, in makedirs
Jul 13 10:53:51 technolinux mopidy[28005]: mkdir(name, mode)
Jul 13 10:53:51 technolinux mopidy[28005]: OSError: [Errno 13] Permission denied: '/var/lib/mopidy/.local'
Jul 13 10:53:51 technolinux systemd[1]: mopidy.service: Main process exited, code=exited, status=1/FAILURE
Jul 13 10:53:51 technolinux systemd[1]: mopidy.service: Unit entered failed state.
Jul 13 10:53:51 technolinux systemd[1]: mopidy.service: Failed with result 'exit-code'.
```

When I checked the /var/lib/mopidy directory, the ownership didn't make sense: user:group was set to 46:46

```
total 20K
drwxr-xr-x  5  root root 4.0K Jul  8 20:24 .
drwxr-xr-x 28 root root 4.0K Jul 13 10:21 ..
drwxr-xr-x  2   46   46 4.0K Jul  8 20:24 local
drwxr-xr-x  2   46   46 4.0K Jul  8 20:24 media
drwxr-xr-x  2   46   46 4.0K Jul  8 20:24 playlists
```

When I executed `chown -R mopidy:mopidy /var/lib/mopidy/*`, the service started fine.

**Comment by chookies** [comment]
As a follow-up, the service seems to run as user `mopidy`, while I have my configuration file in my own home directory `~/.config/mopidy` (as documented [here](https://docs.mopidy.com/en/latest/config/)). Wouldn't it be better to have the service run by the logged in user, so the configuration is loaded from home and music/playlists can be put there as well?

**Comment by chookies** [comment]
Not sure I'm going in the right direction with this, but I'll just go for it: I created the following systemd Unit file and put it in `/usr/lib/systemd/user/mopidy.service`:

```
[Unit]
Description=Mopidy music server
After=avahi-daemon.service
After=dbus.service
After=network.target
After=nss-lookup.target
After=pulseaudio.service
After=remote-fs.target
After=sound.target

[Service]
User=%i
ExecStart=/usr/bin/mopidy --config /home/%i/.config/mopidy:/usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf

[Install]
WantedBy=multi-user.target
```

This _user_ service (as opposed to the original _system_ service) is started by executing `systemctl --user start mopidy`. Now the configuration file in `~/.config/mopidy` is read first and the home directory is interpreted as the one from the logged in user (e.g. `/home/chookies`).

Not sure if I should add `Group=mopidy` to `[Service]` for mopidy to perform adequately, but for now it works fine.

**Comment by adamcik** [comment]
Closing in favor of https://bugs.archlinux.org/task/45637?project=5&cat%5B0%5D=33&string=mopidy which I assume you also filed. We don't maintain the mopidy arch packaging ourselves.
