### ISSUE TITLE
Setting to change the balance?

### ISSUE THREAD

**Issue by barryvdh** [mopidy/mopidy#1227]
Is it possible to change the balance (left/right volume) using the API?

**Comment by jodal** [comment]
No, there is currently no such option.

**Comment by adamcik** [comment]
https://blogs.gnome.org/jessevdk/2010/12/17/fun-with-gstreamer-controlling-volume-of-channels-independently/ explains how to do this in a GStreamer pipeline. So you could combine this with our `audio/ouptut` setting to get it to do what you want.

But I don't think we are going to add any explicit support for this beyond the method explained above. In there future we will likely add output extensions, at which point someone could create one that does this for you.
