### ISSUE TITLE
Google Play doesn't count the reproduction

### ISSUE THREAD

**Issue by pattyco** [mopidy/mopidy#1229]
We use to put random playlist in our business, and from time to time we delete from that list the ones that haver more plays ( playlists of more than 8 hours) But in the last month we see yesterday that it didn't count any play at the google music website (we only use now Mopidy conected directly to our audio instalation) , but if we do it from the browser it works in real time! :S 
Any clue?
Thanks!

**Comment by jodal** [comment]
Please open an issue with the Mopidy-GMusic extension at https://github.com/hechtus/mopidy-gmusic/issues

Mopidy core knows nothing of Google Music.

**Comment by pattyco** [comment]
Sorry!
