### ISSUE TITLE
Add link checks to tests

### ISSUE THREAD

**Issue by txomon** [mopidy/mopidy#1236]
There are some broken link in the docs (outdated applications, etc.) and adding a check to them should improve them.

Sphinx has a builtin checker, which can be executed with `make linkcheck`.

The task would be to add this to the ci tests and fix them.

**Comment by jodal** [comment]
:+1:

**Comment by ghallberg** [comment]
Hi I'm gonna try to do this as my first mopidy issue, please tell me if that's not a good idea :)

**Comment by jodal** [comment]
Go ahead! :-)

**Comment by ghallberg** [comment]
linkcheck is telling me some links are broken, even though they work for me in a browser, I'm not sure what to do about those. Adding them to ignore seems wrong but I'm not sure what else to do... http://vk.com is an example.

**Comment by jodal** [comment]
Fixed by PR #1317.
