### ISSUE TITLE
Unhandled exception in Audio

### ISSUE THREAD

**Issue by Kruemmelmonster** [mopidy/mopidy#1244]
Greetings everyone everytime i try to start mopidy with the output set to liquidsoap i get the following error: 
```python
ERROR    Unhandled exception in Audio (urn:uuid:02349e3c-3a54-44eb-b3d5-d0bc8ed7cf45):
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 191, in _actor_loop
    self.on_start()
  File "/usr/lib/python2.7/site-packages/mopidy/audio/actor.py", line 407, in on_start
    self._setup_audio_sink()
  File "/usr/lib/python2.7/site-packages/mopidy/audio/actor.py", line 481, in _setup_audio_sink
    volume.link(self._outputs)
LinkError: failed to link volume0 with outputs
```

Hope this can be fixed soon :+1:

**Comment by adamcik** [comment]
All I can tell from the info you've provided is that you likely have something setup wrong in you `audio/output` setting. And without knowing what you've setup there isn't really much more I can do.

As for "fixing" this in mopidy we can consider catching the error in audio to provide a better error message and then force a shutdown of the server. But beyond that there isn't much to be done.

**Comment by Kruemmelmonster** [comment]
i fixed this issue by switching to another audio output
