### ISSUE TITLE
Mopidy 1.1 stops on browsing dir with *.mid files

### ISSUE THREAD

**Issue by szuniverse** [mopidy/mopidy#1247]
Hi

The new filesystem browsing feature stops if the folder contains *.mid file.
I have these two files in a folder: https://www.dropbox.com/s/5pytsexugqh92xv/mid_files.zip?dl=0 and if I open this folder the mopidy server has stopped unexpectedly.

**Comment by adamcik** [comment]
Seems we get stuck on the following:

```
  pykka Current state of FileBackend-6 (ident: 140283202701056):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/adamcik/dev/mopidy-virtualenv/local/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/home/adamcik/dev/mopidy-virtualenv/local/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/home/adamcik/dev/mopidy/mopidy/file/library.py", line 74, in browse
    elif os.path.isfile(child_path) and self._is_audio_file(uri):
  File "/home/adamcik/dev/mopidy/mopidy/file/library.py", line 136, in _is_audio_file
    result = self._scanner.scan(uri)
  File "/home/adamcik/dev/mopidy/mopidy/audio/scan.py", line 60, in scan
    pipeline.set_state(gst.STATE_NULL)
```

**Comment by adamcik** [comment]
Strange running `python mopidy/audio/scan.py tmp/music/tetrisc.mid ` doesn't seem to reproduce any of this.

**Comment by adamcik** [comment]
Hmm, the mid file works just fine in my case, but I am getting it to hang while I was trying to browse to the dir I put them in...

**Comment by adamcik** [comment]
Which is due to an other file from a previous bug which is rather broken and gets GStreamer 0.10 into an endless loop... So I can't seem to reproduce to be honest.

**Comment by szuniverse** [comment]
how can I send you a log (what happened with my mopidy if i open this folder) ?

**Comment by adamcik** [comment]
See https://docs.mopidy.com/en/latest/troubleshooting/#debug-logging and onwards, I would be interested in the the Mopidy log, a GST_DEBUG=3 log and the tracebacks from the deadlocks. Between those I should hopefully be able to make some sense of this.

**Comment by jodal** [comment]
Removing from the v1.1.1 milestone as there's not much to work on here currently.

**Comment by adamcik** [comment]
Is this still an issue with the new 2.0 release?

**Comment by jodal** [comment]
Putting this in the v2.0.1 milestone just to remember to try to reproduce it.

**Comment by szuniverse** [comment]
I will try to reproduce it in this week

**Comment by vrs01** [comment]
I don't get errors when I browse via "Files" into a directory containing *.mid files with mopidy 2.0. Seems to work fine now.

**Comment by jodal** [comment]
Thanks for testing this!
