### ISSUE TITLE
Expand nested playlists in stream

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1250]
https://discuss.mopidy.com/t/playlist-radiostream-not-working-anymore-with-1-1-0/839

We regressed with respect to nested playlists in 1.1, though it still somewhat common to have nested playlists for radio streams. So we should probably re-add this.

**Comment by kingosticks** [comment]
My experience with stations via TuneIn is that it is (unfortunately) very
common.

**Comment by r100gs** [comment]
THX for the quick answer!

Best regards,
Stefan

**Comment by hakanpalm** [comment]
I have the same experience but I extract the uri from an XML file like:
```xml   
<station>
     <name>Lugna Favoriter</name>
      <uri>http://stream-ice.mtgradio.com:8080/stat_lugna_favoriter.m3u</uri>
       <genre>Mer musik, mindre prat!</genre>
        .....................
```

Works fine with uri like http://fm01-icecast.mtg-r.net/fm01_mp3 but all m3u links are unplayable after upgrading to 1.1

**Comment by hakanpalm** [comment]
It seems like I messed up with Debian and pip installations. After uninstall all pip packages and reinstall Mopidy  with apt I can play all my Radiostations again. Do not know why the fault appears with the upgrade. I probably have had this mess since Mopidy 0.19.3. Sorry to bother you

**Comment by jodal** [comment]
For future reference, the following setup was used to fix this:

An M3U playlist, `~/.local/share/mopidy/m3u/bug1250.m3u`, containing:

```
http://www.wqxr.org/stream/wqxr/mp3.pls
http://streams.br.de/bayern2nord_2.m3u
```

Streams are from https://discuss.mopidy.com/t/playlist-radiostream-not-working-anymore-with-1-1-0/839 and https://discuss.mopidy.com/t/http-server-fails-at-boot-gstreamer-text-uri-list-problems/870. They both work with 1.0.8 and should both work when this bug is fixed. They fail in different ways.

**Comment by jodal** [comment]
Debug log with my current implementation...

When playing: http://www.wqxr.org/stream/wqxr/mp3.pls

```
DEBUG    2015-09-13 23:06:02,680 [11920:StreamBackend-3] mopidy.stream.actor
  Unwrapping stream from URI: http://www.wqxr.org/stream/wqxr/mp3.pls
DEBUG    2015-09-13 23:06:03,299 [11920:StreamBackend-3] mopidy.stream.actor
  GStreamer failed scanning URI (http://www.wqxr.org/stream/wqxr/mp3.pls): Could not determine type of stream.
DEBUG    2015-09-13 23:06:03,553 [11920:StreamBackend-3] mopidy.stream.actor
  Parsed playlist (http://www.wqxr.org/stream/wqxr/mp3.pls) and found new URI: http://stream.wqxr.org/wqxr
DEBUG    2015-09-13 23:06:03,553 [11920:StreamBackend-3] mopidy.stream.actor
  Unwrapping stream from URI: http://stream.wqxr.org/wqxr
DEBUG    2015-09-13 23:06:04,376 [11920:StreamBackend-3] mopidy.stream.actor
  Unwrapped potential audio/mpeg stream: http://stream.wqxr.org/wqxr
```

When playing: http://streams.br.de/bayern2nord_2.m3u

```
DEBUG    2015-09-13 23:08:08,953 [11920:StreamBackend-3] mopidy.stream.actor
  Unwrapping stream from URI: http://streams.br.de/bayern2nord_2.m3u
DEBUG    2015-09-13 23:08:09,101 [11920:StreamBackend-3] mopidy.stream.actor
  Parsed playlist (http://streams.br.de/bayern2nord_2.m3u) and found new URI: http://br-mp3-bayern2nord-m.akacast.akamaistream.net/7/841/256282/v1/gnl.akacast.akamaistream.net/br_mp3_bayern2nord_m
DEBUG    2015-09-13 23:08:09,101 [11920:StreamBackend-3] mopidy.stream.actor
  Unwrapping stream from URI: http://br-mp3-bayern2nord-m.akacast.akamaistream.net/7/841/256282/v1/gnl.akacast.akamaistream.net/br_mp3_bayern2nord_m
DEBUG    2015-09-13 23:08:10,133 [11920:StreamBackend-3] mopidy.stream.actor
  Unwrapped potential audio/mpeg stream: http://br-mp3-bayern2nord-m.akacast.akamaistream.net/7/841/256282/v1/gnl.akacast.akamaistream.net/br_mp3_bayern2nord_m
```

This should greatly help the debugging of future stream playlist unwrapping issues.

**Comment by digrix** [comment]
I agree this is fixed for stream module, but for example in **mopidy-tunein** it still does not work. How are other backends supposed to fix this issue? 

I found this fork https://github.com/ZenithDK/mopidy-tunein/commit/452722a3ec2b7f0919072f1336f4e02315a2bca3 and it fixes the problem for me, but I guess, it is not the right way :).

**Comment by kingosticks** [comment]
I'm still sitting on that PR as I've still not had a chance to get into it.
And, as you say, is it the right way.

**Comment by ZenithDK** [comment]
I've been meaning to revisit my work (which is really just a cleaned up version of some quick hacking Tobias Schlemmer did, based on what @jodal did for the stream backend.

I suspect rewriting tunein to base itself on the Stream module would be a better way to do it, if possible.
