### ISSUE TITLE
stop on error in other backend  

### ISSUE THREAD

**Issue by fzerorubigd** [mopidy/mopidy#1252]
I have spotify backend and file backend, When I am offline, I use file backend, but the spotify try to connect and when reached to its timeout, mopidy stop the playback on file backend. I play it again, and then again and again and ...
In this case I should change the config and disable the spotify, which is not a good thing to do .

**Comment by jodal** [comment]
This is mopidy/mopidy-spotify#1, which should have been fixed in Mopidy-Spotify 2.0 released a few days ago. What version of Mopidy-Spotify are you running?

**Comment by fzerorubigd** [comment]
Thank you. yes. its fixed. sorry :)

**Comment by jodal** [comment]
No problem! This has been an issue for years, only to be finally fixed this
week :-)
