### ISSUE TITLE
Empty core/cache_dir setting probably crashes extensions

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1253]
Looking at the code we allow the `core/cache_dir` to be blank, but don't actually handle the `None` case in the extension helper for getting the dir.

And while we are at it we probably want to make the `data_dir` and `config_dir` be unset.

Finally, some more hints in the docs about what each of these are used for probably makes sense. For instance also what settings to recommend for SD cards.

**Comment by tkem** [comment]
So how should a blank/`None` setting actually be handled? As a backend author, I'd like to rely on `get_cache_dir()` giving me an actual directory I can write to, and not handling a `None` return myself...

**Comment by jodal** [comment]
In Mopidy-Spotify 2.0 I added a new config `spotify/allow_cache` to disable caching. I didn't even consider having a global config like `core/cache_dir=` mean that all caching should be turned off. I guess the amount of caching and how important the cache is will vary wildly from extension to extension. Is it useful to have a global way to turn off caching? Maybe better to recommend 1) turning off caching in some specific heavily caching extensions, and 2) having `core/cache_dir` point to a tmpfs.

**Comment by adamcik** [comment]
My though was that the helpers return `None` signaling that the backend shouldn't cache. But of course that might be problematic if the backend can't function without a cache dir. So if we wan't to make this mandatory then the config scheme should reflect that.

**Comment by tkem** [comment]
Haven't thought this through, but my first impulse is that all `get_*_dir()` methods should behave the same. And telling an extension to work without a data dir might be going too far. I think we should make life easier for extension developers, and if we choose to provide a caching facility, they should've able to rely on that.

**Comment by tkem** [comment]
@jodal: I have something like `allow_cache` in mind for mopidy-podcast myself. So I think this should be configurable on a per-extension basis.

**Comment by jodal** [comment]
```
$ head -2 ~/.config/mopidy/mopidy.conf
[core]
cache_dir =
$ mopidy
# ...
WARNING  Found fatal core configuration errors:           
WARNING    core/cache_dir must be set.                    
ERROR    Please fix fatal configuration errors, exiting...
$
```

This doesn't look like a problem?

**Comment by jodal** [comment]
> And while we are at it we probably want to make the data_dir and config_dir be unset.

I don't know. What's the reasoning for this?

**Comment by jodal** [comment]
@adamcik With that commit, is there anything left to address here?

**Comment by adamcik** [comment]
LGTM
