### ISSUE TITLE
Mopidy-File browsing should not scan files

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#1260]
After the 1.1 release there was a discussion in IRC about Mopidy-File scanning files when browsing, making browsing quite a bit slower than necessary. The idea was that if you have a clean enough music collection to be able to find anything by browsing the file hierarchy, then the file names are probably  good enough for finding the music you want to listen to. The scanning can be delayed to you actually start playing a file.

**Comment by jodal** [comment]
I tried removing the `is_audio_file()` check in Mopidy-File's `browse()`. This didn't noticeably speed up browsing of single-album dirs, and I still got metadata from tags when browsing with ncmpcpp.

The reason is that the MPD command `lsinfo` use the MPD browse helper, `MpdContext.browse()`, which by default does a `core.library.lookup()` of all `Ref.track` objects.

If we change `lsinfo` to call `MpdContext.browse()` with `lookup=False`, we're removing the amount of metadata available to MPD clients for anything that can be browsed, not just Mopidy-File. IMHO, not very acceptable.

The other solution is to remove all scanning from Mopidy-File, both from `browse()` and `lookup()`. If I do this, browsing becomes instant, but if I add a track to the tracklist and play it, I still only have the filename to go by. No metadata is available. IMHO, not a very optimal solution.

**Comment by adamcik** [comment]
Removing the `is_audio_file()` check is a good start given that we at least avoid double scanning when MPD comes along and does the `lookup()`.

As for getting the track metadata at play time, this is in theory where we start overlapping with dynamic playlists as we would be able to just supplement with the metadata we get when playback starts. Not that this helps the MPD browse case. 

I wonder if we could have the browse add tracks to a queue which does the scanning in the background and sticks them in some LRU? Might be over engineering things though :-)

Other thing we mentioned on IRC was possibly having extension include/exclude lists.

**Comment by jodal** [comment]
I saw the mention of include/exclude lists, but... who keeps lots of non-music files in their music collection? Feel free to open another issue for it, though :-)

**Comment by adamcik** [comment]
Main thing would be excluding coverart and cue files.

**Comment by jodal** [comment]
Fixed by #1260.
