### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by robin92** [mopidy/mopidy#1264]
I've cloned your repo and followed [this guide](https://docs.mopidy.com/en/latest/devenv/#initial-setup) and reached testing step. Clear repo fails 64 tests, eg. ImportErrors for _testscenario_, _testresources_ or _fixtures_. After installing those missing packages I get even more (~120) failed tests =. I can see that Travis builds are passing. Can any developer help?

My shell session is available [here](http://pastebin.com/fuviKV7r).

**Comment by jodal** [comment]
I think you've created the virtualenv inside the Git repo, so when you run the tests, it finds the tests of all our dependencies as well. I never heard of `testscenario` or `testresources`. I can see from your session that you're for example running flake8's tests.

In the future, please use https://discuss.mopidy.com to get help, and the issue tracker just for actual bugs and feature requests.

**Comment by jodal** [comment]
The devenv guide you link to recommends the following layout:

- `~/mopidy-dev/` -- a dir for all mopidy related stuff
- `~/mopidy-dev/mopidy/` -- the core mopidy git repo
- the use of virtualenvwrapper, which keeps the virtualenv somewhere else

If you want to make the virtualenv yourself with plain virtualenv, a proper place would be for example `~/mopidy-dev/env`, outside the git repo.
