### ISSUE TITLE
local scan json not updated until restart (Ubuntu 14.04 LTS)

### ISSUE THREAD

**Issue by oliverjkb** [mopidy/mopidy#1267]
I just happened to install Mopidy on a spare Ubuntu machine, which I recently bought. 
I installed the newest apt-package (1.0.8). 
Now, when I start local scan (mopidyctl local scan) local scan is running without problems and the library.json.gz file is populated correctly. 
Unfortunately Mopidy will not show these local files no neither MPD client nor Mopidy-Musicbox-Webclient unless I restart the service.

**Comment by jodal** [comment]
You are correct. This is currently how Mopidy-Local works. It only reads the library file on startup. If you switch from the JSON backed library bundled with Mopidy-Local to the Mopidy-Local-SQLite extension, you'll get instant library updates without restarting Mopidy.

**Comment by oliverjkb** [comment]
Ouch -.- 
Guess I might have read that somewhere, right? 
Thanks for the unbelievable quick reply!

**Comment by jodal** [comment]
It's not very explicit, but can be interpreted into the third point at https://docs.mopidy.com/en/latest/ext/local/#generating-a-local-library if you know how to interpret it.

With time, we'll move Mopidy-Local out of core and merge -SQLite into it. It will probably replace the current JSON solution as the default.

**Comment by oliverjkb** [comment]
Yep, can almost clearly be interpreted in point three. 
Never mind. I just switched to local-SQLite. 
Thanks again!

**Comment by jodal** [comment]
I'll improve the docs a bit before I close this :-)

**Comment by tkem** [comment]
@oliverjkb: For "instant" updates to work flawlessly, please make sure to set your `local/scan_flush_threshold` to 100, or an even lower value. Otherwise, the local backend may run into timeouts while the local scan is running.

@jodal: any chance we can make this the default in upcoming releases? Shouldn't hurt the `json` library much, and definitely a boon for everyone switching to sqlite...

**Comment by oliverjkb** [comment]
@tkem Thanks for the hint! I changed it just before I started the first scan. So that should be quite right.

**Comment by tkem** [comment]
@oliverjkb: It's also in the Mopidy-Local-SQLite README, but I don't know how many people actually read that ;-)

**Comment by jodal** [comment]
Docs updated in 0360936135ef8193cc2b508cecb766e943b1294e. PR #1270 opened to reduce `local/scan_flush_threshold`.
