### ISSUE TITLE
TracklistController.get_eot_tlid functionality does not match docstring

### ISSUE THREAD

**Issue by kingosticks** [mopidy/mopidy#1269]
The docstring for  `get_eot_tlid` states
> The TLID of the track that will be played after the given track.

but the function takes no arguments and in fact uses the current track as the 'given track'. So either the docstring is wrong or the function does the wrong thing.

**Comment by jodal** [comment]
Looking at #1231, it seems the intention was for the new methods to be argument-less, so the docstring is at fault.

**Comment by jodal** [comment]
Fixed in v1.1.x branch.
