### ISSUE TITLE
Option to let LibraryController.browse return full models

### ISSUE THREAD

**Issue by dirkgroenen** [mopidy/mopidy#1271]
At the moment the `LibraryController.Browse` endpoint returns a list of `Ref` models. For the new version of Mopify I need to retrieve a list of full models instead of the refs. 

The documentation categories the decision to return refs instead of full models as a performance issue, but I think returning full `Track` models in the browse request is faster than doing a `Browse` request, wait for the result and do a lookup on each track. 

Would it be possible to add an extra parameter which can be set to True o the request returns full models?

**Comment by tkem** [comment]
Though I can understand this request from a client developer's perspective, -1 from me regarding "the grand scheme" of things. I personally think `Ref`s should be used throughout the Mopidy API, esp. including `Library.search`.
@dirkgroenen: Have you looked at the new `lookup` API? It's possible to retrieve multiple models in a single request.

**Comment by tkem** [comment]
And while ruminating on this (and completely off-topic), I think the major issue with the Mopidy API from a client perspective is not supporting pagination (i.e. limit/offset) ;-)

**Comment by jcass77** [comment]
I'm going through some of the older issues to see if we can reduce the list slightly.

Can I propose to have this closed as something that won't be supported, seeing as the design decision seems to be to rely on Refs?

I've seen enough posts on the discussion forum by people with folders containing more than 10k tracks to think that what is proposed here will not be viable.

**Comment by jodal** [comment]
:+1: @jcass77. Closing.
