### ISSUE TITLE
Consider making Extension.get_data_dir() etc. @classmethods

### ISSUE THREAD

**Issue by tkem** [mopidy/mopidy#1275]
Since `LibraryProvider` and other likely users of these methods don't have access to `Extension` instances, these are pretty much unusable without resorting to ugly hacks like creating a temporary Extension instance just to get access to the directory.

So I'd suggest either making these `@classmethod`s, which should work in a backwards-compatible way, or giving backends somehow access to the Extension instance they're created from.

**Comment by jodal** [comment]
We've discussed this a couple of times, and I don't find my own arguments for not making this a `@classmethod` compelling. Let's just do this :-)
