### ISSUE TITLE
No sound with 'autoaudiosink' running mopidy as service. Specifying the preferred device with ALSA works, but captures the device indefinitely.

### ISSUE THREAD

**Issue by rsolvang** [mopidy/mopidy#1278]
I have a simple USB Toslink (SPDIF) output. Running `gst-launch-0.10 audiotestsrc ! audioresample ! autoaudiosink` as my own user works, but when mopidy uses `autoaudiosink` running as a service (under Arch), it probably selects the standard on-board headphone output instead of the USB Toslink.

Using ALSA to specify the output device (hw:1,0) works, but unfortunately this 'captures' the sound device and blocks other apps from sending sound through the USB output – also when songs are stopped/paused in Mopidy.

Is there a simple way to fix this within the mopidy.conf file? Or is there a way to set the preferred output device for the mopidy user that is running the service?

**Comment by adamcik** [comment]
The config value `audio/output` can be set to any valid GStreamer output pipeline, be it just an `alsasink` or anything more complex you can come up with. So you just need to find the right sink to use.

On a side note, we've been trying to funnel user questions to https://discuss.mopidy.com as there is a larger community there that can answer support questions, freeing up more developer time for actual bugs and improvements :-)
