### ISSUE TITLE
Published zeroconf service can’t be resolved

### ISSUE THREAD

**Issue by emontnemery** [mopidy/mopidy#1283]
If the entry localhost6.localdomain6.local is present in /etc/hosts, this will be published as hostname for the mopidy service.
As discussed in [the forum][2], the root cause is that calling socket.getfqdn() with no argument is not a reliable name to discover the hostname.

The avahi [documentation][3] actually recommends passing NULL as hostname to the C-API because:

    We recommend to pass NULL here, the daemon will than automatically insert the local host name in that case

Passing the empty string to the python wrapper is working well, this has been tested by simply modifying zeroconf.py (around line 60) from:

    self.host = '%s.local' % socket.getfqdn()

To:

    self.host = ''

  [2]: https://discuss.mopidy.com/t/published-zeroconf-service-cant-be-resolved/828
  [3]: http://avahi.org/download/doxygen/publish_8h.html

**Comment by jodal** [comment]
To test possible changes here, can you provide the output of this script on your system?

``` python
import dbus

bus = dbus.SystemBus()
server = dbus.Interface(
    bus.get_object('org.freedesktop.Avahi', '/'),
    'org.freedesktop.Avahi.Server')

print server.GetHostName()
print server.GetHostNameFqdn()
```

**Comment by emontnemery** [comment]
Sure:

    osmc@osmc-livingroom:~$ cat debug.py
    import dbus

    bus = dbus.SystemBus()
    server = dbus.Interface(
        bus.get_object('org.freedesktop.Avahi', '/'),
        'org.freedesktop.Avahi.Server')

    print server.GetHostName()
    print server.GetHostNameFqdn()
    osmc@osmc-livingroom:~$ python debug.py
    osmc-livingroom
    osmc-livingroom.local

**Comment by jodal** [comment]
That looks good. Way better than "localhost6.localdomain6" which you got from `socket.getfqdn()`.
