### ISSUE TITLE
SIGSEGV in g_mutex_lock glib2 2.44.1-1 at end of song

### ISSUE THREAD

**Issue by joepvd** [mopidy/mopidy#1284]
Hi. mopidy regularly crashes when a song ends. It does not seem to matter of there is another song upcoming. 

I managed to get a dump from `gdb`:

    % gdb --args python2 $(pacman -Ql mopidy | awk '/__main__.py$/{print $2}')
    GNU gdb (GDB) 7.10
    Copyright (C) 2015 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-unknown-linux-gnu".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from python2...(no debugging symbols found)...done.
    (gdb) run
    Starting program: /usr/bin/python2 /usr/lib/python2.7/site-packages/mopidy/__main__.py
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/usr/lib/libthread_db.so.1".
    ** Message: pygobject_register_sinkfunc is deprecated (GstObject)
    INFO     Loading config from builtin defaults
    INFO     Loading config from /home/joep/.config/mopidy/mopidy.conf
    INFO     Loading config from command line options
    INFO     Starting Mopidy mixer: SoftwareMixer
    [New Thread 0x7fffed918700 (LWP 8819)]
    INFO     Starting Mopidy audio
    [New Thread 0x7fffed117700 (LWP 8820)]
    INFO     Starting Mopidy backends: M3UBackend, LocalBackend
    INFO     Loaded 0 M3U playlists from /home/joep/.local/share/mopidy/m3u
    [New Thread 0x7fffe7fff700 (LWP 8821)]
    INFO     Audio output set to "autoaudiosink"
    INFO     Loaded 22972 local tracks using json
    [New Thread 0x7fffe4c94700 (LWP 8824)]
    INFO     Starting Mopidy core
    [New Thread 0x7fffdbfff700 (LWP 8825)]
    INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
    INFO     MPD server running at [::ffff:127.0.0.1]:6600
    [New Thread 0x7fffdb7fe700 (LWP 8827)]
    [New Thread 0x7fffdaffd700 (LWP 8828)]
    INFO     HTTP server running at [::ffff:127.0.0.1]:6680
    [New Thread 0x7fffda7fc700 (LWP 8829)]
    [New Thread 0x7fffd9ffb700 (LWP 8845)]
    INFO     New MPD connection from [::ffff:127.0.0.1]:34588
    [Thread 0x7fffd9ffb700 (LWP 8845) exited]
    [New Thread 0x7fffd9ffb700 (LWP 8850)]
    INFO     New MPD connection from [::ffff:127.0.0.1]:34590
    [New Thread 0x7fffbe105700 (LWP 8863)]
    [New Thread 0x7fffbcea6700 (LWP 8864)]
    [New Thread 0x7fffb3be5700 (LWP 8865)]
    [New Thread 0x7fffb33e4700 (LWP 8866)]
    [New Thread 0x7fffb2be3700 (LWP 8867)]
    [New Thread 0x7fffb23e2700 (LWP 8868)]
    [New Thread 0x7fffb1be1700 (LWP 8869)]
    [Thread 0x7fffb1be1700 (LWP 8869) exited]
    [Thread 0x7fffbe105700 (LWP 8863) exited]
    
    Program received signal SIGSEGV, Segmentation fault.
    [Switching to Thread 0x7fffed117700 (LWP 8820)]
    0x00007ffff4e9e3f5 in g_mutex_lock () from /usr/lib/libglib-2.0.so.0
    (gdb) 

System:
A freshly installed Archlinux 64 bit system. 

    % pacman -Qi glib2
    Name           : glib2
    Version        : 2.44.1-1
    Description    : Common C routines used by GTK+ and other libs
    Architecture   : x86_64
    Optional Deps  : python2: for gdbus-codegen and gtester-report [installed]
                     elfutils: gresource inspection tool [installed]
    Required By    : at-spi2-core  atk  avahi  cairo  dbus-glib  dconf  desktop-file-utils  fribidi  gdk-pixbuf2  gettext  glib-networking  glibmm  gsettings-desktop-schemas  gstreamer  gstreamer0.10  harfbuzz
                     json-glib  libcroco  libfm-extra  libgusb  liblqr  libmpd  libsecret  libsoup  ncmpc  pkg-config  polkit  python2-gobject2  rest  shared-mime-info  udisks  udisks2
    Optional For   : libproxy
    Build Date     : Wed 13 May 2015 06:04:12 AM CEST
    Install Date   : Sat 12 Sep 2015 11:26:57 PM CEST

    % pacman -Qi mopidy
    Name           : mopidy
    Version        : 1.1.1-1
    Description    : Mopidy is an extensible music server written in Python
    Architecture   : any
    Depends On     : python2  python2-pykka>=1.1  python2-setuptools  python2-requests  gstreamer0.10-python  gstreamer0.10-base-plugins  gstreamer0.10-good-plugins  gstreamer0.10-ugly-plugins
                     python2-tornado>=2.3
    Installed Size :   7.25 MiB
    Build Date     : Mon 14 Sep 2015 12:09:05 PM CEST
    Install Date   : Tue 15 Sep 2015 10:18:39 AM CEST

My (truncated) configuration:

    [core]
    
    [logging]
    
    [audio]
    #mixer = software
    #mixer_volume = 
    #output = autoaudiosink
    
    
    [mpd]
    #enabled = true
    
    [http]
    enabled = true
    
    [stream]
    enabled = false
    
    [m3u]
    #enabled = true
    #playlists_dir = $XDG_DATA_DIR/mopidy/m3u
    
    [softwaremixer]
    #enabled = true
    
    [file]
    enabled = false
    
    [local]
    #enabled = true

Please let me know if other infos would be useful.

**Comment by jodal** [comment]
I believe this is the same issue as #933.
