### ISSUE TITLE
Raspbian mopidy not wanting to boot

### ISSUE THREAD

**Issue by chriseilander** [mopidy/mopidy#1287]
On the moment I try to run mopidy I get the following:

```
Traceback (most recent call last):
  File "/usr/bin/mopidy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.0
```

**Comment by jodal** [comment]
Please use https://discuss.mopidy.com for support requests.

You're probably running Raspbian wheezy (oldstable), but are using Mopidy packages for Raspbian jessie (stable). To fix this:

1. Replace "stable" with "wheezy" in /etc/apt/sources.list.d/mopidy.list by running: `sed -i -e 's/stable/wheezy/' /etc/apt/sources.list.d/mopidy.list`
2. Run `sudo apt-get update`
3. Run `sudo apt-get upgrade`

This will install packages working with wheezy (some are identical with jessie, some have differences) and will also give you a few needed package backports, like Requests 2.

**Comment by chriseilander** [comment]
Just fixed it myself using `sudo apt-get dist-upgrade`. It installed python-urllib3 and upgraded python-request. I did have the right packages, as I double checked that.

**Comment by jodal** [comment]
Good to hear to you got it working :-)
