### ISSUE TITLE
RFE - Include regex exclude directories setting for local and file

### ISSUE THREAD

**Issue by kevinclevenger** [mopidy/mopidy#1290]
There are a few directories in my media directories that I don't want to scan and list. I would be great if there was a configuration option for this, something like "excluded_directories = ${media_dir}/New* ${media_dir}/Artist/Meh\ Album" for file and local.

**Comment by adamcik** [comment]
Blacklisting directories is not something I think we will be supporting. We have some mechanisms for deciding what files to consider, and to ignore hidden files/directories. But beyond that I don't think we will be adding any more features in this area.
