### ISSUE TITLE
ERROR: Mopidy requires Python 2.7, but found 3.4.3.

### ISSUE THREAD

**Issue by Tmplt** [mopidy/mopidy#1294]
`mopidy local scan` gives me `ERROR: Mopidy requires Python 2.7, but found 3.4.3.`, but I have both Python 2.7 and 3.4.3 installed.

Is there a way to make it use the output from `which python2.7` instead?

**Comment by Tmplt** [comment]
Fixed by installing `mopidy-git`.

**Comment by ask-compu** [comment]
where do i get mopidy-git?

**Comment by Tmplt** [comment]
It's available in the [AUR](https://aur.archlinux.org/packages/mopidy-git/).
Otherwise you can just clone the latest update from master and install that.

**Comment by ask-compu** [comment]
But I installed my mopidy from apt-get 

-------- Original message --------

**Comment by 1percent** [comment]
Found the solution. Instead of
`sudo python setup.py install`
which will use the default interpreter as the program doesn't specify to python2,
`sudo python2 setup.py install` 
when installing from source will force the 2.7 interpreter.
