### ISSUE TITLE
ogg streams not playing

### ISSUE THREAD

**Issue by vasyugan** [mopidy/mopidy#1299]
In Mopidy 1.1.x, Ogg audio streams are not playing at all. In Mopidy 1.0.x they play just fine. 

This is one stream I tried:

http://dradio-ogg-dlf-l.akacast.akamaistream.net/7/629/135496/v1/gnl.akacast.akamaistream.net/dradio_ogg_dlf_l

This is all I find in the log file:

2015-10-04 14:52:18,425 INFO [1028:StreamBackend-9] urllib3.connectionpool: Starting new HTTP connection (1): dradio-ogg-dlf-l.akacast.akamaistream.net

Meanwhile CPU usage shoots up, and any attempt to play another file or stream or podcast after trying to play the ogg stream also fails until I restart mopidy.

The stream itself plays fine with gst-launch playbin uri=http://dradio-ogg-dlf-l.akacast.akamaistream.net/7/629/135496/v1/gnl.akacast.akamaistream.net/dradio_ogg_dlf_l so it's no a gstreamer issue

as noted above, downgrading to 1.0.x fixes this (and a number of other issues, which are also broken in 1.1.x currenly making it virtually unusable for me)

**Comment by adamcik** [comment]
https://github.com/mopidy/mopidy/blob/develop/mopidy/stream/actor.py#L126 incorrectly catches 'application/ogg' MIMEs so we trigger the playlist handling path. More fallout from our playlist handling changes.

We should add a `if scan_result.playable: return uri` to that code.

**Comment by jodal** [comment]
Fixed in release-1.1 branch by PR #1300.

**Comment by vasyugan** [comment]
Thanks! Looking forward to a released fix. For now I have gone back to 1.0.x, because there are just too many essential features which have stopped working altogether in 1.1.x, presumably all for the same reason (playlists not working from musicbox webclient, Ogg not playing, tunein.com stations not playing). 

I use mopidy primarily as a podcast and webradio player, which due to these bugs is currently mostly impossible. Is 1.1.x a development branch? If so, maybe separate stable & development package repositories would make sense

**Comment by kingosticks** [comment]
You are free to install directly from git. It's well documented.

**Comment by adamcik** [comment]
We try and keep the branch `develop` usable, and our releases even more so.  1.1.x does indeed have more issues that we would like related to the playlist handling. Which we sadly have had to rush as it was blocking migration to GStreamer 1.0 which we need to get done ASAP or our Debian packages get kicked out of the repos :(
