### ISSUE TITLE
Cant start mopidy

### ISSUE THREAD

**Issue by malteee** [mopidy/mopidy#1307]
I tried to install mopidy on my raspberry pi. Everything (install process) worked fine, but I cant start mopidy:

```
pi@raspberrypi ~ $ mopidy
Traceback (most recent call last):
  File "/usr/bin/mopidy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.0
pi@raspberrypi ~ $ 
```

I followed this tutorial to install mopidy: http://geeks.noeit.com/turn-your-raspberry-pi-into-a-spotify-server/

**Comment by adamcik** [comment]
See https://github.com/mopidy/mopidy/issues/1292#issuecomment-142010392 - this sounds like the same issue. Closing this, as this isn't a bug in mopidy, but feel free to ask for help at http://discuss.mopidy.com :-)
