### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by dedenker** [mopidy/mopidy#1309]
Feature request

I did not yet investigate how to implement this feature myself, but perhaps somebody else did...
To add [SPDY](https://tatsuhiro-t.github.io/spdylay) support, as it might greatly improve website serving performance.

**Comment by jodal** [comment]
As HTTP/2 has been standardized, it makes more sense to support HTTP/2 than SPDY which is mostly deprecated by HTTP/2.

I don't see a huge benefit in HTTP/2 for Mopidy, as most Mopidy usage is across the local network, where network performance is generally good.

As we use Tornado for our web server, this depends on Tornado supporting HTTP/2 and is blocked on tornadoweb/tornado#1438. Existing workarounds includes placing e.g. nginx in front of Mopidy and let it do the HTTP/2 work.

**Comment by jodal** [comment]
I should ask, what's your use case for SPDY and/or HTTP/2? What do you want it for?

**Comment by dedenker** [comment]
You completely right about the HTTP/2 part.
How ever my use case is to control my music source control via internet.
As I want to be able to change/view those things remotely, but I can put nginx in front, that can solve it also.

**Comment by adamcik** [comment]
I think our current stance on this is still put something in front of Mopidy. Which also has the benefit of not giving the private key to a Python process that runs a bunch of random plugin extensions.

If we were to add this it would currently be a question of figuring out how to setup Tornado for this case, that is if it supports it at all. With that in mind I think I'm just going to close this and if any one things we should change our mind they can chime in here with their reasons.
