### ISSUE TITLE
ProxyPass. Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by muhahacz** [mopidy/mopidy#1312]
I have just upgraded to latest version of mopidy. Seems there is problem with proxypass of websockets.

```
ProxyPass /mopidy/ ws://127.0.0.1:6680/mopidy/
ProxyPassReverse /mopidy/ ws://127.0.0.1:6680/mopidy/
```

ws://10.0.0.47:6680/mopidy/ws (working OK with https://www.websocket.org/echo.html)

wss://10.0.0.47:9999/mopidy/ws  ( doesnt work, chrome says problem about handshake,  ) I have selfsigned cert, but others proxied websockets works ok. 
```
WebSocket connection to 'wss://10.0.0.47:6680/mopidy/ws' failed: Error during WebSocket handshake: Unexpected response code: 400
```

@jodal will you look at this ? Thanks

**Comment by muhahacz** [comment]
EDIT: ws proxypass should be above http proxypass if the context is same
```
ProxyPass /mopidy/ ws://127.0.0.1:6680/mopidy/
ProxyPassReverse /mopidy/ ws://127.0.0.1:6680/mopidy/

ProxyPass /mopidy/ http://127.0.0.1:6680/mopidy/
ProxyPassReverse /mopidy/ http://127.0.0.1:6680/mopidy/
```

**Comment by adamcik** [comment]
This isn't really a mopidy bug, for support questions http://discuss.mopidy.com is normally much better as there are more people watching it and trying to give assistance. And since you figured it out I'm going to close this.
