### ISSUE TITLE
Catch bad logging configs

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1320]
We had a recent report where someone was struggling because their log config file had an error in it and it caused startup issues. We should probably wrap that code in and except that catches config parser errors just to improve our startup robustness and give a helpful error message.

**Comment by adamcik** [comment]
Fixed by ede5b8abff6ff269f7180288f98ff1f68c3de1fc

**Comment by jodal** [comment]
Shouldn't this fix go into release-1.1?

**Comment by jodal** [comment]
Cherry-picked to release-1.1 in commit 92bb9b9b77e206d9dac1df3bd005afc289cdf8a5.
