### ISSUE TITLE
Update Raspberry Pi specific install instructions

### ISSUE THREAD

**Issue by kingosticks** [mopidy/mopidy#1326]
A Debian Jessie version of Rasbian is now available and we should update our install instructions:
* Link to https://www.raspberrypi.org/documentation/installation/installing-images/README.md for images and how to write them
* ipv6 module already loaded
* Audio firmware should now be fine
* `output = alsasink` seems to now be redundant?
* Xbian and Xbmc workarounds are possibly now outdated.

**Comment by souravsingh** [comment]
I would like to work on the issue

**Comment by jodal** [comment]
Great :-)

**Comment by jodal** [comment]
As I was doing a fresh install of Jessie on a Raspberry Pi anyway I updated the howto at the same time. Improvements are still welcome.

**Comment by tkem** [comment]
Raspbmc has been replaced by OSMC [http://osmc.tv] which is based on Jessie. The Pi2 image is even based on Debian armhf and not on Raspbian, and `apt-get install mopidy` works out of the box, installing Mopidy v0.19, of course. Adding Mopidy's apt repository and upgrading worked also without problems, no `libtag` issues, etc.
So the Raspbmc section may be removed altogether, AFAICS.

**Comment by jodal** [comment]
@tkem Thanks! Removed now :-)
