### ISSUE TITLE
Return backend type in __model__ objects

### ISSUE THREAD

**Issue by LukeMcDonnell** [mopidy/mopidy#1327]
For web extension developers, it would be much easier to organize and present data if we knew which backend that specific tracks, albums, etc have originated from. Currently, this can be obtained by splicing the uri, but these operations can be cpu expensive in javascript when dealing with large lists such as search results or track lists. 

If the __model__ object for artists, albums, tracks, playlists and ref returned by the http extension listed which backend extension these objects originate from, we could save a lot of unnecessary client side processing.

**Comment by adamcik** [comment]
See #1108 and PR #1234 :-)

**Comment by LukeMcDonnell** [comment]
Damn. Sorry. I tried a few search terms but came up empty. Thanks :)
