### ISSUE TITLE
Core events not mapped in MPD handler

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1331]
Following events don't seem to be handled by the idle code

- [x] `seeked` - needs to be added
- [x] `playlists_loaded` - unsure
- [x] `track_playback_*` - probably okay without as `state_changed` handles this.

This manifests itself in develop by `idle` based players never getting seek events. This might have worked before gapless assuming it triggered a `state_changed` on seek.

**Comment by adamcik** [comment]
In a sense this is the other half of #312 with respect to getting ncmpcpp handling seek events.

**Comment by adamcik** [comment]
Fixed by #1347

**Comment by jodal** [comment]
Nothing here that needs to be backported to 1.1.2?

**Comment by adamcik** [comment]
Maybe the seek one, other than that no.

**Comment by jodal** [comment]
I cherry-picked 19daa89e15efa64cc128e742f6f8d3426f1adb0b to 22ec9d906032c6341dd290f8d400c4234c9ee0dd, so this is complete then.
