### ISSUE TITLE
No documentation for ExtensionConfigSchema

### ISSUE THREAD

**Issue by tkem** [mopidy/mopidy#1332]
I recently discovered that the link to `ExtensionConfigSchema`'s documentation is broken:
https://mopidy.readthedocs.org/en/latest/api/ext/#mopidy.ext.Extension.get_config_schema

AFAICS, all of `mopidy.config` is missing from the API docs, maybe since some of this is internal or not yet deemed production-ready. If so, maybe `ExtensionConfigSchema` can be moved to `mopidy.ext`? Or is thus just an oversight?

**Comment by tkem** [comment]
My bad, completely missed the `mopidy.config` section. Still, no `ExtensionConfigSchema`.

**Comment by tkem** [comment]
So, after becoming utterly confused and reading the source several times, I guess it's just a mistake in the doc comment, since there apparently is no `mopidy.config.schema.ExtensionConfigSchema` ;-)

**Comment by jodal** [comment]
Thanks!
