### ISSUE TITLE
Scan for local media while using systemd

### ISSUE THREAD

**Issue by poisonby** [mopidy/mopidy#1336]
Is this possible? If so, how?

I was forced to use the config file located at `/etc/mopidy/mopidy.config` when starting the service using `systemctl start mopidy` because I couldn't get it to use my local config file (that doesn't really matter though).

I've tried to send a `local scan` command to the service using `systemd-run` but it complains about errors in the configuration file (I assume it's not using `/etc/mopidy/mopidy.config` for some reason). There aren't any errors in the configuration file it's supposed to use.

I'm not sure if I'm even supposed to use `systemd-run`, but I assumed it was something similar to `service mopidy local scan` for other distributions.

I'm using Arch Linux and the mopidy version is 1.1.1.

**Comment by kingosticks** [comment]
System services use system config, have a read of https://docs.mopidy.com/en/latest/debian/#differences-when-running-as-a-system-service if you have not already done so. That page also documents the use of mopidyctl and should answer your question. 

This issue tracker is just for bugs and user questions belong at http://discuss.mopidy.com so if you have any more problems please make a post there. Thanks.
