### ISSUE TITLE
Empty Track URI can cause crash

### ISSUE THREAD

**Issue by blueyed** [mopidy/mopidy#1340]
I've seen an issue where using an empty file URI (as `file: `) would crash ncmpcpp: http://bugs.musicpd.org/view.php?id=4468

I could imagine several ways to prevent this, e.g. by not returning lists with empty uris in `lsinfo`.
Another possibility might be to have something like `blank=False` for URI attributes in Track classes, but that's not so straight-forward (but I've some patch in this regard already).

The track comes from mopidy-soundcloud, where this should be fixed additionally, too.

What do you think?

**Comment by jodal** [comment]
I don't think there's any valid use case for a track without an URI, so I'm +1 to filtering out any tracks without an URI. We could filter out these tracks in core, but as this is really a bug in Mopidy-SoundCloud combined with a bad fallback value in `mopidy/mpd/translator.py:38` I propose to fix Mopidy-SoundCloud and the `track_to_mpd_format()` method.

**Comment by adamcik** [comment]
Are we somehow ending up with an uri of `file:` as in `track.uri = 'file:'` or do you mean in the MPD protocol sense?

**Comment by blueyed** [comment]
`.uri` is empty, and results in `file: ` then.

**Comment by jodal** [comment]
I consider this fixed by the combination of #1343 (MPD), #1381 (core) and mopidy/mopidy-soundcloud#62.
