### ISSUE TITLE
History not updated when doing next/previous in "paused" state

### ISSUE THREAD

**Issue by jcass77** [mopidy/mopidy#1352]
I think this is related to https://github.com/mopidy/mopidy/issues/1177. 

When the user skips to the next / previous track while in 'paused' state the new track being changed to is never added to the history.

**Comment by adamcik** [comment]
What version was this tested against?

**Comment by jcass77** [comment]
1.1.1 - I know a lot of this will change in the new gapless playback, but I'll try to submit a PR with more details in case you would consider a bug fix release in the interim.

**Comment by adamcik** [comment]
Yeah, we are planing a 1.1.2, so we can probably include the fix there. And I see you put in a regression test which to me is the more interesting bit for develop :-)

**Comment by jodal** [comment]
Fixed by PR #1353.
