### ISSUE TITLE
Unplayable tracks are not consumed in consume mode

### ISSUE THREAD

**Issue by jcass77** [mopidy/mopidy#1358]
Unplayable tracks should be removed from the tracklist when consume mode is turned on, just like regular playable tracks.

When consume mode is turned on, tracks are removed from the tracklist as they are played: https://github.com/mopidy/mopidy/blob/9cd43cf79a122919b6a8b30782d262bdc384841c/mopidy/core/tracklist.py#L626-L631

However if the track is not playable it will simply be logged and left in the tracklist: https://github.com/mopidy/mopidy/blob/9cd43cf79a122919b6a8b30782d262bdc384841c/mopidy/core/tracklist.py#L620-L624

**Comment by jcass77** [comment]
This may not be a valid issue - see https://github.com/mopidy/mopidy/pull/1359

**Comment by jodal** [comment]
Then let's close this and work on merging #1359 :-)
