### ISSUE TITLE
[solved] No Music more on Raspberry

### ISSUE THREAD

**Issue by Baebeca** [mopidy/mopidy#1375]
Since some days i recieve no music in the audiojack on my raspberry.
I load a Spotify list and click play

The Logfile says:

2015-12-27 17:10:36,610 WARNING [2277:Audio-2] py.warnings: /usr/lib/python2.7/dist-packages/mopidy/audio/actor.py:714: Warning: /usr/src/packages/BUILD/glib2.0-2.40.0/./gobject/gsignal.c:2580: instance '0x1af7b98' has no handler with id '31'
  result = self._playbin.set_state(state)

2015-12-27 17:10:37,176 WARNING [2277:MainThread] mopidy.audio.gst: Element doesn't implement handling of this stream. Please file a bug.

any ideas?

**Comment by emilithe** [comment]
I'm getting similar warning then starting playing music from spotify - but music plays and sound is ok.
WARNING [1691:MainThread] mopidy.audio.gst: Element doesn't implement handling of this stream. Please file a bug.

I use audio output alsasink. Normally I use cirrus logic audio card module for output, but I've tested also output to raspberry's audiojack and it works ok.

my config: mopidy: 1.1.1; mopidy-spotify: 2.2.0; pyspotify: 2.0.5

**Comment by Baebeca** [comment]
thanks for test!
I got it! ;)

A Raspbeery PI Update has reset the default "audio out" to plugged HDMI-Touch Screen ;)

You can set the default audio-output to audio Jack with the following command
[code]
amixer cset numid=3 2
[/code]

reference: https://www.raspberrypi.org/documentation/configuration/audio-config.md

@maintainer
please close this issue as 3th party issue and solved this issue

thanks for your test!
