### ISSUE TITLE
Unplayable tracks are not processed correctly when 'paused'.

### ISSUE THREAD

**Issue by jcass77** [mopidy/mopidy#1378]
When the user performs stop->next->play, Mopidy will keep skipping over unplayable tracks until it finds one that can be played.

This also works if the user does pause->next->play.

However, when the sequence changes to pause->next->resume, Mopidy will try to resume playback on the unplayable track, which could produce unexpected results.

**Comment by jcass77** [comment]
...forgot to mention that this issue is only relevant for the release-1.1 branch. All three scenarios work correctly in 'develop'.

**Comment by jodal** [comment]
Fixed with merge of #1379.
