### ISSUE TITLE
loglevels/* has no effect on mopidy.log

### ISSUE THREAD

**Issue by jcass77** [mopidy/mopidy#1382]
The ```loglevels/*``` configuration [as currently documented](http://mopidy.readthedocs.org/en/develop/config/?highlight=loglevels#confval-loglevels/*) can probably be refined a little in the following respects:

1. the documentation should make it clear that the configuration parameters can only be used to **reduce** the log levels of specific modules, not increase it. In other words, one should set the root logger to the highest level, and then reduce everything except the module that you would like to debug to something like ```INFO```.

2. the configuration parameters only have an effect on what is being logged to the console. Now that most users (at least everybody using the Pi Musicbox) are probably running Mopidy as a service, it may make sense to also apply the settings to the output that goes to the ```mopidy.log``` file as well.

I can take a stab at creating a PR for this if there is general agreement on the above?

**Comment by adamcik** [comment]
1. I fully agree, and have often been annoyed by this. Not a 100% sure how to solve this in a sane way when we don't know the logger names up front. But it sounds like you want it to work the same way I think it should :-)

2. Sounds reasonable. Only catch I can think of is how this interacts with the log config file thing we still support as an escape hatch for doing whatever you want with the logging setup.

**Comment by kingosticks** [comment]
I'm all for both these enhancements.

**Comment by jcass77** [comment]
This [Mopidy discuss](https://discuss.mopidy.com/t/is-loglevels-still-working/1030/4) thread has reference.

If the long term goal is to do away with ``logging.conf`` and ``--save-debug-log`` and rely solely on stdout, then ``loglevels/*`` will actually be fine the way it is.

Should we park this issue in anticipation of transitioning to systemd and journals in some future release of Mopidy?

**Comment by jodal** [comment]
@adamcik Any comments after reading the discuss thread?

**Comment by jodal** [comment]
@jcass77 Assuming #1452 is implemented, the remaining part in this issue is just better docs for the loglevels config section?

**Comment by jcass77** [comment]
Yes, we can probably close this assuming the docs will be updated as part of #1452 anyway.
