### ISSUE TITLE
Mopidy does not close file handle to audio device

### ISSUE THREAD

**Issue by trallarn** [mopidy/mopidy#1384]
It would be nice if Mopidy closed the file handle to the audio device when it isn't used. In my case I control the power switch to my stereo depending on any open audio devices. Since mopidy doesn't close the file handle, I can't shut off the stereo.

This is how I check for audio device usage:

```
$ sudo fuser -v /dev/snd/pcmC0D0p 
                     USER        PID ACCESS COMMAND
/dev/snd/pcmC0D0p:   mopidy    21464 F.... mopidy
```

Running version 1.1.1-1 on raspberry pi, wheezy.

**Comment by jodal** [comment]
Do you know if you use PulseAudio or ALSA directly? You can try setting the `audio/sink` config to `pulsesink` to force it to be used. The default is `autoaudiosink` which will select whatever it finds available.

**Comment by trallarn** [comment]
I use alsa and the autoaudiosink.

**Comment by kingosticks** [comment]
Is then when you have paused playback or also when you have explicitly stopped playback? Last time I checked the audio device was released when stopped.

**Comment by trallarn** [comment]
That was a great question. I pause playback (press the pause button) and I cannot find a stop button in the interfaces that I have tested. 

I have tested with mopify and spotmop:

https://github.com/dirkgroenen/mopidy-mopify
https://github.com/jaedb/spotmop

Would it be a valid solution that pausing for a long enough amount of time (20 min?) caused a stop (enforced by mopidy), or should the stop button be added to the guis?

**Comment by trygveaa** [comment]
> Would it be a valid solution that pausing for a long enough amount of time (20 min?) caused a stop (enforced by mopidy)

I don't think so. A pause keeps the current track and position, while stop does not, so it shouldn't happen automatically. Maybe the audio device could be released after pausing for a long time though?

**Comment by tkem** [comment]
I think "stop" functionality simply belongs in a decent GUI. No need to for work-arounds if clients fail to provide that functionality. Note that clients that for some reason don't want to provide a dedicated stop-button can also implement timeouts and after a given period of "pausing" call `playback.stop()` themselves.

**Comment by trallarn** [comment]
I think the stop button is omitted in a lot of players since users doesn't use it. E.g. the spotify client doesn't have it. For a user, pause and stop does pretty much the same thing. 

In general, a program that doesn't use a resource should not claim it. When the playback is paused the player should not claim the audio device. This is exactly how the spotify client works: press pause and the audio device is released. I just tested it. This happens instantaneously, without delay.

**Comment by allquixotic** [comment]
There are two situations where I would want this to not be hard-coded into the core:

Case 1: mopidy-spotify being streamed via Icecast. In this case I want the stream to continue to send silence even if mopidy-spotify is not itself generating anything. Keeping the "device" open effectively means to just send empty frames of silence. 

Case 2: Some users' sound cards have a hardware issue, that I don't *think* can be worked-around in software, where the act of starting or stopping playback causes an audible (sometimes loud and jarring) "pop". I think this is due to bad electrical design of the 3.5mm port, but I had this on three laptops I've owned, one as recently as 2013. These users would want their ALSA device always-open unless they have an urgent need to conserve battery life.

I think this should be configurable somehow, or at least have different backends handle it differently by default and have some kind of user override.

**Comment by adamcik** [comment]
As other people have covered, paused keeps the device open while stop releases all audio related resources. This is mostly a function of how GStreamer works. To "fix" this would mean spending a lot of time and effort working against GStreamer, which is likely more trouble than it's worth. As such I consider it unlikely that this will change.

**Comment by kingosticks** [comment]
You might also be able to come up with some cron script that regularly checks the current status against a saved on and fires off a stop command if it *appears* to remain paused for a certain period.

**Comment by trallarn** [comment]
Good idea. Do you know how I can retrieve the playback status from bash?

**Comment by trygveaa** [comment]
For example:

```
$ echo status | nc localhost 6600 | grep state
state: play
```

If you want to be fancy, and don't poll all the time, you may want to look into [mpds idle command](https://docs.mopidy.com/en/latest/modules/mpd/#mopidy.mpd.protocol.status.idle) or [websockets](https://docs.mopidy.com/en/latest/api/http/#websocket-api).

**Comment by kingosticks** [comment]
Or the top two output lines of `mpc status` would have everything you need.

**Comment by trallarn** [comment]
Thank you @trygveaa and @kingosticks. Checking status with cron and mpc and sending a stop command after a long pause works. It's a valid workaround of GStreamer and I think you have reasons not to change it @adamcik.

Thank you all for helping out in this issue and great work with Mopidy. It's an awesome software.
