### ISSUE TITLE
docs: models.Ref classmethods and constants missing

### ISSUE THREAD

**Issue by tkem** [mopidy/mopidy#1385]
Looking at http://mopidy.readthedocs.org/en/latest/api/models/#mopidy.models.Ref, I just realised that factory methods (`Ref.album`, `Ref.artist`, etc.) and the type constants (`Ref,ALBUM`, `Ref.ARTISTS`, etc.) seem to be missing.

**Comment by jodal** [comment]
Fixed in release-1.1 branch.
