### ISSUE TITLE
Spotify track control: "about-to-finish in actor, aborting to avoid deadlock"

### ISSUE THREAD

**Issue by happyleavesaoc** [mopidy/mopidy#1394]
Hi, I believe this is a known issue, but reporting it here for the record.

When switching Spotify tracks, or (sometimes?) while hitting play/pause, you'll get this error message in the log:

```
ERROR    about-to-finish in actor, aborting to avoid deadlock.
```

I'm testing with `develop`@https://github.com/mopidy/mopidy/commit/aa9e806230dc2d144b1b63fb454f344407245289

**Comment by timothylhuillier** [comment]
I have the same things.

**Comment by adamcik** [comment]
Could you please retest this with develop at 3429487f701e5eb9ea53a0ebee1ea2779b595e1f or later?

**Comment by happyleavesaoc** [comment]
`mopidy-spotify` doesn't appear to be compatible yet.

**Comment by trygveaa** [comment]
@happyleavesaoc: You can use this branch of Mopidy-Spotify: https://github.com/jodal/mopidy-spotify/tree/feature/gst1

**Comment by trygveaa** [comment]
Now I could consistently reproduce this with Mopidy and Mopidy-Spotify with the latest code before gst1, by playing a Spotify track and changing to a non-Spotify track.

I've been playing around quite a bit with Mopidy and Mopidy-Spotify using gst1 this week, and have not been able to reproduce this with that, so it seems like it has been fixed.

**Comment by jodal** [comment]
OK. Assuming this is fixed. Closing until I hear otherwise.

**Comment by happyleavesaoc** [comment]
Hi, sorry it took me awhile to test, but I can also confirm that it works now! Thanks guys.
