### ISSUE TITLE
Rdio support

### ISSUE THREAD

**Issue by kelly** [mopidy/mopidy#140]
http://developer.rdio.com/

**Comment by nklmilojevic** [comment]
Any news about Rdio support?

**Comment by adamcik** [comment]
As far as I know no one has released anything, see https://discuss.mopidy.com/t/supporting-new-streaming-services-and-other-music-sources/22 for some general info about what is needed to add new services.

**Comment by dddanmar** [comment]
Rdio is shutting down, it might pay to just close this issue:
http://www.theverge.com/2015/11/16/9746220/pandora-to-acquire-key-parts-of-rdio

**Comment by jodal** [comment]
Rdio is indeed shutting down. However, this issue has been closed for three years already ;-)
