### ISSUE TITLE
tl_track info not included in 'track_playback_ended' event

### ISSUE THREAD

**Issue by jcass77** [mopidy/mopidy#1402]
When ``consume`` mode is enabled, the ``track_playback_ended`` event that is emitted does not include the ``tl_track`` information as expected.

This is due to the fact that the track is marked as having been played, and removed from the tracklist, by the time that the event is triggered.

**Comment by jodal** [comment]
Fixed by PR #1403.

Next time, include "Fixes #1402" in one of the commit messages, and the bug will automatically be closed when the PR is merged.

Also, could you update the changelog? I forgot to think about that before merging.
