### ISSUE TITLE
Stop start of audio when moving to the next track?

### ISSUE THREAD

**Issue by hdijkema** [mopidy/mopidy#1421]
I'm experiencing clicks on my stereo when a track ends and a new one begins. In short sequence when listening to local music. The interval gets between the 'off-click' and the 'on-click' gets longer when using Spotify.

**Comment by jodal** [comment]
We've already landed gapless playback support in the develop branch which will become Mopidy 1.2 soon. That'll probably fix this. Feel free to test using develop, so we can close this.

**Comment by hdijkema** [comment]
Can I test develop using a package (debian)?

2016-02-02 22:36 GMT+01:00 Stein Magnus Jodal <notifications@github.com>:

**Comment by jodal** [comment]
No, you must git clone and install from source or use `pip install https://github.com/mopidy/mopidy/archive/develop.zip`. If you're not comfortable with that, it might be better to just wait for the next release and Debian package update.

**Comment by hdijkema** [comment]
Oke, Then I'd probably first deinstall the regular debian mopidy and 
then install via pip?

Op 3-2-2016 om 09:38 schreef Stein Magnus Jodal:
>
> No, you must git clone and install from source or use |pip install 
> https://github.com/mopidy/mopidy/archive/develop.zip|. If you're not 
> comfortable with that, it might be better to just wait for the next 
> release and Debian package update.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mopidy/mopidy/issues/1421#issuecomment-179091774>.
>

-- 
Hans Dijkema
Weerdslag 64
7206BT Zutphen

tel. 06 4639 0827
email: hans@dykema.nl <mailto:hans@dykema.nl>

**Comment by jodal** [comment]
No, keep the Debian install. The first few sections of https://docs.mopidy.com/en/latest/devenv/ should be helpful to you.

**Comment by adamcik** [comment]
We are releasing 2.0 with gapless today, please give this a go. I'm closing this now, but if it's still an issue let us know.
