### ISSUE TITLE
Make sure about to change skips unplayable tracks

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1425]
This is one of the outstanding tasks for the gapless changes. It will probably end up being intertwined with #1306 as next will essentially be handled by sending an EOS.

**Comment by jodal** [comment]
@adamcik You say this will be intertwined with #1306, but it is currently planned for v2.1?

**Comment by adamcik** [comment]
Basically this is just stealing something along the lines of https://github.com/mopidy/mopidy/blob/develop/mopidy/core/playback.py#L287-L296 and adding a test.

**Comment by adamcik** [comment]
As for #1306, at that point the code we are stealing from `next` and the equivalent code in `previous` goes away. And all cases need to be handled in this one place. But that is not in scope for this fix. Just stealing the `next` code and using `eot_track` instead of `next_track` should be enough.

**Comment by jodal** [comment]
Fixed by PR #1440.
