### ISSUE TITLE
mopidy freeze while importing Gst

### ISSUE THREAD

**Issue by dublok** [mopidy/mopidy#1427]
I think it is an issue with my Ubuntu 14.04 installation or the virtualenv environment. Maybe I have to install something.

After the merge to 4e39f09 (and current develop b3f8460a940) mopidy does not start anymore. Seems to be the port to gst 1.0.
```
jens@2014Ubuntu:~$ workon mopidy
(mopidy)jens@2014Ubuntu:~/mopidy-dev$ mopidy
/usr/lib/python2.7/dist-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python2.7/dist-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python2.7/dist-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  import gobject._gobject
/usr/lib/python2.7/dist-packages/gst-0.10/gst/__init__.py:193: Warning: cannot register existing type 'GstObject'
  from _gst import *
/usr/lib/python2.7/dist-packages/gst-0.10/gst/__init__.py:193: Warning: g_once_init_leave: assertion 'result != 0' failed
  from _gst import *
/usr/lib/python2.7/dist-packages/gst-0.10/gst/__init__.py:193: Warning: g_type_register_static: assertion 'parent_type > 0' failed
  from _gst import *
/usr/lib/python2.7/dist-packages/gst-0.10/gst/__init__.py:193: Warning: interface type 'GstImplementsInterface' or prerequisite type '<invalid>' invalid
  from _gst import *
```
mopidy is blocked there. I have to 'killall -9 mopidy' to stop it.

**Comment by jodal** [comment]
From the stack trace it looks like gst-0.10 is used.

We're both telling `gi` that we require GStreamer compatible with 1.0 at https://github.com/mopidy/mopidy/blob/develop/mopidy/internal/gi.py#L9 and we do a version check ourselves to require GStreamer >= 1.2 at https://github.com/mopidy/mopidy/blob/develop/mopidy/internal/gi.py#L28-L33. Thus you're probably experiencing a hang before you get to the version checks that would have told you what the problem was.

Can you try installing the GStreamer 1.0 packages? Ref https://docs.mopidy.com/en/develop/installation/source/:

```
sudo apt-get install python-gst-1.0 gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-tools
```

**Comment by dublok** [comment]
All these packages are already installed. An update installation did not fix the issue.

**Comment by dublok** [comment]
After deinstallation of `python-gst0.10` I got an exception with pointed to the real cause.
In one with cookiecutter generated extensions are the following lines:
``` 
# TODO: Remove entirely if you don't register GStreamer elements below
import pygst
pygst.require('0.10')
import gst
import gobject
```
Not importing gst solves the issue.
