### ISSUE TITLE
Spotify error on RPI 2

### ISSUE THREAD

**Issue by loicfavory** [mopidy/mopidy#1429]
I try to install mopidy with mopidy-spotify, but I have this error : 

> $ mopidy
> INFO     Starting Mopidy 1.1.2
> INFO     Loading config from builtin defaults
> INFO     Loading config from /home/osmc/.config/mopidy/mopidy.conf
> INFO     Loading config from command line options
> INFO     Enabled extensions: mopify, spotify, mpd, http, stream, m3u, softwaremixer, file
> INFO     Disabled extensions: local
> WARNING  Found local configuration errors, the extension has been automatically disabled:
> WARNING    local/media_dir must be set.
> WARNING  Please fix the extension configuration errors or disable the extensions to silence these messages.
> ERROR    Extension spotify failed during setup, this might have left the registry in a bad state.
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/mopidy/__main__.py", line 145, in main
>     extension.setup(registry)
>   File "/usr/local/lib/python2.7/dist-packages/mopidy_spotify/__init__.py", line 49, in setup
>     from mopidy_spotify.backend import SpotifyBackend
>   File "/usr/local/lib/python2.7/dist-packages/mopidy_spotify/backend.py", line 13, in <module>
>     from mopidy_spotify import Extension, library, playback, playlists
>   File "/usr/local/lib/python2.7/dist-packages/mopidy_spotify/library.py", line 8, in <module>
>     from mopidy_spotify import browse, distinct, images, lookup, search, utils
>   File "/usr/local/lib/python2.7/dist-packages/mopidy_spotify/browse.py", line 27, in <module>
>     'albums': spotify.ToplistType.ALBUMS,
> AttributeError: 'module' object has no attribute 'ToplistType'
>

**Comment by trygveaa** [comment]
This is probably caused by using Mopidy-Spotify 2.x together with pyspotify 1.x. This is not supported, it requires pyspotify 2.x as stated by the dependencies.

Can you print the output of `mopidy deps`?

**Comment by loicfavory** [comment]
Thanks for your help, I made it working by uninstalling & reinstalling pyspotify
