### ISSUE TITLE
Gst.NotInitialized exception on startup

### ISSUE THREAD

**Issue by j0s** [mopidy/mopidy#1432]
When starting mopidy built from git develop branch, starting mopidy failed with `gi.overrides.Gst.NotInitialized: Please call Gst.init(argv) before using GStreamer`. It seems the call to `Gst.is_initialized()` before `Gst.init()` in `mopidy/internal/gi.py` is causing it. When I changed it to call `Gst.init([])` without checking if it's already initialized, the problem went away. `Gst.init()` also needed an argv-array as argument in my version, so I also passed an empty list as argument. Don't know if these changes are compatible with earlier versions of gst-python.

I'm on Archlinux, running gstreamer 1.6.3 and gst-python 1.6.2.

**Comment by trygveaa** [comment]
I can reproduce this on Arch after installing `gst-python2` (it did not happen without that). The exception is thrown when calling `Gst.is_initialized()`. I also get some warnings when I run `from gi.repository import GLib, GObject, Gst, GstPbutils` that I didn't get before installing `gst-python2`.

```
>>> import gi
>>> gi.require_version('Gst', '1.0')
>>> gi.require_version('GstPbutils', '1.0')
>>> from gi.repository import GLib, GObject, Gst, GstPbutils
/usr/lib/python2.7/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python2.7/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python2.7/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
>>> Gst.is_initialized()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/gi/overrides/Gst.py", line 347, in fake_method
    raise NotInitialized("Please call Gst.init(argv) before using GStreamer")
gi.overrides.Gst.NotInitialized: Please call Gst.init(argv) before using GStreamer
```

**Comment by trygveaa** [comment]
The not initialized check was introduced in version 1.5.2 of gst-python, released 2015-06-24, see https://cgit.freedesktop.org/gstreamer/gst-python/commit/?id=a4bbd96af18a2065995610e824b9a0165632a56e and https://cgit.freedesktop.org/gstreamer/gst-python/commit/?id=6b32ccbbb250f7516f36a1ea82c0fbba8925af09.

> gi/overrides/Gst.py:
> overrides: Disable all GStreamer APIs until Gst has been initialized
> Summary:
> And throw an exception if the user tries to call any Gst API without
> initializing gst.
> 
> https://bugzilla.gnome.org/show_bug.cgi?id=747555

Did they forget about `Gst.is_initialized()` and that `Gst.init()` doesn't require arguments when they added that?
