### ISSUE TITLE
Mopidy 2.0 does not run on raspbian

### ISSUE THREAD

**Issue by dublok** [mopidy/mopidy#1434]
On a Raspberry PI I had to install additional packets.
```
sudo apt-get install gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0
```
If the issue occurs only on my system, then close it.
Else, please check:
- installation instructions
- installation dependencies

**Comment by HalfEatenPie** [comment]
You need more information.

Which OS Distribution are you using?  

Are you using Rasbian?  When was the image made?

**Comment by dublok** [comment]
It's a up-to-date raspbian. Installed ~3 month ago with a yesterdays dist-upgrade.

**Comment by jodal** [comment]
I think it may be the case that the deps we list are sufficient if you system installs Suggested packages, but not enough when it installs just Depends. I'll have a closer look later today.

**Comment by jodal** [comment]
Our current docs includes the following Debian packages:

- python-gst-1.0
- gstreamer1.0-plugins-good
- gstreamer1.0-plugins-ugly
- gstreamer1.0-tools

In both Ubuntu 15.10, 16.04 and Debian stretch/testing, python-gst-1.0 "Depend" on both gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0, but this is not the case on Debian jessie, Ubuntu 14.04 or Ubuntu 15.04.
