### ISSUE TITLE
Can' stop mopidy

### ISSUE THREAD

**Issue by dublok** [mopidy/mopidy#1435]
V2.0 c4da2c2:
A  `sudo service mopidy stop` does not stop mopidy. At last it stops after a timeout.

Enabled extensions: mpd, dleyna, http, stream, alsamixer, m3u, local-images, softwaremixer, file, musicbox_webclient, tidal, local, local-sqlite

Target: RPi 2, raspbian

[Edit: removed the `<ctrl-c>`]

**Comment by kingosticks** [comment]
This report needs a lot more data. At the very least, the full output of `mopidy deps` and a log file.

**Comment by dublok** [comment]
[mopidy_deps.txt](https://github.com/mopidy/mopidy/files/123611/mopidy_deps.txt)
[log_short.txt](https://github.com/mopidy/mopidy/files/123639/log_short.txt)

A detailed log will follow.

Anything else?

**Comment by adamcik** [comment]
https://docs.mopidy.com/en/latest/troubleshooting/#debugging-deadlocks might be of use.

**Comment by dublok** [comment]
Thanks.
[pkill_sigusr.txt](https://github.com/mopidy/mopidy/files/123663/pkill_sigusr.txt)

**Comment by dublok** [comment]
The error occurs only if mopidy is running as server.
How do I enable detailed debug output when running as server?

**Comment by dublok** [comment]
To stop a running mopidy service a `SIGTERM` is send to the process.
Mopidy does not stop, because the `SIGTERM` is not handled correctly:

```
INFO     Got SIGTERM signal
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py", line 702, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
KeyboardInterrupt
<< still running here >>
```

To reproduce:
- start mopidy
- from a different shell: `killall mopidy`

**Comment by trygveaa** [comment]
Ah, SIGTERM doesn't work for me either. This is a regression from version 1.1.2.

**Comment by dublok** [comment]
`thread.interrupt_main()` seems not to work anymore.
Using `os.kill(os.getpid(), signal.SIGINT)` instead stops mopidy.

I could prepare a PR if the solution is OK.

```
def exit_process():
    logger.debug('Interrupting main...')
    os.kill(os.getpid(), signal.SIGINT)
    logger.debug('Interrupted main')
```
