### ISSUE TITLE
enhancement: Alarm clock api request

### ISSUE THREAD

**Issue by szuniverse** [mopidy/mopidy#1448]
Hi.
Do you plan to implement "Alarm clock" feature?
I think it would be great if somehow the client set an alarm event via HTTP-JSON. Send the trackID and time to mopidy or something like that.

What do you think? Will be available this feature in the near feature?

**Comment by trygveaa** [comment]
Take a look at https://github.com/DavisNT/mopidy-alarmclock. That might be what your after.

**Comment by adamcik** [comment]
As with #956 this is not something we intend to solve in mopidy itself. Additions like #1100 or the extension which Trygve linked to is the way to go.

**Comment by szuniverse** [comment]
@trygveaa  thanks but the only way to set up the alarm clock is to edit the mopidy.conf file. And I would like to set it up via JSON from the client side.

**Comment by trygveaa** [comment]
@szuniverse: You don't have to set it in the mopidy.conf file. You can set an alarm through the HTTP interface, by default http://localhost:6680/alarmclock/.
