### ISSUE TITLE
Endless loop if no playable track is in the tracklist.

### ISSUE THREAD

**Issue by dublok** [mopidy/mopidy#1454]
During development of PR #1376 I run into this issue and fixed it in #1376.
I think this issue is independent of #1376.

I revert the fix in #1376 and create a new pull request with the fix.

**Comment by dublok** [comment]
Sorry, with 75a365ea0d10eadc0a1f350ad28e03ceb912e073 the issue it is not reproducible.

**Comment by dublok** [comment]
It is reprocible if `consume` is `false`.

**Comment by jodal** [comment]
This sounds quite related to #1221.

**Comment by jodal** [comment]
Fixed by PR #1454.
