### ISSUE TITLE
Position freezes after seek in FLAC via HTTP

### ISSUE THREAD

**Issue by dublok** [mopidy/mopidy#1462]
Mopidy 2.0 9c05cc8d0581a5b4edfdf9ce069c8b358701c4d7. To reproduce:

- play FLAC audio from UPnP server (or internet)
- seek
- -> position freezes

Problem: core.PlaybackController._on_position_changed is called with 0 instead of the expected position 171150, so seek never finishes. 

https://github.com/mopidy/mopidy/blob/develop/mopidy/core/playback.py#L233
```
INFO     seek pending_pos=171150
INFO     Audio event: position_changed(position=0L)
INFO     _on_position_changed pos=0 pen_pos=171150
```

**Comment by adamcik** [comment]
https://botbot.me/freenode/mopidy/2016-02-08/?msg=59602124 and onward has a suggestion for a possibly better way of handling seek detection. Problem with the current approach is that we listen for pad events. Which means that we catch the seek on it's way into the last element, and we might have a race.
