### ISSUE TITLE
Remove deprecated Model APIs

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#1464]
The following deprecated APIs in `mopidy.models` should be removed:
- `ImmutableObject.copy()` method
- `Album.images` attribute

Before removing the deprecated APIs, we should review both [backends](https://github.com/jodal/mopidy-backend-api-users) and [frontends](https://github.com/jodal/mopidy-core-api-users) and open issues or pull requests on those still using these.

**Comment by tkem** [comment]
Just note that when removing `Album.images` the default implementation of `LibraryProvider.get_images()` should probably changed to just return an empty `dict`.
