### ISSUE TITLE
Remove deprecated Audio APIs

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#1465]
We should remove all deprecated audio APIs:
- [ ] `Audio.emit_end_of_stream()` method

**Comment by sticken88** [comment]
Should we just remove it or replace it with something else/similar?

**Comment by kingosticks** [comment]
This is really just a reminder to remove these.  Anything marked as deprecated for removal in the next major version should already be handled in some other way (or no longer required at all) in the current version. 

In the case of `Audio.emit_end_of_stream()` the changelog has the details:
> Deprecated mopidy.audio.Audio.emit_end_of_stream(). Pass a None buffer to mopidy.audio.Audio.emit_data() to end the stream. This should only affect Mopidy-Spotify.
