### ISSUE TITLE
Scanner: Date tags not extracted since Mopidy 2.0

### ISSUE THREAD

**Issue by fatg3erman** [mopidy/mopidy#1471]
Running on ubuntu, installed from the PPA. I've just added a few new local tracks (both MP3 and FLAC) and scanned them using mopidy local scan but I don't see the Date information for any of the tracks.

Eg by using mpd command 'lsinfo "directory/with/new/tracks"', I get all the usual stuff except for Date. If I do lsinfo on a directory I had scanned prior to the upgrade to mopidy 2.0, I still see the Date information so it looks as if the scanner is broken.

**Comment by adamcik** [comment]
What local library provider are you using? I could be that one of them isn't handling jodal's change from datetime objects to strings?

**Comment by fatg3erman** [comment]
I'm using local-JSON

**Comment by freddez** [comment]
I don't know if it is the same problem, but I have no results if I try to browse by relase year in mopidy-local-sqlite

**Comment by teake** [comment]
I'm having the same issue as @freddez. The scanner doesn't pick up the date of the tracks, whiles it does sees the date of the albums. Here's a bit of sample output from `mopidy -v local scan`:

```
DEBUG    2016-06-13 07:22:12,887 [11631:MainThread] mopidy_local_sqlite.schema
  SQLite insert statement: INSERT OR REPLACE INTO album (images, name, artists, date, musicbrainz_id, uri, num_discs, num_tracks) VALUES (?, ?, ?, ?, ?, ?, ?, ?) [None, u'Neon Golden', 'local:artist:md5:c51bd80a9670257b4a9015a2bef9c67b', u'2002-02-04', '0e9c6c79-02b7-4111-8c86-e1b173572113', 'local:album:mbid:0e9c6c79-02b7-4111-8c86-e1b173572113', 1L, 10L]
DEBUG    2016-06-13 07:22:12,889 [11631:MainThread] mopidy_local_sqlite.schema
  SQLite insert statement: INSERT OR REPLACE INTO track (comment, composers, disc_no, genre, last_modified, artists, date, bitrate, album, name, performers, uri, length, track_no, musicbrainz_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [None, None, 1L, None, 1362496253000L, 'local:artist:md5:c51bd80a9670257b4a9015a2bef9c67b', None, None, 'local:album:mbid:0e9c6c79-02b7-4111-8c86-e1b173572113', u"One Step Inside Doesn't Mean You Understand", None, 'local:track:Notwist%2C%20The/2002%20Neon%20Golden/01%20One%20Step%20Inside%20Doesn%27t%20Mean%20You%20Understand.flac', 195626L, 1L, '2d1b31d1-e5ce-4209-ad99-38c83f6c063f']
```

I'm on Mopidy  2.0.0 with mopidy-local-sqlite 1.0.0.
