### ISSUE TITLE
Add get_images support for playlists

### ISSUE THREAD

**Issue by pft** [mopidy/mopidy#1478]
E.g. spotify playlists may have images associated. I don't know about other backends.

They cannot currently be retrieved with `get_images()`. I have no idea how difficult it would be to add support though. Parsing the URI already errors out.

```
ValueError: Could not parse u'spotify:user:accountname:playlist:2BCH....nws1' as a Spotify URI
```

**Comment by adamcik** [comment]
This isn't a mopidy issue, please file this against mopidy-spotify. We just pass whatever URL you give use through to the backends.

**Comment by pft** [comment]
Thanks for the pointer. I have refiled the issue:

https://github.com/mopidy/mopidy-spotify/issues/100
