### ISSUE TITLE
can't play rtsp stream

### ISSUE THREAD

**Issue by mczerski** [mopidy/mopidy#1479]
Hi,

I'm using version 2.0 and I can't play rtsp stream, this is log output:

```
WARNING  Download of 'rtsp://rozpruwacz.local:5004/test' failed due to unsupported schema
INFO     Unwrapping stream from URI (rtsp://rozpruwacz.local:5004/test) failed: error downloading URI rtsp://rozpruwacz.local:5004/test
WARNING  Track is not playable: rtsp://rozpruwacz.local:5004/test
```

I norrowed it down to the mopidy.audio.scan.Scanner class.
if I type:

```
python /usr/lib/python2.7/dist-packages/mopidy/audio/scan.py rtsp://rozpruwacz.local:5004/test
```

I get:

```
gst-stream-error-quark: Internal data flow error. (1)
```

You can reproduce it with some accessible link, e.g.:
python /usr/lib/python2.7/dist-packages/mopidy/audio/scan.py rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov

**Comment by adamcik** [comment]
I can confirm testing with:

```
$ python mopidy/audio/scan.py rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov: Internal data flow error.
```

**Comment by adamcik** [comment]
Though looking at 

```
gst-discoverer-1.0 rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov         
Analyzing rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
Done discovering rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov

Topology:
  unknown: application/x-rtp
    video: H.264

Properties:
  Duration: 0:09:56.480000000
  Seekable: yes
```

It seems my GStreamer install is only finding the movie part of it. Also `gst-play-1.0` play doesn't seem to like the URL. While VLC plays it just fine and also has sound. Might be an upstream issue :(

**Comment by adamcik** [comment]
Figured out what is going on here, `rtspsrc` has `SOMETIMES` pads. Which in turn means that we have to handle pad added on the src and then attach typefind+decodebin on each of the pads it produces.

Have a working hack the gets this functioning now, but still needs some cleanup before I can create a PR.
