### ISSUE TITLE
Improve get_images() for stream and file backends

### ISSUE THREAD

**Issue by tkem** [mopidy/mopidy#1486]
AFAICS, both the `stream` and `file` backends rely on the default implementation of `get_images()`, which does a `lookup()` for every single URI and checks for `album.images` (which is deprecated, anyway).

This is unnecessarily inefficient, since these backends won't provide images, and scanning for metadata may take a rather long time.

So I'd suggest either
- changing the default `get_images()` implementation to return an empty `dict`, urging extensions to implement `get_images()` if they haven't done so already
  or
- add no-op `get_images()`  implementations for the `stream` and `file` backends specifically.

**Comment by adamcik** [comment]
We can probably check the mopidy-backend-api-users repo to see how many backends option one would effect. I suspect that for many of them it ends up being a noop as they probably don't support images any way.

**Comment by tkem** [comment]
Option no. 3, which I didn't dare to even hint at, would of course be actually implementing some sort of `get_images()` for streams and local files by means of a Tornado Web app or something like that... 

But I guess we'll reserve that for Mopidy v5.0 or so ;-)

**Comment by adamcik** [comment]
https://github.com/mopidy/mopidy/commit/ed046f1781f4f2ca4083b31940cdc7183e577f1f#diff-e241383f9bf6517fa189eef789749469R123 fixed this for `get_images`. So I think there is nothing left to do as the default behavior has been fixed to return nothing.
