### ISSUE TITLE
Set intelligable sink-input name for pulseaudio

### ISSUE THREAD

**Issue by joepvd** [mopidy/mopidy#1488]
When hooking up Mopidy directly up to pulseaudio, the reported application name in PulseAudio is `python2`. It would be nice to have the application name be set explicitly to "Mopidy" / user configurable string. 

When running Mopidy as a service under its own credentials and connecting to my user's pulseaudio session over TCP, the name becomes python2@127.0.0.1. Not sure if it is possible to get rid of the network part of the name, but it would be nice to have the option to mask that information. 

Concretely, this is about `application.name` under Properties after running the command `pactl list sink-inputs`.

**Comment by adamcik** [comment]
`output = pulsesink client-name="foobar"` should do the trick. Given that we currently just have generic output support I don't think we want to solve this in mopidy beyond the config I just suggested. If we add outputs as something extensions provide that would be the right place to solve it.

So closing as we can't do anything to really fix this.

**Comment by jodal** [comment]
We could try to import [setproctitle](https://pypi.python.org/pypi/setproctitle) and if it is available change the process name from `python`/`python2` to `mopidy`. That would be a bit easier for newbies looking for Mopidy in `ps`/`top`, or trying to kill Mopidy. It would probably also help with the default sink-input name in PulseAudio.

All that said, I don't want to add a dependency on `setproctitle`, so all of this would need to be optional.
