### ISSUE TITLE
Running Mopidy 2.0.0 fails

### ISSUE THREAD

**Issue by neeohw** [mopidy/mopidy#1490]
INFO     Starting Mopidy 2.0.0
INFO     Loading config from builtin defaults
INFO     Loading config from /etc/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mopify, spotify, mpd, alsamixer, http, moped, stream, mobile, m3u, softwaremixer, file, local
INFO     Disabled extensions: none
ERROR    Extension spotify failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy/__main__.py", line 121, in main
    extension.setup(registry)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_spotify/__init__.py", line 33, in setup
    from .backend import SpotifyBackend
  File "/usr/local/lib/python2.7/dist-packages/mopidy_spotify/backend.py", line 12, in <module>
    from mopidy_spotify.session_manager import SpotifySessionManager
  File "/usr/local/lib/python2.7/dist-packages/mopidy_spotify/session_manager.py", line 28, in <module>
    class SpotifySessionManager(process.BaseThread, PyspotifySessionManager):
AttributeError: 'module' object has no attribute 'BaseThread'

The version of pyspotify I installed is 1.9.1

Does someone have an idea on what may be the problem here?

**Comment by jodal** [comment]
You're using an old version of Mopidy-Spotify that uses an internal class in Mopidy that has been removed in recent versions. Upgrade to Mopidy-Spotify 3 for compatibility with Mopidy 2.

**Comment by neeohw** [comment]
It's because I had installed a newer version of libpyspotify of which mopidy then complained that is was too new. Didn't know that I had to update Mopidy-Spotify separately.

Thanks!
