### ISSUE TITLE
mopidy.js implementation in website

### ISSUE THREAD

**Issue by chises** [mopidy/mopidy#1497]
hi all,
thanks for this great program!
unfortunally i am stuck with the mopidy.(min.)js.
mopidy http is available at http://hostname:6680
i create a new webinterface with different Content and try to implement some simple mopidy checks at http://hostname
mopidy.js is downloaded from github, uploaded to http://hostname/inc/js/mopidy.js and available at the url
my current code

```
<script type="text/javascript" src="./inc/js/mopidy.js">
	var mopidy = new Mopidy({
			webSocketUrl: "ws://10.10.100.61:6680/mopidy/ws/",
			callingConvention: "by-position-or-by-name",
			console: true
		});
		mopidy.on(console.log.bind(console)); 
		mopidy.on("state:online", function () {
			mopidy.playback.next();
		});
</script>
```

i dont get any Output in JavaScript console or the next song is played. Webserver log is without Errors.

Can someone push right direction? Thanks!

**Comment by chises** [comment]
Solved.

**Comment by kingosticks** [comment]
How did you solve it (for the sake of anyone else who lands here)?
