### ISSUE TITLE
No sound from autoaudiosink

### ISSUE THREAD

**Issue by Mestelan** [mopidy/mopidy#1498]
Hello,

When setting in config:
```
[audio]
output = autoaudiosink
```
I can hear no sound from mopidy.
(Other apps can use the soundcard alright, with hearable volume)

I have tested that
`gst-launch-0.10 audiotestsrc ! autoaudiosink`
plays a beep alright.

mpc play causes this log in mopidy:

> WARNING  GStreamer warning: gst-resource-error-quark: Could not open audio device for playback. (6)
> WARNING  GStreamer warning: gst-stream-error-quark: No volume control found (3)

Could you suggest a way for me to investigate this?

Thank you.

**Comment by adamcik** [comment]
Is the user running mopidy in the audio group? The no volume control is a red herring, which is fixed in the next release.

**Comment by Mestelan** [comment]
`Is the user running mopidy in the audio group?`
Yes. I run mopidy as my regular user.

**Comment by Mestelan** [comment]
For the record, and in case it might help, I am writing this because I tried to change my config due to #1499

**Comment by jodal** [comment]
If you want to compare with Mopidy 2.0, you need to test with GStreamer 1.x, not 0.10:

```
gst-launch-1.0 audiotestsrc ! autoaudiosink
```

**Comment by Mestelan** [comment]
Thank you very much.
This command prints the log below, and plays no sound.
After gstreamer1.0-alsa, the sound plays OK

`gst-launch-1.0 audiotestsrc ! autoaudiosink`
> Setting pipeline to PAUSED ...
> Pipeline is PREROLLING ...
> WARNING: from element /GstPipeline:pipeline0/GstAutoAudioSink:autoaudiosink0: Jack server not found
> Additional debug info:
> gstjackaudiosink.c(357): gst_jack_ring_buffer_open_device (): /GstJackAudioSink:autoaudiosink0-actual-sink-jackaudio:
> Cannot connect to the Jack server (status 17)
> Pipeline is PREROLLED ...
> Setting pipeline to PLAYING ...
> New clock: GstSystemClock
> ^Chandling interrupt.
> Interrupt: Stopping pipeline ...
> Execution ended after 0:00:28.739734000
> Setting pipeline to PAUSED ...
> Setting pipeline to READY ...
> Setting pipeline to NULL ...
> Freeing pipeline ...


`[~/git_repos/main]% sudo aptitude install gstreamer1.0-alsa`
`
gst-launch-1.0 audiotestsrc ! autoaudiosink`
> Setting pipeline to PAUSED ...
> Pipeline is PREROLLING ...
> Pipeline is PREROLLED ...
> Setting pipeline to PLAYING ...
> New clock: GstAudioSinkClock
> ^Chandling interrupt.
> Interrupt: Stopping pipeline ...
> Execution ended after 0:00:01.217111298
> Setting pipeline to PAUSED ...
> Setting pipeline to READY ...
> Setting pipeline to NULL ...
> Freeing pipeline ...

Not sure why the first log mentions Jack server, but as for me, the problem is resolved.

Thanks for mopidy.

**Comment by jodal** [comment]
`jacksink` is often preferred by `autoaudiosink` when `alsasink` isn't present. Once you have `alsasink` that is used instead and the `jack` warning disappears.
