### ISSUE TITLE
Alsasink stopped working in 2.0.0

### ISSUE THREAD

**Issue by Mestelan** [mopidy/mopidy#1499]
Hello. 

I have in my config:
```
[audio]
output = alsasink
```

which stopped working as of 2.0.0-1 (Debian package).

> [~]% mopidy
> INFO     Starting Mopidy 2.0.0
> INFO     Loading config from builtin defaults
> INFO     Loading config from /home/anon/.config/mopidy/mopidy.conf
> INFO     Loading config from command line options
> INFO     Enabled extensions: mpd, alsamixer, stream, m3u, softwaremixer, file, local, local-sqlite
> INFO     Disabled extensions: spotify, http, soundcloud
> INFO     Starting Mopidy mixer: SoftwareMixer
> INFO     Starting Mopidy audio
> INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, LocalBackend
> ERROR    Failed to create audio output "alsasink": gst_parse_error: no element "alsasink" (1)
> INFO     Interrupted. Exiting...

Although, 
`
gst-launch-0.10 audiotestsrc ! alsasink`
plays a beep alright

Could you suggest a way for me to investigate this?

Thank you for attention.

**Comment by jodal** [comment]
Mopidy 2.0 changed from GStreamer 0.10 (which is quite old) to GStreamer 1.x. The proper command to test alsasink outside Mopidy is:

```
gst-launch-1.0 audiotestsrc ! alsasink
```

You probably need to install the package gstreamer1.0-alsa (Debian/Ubuntu), which is only "Recommended" by the mopidy Debian package thus might not be installed by default.

**Comment by Mestelan** [comment]
Thank you very much.

You are all correct, it works after installing gstreamer1.0-alsa.
Thanks for mopidy.
