### ISSUE TITLE
docs: mopidy.audio.Audio docs broken

### ISSUE THREAD

**Issue by tkem** [mopidy/mopidy#1500]
Starting with `release-2.0`: http://mopidy.readthedocs.org/en/release-2.0/api/audio/.

**Comment by adamcik** [comment]
Is `alias of <Mock object at 0x7fbb512530d0>` the problem you had in mind?

**Comment by tkem** [comment]
Yes. I guess I should be more explicit in my issue reports ;-)

**Comment by jodal** [comment]
This is also partly responsible for the mopidy package build not being fully reproducible in Debian, ref. https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/mopidy.html
