### ISSUE TITLE
error in play track

### ISSUE THREAD

**Issue by hadihabashi** [mopidy/mopidy#1503]
i run mopidy as service and use web extention but in any web client click on track 
not playing track and show in log file below error

2016-04-27 11:27:07,989 WARNING [31033:Audio-1] mopidy.audio.actor: Setting GStreamer state to GST_STATE_PLAYING failed
2016-04-27 11:27:07,989 ERROR [31033:MainThread] mopidy.audio.gst: GStreamer error: Could not initialize supporting library.
2016-04-27 11:27:07,990 WARNING [31033:Core-6] mopidy.core.tracklist: Track is not playable: local:track:Artist/Pallet/Shahre_Man_Bekhand/12-Pallett_Shahre_Man_Bekhand.mp3

**Comment by kingosticks** [comment]
As you probably have seen, an Internet search for that error message brings up pulseaudio related problems. Have you read and tried what's described at https://docs.mopidy.com/en/latest/service/#configure-pulseaudio 

Failing that, you should provide the output of `mopidy deps` and `mopidy config` as outlined at https://docs.mopidy.com/en/latest/troubleshooting/

**Comment by hadihabashi** [comment]
this problem fix bye install all gst
sudo apt-get install gst*

tnx kingostick

**Comment by hadihabashi** [comment]
but now i dont hear noting 
track start but not sound

**Comment by kingosticks** [comment]
Did you read the pulseaudio section? Please make sure you follow all the advice in my first post as there is not enough information here to help you.

**Comment by hadihabashi** [comment]
yes i change autoaudiosink  to 
output = pulsesink server=127.0.0.1

but after restart modipy my first error is comeback :(

ERROR [2304:MainThread] mopidy.audio.gst: GStreamer error: Failed to connect: Connection refused
2016-04-27 13:27:46,169 WARNING [2304:Audio-2] mopidy.audio.actor: Setting GStreamer state to GST_STATE_PLAYING failed
2016-04-27 13:27:46,170 WARNING [2304:Core-7] mopidy.core.tracklist: Track is not playable: local:track:Artist....

**Comment by hadihabashi** [comment]
i test by this command 
 gst-launch-1.0 audiotestsrc ! audioresample ! pulsesink

get error


Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstPulseSink:pulsesink0: Failed to connect: Access denied
Additional debug info:
pulsesink.c(591): gst_pulseringbuffer_open_device (): /GstPipeline:pipeline0/GstPulseSink:pulsesink0
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by ZenithDK** [comment]
As you have just discovered yourself, your issue is with pulseaudio and not with mopidy.
As we try to keep the bug tracker contain only issues that are with mopidy, please take this discussion to the discussion forums at https://discuss.mopidy.com/

**Comment by hadihabashi** [comment]
i install mopidy om vps and test output by audiosink or pulsesink 
in each case have some error in audiosink no hear any sound and in pulsesink error in pulseaudio that no sound card
do mipidy need dedicated server with audio device ?? or did not need to audio device ?

**Comment by kingosticks** [comment]
See https://github.com/mopidy/mopidy/issues/1504
