### ISSUE TITLE
dont hear any sounf

### ISSUE THREAD

**Issue by hadihabashi** [mopidy/mopidy#1504]
hi i try with pulssink or audiosink and after solve all error in mopidy but not hear sound 
in case pulssink error pulssink about soundcard

do mopidy need sound card?
i install on VPS and use it please help me

**Comment by kingosticks** [comment]
Please use https://discuss.mopidy.com/ for support questions (as stated in our issue template).

When you create your new post at https://discuss.mopidy.com/ please include more details about what you are trying to accomplish here and the output of `mopidy config`. Thanks.
