### ISSUE TITLE
ValueError from bad audio tags

### ISSUE THREAD

**Issue by jmsaaren** [mopidy/mopidy#1506]
audio/tags.py:

> def convert_taglist(taglist):
> ...
> date = datetime.date(
>                     value.get_year(), value.get_month(), value.get_day())

This raises a ValueError that is not catched when audio track has badly set year. 
I suggest that if the year exceeds datetime.MAXYEAR then use datetime.MAXYEAR or 0 as the audio itself is probably not broken.

**Comment by sticken88** [comment]
Could you please write the steps to reproduce it?

**Comment by palfrey** [comment]
I've just created a PR https://github.com/mopidy/mopidy/pull/1525 that reproduces this problem in a test and fixes it
