### ISSUE TITLE
Support AF_UNIX sockets for mpd

### ISSUE THREAD

**Issue by dondelelcaro** [mopidy/mopidy#1531]
It would be great if mopidy supported AF_UNIX style sockets for mpd instead of listening on localhost. [This is especially useful for configurations where mopidy is running as a user, and may have a conflict on localhost:6600.]

Something like the following would probably work (but there's probably a better, more general method.)

```
diff --git a/mopidy/internal/network.py b/mopidy/internal/network.py
index cefdf8e..ae5a87b 100644
--- a/mopidy/internal/network.py
+++ b/mopidy/internal/network.py
@@ -79,9 +79,14 @@ class Server(object):
         self.register_server_socket(self.server_socket.fileno())

     def create_server_socket(self, host, port):
-        sock = create_socket()
-        sock.setblocking(False)
-        sock.bind((host, port))
+        if (re.match(r'/',host):
+            sock = socket.socket(socket.AF_UNIX)
+            sock.setblocking(False)
+            sock.bind(host)
+        else:
+            sock = create_socket()
+            sock.setblocking(False)
+            sock.bind((host, port))
         sock.listen(1)
         return sock
```

**Comment by kingosticks** [comment]
Does this have an advantage over just using another port?

**Comment by dondelelcaro** [comment]
Yes, because a user can control sockets in directories they own; they have no control over what service gets spawned on a non-privileged port. It also means that only a user who can write to the socket can talk to mopidy, which is often useful.

(For me, it means that I don't have to worry if there's a system-wide mopidy running; my configuration will always "just work" because it uses MPD_HOST=~/var/mpd/socket.)

**Comment by dondelelcaro** [comment]
https://github.com/mopidy/mopidy/compare/develop...dondelelcaro:develop seems to work here; someone with better python-fu can probably make this more elegant than what I've done.

**Comment by dondelelcaro** [comment]
I think that checking the hostname parameter would be enough; I suggest not just limiting to `startswith('/')` so you could potentially do `hostname=~/var/mpd/socket `, but I think that `startswith('/') ` or startswith(`~`) would be work, or maybe just `os.path.expanduser(value).startswith('/')`?

**Comment by jradtilbrook** [comment]
I'm very keen on this functionality, but am new to mopidy. It looks like nothing has happened from this so far so I'd be willing to give it a go although I'll need to get up to speed on development within this project.  
Is it something you would consider accepting if I did do it?

**Comment by kingosticks** [comment]
Yes, certainly, the comments above still stand. 

If you have not already seen, there's lots of info to get started at https://docs.mopidy.com/en/latest/contributing/ and https://docs.mopidy.com/en/latest/devenv/. Feel free to ask any questions here, on IRC or at https://discuss.mopidy.com/.

**Comment by kingosticks** [comment]
Can we support this for http also? i.e. https://gist.github.com/superduper/5579037

**Comment by jradtilbrook** [comment]
Wow hadn't considered that. Seems pretty cool but would you want to wrap that in a separate issue/PR?

**Comment by kingosticks** [comment]
That's probably a good idea, maybe just worth keeping in mind for your PR that anything reusable would be welcome.
