### ISSUE TITLE
WebSocket API & Play Command

### ISSUE THREAD

**Issue by dmbuchta** [mopidy/mopidy#1532]
I am having an issue with the Play command not working when I use tlid. I have a spotify playlist already added to the tracklist, and then I send the following json:

`{
    "method": "core.playback.play",
    "jsonrpc": "2.0",
    "params": {
        "tlid": 5227
    },
    "id": 1
}`

The playback will then stop playing, change to the supplied track id, but then never resume playing. Even with an added play command:

`{
    "method": "core.playback.play",
    "jsonrpc": "2.0",
    "params": { },
    "id": 1
}`

It will not start playing. Yet Mopidy thinks it's state is "Playing". It will only start playing if I send multiple play commands (usually 2 or 3) or I clear the tracklist entirely and then re-add the songs.

Has anybody else experienced this?

**Comment by adamcik** [comment]
Sorry there really isn't enough here for us to do anything about. If you get enough info to turn this into a bug report please do followup, otherwise perhaps asking on https://discuss.mopidy.com will yield more results.
