### ISSUE TITLE
Implement DAAP support

### ISSUE THREAD

**Issue by mhalano** [mopidy/mopidy#1540]
Mopidy should share musics over DAAP protocol, so DAAP apps (like iTunes) could control mopidy. There an implementation of DAAP protocol using Python (http://jerakeen.org/code/pythondaap/) which could be useful. I know there is a bug to use Grilo to importa  lot of features, but I think if use pythondaap this feature could be implemented in no time.

**Comment by adamcik** [comment]
See https://discuss.mopidy.com/t/supporting-new-streaming-services-and-other-music-sources/22/1

Closing this as we no longer keep extension requests open in the main bug tracker.

**Comment by adamcik** [comment]
But do feel free to create, publish and hopefully maintain a mopidy-daap extension :-)
