### ISSUE TITLE
Load Playlist

### ISSUE THREAD

**Issue by chises** [mopidy/mopidy#1548]
Hi, a short question, not really a issue.
What is the "correct" way to load a Playlist?
The URI for the Playlist is: m3u:local_test.m3u

i am not able to load the Playlist with the following command:
`mpc load m3u:local_test.m3u`
or with the JS Backend
`mopidy.tracklist.add({"uri": "m3u:local_test.m3u"});`

Any suggestions?

**Comment by tkem** [comment]
General questions shoudl be posted to https://discuss.mopidy.com, but in short:

```
tkem@cookie:~$ mpc lsplaylists
LibriVox
ORF
tkem@cookie:~$ mpc load ORF
loading: ORF
```
HTTP-Clients should use the playlists controller: http://mopidy.readthedocs.io/en/latest/api/core/#mopidy.core.mopidy.core.PlaylistsController

**Comment by chises** [comment]
Thank you.
It is not possible for me to use the WebSocket API to add specific Playlists by his URI.
mpc lsplaylists && load is working. 
As describe in the documentation the TracklistController.add should accept a URI (m3u:local_test.m3u for example). But this is not working :-/
please let me know if you need any logs

**Comment by tkem** [comment]
That's because `m3u` is a `PlaylistsProvider`, but not a `LibraryProvider`.
You need to use the methods of the `PlaylistsController` to get the Refs/URIs of the tracks and pass those to `TracklistController.add`.
