### ISSUE TITLE
Wrong character password

### ISSUE THREAD

**Issue by schermi** [mopidy/mopidy#1554]
I can't put this char " in my spotify password. Without this everting is OK
I use pi musicbox

**Comment by adamcik** [comment]
PiMusicbox used to do it's own config parsing that assumed `"` around values. Mopidy has never done this, so this isn't anything we can fix in Mopidy.

For a workaround change your password if you haven't already, and other than that I think all you can do is wait for the next PiMusicbox version which I believe fixes this and many other issues.

**Comment by schermi** [comment]
Ok thank you. I didn't know where talk about this issue
