### ISSUE TITLE
Hidden directory not skipped when at top level

### ISSUE THREAD

**Issue by drhoet** [mopidy/mopidy#1559]
When building a local library with `mopidy local scan`, hidden directories are being skipped, but only if they are in a subdirectory of the `media_dir`. If they are directly in the `media_dir`, they are scanned.

I believe the offending code is in class `ScanCommand#121`, which checks for `/.` in the relative path.

**Comment by dondelelcaro** [comment]
Pull request #1555 fixes this issue.
