### ISSUE TITLE
Option to browse "Local media" by filename

### ISSUE THREAD

**Issue by allo-** [mopidy/mopidy#1560]
When i use mopidy with mpd-frontends, i can find my local music under "Local media/..." ordered by artist, album, etc. but there is no option to just browse by folder, which would be faster and more useful for some compilations.

**Comment by adamcik** [comment]
Please see https://github.com/mopidy/mopidy-local-sqlite - we are barely doing any work on the built in mopidy-local-json any more and plan to split out mopidy-local* once we have time.

**Comment by allo-** [comment]
Sorry, but i am unable to see where i should find my local files with it.

    [local]
    enabled = true
    library = sqlite
    scan_flush_threshold = 100
    data_dir = /data/mopidy/local
    media_dir = /data/music
    excluded_file_extensions = .directory, .html, .jpg, .jpeg, .m3u, .nfo, .png, .txt, .sid, .hvs, .sfv, .ini, .lrc, .url, .scn, .torrent, .gif, .db, .d64, .pls, .pdf, .doc

``mopidy-local-sqlite`` installed via debian packages.

Now i have:

- Files: local: empty, media: empty, playlists: empty, spotify/Users/myusername: some .bnk files (whatever this should be), unrelated to local media anyway
- Local media: Albums/Artists/.../Tracks, but still no possibility to just browse the directories.

Am i missing some config option?

**Comment by adamcik** [comment]
Sorry, skipped over a bit too much in my head when writing my first response.

As for adding the feature my point is that we aren't likely to do it in Mopidy itself. It will need to be solved in mopidy-local-sqlite or the future mopidy-local assuming my plan goes through (#1563)

When it comes to your immediate problem looking at it again perhaps you should just try mopidy-file instead? The only thing it provides is the file browsing, nothing else, you don't even have to scan the files up front.

**Comment by allo-** [comment]
Yep, i think it's what i am searching for, it was just empty. I guess because it has its own media_dirs setting.
Now that i set media_dirs to one path it loads for like 10 seconds (mpd interface) and then shows an empty dir.

    [file]
    enabled = true
    media_dirs = /data/music

**Comment by allo-** [comment]
The files plugin works.

In gmpc, but not in ncmpc, but i guess that's not mopidy's fault.
