### ISSUE TITLE
Split out mopidy-local*

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1563]
I've lost track of if we have bug for this, so dedupe if needed.

We should kick mopidy-local out of mopidy itself, kill off mopidy-local-json and merge with mopidy-local-sqlite. mopidy-file covers enough basic functionality that I think it's time to move this out.

This change removes complexity from the main project and will allow more experimentation and faster iteration for what mopidy-local can do. Additionally our whole idea of having mopidy-local be plugable didn't really pan out, so I think its best to cut our loses now.

@tkem and @jodal, quick sanity check, sound good to you?

**Comment by adamcik** [comment]
Only immediate downside is that part of our test suite still uses local as it's main integration test for core.

**Comment by tkem** [comment]
As soon as the test suite has been cleaned up, this sounds good to me.

**Comment by tkem** [comment]
See also #1003.

**Comment by adamcik** [comment]
Yeah, I though we already had one covering this. Thanks.
