### ISSUE TITLE
failed to allocate memory crash triggered by specific audio file.

### ISSUE THREAD

**Issue by bigredfrog** [mopidy/mopidy#1569]
Specific audio file causes mopidy to crash during local scan

```
sudo mopidyctl -v local scan

(python:19152): GLib-ERROR **: /build/glib2.0-NyxCB6/glib2.0-2.48.1/./glib/gmem.c:100: failed to allocate 3634425503 bytes
Trace/breakpoint trap (core dumped)
```

I was able to isolate the specific audio file by looking at the last processed file, and it was next alphabetically which happened to be into the next album.

It would help if the -v logged the file name before it was processed, then this would of been much easier to isolate.

I have zipped the wma file and attached.

Issue was apparent originally on my NAS.

I set up a local music store directly on the raspberry pi running ubuntu mate with just the offending folder, and pruned it down to just this file. Then moved just this file into a new folder and the issue was reproducible.

[01 Praying for Time.zip](https://github.com/mopidy/mopidy/files/518318/01.Praying.for.Time.zip)

```
big_red_frog@bonkers2:/media/test2$ sudo mopidyctl -v deps
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf -v deps" as user mopidy
INFO     Starting Mopidy 2.0.0
INFO     Loading config from builtin defaults
INFO     Loading config from /etc/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mpd, http, file, stream, m3u, softwaremixer, moped, websettings, local
INFO     Disabled extensions: none
Executable: /usr/bin/mopidy
Platform: Linux-4.1.19-v7+-armv7l-with-Ubuntu-16.04-xenial
Python: CPython 2.7.12 from /usr/lib/python2.7
Mopidy: 2.0.0 from /usr/lib/python2.7/dist-packages
Mopidy-WebSettings: 0.1.4.2 from /usr/local/lib/python2.7/dist-packages
  Jinja2>=2.7: 2.8 from /usr/local/lib/python2.7/dist-packages
    MarkupSafe: 0.23 from /usr/local/lib/python2.7/dist-packages
  ConfigObj>=4.0.0: 5.0.6 from /usr/lib/python2.7/dist-packages
    six: 1.10.0 from /usr/lib/python2.7/dist-packages
  Mopidy>=0.19: 2.0.0 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  setuptools: 20.7.0 from /usr/lib/python2.7/dist-packages
Mopidy-Moped: 0.6.4 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.0.0: 2.0.0 from /usr/lib/python2.7/dist-packages
  setuptools: 20.7.0 from /usr/lib/python2.7/dist-packages
GStreamer: 1.8.2.0 from /usr/lib/python2.7/dist-packages/gi
  Detailed information:
    Python wrapper: python-gi 3.20.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mad
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
```

**Comment by kingosticks** [comment]
I think this was already mentioned on IRC but this is most likely an upstream gstreamer issue rather than something in Mopidy itself. I suggest you try running the scan with just the problem file but with gstreamer debug logging enabled as per the documentation [suggest](https://docs.mopidy.com/en/latest/troubleshooting/#debugging-gstreamer). 

Also, if you have a core dump you should see if that reveals anything. You can find tips on how to do this [here](https://jodal.no/post/5779178001/log-from-the-debugging-of-a-segfault/).

**Comment by adamcik** [comment]
Tried this with GStreamer 1.8.2.0 on a x86 machine, no luck reproducing. I doubt we can do much about this without it being shown to also occur with with gst-discover and/or gst-play, in which case it should be filled upstream and closed here. If it doesn't happen there and we figure out how to reproduce we can look more into it.

Closing for now as there is nothing more we can do on our end for now.
