### ISSUE TITLE
MPD: sqlite3 and concurrency

### ISSUE THREAD

**Issue by muhahacz** [mopidy/mopidy#1574]
Running into issue when using home assistant:
http://pastebin.com/xmw9TvFR

Maybe is it issue report for authors of MPD?

**Comment by tkem** [comment]
Maybe you can explain what your problem is, where you got this log from, details about your setup, and what made you open a Mopidy issue for this?

**Comment by tkem** [comment]
@muhahacz : `sqlalchemy` is a database abstraction library that, to my knowledge, neither Mopidy nor Mopidy-Local-SQLite nor any of the Mopidy extensions I'm aware of use. So this is probably the wrong place for this.

**Comment by adamcik** [comment]
As Thomas pointed out this doesn't look like a Mopidy bug, closing.
