### ISSUE TITLE
Establish with mopidy.js from https page

### ISSUE THREAD

**Issue by chises** [mopidy/mopidy#1578]
Hello,
i need a bit support.
i already read that thread: https://github.com/mopidy/mopidy/issues/950 
but it did not solve my problem.
I have a php page with javascript content:
```
protocol = 'ws';

if(location.protocol == 'https:')

protocol = 'wss';
						
console.log(protocol);

mopidy = new Mopidy({

webSocketUrl: protocol+"://"+location.host+":6680/mopidy/ws/",

callingConvention: "by-position-or-by-name",
						
});
```
Issue in javascript log:
"Firefox kann keine Verbindung zu dem Server unter wss://10.10.100.15:6680/mopidy/ws/ aufbauen."
in english
"Firefox is unable to establish a connection to wss://10.10.100.15:6680/mopidy/ws/"

if the address is ws://10.10.100.15:6680/mopidy/ws/ everything is working fine :-/

Any help here?

**Comment by adamcik** [comment]
Mopidy doesn't support HTTPS, if you need that you have to put some sort of proxy in front. Google should be able to help setup something that supports https and WS proxying.

Also we prefer that support questions go to http://discuss.mopidy.com so we can focus on actual bugs here.
