### ISSUE TITLE
[Feature request] Extension for vtuner

### ISSUE THREAD

**Issue by hitam4450** [mopidy/mopidy#1586]
Hi, I love the vtuner Internet radio station and would love to see an extension for the mopidy server app!

Many Thanks ! regards, hitam4450

**Comment by kingosticks** [comment]
> https://discuss.mopidy.com/t/supporting-new-streaming-services-and-other-music-sources/22 has some notes for adding support for new services. Per our usual policy I'm closing this bug as we won't be adding it in mopidy itself, but it can still be found under the Extension wishlist label with other suggested services.
