### ISSUE TITLE
Changing volume is extremely slow

### ISSUE THREAD

**Issue by d33tah** [mopidy/mopidy#1591]
I have about 0.2-0.5s of a lag while changing volume on mopidy. Is this a common problem or is it something specific to my system? What could it depend on?

**Comment by kingosticks** [comment]
Please post usage questions at http://discuss.mopidy.com rather than our bug tracker. 

If you search on there you'll find https://discuss.mopidy.com/t/slow-volume-response-with-raspberri-pi2-hifiberry-dac/661/ which may or may not be applicable to your system.

**Comment by adamcik** [comment]
This has to do with the queues in our output tee, fixing it conflicts with multi-output. So we are still trying to figure out how to get both. I think we have an other issue open for it.

**Comment by adamcik** [comment]
#1501
