### ISSUE TITLE
MPD idle command is missing from list issued by "commands" command

### ISSUE THREAD

**Issue by djselbeck** [mopidy/mopidy#1593]
Mopidy 2.1.0 is missing the "idle" command in the list of available commands issued when calling the 

> commands

command. MPD includes it properly

**Comment by adamcik** [comment]
45a0a9233cfc5c2044b661ec04d92e3ddd5c9008 (#654) removed it and a bunch of other commands from the listings on purpose. To the best of my knowledge I checked it against MPD at the time. So they must have changed their mind / fixed it and now we are lagging behind again.

**Comment by djselbeck** [comment]
Seems to be. MPD 0.20.2 is listing it. 

MPD output:

`telnet localhost 6600
Trying ::1...
Connected to localhost.
Escape character is '^]'.
OK MPD 0.20.0
commands
command: add
command: addid
command: addtagid
command: channels
command: clear
command: clearerror
command: cleartagid
command: close
command: commands
command: config
command: consume
command: count
command: crossfade
command: currentsong
command: decoders
command: delete
command: deleteid
command: disableoutput
command: enableoutput
command: find
command: findadd
command: idle
command: kill
command: list
command: listall
command: listallinfo
command: listfiles
command: listmounts
command: listplaylist
command: listplaylistinfo
command: listplaylists
command: load
command: lsinfo
command: mixrampdb
command: mixrampdelay
command: mount
command: move
command: moveid
command: next
command: notcommands
command: outputs
command: password
command: pause
command: ping
command: play
command: playid
command: playlist
command: playlistadd
command: playlistclear
command: playlistdelete
command: playlistfind
command: playlistid
command: playlistinfo
command: playlistmove
command: playlistsearch
command: plchanges
command: plchangesposid
command: previous
command: prio
command: prioid
command: random
command: rangeid
command: readcomments
command: readmessages
command: rename
command: repeat
command: replay_gain_mode
command: replay_gain_status
command: rescan
command: rm
command: save
command: search
command: searchadd
command: searchaddpl
command: seek
command: seekcur
command: seekid
command: sendmessage
command: setvol
command: shuffle
command: single
command: stats
command: status
command: stop
command: subscribe
command: swap
command: swapid
command: tagtypes
command: toggleoutput
command: unmount
command: unsubscribe
command: update
command: urlhandlers
command: volume
OK`

**Comment by Btjones711** [comment]
Hi I am new to contributing to open source and due to my love of music and python being my language of choice for programming I started with this project as it looks like a great project to learn about and learn from. I am currently searching through the files and trying to help fix this bug as it is labeled for beginners. Unfortunately I have not been able to find where the commands are stored. Is there anyone who can help me figure out where to start?

**Comment by djselbeck** [comment]
Not that I'm developing mopidy, it looks like you have to start here: mopidy/mpd/protocol/status.py  look  for idle and list_command

**Comment by Btjones711** [comment]
Thanks for the quick response and advice I will look into that! It looks like I have some terminology and conventions to learn and get used to. Thanks!

**Comment by Btjones711** [comment]
Would changing the list_command from False to True do the trick?

Sorry if dumb question. Thanks!
![bug_fix1](https://cloud.githubusercontent.com/assets/21178349/22353267/49059b5a-e3e5-11e6-9035-b81305dcd727.png)

**Comment by jodal** [comment]
Fixed by PR #1597.

**Comment by jodal** [comment]
Fix cherry-picked into the release-2.1 branch.
