### ISSUE TITLE
Mopidy user never added

### ISSUE THREAD

**Issue by AuditeMarlow** [mopidy/mopidy#1596]
I've installed Mopidy along with the ncmpcpp front-end and I've managed to get it up and running as a service, although not with the mopidy user, as it was never created during installation (or reinstalls, for that matter). I've setup the service to run as my main user, and this works fine.

However, I've been messing around with HTTP front-ends today, and wanted to make sure Mopidy was picking up pip by running `sudo mopidyctl deps`. It tries to run this as user mopidy, but alas, there is no user mopidy. I've created it, but without the proper permissions it still cannot do whatever the mopidy user is meant to do.

Can I run the `deps` command as other users as well? If not, what permissions do I need for the mopidy user in order to run everything accordingly?

**Comment by trygveaa** [comment]
Which OS/distro do you use? How did you install Mopidy?

> Can I run the deps command as other users as well?

You should be able to run `mopidy deps` as any user.

**Comment by AuditeMarlow** [comment]
I am using Arch Linux. I have a hunch the package maintainer forgot something.

**Comment by trygveaa** [comment]
The package in Arch should create the user for you. Here you can see how it is created:
https://git.archlinux.org/svntogit/community.git/tree/trunk/mopidy.install?h=packages/mopidy

**Comment by AuditeMarlow** [comment]
Thanks, I guess something went wrong in this process. I already have a group with GID 46, xmms2, which results in the group mopidy not being added in the first place.

**Comment by trygveaa** [comment]
Then I think something else must have misbehaved, since the GID 46 should be reserved for mopidy in Arch, see: https://wiki.archlinux.org/index.php/DeveloperWiki:UID_/_GID_Database

If you still think this is an issue, please file a bug at https://bugs.archlinux.org/

**Comment by jotebe** [comment]
I also encountered this issue, and believe this bug was related to the mopidy system user not being created due to its UID being taken as you discovered. I have filed a bug with Arch. https://bugs.archlinux.org/task/55536

**Comment by jotebe** [comment]
This issue was fixed upstream with arch at the xmms2 package.
