### ISSUE TITLE
UnicodeDecodeError during local scan

### ISSUE THREAD

**Issue by raqua** [mopidy/mopidy#1599]
Hi, I was using Mopidy and it worked fine. Without any change to config, I altered my collection.
I run a ReplayGain software on in in order to get relative volume levels. I am aware that this is not supposed to work with Mopidy, but I also use other players on the same collection. 

After that, local scan started to crash. I had a backup of my collection and restored that, but I still get the crash and there is no info that would help me to identify on what songs it crashes. 
 
Log attached. 
[mopidy.txt](https://github.com/mopidy/mopidy/files/763761/mopidy.txt)

**Comment by alexjaw** [comment]
Have looked at mopidy.txt and searched for similar errors. The cause for this error might be that your locale LANG variable is unset, see [SO](https://stackoverflow.com/questions/10561923/unicodedecodeerror-ascii-codec-cant-decode-byte-0xef-in-position-1). At least I got the same error with locale_decode(bytestr) when I unset my LANG variable.

I propose that local_decode() returns a string to scan.py if it fails with decoding. The error string could be "Codec <the actual codec> can't decode content. Check your LANG setting ($ echo $LANG).". Then I assume that the scanner stops at the track that failed, thus giving better feedback to the user.
