### ISSUE TITLE
repeated polling of mpd interfacing (using mpc or other methods) causes CPU spikes

### ISSUE THREAD

**Issue by lilmike** [mopidy/mopidy#1601]
I have a tintin++ pack of scripts, and one of the features is, without going into too much detail, to set your title to your currently playing song. It polls mopidy (or other music players, depending on what you have set), as to what the current song is every 1.5 seconds. I'm aware this is technically far too short for a song to have changed, and I'm looking into changing it, but while using this feature, mopidy causes my CPU to spike pretty high. I've reproduced it with a script like this:

while :; do mpc current; sleep 0.1; done

or:

while :; do { echo -e "currentsong\nclose"; sleep 0.1; } | nc localhost 6600; done

I've also noticed that many times, simply querying mopidy (again with mpc or similar) takes anywhere from half a second to maybe 2 seconds or so (which doesn't seem normal). This is extremely agrivated when this 1.5 s polling is going on as well.
-Michael.

**Comment by kingosticks** [comment]
You should change your script to use MPD's idle command. It's designed for this sort of thing. 

Are you using the Spotify extension? I'd guess it's probably related to a known issue that occurs when Mopidy receives a new connection. If so,  then it'll be fixed in the next major version.

**Comment by lilmike** [comment]
Yep, looks like disabling spotify fixed it. Thanks!
-Michael.

**Comment by adamcik** [comment]
https://github.com/mopidy/mopidy/blob/92ddd888ee3b09c17c935828483f6c788cfb0e36/mopidy/core/playlists.py#L136 is probably to blame. That is yeah time you connect it creates a new MPD context, which creates a new link to core, which re-triggers getting the playlists property. This is already deprecated and should be killed off as part of #1461
