### ISSUE TITLE
Debian instructions fails to mention gstreamer0.10-pulseaudio

### ISSUE THREAD

**Issue by telefax** [mopidy/mopidy#1605]
I struggled trying to get mopidy run using https://docs.mopidy.com/en/latest/service/#service-management-on-debian

I kept getting:

> mopidy.audio.actor: Failed to create audio output "pulsesink server=127.0.0.1": no element "pulsesink"

It turns out that the documentation fails to mention that you need to install gstreamer0.10-pulseaudio (and not gstreamer1.0-pulseaudio which is also tempting):

> apt-get install gstreamer0.10-pulseaudio

**Comment by jodal** [comment]
Mopidy has used GStreamer 1.x exclusively since 2.0. If you need gstreamer0.10-pulseaudio, you're using an old Mopidy version.
