### ISSUE TITLE
Simple html / url command to set volume ??

### ISSUE THREAD

**Issue by githubos1** [mopidy/mopidy#1606]
Hi guys,

I'm using Musicbox 0.6 for many months successfully.. and I realy love it !!

As I'm using it mainly with my mobile phone the webgui somewhat could need some improvement... 
Is there any easy way to send a command by URL to set a specific volume ? rather than using the slider ??

like:  http://192.168.xxx.xxx/"#doVolume(15)"  

That way I could simply save some predefined Bookmarks on my mobile to set the volume accordingly..

similar would be helpful for selecting/changing_to a predefined radiostation...  without having to use the webgui..

Thank'S

Oliver

**Comment by kingosticks** [comment]
Hi, usage questions are best directed at http://discuss.mopidy.com (or better yet, https://discuss.mopidy.com/c/pi-musicbox) rather than this bug tracker, please post your questions there instead. Thanks.

**Comment by adamcik** [comment]
See for instance https://discuss.mopidy.com/t/rest-api-questions/1024 which has a similar question.
