### ISSUE TITLE
[Feature request] Intergate Mopidy server with Yandex Music and Radio service

### ISSUE THREAD

**Issue by MurzNN** [mopidy/mopidy#1607]
Yandex provide API for Music and Radio (Яндекс.Музыка и Яндекс.Радио) services in this github repository: https://github.com/yandex/audio-js - this is popular music service like Google Music.
Will be good to see integration with Yandex.Music and Yandex.Radio in Mopidy server.

**Comment by adamcik** [comment]
Please see https://discuss.mopidy.com/t/supporting-new-streaming-services-and-other-music-sources/22 - closing as with other requests like this as the feature needs to be in a plugin, not mopidy itself.

If someone creates a plugin feel free to update this bug so other can find it.

**Comment by MurzNN** [comment]
Here is implementation of Yandex.Music API in non-python language:
PHP: https://github.com/sonrac/yandex-music-api
Node.JS: https://github.com/itsmepetrov/yandex-music-api
Hope that I'll find something same on Python for intergate Yandex.Music with Mopidy.
