### ISSUE TITLE
Badly handles config files not being available/missing/readable

### ISSUE THREAD

**Issue by Winter-Guerra** [mopidy/mopidy#1613]
`/usr/bin/mopidy --config /etc/mopidy/mopidy.conf` silently falls back to defaults if `/etc/mopidy/mopidy.conf` is not readable by the current user. 

Ideally, mopidy should at least warn the user if it's expecting config file(s), but cannot access any. Failing silently makes an easily fixable problem annoying to debug.

**Comment by kingosticks** [comment]
I'm a bit confused by what you mean, [there is a warning for exactly this](https://github.com/mopidy/mopidy/commit/4bf7a568d1ce258aaf626f7d1e385a7107ab11df). And it works...

> Apr 25 16:15:44 NSTEEL systemd[1]: Starting Mopidy music server...
Apr 25 16:15:44 NSTEEL systemd[1]: Started Mopidy music server.
Apr 25 16:15:45 NSTEEL mopidy[17751]: INFO     Starting Mopidy 2.1.0
Apr 25 16:15:45 NSTEEL mopidy[17751]: INFO     Loading config from builtin defaults
Apr 25 16:15:45 NSTEEL mopidy[17751]: WARNING  Loading config from /etc/mopidy/mopidy.conf failed; read permission missing
Apr 25 16:15:45 NSTEEL mopidy[17751]: INFO     Loading config from command line options

**Comment by kingosticks** [comment]
Please reopen if there is actually something to do here.
