### ISSUE TITLE
Raspbian Install from apt.mopidy.com not working

### ISSUE THREAD

**Issue by peagaah** [mopidy/mopidy#1615]
Hi, 

I have installed a fresh new Raspbian Lite Jessie from https://www.raspberrypi.org/downloads/raspbian/ and added the APT repo as described here: https://docs.mopidy.com/en/latest/installation/debian/#debian-install

I receive an error when I run sudo apt-get update and when I try to install
Install error:
![screen shot 2017-04-30 at 21 33 02](https://cloud.githubusercontent.com/assets/7211142/25569383/bee54f86-2dec-11e7-891e-aeb62c9244d6.png)

Update error:
![screen shot 2017-04-30 at 21 33 18](https://cloud.githubusercontent.com/assets/7211142/25569384/bee95540-2dec-11e7-8af6-2a0032891681.png)

 Any idea what could I do to workaround this issue?

**Comment by trygveaa** [comment]
Seems like your having some network issues? The screenshot says it fails to connect to apt.mopidy.com, but also to mirror.nbtelecom.com.br. From my machine, apt.mopidy.com is working fine.

**Comment by peagaah** [comment]
Hi @trygveaa ,

I solved this problem right now, changed the mirror in sudo nano /etc/apt/sources.list to another URL.
