### ISSUE TITLE
local/media_dir - support multiple dirs

### ISSUE THREAD

**Issue by bernd-wechner** [mopidy/mopidy#1624]
According to the doc:

https://docs.mopidy.com/en/latest/ext/local/#confval-local/media_dir

local/media_dir is one directory.

I'd like to define more than one. 

I experimented empirically quickly and can confirm:

1) if I specify media_dir twice only the second definition is respected
2) I can't think of an obvious (not needing documentation) way to specify two dirs once, but tried: `media_dir = dir1;dir2` and that fails. 

But, it's not unusual to have multiple local media stores and it's definitely very conducive to testing to be able to add dirs one by one and see what comes of it so I'd really like to see meda_dir accept multiple directories somehow and see that documented.

**Comment by trygveaa** [comment]
> I can't think of an obvious (not needing documentation) way to specify two dirs once, but tried: media_dir = dir1;dir2 and that fails.

We do have some other config options that accept multiple values, so if this is implemented it should use the same format. Take a look at e.g. https://docs.mopidy.com/en/latest/ext/local/#confval-local/excluded_file_extensions:

> Values should be separated by either comma or newline.

**Comment by bernd-wechner** [comment]
Yep, consistency would be good. if using commas or any delimiter other than newline I expect dirs would need be enclosed in quotes given they can contain commas legally in some filesystems.

I think a plausible workaround in the interim is to create a proxy media_dir in which you place a symbolic link to each media_dir you actually have and ensure scan_follow_symlinks is true. Justa thought that might get me rolling, as klunky as I think this work around is. 

I've scanned the code and it seems the assumption that media_dir is a single directory is spread pretty wide around the code base alas. Not unassailable but suggests such a feature is not a trivial fix.

**Comment by adamcik** [comment]
This would break all kinds of assumptions around local URI handling. Currently we assume that `local:/...` works such that we can just replace the start with the singular media dir. If you want to add multiple ones you need to come up with some sane way to handle this.

Likely your better bet is to have local media dir with symlinks to the locations you have and just let local/the scanner follow symlinks?

**Comment by bernd-wechner** [comment]
We're on the same page there. I already concluded as much. Still I'll have a quick look later at how many places in the code I see local referenced and have a guess at how big a refactor might be. Not a priority because of this clear work around, but I'd keep it on the horizon as I find it a slightly surprising assumption that I don't remember seeing in any other players yet. 

I'd keep this in mind with #1003 and vice versa, but not consider this a bug so much as a feature request.

**Comment by juanlugm** [comment]
I think it would be easier to just define a single folder in local to contain a number of symlinks to the user defined folders. Wouldn't that work for all?

**Comment by jodal** [comment]
Closing. Our recommended solution is a single media dir with symlinks to "mount" multiple dirs inside the media dir.
