### ISSUE TITLE
/usr/local/bin/mopidy forcing python3 by default

### ISSUE THREAD

**Issue by GNUGradyn** [mopidy/mopidy#1635]
I recently installed mopidy on my raspberry pi. It was complaining about having the wrong python version, however /usr/bin/python was pointing to python2.7. Upon further inspection, I noticed this is the first line of /usr/local/bin/mopidy:
`#!/usr/bin/python3`
changing it to:
`#!/usr/bin/python2`
solves the problem
this issue occurs regardless if mopidy is installed via pip or apt

**Comment by trygveaa** [comment]
Which distro are you using, and which repo did you install Mopidy from with apt? The package on `apt.mopidy.com` has `#!/usr/bin/python` in the top at least.

If you install it with pip you should get the same as the python version pip is for, i.e. you should use pip for python 2, not for python 3. Which did you use?

**Comment by jodal** [comment]
Commit 33856830c946182a623079853a8590575c5d23d2 (not yet released) will probably help a bit here, as newer pip versions will understand that Mopidy requires Python 2.7. And when we make a Python 3 only release, pip on Python 2 will still install the latest version compatible with Python 2.

Anyway, this is old and no reply from author, so there's little to go on here.
