### ISSUE TITLE
Mopidy not working

### ISSUE THREAD

**Issue by djl236** [mopidy/mopidy#1637]
Did a clean install of Mopidy on a Pi 3. Was working great, both local and Gmusic. Now neither work, no idea why. Mopidy is newest version. This is what the status gives me (Mopidy runs as a service):

Aug 18 21:01:12 mopidy mopidy[800]: WARNING  Track is not playable: local:track:ACDC-%201975-2008/07-ACDC-1977-Let%20There%20Be%20Rock/05-Problem%...ild-mw.mp3
Aug 18 21:01:12 mopidy mopidy[800]: ERROR    GStreamer error: gst-resource-error-quark: Resource not found. (3)
Aug 18 21:01:12 mopidy mopidy[800]: WARNING  Setting GStreamer state to GST_STATE_PLAYING failed
Aug 18 21:01:12 mopidy mopidy[800]: WARNING  Track is not playable: local:track:ACDC-%201975-2008/07-ACDC-1977-Let%20There%20Be%20Rock/06-Overdose-mw.mp3
Aug 18 21:01:12 mopidy mopidy[800]: ERROR    GStreamer error: gst-resource-error-quark: Resource not found. (3)
Aug 18 21:01:12 mopidy mopidy[800]: WARNING  Setting GStreamer state to GST_STATE_PLAYING failed
Aug 18 21:01:12 mopidy mopidy[800]: WARNING  Track is not playable: local:track:ACDC-%201975-2008/07-ACDC-1977-Let%20There%20Be%20Rock/07-Hell%20A...0Be-mw.mp3
Aug 18 21:01:12 mopidy mopidy[800]: ERROR    GStreamer error: gst-resource-error-quark: Resource not found. (3)
Aug 18 21:01:12 mopidy mopidy[800]: WARNING  Setting GStreamer state to GST_STATE_PLAYING failed
Aug 18 21:01:12 mopidy mopidy[800]: WARNING  Track is not playable: local:track:ACDC-%201975-2008/07-ACDC-1977-Let%20There%20Be%20Rock/08-Whole%20...sie-mw.mp3
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by djl236** [comment]
restarted the service:
sudo systemctl status mopidy
● mopidy.service - Mopidy music server
   Loaded: loaded (/lib/systemd/system/mopidy.service; enabled)
   Active: active (running) since Fri 2017-08-18 21:11:24 EDT; 33s ago
  Process: 1127 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
  Process: 1124 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
 Main PID: 1130 (mopidy)
   CGroup: /system.slice/mopidy.service
           └─1130 /usr/bin/python /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf

Aug 18 21:11:25 mopidy mopidy[1130]: INFO     Starting Mopidy 2.1.0
Aug 18 21:11:25 mopidy mopidy[1130]: INFO     Loading config from builtin defaults
Aug 18 21:11:25 mopidy mopidy[1130]: INFO     Loading config from /etc/mopidy/mopidy.conf
Aug 18 21:11:25 mopidy mopidy[1130]: INFO     Loading config from command line options
Aug 18 21:11:26 mopidy mopidy[1130]: INFO     Enabled extensions: mpd, http, file, stream, gmusic, scrobbler, musicbox_webclient, softwaremixer, ...local, m3u
Aug 18 21:11:26 mopidy mopidy[1130]: INFO     Disabled extensions: none
Aug 18 21:11:29 mopidy mopidy[1130]: INFO     Starting Mopidy mixer: SoftwareMixer
Aug 18 21:11:29 mopidy mopidy[1130]: INFO     Starting Mopidy audio
Aug 18 21:11:29 mopidy mopidy[1130]: INFO     Starting Mopidy backends: GMusicBackend, StreamBackend, M3UBackend, FileBackend, LocalBackend
Aug 18 21:11:29 mopidy mopidy[1130]: INFO     Audio output set to "alsasink device=hw:1,0"

**Comment by djl236** [comment]
sudo systemctl status mopidy
● mopidy.service - Mopidy music server
   Loaded: loaded (/lib/systemd/system/mopidy.service; enabled)
   Active: active (running) since Fri 2017-08-18 21:11:24 EDT; 1min 14s ago
  Process: 1127 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
  Process: 1124 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
 Main PID: 1130 (mopidy)
   CGroup: /system.slice/mopidy.service
           └─1130 /usr/bin/python /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf

Aug 18 21:12:04 mopidy mopidy[1130]: INFO     Logged in to Google Music
Aug 18 21:12:06 mopidy mopidy[1130]: INFO     Start refreshing Google Music library
Aug 18 21:12:08 mopidy mopidy[1130]: INFO     Start refreshing Google Music playlists
Aug 18 21:12:32 mopidy mopidy[1130]: INFO     Loaded 19074 local tracks using json
Aug 18 21:12:32 mopidy mopidy[1130]: INFO     Starting Mopidy core
Aug 18 21:12:32 mopidy mopidy[1130]: INFO     Starting Mopidy frontends: ScrobblerFrontend, GMusicScrobblerFrontend, MpdFrontend, HttpFrontend
Aug 18 21:12:32 mopidy mopidy[1130]: INFO     MPD server running at [::]:6600
Aug 18 21:12:32 mopidy mopidy[1130]: INFO     HTTP server running at [::]:6680
Aug 18 21:12:32 mopidy mopidy[1130]: INFO     Starting GLib mainloop
Aug 18 21:12:33 mopidy mopidy[1130]: INFO     Scrobbler connected to Last.fm

**Comment by djl236** [comment]
sudo systemctl status mopidy
● mopidy.service - Mopidy music server
   Loaded: loaded (/lib/systemd/system/mopidy.service; enabled)
   Active: active (running) since Fri 2017-08-18 21:11:24 EDT; 6min ago
  Process: 1127 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
  Process: 1124 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
 Main PID: 1130 (mopidy)
   CGroup: /system.slice/mopidy.service
           └─1130 /usr/bin/python /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf

Aug 18 21:12:32 mopidy mopidy[1130]: INFO     Loaded 19074 local tracks using json
Aug 18 21:12:32 mopidy mopidy[1130]: INFO     Starting Mopidy core
Aug 18 21:12:32 mopidy mopidy[1130]: INFO     Starting Mopidy frontends: ScrobblerFrontend, GMusicScrobblerFrontend, MpdFrontend, HttpFrontend
Aug 18 21:12:32 mopidy mopidy[1130]: INFO     MPD server running at [::]:6600
Aug 18 21:12:32 mopidy mopidy[1130]: INFO     HTTP server running at [::]:6680
Aug 18 21:12:32 mopidy mopidy[1130]: INFO     Starting GLib mainloop
Aug 18 21:12:33 mopidy mopidy[1130]: INFO     Scrobbler connected to Last.fm
Aug 18 21:15:40 mopidy mopidy[1130]: INFO     Finished refreshing Google Music library in 217s
Aug 18 21:15:41 mopidy mopidy[1130]: INFO     Loaded 6 playlists from Google Music
Aug 18 21:15:41 mopidy mopidy[1130]: INFO     Starting to loading radio stations

**Comment by djl236** [comment]
ok now its working? I got nothing. So. Weird.

**Comment by sumpfralle** [comment]
I am glad, it is working for you now. Thank you for reporting back!
