### ISSUE TITLE
It seems like /root/.config/mopidy/mopidy.conf doesn't exist. But it does.

### ISSUE THREAD

**Issue by GabrielM120** [mopidy/mopidy#1640]
When I do: "mopidy config" or "mopidy" or "mopidy local scan" it says:

WARNING  Unable to initialize /root/.config/mopidy/mopidy.conf with default config: [Errno 5] Input/output error: '/root/.config/mopidy/mopidy.conf'
[core]
cache_dir = $XDG_CACHE_DIR/mopidy
config_dir = $XDG_CONFIG_DIR/mopidy
data_dir = $XDG_DATA_DIR/mopidy
max_tracklist_length = 10000
restore_state = false

[logging]
color = true
console_format = %(levelname)-8s %(message)s
debug_format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
debug_file = mopidy.log
config_file =

[audio]
mixer = software
mixer_volume =
output = autoaudiosink
buffer_time =

[proxy]
scheme =
hostname =
port =
username =
password =

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600
password =
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist =
  listall
  listallinfo
default_playlist_scheme = m3u

[http]
enabled = true
hostname = 127.0.0.1
port = 6680
static_dir =
zeroconf = Mopidy HTTP server on $hostname

[stream]
enabled = true
protocols =
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist =
timeout = 5000

[m3u]
enabled = false  ; Extension disabled due to config errors.
base_dir =  ; 'ascii' codec can't encode character u'\xfa' in position 7: ordinal not in range(128)
default_encoding = latin-1
default_extension = .m3u8
playlists_dir =

[softwaremixer]
enabled = true

[file]
enabled = true
media_dirs =
  $XDG_MUSIC_DIR|Music
  ~/|Home
excluded_file_extensions =
  .jpg
  .jpeg
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[local]
enabled = false  ; Extension disabled due to config errors.
library = json
media_dir =  ; 'ascii' codec can't encode character u'\xfa' in position 7: ordinal not in range(128)
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .png
  .txt

[local-sqlite]
enabled = true
directories =
  Albums                  local:directory?type=album
  Artists                 local:directory?type=artist
  Composers               local:directory?type=artist&role=composer
  Genres                  local:directory?type=genre
  Performers              local:directory?type=artist&role=performer
  Release Years           local:directory?type=date&format=%25Y
  Tracks                  local:directory?type=track
  Last Week's Updates     local:directory?max-age=604800
  Last Month's Updates    local:directory?max-age=2592000
timeout = 10
use_album_mbid_uri = true
use_artist_mbid_uri = false
use_artist_sortname = false

[local-images]
enabled = true
library = json
base_uri = /images/
image_dir =
album_art_files =
  *.jpg
  *.jpeg
  *.png

[iris]
enabled = true
country = NZ
locale = en_NZ
authorization_url = https://jamesbarnsley.co.nz/auth_v2.php

[spotify]
enabled = false  ; Extension disabled due to config errors.
username =   ; Must be set.
password =   ; Must be set.
client_id =   ; Must be set.
client_secret =   ; Must be set.
bitrate = 160
volume_normalization = true
private_session = false
timeout = 10
allow_cache = true
allow_network = true
allow_playlists = true
search_album_count = 20
search_artist_count = 10
search_track_count = 50
toplist_countries =

But I have "mopidy.conf" with all the configurations.

And when I try to do the:

ls -l ~/.config/mopidy/mopidy.conf
ls: no se puede acceder a /root/.config/mopidy/mopidy.conf: No existe el archivo o el directorio

It seems like it doesn't exist.

I don't know what to do. Please, help me. Sorry for my bad english

**Comment by kingosticks** [comment]
This issue tracker is for confirmed bugs/feature requests rather than usage questions such as this. Please repost at http://discuss.mopidy.com.

When you do, you'll have to provide some more information regarding why you are running Mopidy as root and why you think your following statement to be true, considering the fact your filesystem is telling you the complete opposite.  

>But I have "mopidy.conf" with all the configurations.
>
>And when I try to do the:
>
>ls -l ~/.config/mopidy/mopidy.conf
>ls: no se puede acceder a
