### ISSUE TITLE
[Feature Request] ID3-Tag rating

### ISSUE THREAD

**Issue by tatoosh** [mopidy/mopidy#1644]
It would be nice to read and write out the id3-tag rating fields.
Is this possible?

**Comment by kingosticks** [comment]
If gstreamer supports the rating field then it's possible to read it and include it in our Track model.

Don't understand what you mean by write it out. Mopidy doesn't support writing any id3 tags as there are already other programs far better suited for that.

**Comment by tatoosh** [comment]
Reading would be nice so you can sort form 1 till 5 stars. 
If wrtiting back to the file is not supported thats okay.
Can you check gstreamer vor should i do it?

**Comment by kingosticks** [comment]
The other reasons we don't already do this that I'm forgetting are that the MPD protocol doesn't support the tag and other Backends may not have an equivalent concept so it'd be a special case for Local. I don't *think* Spotify supports track ratings anymore (at least not in their Android app). 

https://github.com/mopidy/mopidy/issues/327 is somewhat related.

**Comment by bernd-wechner** [comment]
For what it's worth, I see ratings support (reading, and setting) as a 
fairly important thing in local library management. And indeed MPD 
doesn't support it, but I always figured it worth augmenting the MPD 
protocol by adding it ;-). It takes some proactive leadership to see 
such norms evolved form the grassroots up (through end user adoption) at 
times.

Nick Steel wrote:

**Comment by kingosticks** [comment]
The music library is designed to be read only. The suggested support in MPD is through stickers, as I think #327 mentions. It is very unlikely to be included in the MPD protocol and I personally think that's reasonable. 

But, of course, that doesn't stop us adding it to our models, it's just some background to the issue. I don't see why we wouldn't consider a PR but it's not planned.

**Comment by ZenithDK** [comment]
@bernd-wechner You are more than welcome to submit a PR implementing this, but this is not on the roadmap for Mopidy, so while you and others may consider it important, it is not currently a priority - so you need to drive (or implement) this yourself.

**Comment by jodal** [comment]
Closing. If anyone wants to contribute a feature like this, feel free to open a new issue to discuss the design of it.
