### ISSUE TITLE
Playlist add from RPC 

### ISSUE THREAD

**Issue by freedreamer82** [mopidy/mopidy#1647]
Hi,

I'm trying to load a playlist from json Rpc but i 've been having some issues.Maybe someone could help me.
first thing i do is to get the playlists with

curl -d '{"jsonrpc": "2.0", "id": 1, "method": "core.playlists.as_list"} '  http://localhost:6680/mopidy/rpc

and it works. 
Once i have the uri i use it as parameter for "core.tracklist.add"  but the playlist uri does not load anything. If I ask the length is still 0.
If I  use playlists.get_items( uriPlaylist ) and i manually add all the uris, it works properly.

Is this by design ?
I would like to expose a method on tracklistController to load the playlist doing all the stuff under the hood , what do u think ?

something like core.tracklist.load_playlist( uri )

I could try to modify the sources doing a pull request.

Let me know.

Thanks

Marco 

PS
using mpc load <name> works properly

**Comment by kingosticks** [comment]
From https://docs.mopidy.com/en/latest/api/core/#mopidy.core.TracklistController.add

> If uri is given instead of tracks, the URI is looked up in the library and the resulting tracks are added to the tracklist.

It's the job of the specific backend to correctly perform the playlist lookup, I guess whatever backend you are using does not. mopidy-spotify and most others work correctly like this but I think m3u is an example of one that doesn't; I think there's an issue already which explains why. 

End users use Frontends (like MPD) which make use of various Core APIs to perform a task. A particular frontend command is not necessarily equivalent to any one core API method.

**Comment by adamcik** [comment]
Closing since this is two years old and there isn't any clear thing for us to fix.
