### ISSUE TITLE
Run Mopidy as service with extensions

### ISSUE THREAD

**Issue by Koeroesi86** [mopidy/mopidy#1650]
Hello everyone,

I have an issue while setting up Mopidy as a service on Ubuntu. It runs as the user created on install what seems not to share the same python packages as the default user neither as the `sudo pip install`.

_Mainly I would like to get web extensions to work, but others might be useful too. Hope it makes sense, and I would appreciate any help. Thanks_

**Comment by jodal** [comment]
Sorry for the very late reply. Please use the discussion forum over at https://discourse.mopidy.com to get help with installing and using Mopidy.
