### ISSUE TITLE
Mopidy is not following symlinks

### ISSUE THREAD

**Issue by gerroon** [mopidy/mopidy#1654]
Hi

I have a setup like this

[file]
  enabled = true
  media_dirs = /DATA//MEDIA
  follow_symlinks = true

The MEDIA folder has 2 symlinks that are directed to shares on Cifs/Samba drives on another computer. So the actual symlinks are residing on the local drive but the directed symlink folders (which are holding the actual media) are on samba network share. 

As far as I can tell I can neither browse files section (comes up empty) nor being able to do any local scan to get those files. The local database has the same path.

I also see no errors regarding the paths in the log.

Mopidy 2.1.0 
Debian Sid 4.14.0-3-amd64

thanks

**Comment by gerroon** [comment]
Whether running as systemd or my user does not make a difference. Both users can access these shares no problem.

**Comment by kingosticks** [comment]
Could you provide a debug level scan log?

**Comment by gerroon** [comment]
@kingosticks 

I will, and I will update the bug when I ca.

thanks

**Comment by sumpfralle** [comment]
@gerroon: did you already create a debug log?

**Comment by gerroon** [comment]
@sumpfralle 

I am sorry I forgot about this because, well I stopped using Mopidy since then, I do not have enough space on the server that is why I was needing to use symlinks from a network drive.

**Comment by piotrkochan** [comment]
Hello, I have same problem. My configuration is as below:

```
[file]
enabled = true
media_dirs =
  /home/me/Music|Music
excluded_file_extensions = .directory .html, .jpeg, .jpg, .log, .nfo, .png, .txt, .mkv, .avi, .divx, .qt, .htm, .zip, .rar, .gz, .pdf, .exe, .ini, .mid, .db, .m3u, .sfv, .midi
show_dotfiles = false
follow_symlinks = true
metadata_timeout = 1000
```

And directories in the  /home/me/Music are:

```
drwxr-xr-x 2 me me 4096 mar  3 16:24 Autrw
lrwxrwxrwx 1 me me   34 mar  3 20:47 Discovery -> /home/me/Daft Punk - Discovery
lrwxrwxrwx 1 me me   23 mar  3 20:38 EE24-7C50 -> /media/me/EE24-7C50
drwxr-xr-x 2 me me 4096 mar  3 16:25 SoundHelix
```

Mopidy detects only Autrw and SoundHelix directories.

**Comment by EdwardBetts** [comment]
I found this in the debug log. Might explain what is going on.

```
Nov 15 14:27:47 nas mopidy[1734766]: DEBUG    [FileBackend-3] mopidy.file.library Browsing files at: file:///var/lib/mopidy/media
Nov 15 14:27:47 nas mopidy[1734766]: DEBUG    [FileBackend-3] mopidy.file.library Ignoring symlink to outside base dir: file:///data/Music
```

**Comment by kingosticks** [comment]
That's a different error and it's also coming from a different extension - Mopidy-Local.
