### ISSUE TITLE
Subscription error playing some song

### ISSUE THREAD

**Issue by sigzegv** [mopidy/mopidy#1658]
I cannot play certain songs, I get this error "NotSubscribed: Store tracks require a subscription to stream.". All my mp3s are uploaded, and I don't understand why it ask for subscription..

What can I do ?

**Comment by kingosticks** [comment]
Can you please open an issue in the repository for the particular backend extension you are talking about.

**Comment by sigzegv** [comment]
oops sorry that's what I wanted to do, I miss the correct github..
