### ISSUE TITLE
Unable to use spotify

### ISSUE THREAD

**Issue by Giusepp3** [mopidy/mopidy#1663]
Please use https://discourse.mopidy.com/ for support questions.

GitHub Issues should only be used for confirmed problems with Mopidy and well-defined feature requests.

<img width="1277" alt="schermata 2018-03-07 alle 14 25 27" src="https://user-images.githubusercontent.com/3754641/37094555-8768006e-2213-11e8-9c13-54823e483eb6.png">

**Comment by herrwusel** [comment]
Some program is using the same ports - maybe another instance of mopidy. Try to find the program that is using these ports first and close them

**Comment by kingosticks** [comment]
> Please use https://discourse.mopidy.com/ for support questions.
