### ISSUE TITLE
Can't build the documentation

### ISSUE THREAD

**Issue by DamienCassou** [mopidy/mopidy#1672]
```
~/Documents/projects/mpd/mopidy/docs> make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.6.6

Configuration error:
The configuration file (or one of the modules it imports) called sys.exit()
make: *** [Makefile:40: html] Error 1
```

The lack of information makes it hard to debug.

**Comment by kingosticks** [comment]
Did you [install the development tools](https://docs.mopidy.com/en/latest/devenv/#install-development-tools) ? Did you try running `tox` like [Travis successfully does](https://travis-ci.org/mopidy/mopidy/jobs/367399049)?

**Comment by DamienCassou** [comment]
Thank you for your quick answer. Configuring a virtual environment made it work.
