### ISSUE TITLE
Mopidy-File: display tag info instead of filename in browsing

### ISSUE THREAD

**Issue by laclaro** [mopidy/mopidy#1674]
Hello,

I am wondering if it is possible to display info from media tags (metadata) instead of the plain filename in the mpd-playlist? 
I would like to browse via directory structure but Mopidy-sqlite does not provide such possibility because mopidy-file exists.

Could you please add it or give me a hint where to insert such code?

Best

Henning

**Comment by kingosticks** [comment]
Have you tried the latest code? Does this not do what you want?

**Comment by laclaro** [comment]
I renamed the issue, since it is the browsing view where only the filename is displayed. And I just found that this is most likely an issue (default behavior) of musicbox_webclient.

Thank you anyway.

**Comment by kingosticks** [comment]
OK, you mentioned mpd so I assumed you were taking about mpd. Please open an issue in musicbox-webclient if you think its something we can improve there.
