### ISSUE TITLE
py2cairo not found

### ISSUE THREAD

**Issue by gretzky** [mopidy/mopidy#1675]
Just wanted to toss this out in case anyone else has/had this issue, as I didn't see it tracked anywhere. It may be related to `gst-python` (dependency) or homebrew itself- but I haven't seen this issue until installing mopidy.

When installing mopidy with homebrew, it fails due to py2cairo not being found or its installation being broken. `brew doctor` shows nothing, but it's easily fixed by installing py2cairo with homebrew.

Side note: on certain terminal emulators (kitty), this error isn't displayed, instead the installation hangs up. In iTerm, the actual error is thrown and process exits with error.

If anyone's come across this at all, or knows the root of the issue, I hope this is useful. I'm also happy to contribute to a fix if its found to be an issue that extends my local env.

**Comment by kingosticks** [comment]
Might be issue be better in https://github.com/mopidy/homebrew-mopidy ?
