### ISSUE TITLE
No sound from 3.5mm Ear Jack (using mpc-mopidy-spotify)

### ISSUE THREAD

**Issue by donghoon-lee** [mopidy/mopidy#1678]
Hi,

I have a raspberry pi connected to a NFC reader, with mpc-mopidy-spotify installed and working.

The NFC reader reads in the spotify URI from a NFC card, and sends it to MPC to play the specific song.

With the command 'mpc status', I can see that the specific song is playing with volume set to 100%.

I have raspi-config set to force audio output to the 3.5mm ear jack, and have a speaker connected to the raspberry-pi's ear jack. The speaker successfully outputs sound when I play youtube, but there is no sound coming from the speaker when MPC is running.

Following is my mopidy.conf : 
[audio]
#mixer = softwar
#mixer_volume = 80
#output = autoaudiosink device=hw:1,0
#buffer_time = 

When I run the following command, I can hear an audible tone:
$ gst-launch-1.0 audiotestsrc ! audioresample ! autoaudiosink

My MPC/Mopidy-Spotify is all up to date.

**Please let me know if any of you have any idea on how I might solve this issue.**

Thank you :)

**Comment by kingosticks** [comment]
Hey, this issue tracker is for bugs and feature requests. Usage help belongs at https://discourse.mopidy.com so can I ask you to repost there? Please include the output of `mopidy config` (or `sudo mopidyctl config` if running as a service). You may even find the answer to your problem on there already. Thanks
