### ISSUE TITLE
Can't install plz help

### ISSUE THREAD

**Issue by MYDEARBOMB** [mopidy/mopidy#1682]
I follow the guide to make install step-by-step but I try many times always "Error: Empty installation"
Even I download zip and brew it still not worked.
I tried many ways, like install just Pykka, and then reinstall, and still failed.
Please help.

brew install mopidy
==> Installing mopidy from mopidy/mopidy
==> Installing dependencies for mopidy/mopidy/mopidy: mopidy/mopidy/python-pykka, mopidy/mopidy/python-backports-abc, mopidy/mopidy/python-backports-ssl-match-hostname, mopidy/mopidy/python-certifi, mopidy/mopidy/python-six, mopidy/mopidy/python-singledispatch, mopidy/mopidy/python-tornado, mopidy/mopidy/python-requests
==> Installing mopidy/mopidy/mopidy dependency: mopidy/mopidy/python-pykka
==> Downloading https://files.pythonhosted.org/packages/source/P/Pykka/Pykka-1.2
==> Downloading from https://files.pythonhosted.org/packages/70/f7/bb8fc78fc52a5
######################################################################## 100.0%
Error: Empty installation

**Comment by jodal** [comment]
I observed this issue myself a couple of days ago and will look into it. The Homebrew tap is in need of a general refresh.

**Comment by jodal** [comment]
Closing this in preference for mopidy/homebrew-mopidy/#27, which is in the proper repo.

**Comment by jodal** [comment]
This issue should be fixed now. Please read my comment at https://github.com/mopidy/homebrew-mopidy/issues/27#issuecomment-394204882 for further help if the upgrade fails somehow.
