### ISSUE TITLE
Support py-idna 2.7

### ISSUE THREAD

**Issue by PureTryOut** [mopidy/mopidy#1687]
Right now mopidy requires a py-idna version between 2.5 and 2.7. I've been cleaning up the package for Alpine Linux [here](https://github.com/alpinelinux/aports/pull/4440), but py-idna got updated by the distro to 2.7 so mopidy won't build anymore. Please add support for py-idna 2.7 so I can package this properly for Alpine Linux.

**Comment by kingosticks** [comment]
Where is this dependency? I don't see it on our setup.py, what am I missing?

**Comment by PureTryOut** [comment]
Ah my mistake. It seems it's a dependency of sphinx, which is used to generate the documentation. Has nothing to do with mopidy, sorry :wink:
