### ISSUE TITLE
Bluetooth backend advancement

### ISSUE THREAD

**Issue by daverck** [mopidy/mopidy#1691]
This post is to revive the request for an hightly anticipated bluetooth backend 🏁 📶 

see
[https://github.com/mopidy/mopidy/issues/705](https://github.com/mopidy/mopidy/issues/705)
[https://github.com/mopidy/mopidy/issues/1118](https://github.com/mopidy/mopidy/issues/1118)

also
[https://github.com/jaedb/Iris/issues/314](https://github.com/jaedb/Iris/issues/314)

Can we make this happen ?

**Comment by adamcik** [comment]
Closing this bug as the features are already tracked in their own bugs.
