### ISSUE TITLE
Python Error mith latest Mopidy on Antergos

### ISSUE THREAD

**Issue by domsch1988** [mopidy/mopidy#1693]
I just tried setting up mopidy and am getting some Python error. Trace:

```
Traceback (most recent call last):
  File "/usr/bin/mopidy", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'futures' distribution was not found and is required by tornado
```

Reinstalling python-tornado, mopidy or python-future didn't fix that.

**Comment by charbar** [comment]
I fixed the same error by installing python2-futures (not the same as either python-future or python2-future).

**Comment by charbar** [comment]
I'm using python2-tornado 5.1.0-1 from the Arch repos without any problems.

**Comment by kingosticks** [comment]
You just said you fixed your problems by installing another package. It's a dependency problem.

**Comment by charbar** [comment]
Seems like it. python2-futures is considered an optional dependency for python2-tornado in the Arch repos. After python2-tornado was updated 2 days ago in the repos to 5.1.0-1, Mopidy would no longer work (On my Arch install, at least. I was previously using python2-tornado 4.5.3-1) without python2-futures. I guess if Mopidy uses python2-tornado<5, it won't need python2-futures? But it will if it uses python2-tornado>5?

**Comment by kingosticks** [comment]
The <5 dependency change was originally to avoid requiring a more recent version of  python2.7 than Travis CI provides: see https://github.com/mopidy/mopidy/commit/86e5e7d34729e0cb644e46d68af5c18348c94585. 

I'm not sure I understand why python2-futures is optional considering the [Tornado v5.0.0. changelog](http://www.tornadoweb.org/en/stable/releases/v5.0.0.html):
> The futures (concurrent.futures backport) package is now required on Python 2.7.

Isn't this an Arch bug?

**Comment by charbar** [comment]
I think it is. I'll file an Arch bug report.

**Comment by kingosticks** [comment]
Can I close this then?

**Comment by domsch1988** [comment]
My response somehow got eaten by my connection, sorry.

Yes, this can be closed. Was able to fix it by installing the correct dependencies as mentioned above by hand. Thanks for the help everyone.

**Comment by parkerlreed** [comment]
```
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tornado<5,>=4.4' distribution was not found and is required by Mopidy
```

Is this related? Using mopidy-git

**Comment by kingosticks** [comment]
@trygveaa have you run into this?

**Comment by parkerlreed** [comment]
What I ended up using was mopidy release and gmusic git.

But yeah mopidy master doesn't seem to like tornado being updated. All the packages I can find are either version 6 or version 401 (Arch AUR)

**Comment by kingosticks** [comment]
Thanks for the update @parkerlreed. I'll look into what we need for v5.x to work with Travis.
