### ISSUE TITLE
Mopidy HDMI sound

### ISSUE THREAD

**Issue by mluired** [mopidy/mopidy#1699]
Hi. I am encountering some problems with Mopidy in Raspberry Pi B+

I have the following extensions in osmc (raspbmc).

osmc@osmc:~$ apt-cache search mopidy
mopidy - music server with support for MPD/HTTP clients
mopidy-doc - music server with support for MPD/HTTP clients - documentation
mopidy-alsamixer - Mopidy extension for extension for ALSA volume control
mopidy-beets - Mopidy extension for playing music from Beets' web plugin
mopidy-dirble - Mopidy extension for browsing Dirble's radio station directory
mopidy-dleyna - Mopidy extension for playing music from Digital Media Servers
mopidy-internetarchive - Mopidy extension for playing music from the Internet Archive
mopidy-local-sqlite - Mopidy extension for keeping your local library in SQLite
mopidy-podcast - Mopidy extension for searching and browsing podcasts
mopidy-podcast-itunes - Mopidy extension for searching and browsing iTunes podcasts
mopidy-scrobbler - Mopidy extension for scrobbling music to Last.fm
mopidy-somafm - Mopidy extension for playing music from SomaFM
mopidy-soundcloud - Mopidy extension for playing music from SoundCloud
mopidy-tunein - Mopidy extension for playing music from TuneIn
mopidy-youtube - Mopidy extension for playing music from YouTube
mopidy-podcast-gpodder - Mopidy extension for searching and browsing gpodder.net podcasts
mopidy-mpris - Mopidy extension for controlling playback through MPRIS
mopidy-spotify - Mopidy extension for playing music from Spotify
mopidy-spotify-tunigo - Mopidy extension for providing the browse feature of Spotify

I am trying to play music with Spotify account. I am testing sound with aplay but I can not execute any aplay command. 

osmc@osmc:~$ aplay /usr/share/sounds/alsa/Front_Center.wav
-bash: aplay: command not found

The config file for mopidy (as a service) is 

[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy
#max_tracklist_length = 10000
#restore_state = false

[logging]
config_file = /etc/mopidy/logging.conf
debug_file = /var/log/mopidy/mopidy-debug.log

[local]
media_dir = /var/lib/mopidy/media
enabled = true

[http]
enabled = true
hostname = 0.0.0.0
port = 6680

[m3u]
playlists_dir = /var/lib/mopidy/playlists

[spotify]
username = 111367496
password = **********
client_id = 72c89b8a-dc1e-4865-8ad3-5338fc6e34f9¡8
client_secret = REDACTED
bitrate = 320

[spotify_tunigo]
enabled = true

[mopify]
enabled = true
debug = false

[audio]
mixer = software
mixer_volume = 8
output = autoaudiosink
buffer_time = ""

[websettings]
enabled = true
musicbox = true
config_file = /etc/mopidy/mopidy.conf
[spotify_web]
enabled = true
[gmusic]
enabled = false
[tunein]
enabled = true
[podcast]
enabled = false
[internetarchive]
enabled = true
[youtube]
enabled = false
[audioaddict]
enabled = false
quality = 40k
difm = false
radiotunes = false
rockradio = false
jazzradio = false
frescaradio = false
[somafm]
enabled = true
[soundcloud]
enabled = false
[network]
enable_ssh = false
enable_firewall = false

[musicbox]
scan_always = false
webclient = musicbox_webclient
downsample_usb = false
enable_upnp = false
enable_shairport = false
enable_stream_watchdog = false
enable_connect = true
[dirble]
enabled = false
[scrobbler]
enabled = false
[subsonic]
enabled = false
ssl = no

Thanks in advance.

**Comment by kingosticks** [comment]
I've edited your post to remove the Spotify client secret. Please use `sudo mopidyctl config` to show the effective config. I'm a little confused why there is a `musicbox` section in there but I guess it's benign.

I'm not familiar with osmc but my guess is that it uses pulseaudio and the alsa packages are not installed.

**Comment by kingosticks** [comment]
There's a lot going on in that config and I'm sure you don't need most of it. 
* In your `sudo mopidyctl config` output there's no `[spotify]` section, which suggests it's not actually installed properly. `sudo mopidyctl deps` shows you all the extensions Mopidy can find.
* The `[musicbox]` section is for PiMusicbox **ONLY**. Mopidy-Musicbox-Webclient is configured using a `[musicbox_webclient]` section which, like all other extensions, is only required when you need to set something other than the default (which you probably don't).

> It is strange because I have a lot of errors when I install anything.

I'd probably start by fixing these errors....

> Why aplay /usr/share/sounds/alsa/Front_Center.wav is not working as a valid command?

aplay is installed as part of the alsa-utils package. Not all systems will have this installed by default, perhaps you need to install it.


This doesn't sound like a problem with Mopidy specifically. As you saw when you created this issue, this is not the place to get support:
> Please use https://discourse.mopidy.com/ for support questions.
>
>GitHub Issues should only be used for confirmed problems with Mopidy and well-defined feature requests.

Please feel free to start a new post on the support forum if you are still having problems using Mopidy.
