### ISSUE TITLE
why not play this radio??

### ISSUE THREAD

**Issue by alfaktulu** [mopidy/mopidy#1703]
Hello:

Why not play this radio http://stream.radiojar.com/ys6u7b05t3duv.mp3?1537489766 

Thanks, good job. I use mopidy in a Orange Pi zero. Is awesome!

**Comment by kingosticks** [comment]
Please post your questions at https://discourse.mopidy.com/c/mopidy and include your deps and a log as described at  https://docs.mopidy.com/en/latest/troubleshooting/
