### ISSUE TITLE
Distribute as Flatpak

### ISSUE THREAD

**Issue by ajvsol** [mopidy/mopidy#1717]
Could we get a Flatpak build? It's easier to back up, can be run on any distro and distro version etc

**Comment by kingosticks** [comment]
We probably need someone in the community to do this and maintain it. If there is anything we need to support in order to make it easier for that someone then please say.

**Comment by hadess** [comment]
That would help me greatly, as most of my attempts at getting the PiMusicBox build automated somewhat have run into uncooperative maintainers (not in mopidy or PiMusicBox, but in the tools I tried to use to automate it).

A couple of notes:
- Flatpak isn't really built to handle non-GUI applications, but it can handle those nonetheless. Building a Flatpak might be a way to build a [systemd portable service](http://0pointer.net/blog/walkthrough-for-portable-services.html), which might or might not be something better suited for release by mopidy itself.
- Building "pip" based modules is be fairly straight forward ([example](https://github.com/flathub/org.musicbrainz.Picard/blob/master/org.musicbrainz.Picard.json#L163-L176)), though defining loads manually would be a pretty awkward, but there's a [tool to help with this](https://github.com/flatpak/flatpak-builder-tools/tree/master/pip), and that could be automated.
- There's a list of Python dependencies in PiMusicBox ([script](https://github.com/pimusicbox/pimusicbox/blob/develop/create_musicbox0.7.sh))

I might give this a try.

**Comment by adamcik** [comment]
Since this isn't an issue about a feature or bug in mopidy itself, but something that would be solved externally I'm closing this issue. Feel free to reach out if changes in Mopidy are needed to realize this.
