### ISSUE TITLE
http/allowed_origins config does not work

### ISSUE THREAD

**Issue by morgoth** [mopidy/mopidy#1719]
Hi.
After adding new config https://github.com/mopidy/mopidy/pull/1668, my online player stopped working (you can find it on http://mopster.cowbell-labs.com)
I added config
```
[http]
allowed_origins = http://mopster.cowbell-labs.com
```
but it didn't help and in the logs I'm getting:
```
2018-10-28 17:54:13,002 WARNING [4937:HttpServer] mopidy.http.handlers: HTTP request denied for Origin "http://mopster.cowbell-labs.com"
2018-10-28 17:54:13,006 WARNING [4937:HttpServer] tornado.access: 403 GET /mopidy/ws/ (192.168.0.101) 5.17ms
```

Is this some misconfiguration on my side or a bug?
I can't see a test case for a provided config value

**Comment by kingosticks** [comment]
The code is pretty fussy and expects `allowed_origins` values to literally be in the same format as the host header: `hostname`[:`port`] i.e. no scheme. This is unnecessarily unforgiving and maybe we should transform the config values into the expected format. Either way, better documentation is obviously required. The following should work:
```
[http]
allowed_origins = mopster.cowbell-labs.com
```
The most relevant test is [here](https://github.com/mopidy/mopidy/blob/develop/tests/http/test_handlers.py#L126-L129).

**Comment by morgoth** [comment]
Yes, thank you - that helps a lot and is working as expected.

**Comment by lblabr** [comment]
i'm trying to configure a reverse proxy, but the found configurations does not work ....

i do get: 

 HTTP request denied for Origin "http://10.100.10.181:8090"

i also configured 10.100.10.181:8090 in allowed_origin

but it does not help

any ideas?
