### ISSUE TITLE
Mopidy randomly hanging when starting new songs

### ISSUE THREAD

**Issue by Wqrld** [mopidy/mopidy#1721]
Every time mopidy starts a new song it goes forward, skip to the begin, go forward without any playback. Setting the track time seems to fix it but it is not fun to have to reopen the music tab every time a song finishes. 

Newest mopidy on raspbian

**Comment by Wqrld** [comment]
basically time played: 0, it goes forward 4 seconds and then back to 0

**Comment by Wqrld** [comment]
fixed by having spotify off

**Comment by Wqrld** [comment]
update: just got 
WARNING  Spotify has been paused because your account is being used somewhere else.
but this did not happen before.

**Comment by kingosticks** [comment]
Please re-open if you can provide a way to reproduce and/or full logs.
