### ISSUE TITLE
Napster extension

### ISSUE THREAD

**Issue by MarcSN311** [mopidy/mopidy#1729]
Has anyone ever attempted a Napster extension?
I just had a brief look at the API, but it just seems to be javascript to include their player: https://developer.napster.com/

**Comment by tkem** [comment]
[Apparently](https://docs.mopidy.com/en/latest/ext/backends/) not. So don't just talk about it - do it!

**Comment by AbgleichDing** [comment]
Would love to see Napster integration! Any plans for that?

**Comment by adamcik** [comment]
https://discourse.mopidy.com/t/supporting-new-streaming-services-and-other-music-sources/22/2 is our general advice for adding new extensions. I've not looked at if it would be possible for this one in particular, but it would need someone else to make the extension as we have our hands full with just mopidy itself.

**Comment by MarcSN311** [comment]
shouldn't the "Extension wishlist"  label be added instead of closing the issue?

**Comment by adamcik** [comment]
The label was reanamed and is already applied to this issue. I've updated the discourse post to point at the right label and clarified that we close these as they will not be fixed in Mopidy itself.
