### ISSUE TITLE
soundcloud "404 Not Authorized"

### ISSUE THREAD

**Issue by supremethememe** [mopidy/mopidy#1747]
when i log in with my soundcloud it says "404 Not Authorized"

**Comment by kingosticks** [comment]
Hi, can you please open an issue in the [mopidy-soundcloud repo](https://github.com/mopidy/mopidy-soundcloud) with the full details we would need to look into this. That would be the output of `mopidy deps`, `mopidy config` and a debug log, you can find more info [here](https://docs.mopidy.com/en/latest/troubleshooting/). Thanks.
