### ISSUE TITLE
There is no official and easily accesible "donate" button please add it. 

### ISSUE THREAD

**Issue by maikeldotuk** [mopidy/mopidy#1748]
This project is too good to let it die. So please add a publicly visible "donate" button in both the README on the repo and the website so I and others can throw our cash at it as an incentive to keep it alive. 

Thank you. 

PD: Fix Cantata integration, the library doesn't show.

**Comment by adamcik** [comment]
I appreciate the gesture and suggestion, but money is not the limiting factor for this project in particular. Time is the main constraint for most of the core developers which is spread thin between work, family/life and other commitments. Finding other ways to help the project is greatly appreciated.

The few expenses the project would have had for hosting and other services is provided by free for opensource offerings.

As such I'm opting to close this issue, if any of the other contributors disagree do not hesitate to reopen and address this.

**Comment by jodal** [comment]
I agree. I'm not interested in spending time on figuring out how fairly spend/split any contributions to the project.

If we ever do anything like this, I believe it would have to be direct donations to individuals, e.g. through GitHub Sponsors on their personal GitHub profiles.
