### ISSUE TITLE
Reload state - file does not exist

### ISSUE THREAD

**Issue by weilbith** [mopidy/mopidy#1752]
I configured _Mopidy_ to reload the state on restart.
```toml
[core]
cache_dir = ~/.cache/mopidy
config_dir = ~/.config/mopidy
data_dir = ~/.local/share/mopidy
restore_state = true
```

All named directories does exist and are in usage.

But in the logs on starting the service it states:
```
INFO     Loading state from /home/user/.local/share/mopidy/core/state.json.gz
INFO     File does not exist: /home/user/.local/share/mopidy/core/state.json.gz
INFO     Failed to delete /home/user/.local/share/mopidy/core/state.json.gz
```

I can confirm that the `~/.local/share/mopidy/core` folder is empty.

**Comment by weilbith** [comment]
Or now it seems to work. Don't know why it sometimes does not. Seems to be kinda random. Since I can't specify it further to make it reproducable I close this issue so far.

**Comment by kingosticks** [comment]
I was about to ask if you have a corresponding log life from the previous run showing it successfully saved the state. 

When there isn't any state, you'll get that INFO message (note, it's not an ERROR). And there won't be any state the very first time you run Mopidy after enabling this option (there can't be). There shouldn't be anything random about this behaviour.

**Comment by weilbith** [comment]
Actually I start _Mopidy_ within my `xinitrc` configuration and never touch it then. Not sure if it is related to the restarts. I will try to observe this in future.
Btw: Is is possible to just restore the current playlist and not the state as well? So if I shutdown my PC while actively playing music and start it again on the next day I would love to continue listening where I stopped but started manually (global key bindings). Since it was not working at all so far I haven't had this situation, but observed it now between restarts during testing.

**Comment by kingosticks** [comment]
> Is is possible to just restore the current playlist and not the state as well

I don't believe it is. But it looks like the code was written with that in mind, it's just not currently exposed at all. If you are interested in making it happen, please take a look.

**Comment by weilbith** [comment]
So you mean [this hardcoded list](https://github.com/mopidy/mopidy/blob/f267e8db206df1a9e5c7967af1d1733ab9ce4290/mopidy/core/actor.py#L148)?

**Comment by kingosticks** [comment]
Yes.

**Comment by dublok** [comment]
@weilbith mopidy will store the state if it is stopped normally (e. g.: by `<ctrl>-c` when running from commandline). 
I assume that mopidy will never be stopped if it is started from xinitrc.
For a correct shutdown you could start mopidy as service. see https://docs.mopidy.com/en/latest/service/

**Comment by weilbith** [comment]
@dublok this is very good point :joy:
