### ISSUE TITLE
Checking file exists before shutil.rmtree can cause problem in case of race condition.

### ISSUE THREAD

**Issue by farziengineer** [mopidy/mopidy#1766]
https://github.com/mopidy/mopidy/blob/09240dae2fadafa904c0fb705f643b769ffdcebf/tests/m3u/test_playlists.py#L47-L48

The above snippet of code can cause problem in case of race condition, where file might be present at the time of `if os.path.exists(path)` but might not exist when we try to read the file and result in exception. The python EAFP(Easy to Ask for Forgiveness than Permission) philosophy suggests that we use a try catch block to avoid this problem. [Suggested changes](https://stackoverflow.com/a/56036903/8577285).
You can read [this stackoverflow answer ](https://stackoverflow.com/a/82852/8577285) to understand the problem more 
Can this issue be assigned to me? 
The above snippets can be replaced by the following.
```python
try:
    shutil.rmtree(self.playlists_dir)
except FileNotFoundError as e:
    raise e

**Comment by jodal** [comment]
As this is in a test case teardown, and not a part of the Mopidy application itself, I'm not too afraid of a race condition here.

That is, unless you've actually experienced issues when running this code?

**Comment by noamzilo** [comment]
I have experienced [a problem](https://stackoverflow.com/questions/70507665/folder-seems-to-exist-in-os-but-fails-silently-upon-sudo-rm-rf-dirname?noredirect=1#comment124635826_70507665).

Code

```
if os.path.exists(cluster_folder_path):
    shutil.rmtree(cluster_folder_path)
os.mkdir(cluster_folder_path)
```

I am left with the bad folder described in the link.
