### ISSUE TITLE
Promote PendingDeprecationWarning to DeprecationWarning

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#1773]
We have a small set of `PendingDeprecationWarning` in our source code now:

- [ ] `core.playback.play()` with "tl_track" argument is pending deprecation, use "tlid" instead
- [ ] `core.tracklist.eot_track()` is pending deprecation, use `tracklist.get_eot_tlid()`
- [ ] `core.tracklist.next_track()` is pending deprecation, use `tracklist.get_next_tlid()`
- [ ] `core.tracklist.previous_track()` is pending deprecation, use `tracklist.get_previous_tlid()`

Before the release of 3.0, we should consider upgrading all of these to `DeprecationWarning`, so that they can be removed in 4.0.

**Comment by hugovk** [comment]
Please see PR https://github.com/mopidy/mopidy/pull/1786.

**Comment by jodal** [comment]
Fixed by #1854 .
