### ISSUE TITLE
Subscribe to Playback controller changes

### ISSUE THREAD

**Issue by weilbith** [mopidy/mopidy#1775]
I would be great to get status update of the player in subscription manner instead of polling. It it useless in 99% of the time to poll, but the important events of stopped music or the next track should be displayed as soon as possible. Therefore it would be great if a callback function could be registered to any state change of the playback controller.
At least I was not able to find such within the API documentation.

**Comment by adamcik** [comment]
You are probably looking for https://docs.mopidy.com/en/latest/api/core/#core-events

**Comment by weilbith** [comment]
Damn I can't read. Thanks for your quick answer!!

**Comment by weilbith** [comment]
Having this simple code snippet:

```
from mopidy.core import CoreListener

class MySubscriber(CoreListener):
    def playback_state_change(self, old_state, new_state):
        print(new_state)

MySubscriber()
```

I miss some kind of `start()`, `listen()` or whatever method. How can I start this script and it print each time I change the state until I kill it? :thinking:

**Comment by jodal** [comment]
If you want to build an extension which can listen to events from the Mopidy core, you want to build a Mopidy "frontend". The example in the [frontend section](https://docs.mopidy.com/en/latest/extensiondev/#example-frontend) of the extension dev howto is close to what you want:

``` python
from mopidy.core import CoreListener

import pykka


class MySubscriber(pykka.ThreadingActor, CoreListener):
    def playback_state_change(self, old_state, new_state):
        print(new_state)
```

**Comment by weilbith** [comment]
Must it be an extension or is there also an option to not register this to mopidy? So just run it with `python2 myscript.py` and see the logging messages?

**Comment by jodal** [comment]
Either it must run as part of the Mopidy process as an extension or you can connect to Mopidy using either:

- MPD (see [python-musicpd](https://pypi.org/project/python-musicpd/))
- HTTP/WebSocket (there was recently someone who made a Python library for this. For JavaScript you have [Mopidy.js](https://github.com/mopidy/mopidy.js)
- D-Bus (see [Mopidy-MPRIS](https://github.com/mopidy/mopidy-mpris))
