### ISSUE TITLE
Mopidy no longer working on MacOS

### ISSUE THREAD

**Issue by fatg3erman** [mopidy/mopidy#1777]
Homebrew have dropped support for python2 in their gstreamer packages, so it's no longer possible to install Mopidy on MacOS.

Given also that python2 will no longer be supported after January 2020, is there a plan for migration to python3? I can offer some help.

**Comment by adamcik** [comment]
See #779 for the current state, short version is that a 3.0 release is planned with Python 3 support whenever it's ready.

**Comment by adamcik** [comment]
...and @jodal can probably comment better in the other thread what help might speed things up.

**Comment by jodal** [comment]
As for the Homebrew issue, that is covered in mopidy/homebrew-mopidy#32.
