### ISSUE TITLE
Icecast2 not working

### ISSUE THREAD

**Issue by nscpro** [mopidy/mopidy#1781]
Hi

I have installed a icecast2 server, but if i go iris website in localhost and choose icecast and my aadress is set http://192.168.1.106:8000/mopidy and config file set Audio output set to "lamemp3enc ! shout2send async=true mount=mopidy ip=192.168.1.106 port=8000 password=proov" this does not working my icecast xml file configure password - proov, hostname - 192.168.1.106 and port - 8000. What can i do wrong?

**Comment by kingosticks** [comment]
Please use https://discourse.mopidy.com/ for support questions.

GitHub Issues should only be used for confirmed problems with Mopidy and well-defined feature requests.

When you post in the user forum please explain exactly what doesn't work (the mount is not visible, it's visible but you can't connect ? etc). Also try running with some Mopidy logging and maybe also some icecast logging.
