### ISSUE TITLE
Strange underwater sound when playing acc stream

### ISSUE THREAD

**Issue by karlkar** [mopidy/mopidy#1782]
Hi.
All streams that I play are working correctly, however there's one that uses AAC encoding and I have issues with it. Sound is like underwater. Basses are very low, trebles are too high. Volume of this stream is at least 50% lower than other streams. I had to install gstreamer1.0-plugins-ugly for the stream to work at all.
Looks like a decoding issue to me.
I'm running mopidy on raspberry pi 3 with rasbian duster installed. 
Mopidy 2.2.3.
On other devices stream works fine.
The stream URL is http://stream.open.fm/40
There are no errors in mopidy logs.
Does anybody have any clue what may be wrong and how can I fix that?

**Comment by jodal** [comment]
We don't do any audio decoding ourselves, so this is probably a GStreamer issue.
