### ISSUE TITLE
Stream backend doesn't handle relative URLs in playlists

### ISSUE THREAD

**Issue by fatg3erman** [mopidy/mopidy#1785]
This radio station was playing until a week ago so I can only assume the BBC have been mucking about with their radio API again.

If I add this URI to Mopidy

http://www.radio-browser.info/webservice/v2/m3u/url/97836

The stream backend correctly unwraps it through 3 (yes 3!) further layers of m3u8 files until it gets this:

```
#EXTM3U
#EXT-X-VERSION:3
## Created with Unified Streaming Platform(version=1.8.4)
#EXT-X-MEDIA-SEQUENCE:244668900
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-TARGETDURATION:6
#USP-X-TIMESTAMP-MAP:MPEGTS=2819807648,LOCAL=2019-08-15T14:55:53.600000Z
#EXT-X-PROGRAM-DATE-TIME:2019-08-15T14:55:53.600000Z
#EXTINF:6.4, no desc
bbc_radio_five_live_sports_extra-audio=320000-244668900.ts
#EXTINF:6.4, no desc
bbc_radio_five_live_sports_extra-audio=320000-244668901.ts
#EXTINF:6.4, no desc
bbc_radio_five_live_sports_extra-audio=320000-244668902.ts
#EXTINF:6.4, no desc
bbc_radio_five_live_sports_extra-audio=320000-244668903.ts
#EXTINF:6.4, no desc
bbc_radio_five_live_sports_extra-audio=320000-244668904.ts

```
Relative URIs! Mopidy tries to add these to the playlist and, of course, fails.

If I try with MPD I can (using 'load') play it successfully.

**Comment by kingosticks** [comment]
This is a HLS playlist which I don't think we support, so fixing the relative URI problem probably won't help much (but I have fixed it anyway).
