### ISSUE TITLE
Documentation in webpage about rpi4

### ISSUE THREAD

**Issue by godzillamesel** [mopidy/mopidy#1787]
![bilde](https://user-images.githubusercontent.com/37759816/63226608-0c030080-c1dc-11e9-8fef-7e0765c89aac.png)

I was looking at the docs of RPI ( https://docs.mopidy.com/en/latest/installation/raspberrypi/ ). 
I discovered that rpi4 is not mentioned anywhere yet, as this is the new model! Is it even compatible yet?

**Comment by kingosticks** [comment]
I mean, we say it runs on all models. Which it does. So yes, it's compatible. If you think what we have is somehow unclear please feel free to submit a PR.

**Comment by kingosticks** [comment]
I've modified the docs so we don't need to keep updating to mention new versions. Please do submit a PR (to the master branch) if you think it still could be improved.

**Comment by godzillamesel** [comment]
Sweet 👍 crystalclear now! 💯

**Comment by godzillamesel** [comment]
Hmm, just been working with the RPI4 today, and I have been stuck with a dependency missing to (mopidy-spotify), unfortunally I lost the error when I tried to format the sdcard (I will come back later to that), but i still remember it partially: It was unmeet dependencies that were not going to be installed. It seems that this will not install to Raspbian Buster...

Then I will continue to the sdcard-story:
When i was trying to get Raspbian Stretch, i noticed one little detail:
It references to [this article](https://www.raspberrypi.org/documentation/hardware/raspberrypi/booteeprom.md) that mentions this:
> The Raspberry Pi 4 has an SPI-attached EEPROM (4MBits/512KB), which contains code to boot up the system and replaces bootcode.bin previously found in the boot partition of the SD card. Note that if a bootcode.bin is present in the boot partition of the SD card in a Pi 4, it is ignored.

Well, it seems like you have to downgrade to Raspbian Stretch from a Raspbian Buster to follow [this article](https://wiki.debian.org/DontBreakDebian) ?

**Comment by kingosticks** [comment]
Use the latest Debian Buster release of Raspbian. I've [updated our installation docs](https://github.com/mopidy/mopidy/commit/458380d72449b62582f1fd7904a7e90ccd2607cc) to point to the buster list, which might have been causing a problem. I just followed these steps myself on a Pi 4 and it installed without error.

**Comment by godzillamesel** [comment]
Sweet, will do some day soon. I am currently moving tommorrow. Thanks for help! :D Lovely response on this project! Kudos!

**Comment by godzillamesel** [comment]
It worked for me as well now! :D
