### ISSUE TITLE
Letting the Mopidy daemon run overnight (paused) causes it to freeze/not work the next morning

### ISSUE THREAD

**Issue by BrainStone** [mopidy/mopidy#1790]
When I leave the server running overnight, the next morning it is in the best case very unresponsive or straight won't do anything. The only way to fix it is to restart it.

The symptoms aren't always the same but I can never play anything. Often requests to receive the queue are unresponded and sometimes I can't even connect to the server.

I check the log but couldn't find anything. Main issue with that is that I have a cronjob running that runs `mopidyctl scan local` every minute (to allow unattended updates to the database) that spams the log.  
It might be possible that the scans are the issue, but I don't think so as they only should touch the database file. (Using `mopidy-local-sqlite`)

If you still wish to have the littered log, I can still provide it to you.

**Comment by kingosticks** [comment]
Did you check the debug log? Are we talking mpd or http frontend here?

**Comment by BrainStone** [comment]
Both frontends. Hardly responsive to completely unresponsive. Always differs from day to day.

And where would I find the debug log? I can only find `/var/log/mopidy/mopidy.log`

**Comment by kingosticks** [comment]
Getting a debug log when running as a service is a bit tricky. If you are OK changing the arguments used by the service (edit the service file if using systemd, for example) then add `--save-debug-log`. Otherwise it might be easier to just run Mopidy from the command line. It's probably worth an experiment where you disable that cron job.

**Comment by jodal** [comment]
Please file a new issue if you still experience this with Mopidy >= 3.0, to be released this weekend.
