### ISSUE TITLE
Feature Request: Ad blocking in radio streams

### ISSUE THREAD

**Issue by vKnmnn** [mopidy/mopidy#1818]
There is a project called [adblockradio](https://www.adblockradio.com/blog/2018/11/15/designing-audio-ad-block-radio-podcast/), developed by Alexandre Storelli, which uses a mixture of audio fingerprinting and statistics to be able to mute advertisements in live audio streams.

Alexandre has open-sourced his work and offers his code on [github](https://github.com/adblockradio/adblockradio) 

In my opinion, this would make a great addition to mopidy

**Comment by kingosticks** [comment]
I think I saw this (or something very similar) recently on HackerNews. I thought it'd be nice if someone could integrate it into a GStreamer filter element to make it available to us (and all other Gst-based projects).

**Comment by adamcik** [comment]
I can't see any clean way of integrating this in Mopidy without major architecture changes, other than having it built into GStreamer. As such this isn't something we are going to work on in Mopidy itself. If someone integrates it with GStreamer feel free to reach out again.
