### ISSUE TITLE
auth.mopidy.com is down

### ISSUE THREAD

**Issue by seb-b** [mopidy/mopidy#1819]
Our mopidy went down, we use iris as a frontend and digging through the stacktrace brought me to a request to this url, which seems to be down.

**Comment by jodal** [comment]
I received an email notification from Rackspace a few hours ago about the VM's host having issues. Will follow up.

**Comment by jodal** [comment]
Latest message from Rackspace, nine hours ago:

> This message is to inform you that the host your cloud server '...' resides on became unresponsive. We have rebooted the server and will continue to monitor it for any further alerts.

The server is still unavailable, so I've asked for further details or an estimated time of fix.

**Comment by jodal** [comment]
And we're back online!
