### ISSUE TITLE
Yunohost app

### ISSUE THREAD

**Issue by HyperCriSiS** [mopidy/mopidy#1832]
Hi,

would it be possible that you create a yunohost app?
[https://yunohost.org/#/packaging_apps](url)

Regards,
Hyper

**Comment by adamcik** [comment]
See https://discourse.mopidy.com/t/supporting-new-streaming-services-and-other-music-sources/22/2

**Comment by adamcik** [comment]
This probably possible, but I doubt this is anyone working directly on mopidy is going to have time for. If someone familiar with Yunohost wants to make this happen it shouldn't need our involvement? As such I'm closing this isn't a bug or anything in Mopidy itself.
