### ISSUE TITLE
Install docs for RPi forgot to install mopidy

### ISSUE THREAD

**Issue by adrianmay** [mopidy/mopidy#1847]
As title.

**Comment by kingosticks** [comment]
The title makes no sense to me.

**Comment by kingosticks** [comment]
OK, I see. The all important step 5 isn't being rendered for some reason.

**Comment by kingosticks** [comment]
It wasn't rendered because some bight spark (me) accidentally removed it. Thanks for pointing this out.

**Comment by kingosticks** [comment]
Fixed in a9ddb36
