### ISSUE TITLE
Awful sound when playing FLAC 44.1 khz

### ISSUE THREAD

**Issue by f1xmAn** [mopidy/mopidy#1858]
Please take a look at [the recording](https://www.dropbox.com/s/wsef5oak9h4ozoy/2019-12-15%2021.39.54.mp3?dl=0).
Here is the original [file](https://www.dropbox.com/s/lz03ly3hksgjcsp/01%20-%20Part%20One.flac?dl=0).
As you can see, the difference is huge. However, 96khz FLAC files played awesomely.

mopidy version is 2.2.3, installed on Raspbian (Buster).

**Comment by adamcik** [comment]
All of the audio handling is done by GStreamer, I would try with `gst-play` as described in https://gstreamer.freedesktop.org/documentation/frequently-asked-questions/using.html?gi-language=c#how-do-i-use-the-gstreamer-command-line-interface - it that works and mopidy is still broken then it might be something we can fix, otherwise it's a pure GStreamer upstream issue.

Also knowning the version of GStreamer, e.g. `mopidy deps` output would help.

**Comment by f1xmAn** [comment]
You're right, it's a GStreamer bug. Thanks.

**Comment by f1xmAn** [comment]
> All of the audio handling is done by GStreamer, I would try with `gst-play` as described in https://gstreamer.freedesktop.org/documentation/frequently-asked-questions/using.html?gi-language=c#how-do-i-use-the-gstreamer-command-line-interface - if that works and mopidy is still broken then it might be something we can fix, otherwise it's a pure GStreamer upstream issue.
> 
> Also knowning the version of GStreamer, e.g. `mopidy deps` output would help.

Is it possible to replace GStreamer with Xine or anything else?

**Comment by kingosticks** [comment]
No. But you might be able to find help from the gstreamer IRC channel or mailing list. I don't know what the actual problem is here but sometimes you can specify extra parameters to fix sample rate issues, for example.

**Comment by f1xmAn** [comment]
Some info for those who struggle with the same issue: it seems like a [bug in gstreamer with alsasink](https://gitlab.freedesktop.org/gstreamer/gstreamer/issues/476). Workaround is to configure mopidy to work with [PulseAudio](https://docs.mopidy.com/en/latest/service/#configure-pulseaudio).

**Comment by kingosticks** [comment]
OK thanks. Or use software resampling as also mentioned in that gst thread. Thanks very much for coming back and updating with what you found.

**Comment by f1xmAn** [comment]
> Or use software resampling as also mentioned in that gst thread. Thanks very much for coming back and updating with what you found.

Can you help me to configure resampling? I've tried the following config
`output = audioresample ! audio/x-raw,rate=48000 ! alsasink`
but mopidy can't play audio. The log is full of the following lines:
```
2020-02-09 17:05:20,606 ERROR [468:MainThread] mopidy.audio.gst: GStreamer error: gst-resource-error-quark: Could not open audio device for playback. (6)
2020-02-09 17:05:20,606 WARNING [468:Audio-2] mopidy.audio.actor: Setting GStreamer state to GST_STATE_PLAYING failed
2020-02-09 17:05:20,608 WARNING [468:Core-8] mopidy.core.tracklist: Track is not playable: local:track:music/Slipknot%20-%20.5_%20The%20Gray%20Chapter/12%20-%20Be%20Prepared%20for%20Hell.flac
```
Here is the full config:
```
[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy

[logging]
config_file = /etc/mopidy/logging.conf
debug_file = /var/log/mopidy/mopidy-debug.log

[local]
media_dir = /home/pi/data/funkwhale
library = sqlite
scan_flush_threshold = 100

[local-sqlite]
enabled = true
use_album_mbid_uri = true

[m3u]
playlists_dir = /var/lib/mopidy/playlists

[audio]
output = audioresample ! audio/x-raw,rate=48000 ! alsasink

[http]
enabled = true
hostname = 192.168.1.42
port = 6680
static_dir =
zeroconf = Mopidy HTTP server on $hostname
allowed_origins =
csrf_protection = true

[funkwhale]
enabled = true
url = <secret>
client_id = <secret>
client_secret = <secret>
cache_duration = 600

[mpd]
hostname = 0.0.0.0
```

**Comment by f1xmAn** [comment]
I've added `device=hw:1,1` after alsasink and it started working.
