### ISSUE TITLE
not showing extetion mopidy on web clinet

### ISSUE THREAD

**Issue by hosein33** [mopidy/mopidy#1864]
i install mopidy  on ubuntu os with apt  and install spotify extention but not showing extention on web client

**Comment by kingosticks** [comment]
Hi, usage issues belong at https://discourse.mopidy.com/ but I can answer this here quickly. Mopidy-Spotify 4 (the version required for use with Mopidy 3) has not yet been uploaded to apt.mopidy.com. We have not yet announced that all Debian packages are available but will do so when they are.

**Comment by kingosticks** [comment]
Mopidy-Spotify 4 should now be available apt.mopidy.com.
