### ISSUE TITLE
Add support for libcec based control

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#187]
Using libcec we could control devices and/or be controlled via HDMI CEC. See http://www.pulse-eight.com/store/products/104-usb-hdmi-cec-adapter.aspx

**Comment by saberone** [comment]
Is this still being worked on? XBMC also uses the Pulse Eight library, and that works well with HDMI CEC.

**Comment by kingosticks** [comment]
Nobody is currently working on this AFAIK.
