### ISSUE TITLE
Question: Disable lookup for browsed Ref.tracks ?

### ISSUE THREAD

**Issue by Eluminae** [mopidy/mopidy#1880]
Context: 
I work on a subsonic backend and I'm browsing artist/albums/tracks.
When returning a list of Ref.track, mopidy want to lookup those uri one by one with my library.

Question: 
It it possible to disable automatic lookup on discovered Ref.track ?
Mopidy can't just lookup uri only if I add them to the queue ?

This case force me to cache model.Tracks on browsing and this is not really convenient. I do not want to caches data.

**Comment by kingosticks** [comment]
> mopidy want to lookup those uri one by one with my library.

Where does Mopidy Core do that?

**Comment by Eluminae** [comment]
> > mopidy want to lookup those uri one by one with my library.
> 
> Where does Mopidy Core do that?

I dunno. But my library.lookup method is call on every Ref.track
returned and my client freeze waiting results.

**Comment by kingosticks** [comment]
Could it be your client thats doing those lookups? Considering Mopidy doesn't do "automatic lookup"s (that would entirely defeat the point of our `Ref`s), I think that's pretty likely.

**Comment by Eluminae** [comment]
> Could it be your client thats doing those lookups? Considering Mopidy doesn't do "automatic lookup"s (that would entirely defeat the point of our `Ref`s), I think that's pretty likely.

I do not call any lookup by myself. Plus, only Ref.track trigger thoses
lookups. Ref.directory/album/artist does not.

I link here the line where Ref.tracks that seems to trigger mopidy
lookups are instanciated.

https://hg.sr.ht/~reedwade/mopidy_multisonic/browse/default/mopidy_multisonic/browser.py#L102

I totaly agree with you. This automatic lookup seems illogic. I just
guessed mopidy really want albums, duration, artists values.

**Comment by Eluminae** [comment]
Oh my. I think I understood your point. You think ncmcpp trigger lookups
?

**Comment by kingosticks** [comment]
Yes. If you turn on the verbose logging you'll see what the client is doing. Perhaps you can stop ncmcpp from doing that.

**Comment by Eluminae** [comment]
There is no secret data so I just paste logs here.
I really don't know if my client request additional informations about tracks.
As you can see, lookups are done before sending the response.
```
DEBUG    2020-02-05 23:32:36,973 [7825:MultisonicBackend-3] mopidy_multisonic.backend
  Browse multisonic:banal:album:53
DEBUG    2020-02-05 23:32:36,978 [7825:MultisonicBackend-3] urllib3.connectionpool
  Starting new HTTPS connection (1): music.misterbanal.net:443
DEBUG    2020-02-05 23:32:37,287 [7825:MultisonicBackend-3] urllib3.connectionpool
  https://music.misterbanal.net:443 "GET /rest/getAlbum?id=53&f=json&u=StacyHarper&t=a1f2a6c30a739c088c02bcedcef2f741&s=56c2e38b1f82433d9989f1ec8044e733 HTTP/1.1" 200 2171
DEBUG    2020-02-05 23:32:37,292 [7825:MultisonicBackend-3] mopidy_multisonic.backend
  Hydrate model: multisonic:banal:track:731
DEBUG    2020-02-05 23:32:37,293 [7825:MultisonicBackend-3] mopidy_multisonic.backend
  Hydrate model: multisonic:banal:track:733
DEBUG    2020-02-05 23:32:37,294 [7825:MultisonicBackend-3] mopidy_multisonic.backend
  Hydrate model: multisonic:banal:track:732
DEBUG    2020-02-05 23:32:37,294 [7825:MultisonicBackend-3] mopidy_multisonic.backend
  Hydrate model: multisonic:banal:track:729
DEBUG    2020-02-05 23:32:37,295 [7825:MultisonicBackend-3] mopidy_multisonic.backend
  Hydrate model: multisonic:banal:track:730
DEBUG    2020-02-05 23:32:37,297 [7825:MultisonicBackend-3] mopidy_multisonic.backend
  Lookup multisonic:banal:track:731
DEBUG    2020-02-05 23:32:37,298 [7825:MultisonicBackend-3] mopidy_multisonic.backend
  Lookup multisonic:banal:track:733
DEBUG    2020-02-05 23:32:37,300 [7825:MultisonicBackend-3] mopidy_multisonic.backend
  Lookup multisonic:banal:track:732
DEBUG    2020-02-05 23:32:37,302 [7825:MultisonicBackend-3] mopidy_multisonic.backend
  Lookup multisonic:banal:track:729
DEBUG    2020-02-05 23:32:37,303 [7825:MultisonicBackend-3] mopidy_multisonic.backend
  Lookup multisonic:banal:track:730
DEBUG    2020-02-05 23:32:37,304 [7825:MpdSession-12] mopidy_mpd.session
  Response to [::ffff:127.0.0.1]:36174:
    file: multisonic:banal:track:731
    Time: 228
    Artist: 3 Doors Down
    Album: Acoustic EP
    Title: Let Me Go
    Date: 2005
    Track: 1
    AlbumArtist: 3 Doors Down
    Disc: 1
    X-AlbumUri: multisonic:banal:album:53
    file: multisonic:banal:track:733
    Time: 285
    Artist: 3 Doors Down
    Album: Acoustic EP
    Title: Landing in London
    Date: 2005
    Track: 2
    AlbumArtist: 3 Doors Down
    Disc: 1
    X-AlbumUri: multisonic:banal:album:53
    file: multisonic:banal:track:732
    Time: 233
    Artist: 3 Doors Down
    Album: Acoustic EP
    Title: Here Without You
    Date: 2005
    Track: 3
    AlbumArtist: 3 Doors Down
    Disc: 1
    X-AlbumUri: multisonic:banal:album:53
    file: multisonic:banal:track:729
    Time: 190
    Artist: 3 Doors Down
    Album: Acoustic EP
    Title: Be Somebody
    Date: 2005
    Track: 4
    AlbumArtist: 3 Doors Down
    Disc: 1
    X-AlbumUri: multisonic:banal:album:53
    file: multisonic:banal:track:730
    Time: 180
    Artist: 3 Doors Down
    Album: Acoustic EP
    Title: My World
    Date: 2005
    Track: 5
    AlbumArtist: 3 Doors Down
    Disc: 1
    X-AlbumUri: multisonic:banal:album:53
    OK
DEBUG    2020-02-05 23:32:37,306 [7825:MpdSession-12] mopidy_mpd.session
  Request from [::ffff:127.0.0.1]:36174: idle
```

**Comment by Eluminae** [comment]
Maybe this is a  Mopid-MPD module issue?

**Comment by Eluminae** [comment]
https://github.com/mopidy/mopidy-mpd/blob/master/mopidy_mpd/dispatcher.py#L314

**Comment by kingosticks** [comment]
Possibly, it's not a Mopidy Core issue. Please provide the full the log if you decide to open another bug report for that repo, then we could see what command it was responding to.
