### ISSUE TITLE
Error in installing

### ISSUE THREAD

**Issue by DinosXa** [mopidy/mopidy#1886]
Error: Failure while executing; `git clone https://github.com/mopipy/homebrew-mopidy /usr/local/Homebrew/Library/Taps/mopipy/homebrew-mopidy` exited with 128.

i have this error. Any suggestions ?

**Comment by kingosticks** [comment]
Please ask in the homebrew repo. But, I would say that the url you've posted is wrong.

**Comment by jodal** [comment]
`mopipy` vs `mopidy` in `brew tap `mopidy/mopidy`.
