### ISSUE TITLE
Buffering Problems when playing FLAC from a media server.

### ISSUE THREAD

**Issue by DerNuntius** [mopidy/mopidy#1901]
Hi,
So I have some issues with buffering when playing a FLAC file from a tidal media server (or my HomeServer..same issue). I played it back with gst-launch to get a proper verbose output. 
And apparently I get an interrupt in the gstreamer pipeline after ca. every 30sec. The playback skips when buffering and it's very annoying.

Here is the verbose log:
`audio-codec=(string)"Free\ Lossless\ Audio\ Codec\ \(FLAC\)", minimum-bitrate=(uint)583033, maximum-bitrate=(uint)920845, bitrate=(uint)741438;
Buffering, setting pipeline to PAUSED ...
Done buffering, setting pipeline to PLAYING ...
`

I did some research and a few people seemed to fix it by disabling the gstreamer buffer.  
`--gstout-buffer-duration=0 `
I don't know how to patch gstreamer with this env.
Has the debian buster release of gstreamer an older header?

Here is my mopidy.conf file:
`[core]`
`cache_dir = $XDG_CACHE_DIR/mopidy`
`config_dir = $XDG_CONFIG_DIR/mopidy`
`data_dir = $XDG_DATA_DIR/mopidy`
`max_tracklist_length = 10000`
`restore_state = false`

`[logging]`
`verbosity = 0`
`format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s`
`color = true`
`config_file =`

`[audio]`
`mixer = software`
`mixer_volume = `
`output = alsasink`
`buffer_time =  `

`[tidal]`
`enabled = true`
`username = `
`password = `
`quality = LOSSLESS`

`[iris]`
`enabled = true`
`country = NZ`
`locale = en_NZ`
`spotify_authorization_url = https://jamesbarnsley.co.nz/iris/auth_spotify.php`
`lastfm_authorization_url = https://jamesbarnsley.co.nz/iris/auth_lastfm.php`
`genius_authorization_url = https://jamesbarnsley.co.nz/iris/auth_genius.php`
`data_dir = $XDG_DATA_DIR/iris`

`[http]`
`enabled = true`
`hostname = 0.0.0.0`
`port = 6680`
`zeroconf = Mopidy HTTP server on $hostname`
`allowed_origins = `
`csrf_protection = true`
`default_app = mopidy`

`[softwaremixer]`
`enabled = true`

`[stream]`
`enabled = true`
`protocols = `
  `http`
  `https`
  `mms`
  `rtmp`
  `rtmps`
  `rtsp`
`metadata_blacklist = `
`timeout = 5000`

**Comment by DerNuntius** [comment]
Update:
So I figured out that Debian Buster gstreamer deb package is based off gstreamer version 1.14.4. They fixed the buffer issue in 1.16:

`queue2: avoid ping-pong between 0% and 100% buffering messages if upstream is pushing buffers larger than one of its limits, plus performance optimisations`

So I installed the gstreamer package from the upstable/bullseye repository (no time to compile it manually) and now everything works perfectly :)

**Comment by kingosticks** [comment]
Good find, thanks for the update that's really interesting. There's probably something to be said for providing some sort of container with the very latest GStreamer. We often end up victim of some GST bug and we're stuck with this version for a long time now.
