### ISSUE TITLE
Assert statement used outside of tests

### ISSUE THREAD

**Issue by pnijhara** [mopidy/mopidy#1903]
Since assert provides an easy way to check some condition and fail execution, it’s very common for developers to use it to check validity. But when the Python interpreter is invoked with the -O (optimize) flag, the assert statements are removed from the bytecode.

Files:
```
mopidy/audio/utils.py
mopidy/core/actor.py
mopidy/core/playback.py
mopidy/core/tracklist.py
mopidy/ext.py
```
are using assert statements.

**Comment by jodal** [comment]
I marked this as a good first issue. The immediate solution is to change from:

```python
assert condition, "Error message"
```

To:

```python
if not condition:
    raise AssertionError("error message")
```

This makes the code behave in the exact same way as it does today, but won't be optimized away when running python with `-O`.

**Comment by pnijhara** [comment]
@jodal, should I solve this or let other first time contributors to solve?

**Comment by jodal** [comment]
Feel free to tackle this if you're interested!

If it was very many instances of the issue, it could make sense to split it up into multiple pull requests by area of the codebase. However, it looks like there are not that many instances, so I suggest just making a single PR fixing all cases.

Counts of `assert` per file, excluding tests:

```
$ rg -c assert mopidy
mopidy/ext.py:3
mopidy/core/actor.py:1
mopidy/core/tracklist.py:8
mopidy/audio/utils.py:1
mopidy/core/playback.py:1
```

**Comment by asmijafar20** [comment]
Hey @pnijhara @jodal I want to work on this issue. Can you please assign me this as I'm first time contributor.

**Comment by kingosticks** [comment]
There's information at https://docs.mopidy.com/en/latest/contributing/ and also at https://docs.mopidy.com/en/latest/devenv/ on how to setup a development environment and run the tests and linters etc.
