### ISSUE TITLE
Official docker image for modipy ?

### ISSUE THREAD

**Issue by M-Gregoire** [mopidy/mopidy#1905]
First of all, thank you for Modipy!

I noticed your installation documentation never mention installation with `docker` and I couldn't find any information about an official Dockerfile that could be use.

I know they are a few Dockerfile for modipy available on Github but most of them are not maintained or are not customizable, meaning only the writer of the Dockerfile can realistically use it "as is".

When deploying multiple software such as Modipy on the same server, installing directly on the OS is quickly unsustainable for maintenance, backups and migration.

Is there any plan of producing an official docker image that could be trusted and maintained up to date by the community? If not, would you be ready to consider this as a feature request? I'm pretty sure I'm not the only one that would be interested in such a feature!

Thank you

**Comment by jjok** [comment]
I don't believe there's any plan to have an official Docker image.

Here's a conversation about it from a while ago:

https://discourse.mopidy.com/t/legit-upto-date-docker-image/2595

You can search for "docker" on the forum to find other related discussions.

**Comment by jodal** [comment]
As mentioned in the forum thread, it's not very obvious what would be included in an official image and not. Mopidy is properly packaged in many Linux distributions, and extensions can be cleanly installed and uninstalled using `pip`. Thus, it is not obvious what the contribution of a Docker image would be.

**Comment by M-Gregoire** [comment]
Thank you for taking the time to answer me.

> Thus, it is not obvious what the contribution of a Docker image would be.

IMHO this would be much more flexible, let me give some examples:
- Use a reverse proxy with automatic certificate renewal (Such as Traefik) and easier routing (Which allows to put mopidy under `mopidy.domain.com` or `domain.com/mopidy/` very easily).

- Much easier to have something more robust, by automatically recreating an instance of mopidy in case of trouble. With something like Kubernetes, a mopidy docker image would allow me to start another instance if one of my nodes fails.

- Easier deployment: Even though the install is quite easy with pip, you can't really do easier than `docker-compose up` if a docker-compose.yml is included in the repo.

- This would make compatibility across platforms easier, looking at Ubuntu 18 (https://mopidy.com/blog/2019/12/27/mopidy-3-faq/#so-how-do-i-install-mopidy-3-on-ubuntu-1804-lts), a docker image would remove the tedious process of manually install packages


> it's not very obvious what would be included in an official image and not

I agree this can be a tricky question, however I'm confident some flexible option can be implemented like having an entrypoint install packages based on environment variable.s That way, just by setting `MOPIDY_SPOTIFY=TRUE`, the Spotify addon would automatically be installed.

They are probably a bunch of other options to do this.


If you were to consider having an official Docker image, I'd be glad to work on it with other members.
