### ISSUE TITLE
Remove unnecessary comprehension

### ISSUE THREAD

**Issue by pnijhara** [mopidy/mopidy#1913]
Builtin function like ``join`` can work directly with a generator expression. They do not require comprehension.

Files:
```
mopidy/internal/process.py
mopidy/internal/deps.py
mopidy/core/history.py
```
contains built-in function ``join`` that uses comprehension.

**Comment by salonigupta1** [comment]
can I work on this issue?

**Comment by kingosticks** [comment]
Please ask if you need help with fixing an issue but there is no need to ask if you can fix things in general. Just go for it! Although there are way more worthwhile things to fix than this but if you went to start with something trivial then I guess this is perfect.

**Comment by pnijhara** [comment]
@salonigupta1 go for it! It is just a code quality issue, which does not bring any change to the workflow. However, it can be considered as the good first issue for you, if you are new to this.
