### ISSUE TITLE
Mopidy eats 100% CPU when the sound-card is disconnected

### ISSUE THREAD

**Issue by tomaspapan** [mopidy/mopidy#1914]
Hi there,

the cpu spikes to 100% when the sound card is disconnected. Mine setup is pure alsa, USB DAC is part of the AMP and directly connected to rpi4. Mopidy is running on rpi4. Everything works until I turn off the AMP or switch different input, then the cpu rises immediately to 100%.

**Comment by kingosticks** [comment]
I'm not sure how we can detect your amp has been turned off.  You also need to provide some information about software versions, especially your operating system. https://docs.mopidy.com/en/latest/troubleshooting/

**Comment by tomaspapan** [comment]
Of course I don't want to detect when the AMP is turned off, I just want to prevent rpi4 to becoming hot and power houngry when I turn off the rpi4.

OK. Technical details:

mopidy --version
Mopidy 3.0.2

OS:
❯ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Proof:
https://imgur.com/a/SnimSTy

Steps to reproduce:
1) Start mopidy
2) Turn on amp (USB soundcard)
3) Play music
4) Turn off amp (USB soundcard)
5) CPU at 100% (doesn't matter if the music was playing, on pause or stopped)

Error log:
May 21 15:42:59 pi mopidy[11995]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not get/set settings from/on resource.

**Comment by kingosticks** [comment]
> Of course I don't want to detect when the AMP is turned off, I just want to prevent rpi4 to becoming hot and power houngry when I turn off the amp.

Sure, but *if* we need to do something different, how would we know when to do it?

When providing version information we need the output of `mopidyctl deps` and I also need your config (`mopidyctl deps`).

I have some cheapo USB dongle soundcard and it doesn't behave like this. I think this is going to be specific to the driver for your soundcard.  

> CPU at 100% (doesn't matter if the music was playing, on pause or stopped) 

I don't quite understand this. When Mopidy is *stopped* it releases the soundcard and is not using it. Do you really see that error when Mopidy is stopped and you turn off the soundcard?

**Comment by tomaspapan** [comment]
```
❯ mopidy deps
Executable: /usr/bin/mopidy
Platform: Linux-4.19.97-v7l+-armv7l-with-debian-10.4
Python: CPython 3.7.3 from /usr/lib/python3.7
Mopidy: 3.0.2 from /usr/lib/python3/dist-packages
Mopidy-Iris: 3.48.0 from /usr/local/lib/python3.7/dist-packages
  Pykka: 2.0.2 from /usr/lib/python3/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  Mopidy: 3.0.2 from /usr/lib/python3/dist-packages
Mopidy-Local: 3.1.1 from /usr/local/lib/python3.7/dist-packages
  Pykka: 2.0.2 from /usr/lib/python3/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  uritools: 3.0.0 from /usr/local/lib/python3.7/dist-packages
  Mopidy: 3.0.2 from /usr/lib/python3/dist-packages
GStreamer: 1.14.4.0 from /usr/lib/python3/dist-packages/gi
  Detailed information:
    Python wrapper: python-gi 3.30.4
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mad
```

```
 mopidy config
[core]
cache_dir = $XDG_CACHE_DIR/mopidy
config_dir = $XDG_CONFIG_DIR/mopidy
data_dir = $XDG_DATA_DIR/mopidy
max_tracklist_length = 10000
restore_state = false

[logging]
verbosity = 0
format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
color = true
config_file =

[audio]
mixer = software
mixer_volume =
output = autoaudiosink
buffer_time =

[proxy]
scheme =
hostname =
port =
username =
password =

[local]
enabled = false  ; Extension disabled due to config errors.
media_dir =  ; Must be set.
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
included_file_extensions =
excluded_file_extensions =
  .cue
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
directories =
  Albums                  local:directory?type=album
  Artists                 local:directory?type=artist
  Composers               local:directory?type=artist&role=composer
  Genres                  local:directory?type=genre
  Performers              local:directory?type=artist&role=performer
  Release Years           local:directory?type=date&format=%25Y
  Tracks                  local:directory?type=track
 Last Week's Updates     local:directory?max-age=604800
  Last Month's Updates    local:directory?max-age=2592000
timeout = 10
use_artist_sortname = false
album_art_files =
  *.jpg
  *.jpeg
  *.png

[iris]
enabled = true
country = NZ
locale = en_NZ
spotify_authorization_url = https://jamesbarnsley.co.nz/iris/auth_spotify.php
lastfm_authorization_url = https://jamesbarnsley.co.nz/iris/auth_lastfm.php
genius_authorization_url = https://jamesbarnsley.co.nz/iris/auth_genius.php
data_dir = $XDG_DATA_DIR/iris

[file]
enabled = true
media_dirs =
  $XDG_MUSIC_DIR|Music
  ~/|Home
excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[http]
enabled = true
hostname = 127.0.0.1
port = 6680
zeroconf = Mopidy HTTP server on $hostname
allowed_origins =
csrf_protection = true
default_app = mopidy

[m3u]
enabled = true
base_dir =
default_encoding = latin-1
default_extension = .m3u8
playlists_dir =

[softwaremixer]
enabled = true

[stream]
enabled = true
protocols =
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist =
timeout = 5000
```

**Comment by tomaspapan** [comment]
> > CPU at 100% (doesn't matter if the music was playing, on pause or stopped)
> 
> I don't quite understand this. When Mopidy is _stopped_ it releases the soundcard and is not using it. Do you really see that error when Mopidy is stopped and you turn off the soundcard?

I've just repeated the steps and you are right. I don't see error message in journal, however the cpu is at 100%.

**Comment by kingosticks** [comment]
That's still very odd that there's any relationship between Mopidy in a stopped state and your hardware. Makes me think this is something else.

**Comment by tomaspapan** [comment]
> That's still very odd that there's any relationship between Mopidy in a stopped state and your hardware. Makes me think this is something else.

Oh no, there is a misunderstanding, mopidy as process was always running. If I stop the service, ergo mopidy as a process is not running and then I turn of the AMP (thus soundcard), obviously there is no process eating my cpu.

The 100 cpu usage is only visible when mopidy process is running (music playing can be in whatever state (playing, paused or nothing (cleared)) and thus the process mopidy is eating the cpu as shown in screenshot. No kernel issue, nothing in dmesg (except of USB disconnect).

**Comment by kingosticks** [comment]
Sorry, I thought I had replied to this.

> Oh no, there is a misunderstanding, mopidy as process was always running.

I did understand what you meant. I agree we can totally ignore any case when Mopidy is not actually running!

What I was trying to explain is that Mopidy only uses the sound device then playing or paused i.e. it releases the sound device when you click stop. What's why that part of the described behaviour is hard to understand. I can only assume you are not actually in the real stopped state, some clients actually only pause when you click their stop button. Using MPD to send a stop command is the easiest way to be sure the Mopidy playback state is "stopped".

**Comment by tomaspapan** [comment]
I'm using Iris as the frontend, but this really doesn't matter, because I think the behavior shouldn't be that CPU goes to 100% in any case, even when I'm listening to music and I just switch off the amplifier (usb dac). Would you agree? I know that this might be a bit hard to pin point the right place in the code, but I would be really grateful :)

**Comment by kingosticks** [comment]
I agree this behaviour is bad and if we can fix it we should but if we don't understand we cannot fix it. So it does matter that we have all the facts straight.

**Comment by kingosticks** [comment]
So, can you try and confirm that this does happen when Mopidy is really stopped, not just paused. What music sources are you using? The only backends I see enabled above are Stream and File, is that right? Exactly what sound hardware are you using? Can you reproduce the problem while [collecting a debug log](https://docs.mopidy.com/en/latest/troubleshooting/#debug-logging) and share that.

**Comment by kingosticks** [comment]
Please reopen and provide the extra info if you are still dealing with this issue.
