### ISSUE TITLE
flake8-import-order violations are being ignored

### ISSUE THREAD

**Issue by kingosticks** [mopidy/mopidy#1919]
Discovered in https://github.com/mopidy/mopidy-local/pull/45#discussion_r432174572 but needs fixing in most (if not all) repos and I don't want to lose track of it once we merge that PR. 

Fixed by adding the 'I' rules to flake8's `select` config setting in setup.cfg e.g.
```
select =
    # Regular flake8 rules
    C, E, F, W
    # flake8-bugbear rules
    B
    # B950: line too long (soft speed limit)
    B950
    # flake8-import-order
    I
    # pep8-naming rules
    N
```

And once fixed, flake8 finds a bunch of failing cases.

**Comment by kingosticks** [comment]
Or did we do this on purpose because it's really noisy?

**Comment by jodal** [comment]
I don't think this was done on purpose. Must have been a glitch when modernizing the project setups.

**Comment by MatthewFlamm** [comment]
I started on addressing this.  I used isort and added it to the CI.  The problem is that black version isn't pinned, and it fails.  Should this be split into two PRs?  One to pin version of black (or update changes for black version)?  The other to actually implement the sort order?

**Comment by jodal** [comment]
Black only has about one release a year, so I'm open to leaving it unpinned and just make PRs that formats with Black 20.

**Comment by kingosticks** [comment]
We usually just update the code base to work with the latest black. And recently @adamcik suggested we disable those checks for the master branch altogether. Maybe pinning the version is a good compromise.

To answer your question, I think we would prefer separate PRs.

**Comment by kingosticks** [comment]
Oh, and then we also need those things for our cookie cutter template also.

**Comment by MatthewFlamm** [comment]
Does it also have to be cascaded to all the extension repos too?
