### ISSUE TITLE
3.7.9 installed, gives error "Mopidy requires Python >= 3.7, but found 3.6.9"

### ISSUE THREAD

**Issue by kerta1n** [mopidy/mopidy#1931]
Hi, when trying to edit Mopidy's config file, I keep getting the error "Mopidy requires Python >= 3.7, but found 3.6.9." When I run `pip3 --version` the CLI spits out 3.7. When I run `python3 --version` CLI says that I have 3.6.9 installed. pip3 is 20.2.3. I installed Mopidy via the normal Ubuntu installation on an i386 machine running Ubuntu 18.04 LTS.

**Comment by kingosticks** [comment]
That version of Ubuntu is too old.

> The packages in the apt.mopidy.com archive are built for:
>
> Debian 10 (Buster), which also works for Raspbian Buster and Ubuntu 19.10 and newer.

Also see https://mopidy.com/blog/2019/12/27/mopidy-3-faq/#what-about-mopidy-3-on-ubuntu-1804-lts
