### ISSUE TITLE
Can't play any tracks at all

### ISSUE THREAD

**Issue by el97** [mopidy/mopidy#1940]
Hello everyone! First of all I want to thank all of you that have developed mopidy. I use it almost everyday and have made my projects better. Now to the bug report...
**Describe the bug**
A clear and concise description of what the bug is. Is this specific to a particular Backend (e.g. Mopidy-Spotify), Frontend (e.g. Mopidy-MPD) or client? Based on what I can see, I that the error is due to the mopidy-spotify backend. Every time I try to play a track, the whole mopidy service freezes and I get a lot of error messages in the log. I'm using the mopidy-iris client and i have tried with other clients with same result. 

**To reproduce**
I try to play any track and the service freezes and I got a lot of error messages in the log.

**Expected behaviour**

**Environment (please complete the following information):**
- Operating system (e.g. Debian Buster, Ubuntu 20.04) I'm using the latest version of Buster.
 - [Running Mopidy](https://docs.mopidy.com/en/latest/running/) as a service or in the terminal? I'm running it as a service
 - Your config (output of `sudo mopidyctl config`)
[mopidy config.txt](https://github.com/mopidy/mopidy/files/5604764/mopidy.config.txt)

 - Software versions (output of `sudo mopidyctl deps`)
[mopidy config deps.txt](https://github.com/mopidy/mopidy/files/5604837/mopidy.config.deps.txt)

 - Any specific hardware (e.g. an exotic USB soundcard)

**Additional context**
Here is the log output:  [mopidy.log](https://github.com/mopidy/mopidy/files/5604878/mopidy.log)
I also use raspberry Pi 4 4GB version.

Add any other context about the problem here. If appropriate, upload an [appropriately verbose](https://docs.mopidy.com/en/latest/troubleshooting/#debug-logging) log file showing the bug.

**Comment by kingosticks** [comment]
I don't see any errors in that log. Everything looks normal and the track starts playing. "Audio buffer stats requested, but no listener" is not an error, it is a debug statement and is normal behaviour. Error messages are labeled as such. 

This is not a Mopidy bug. It's also unlikely to be a Mopidy-Spotify bug. I would guess you're using Raspberry Pi OS and your soundcard configuration is limited to the pi user and does not apply to anything running as a service, such as Mopidy. If so, [this](https://discourse.mopidy.com/t/no-audio-from-mopidy-was-previously-working/4112) forum post should help.

**Comment by kingosticks** [comment]
I inserted an extra step into the [Raspberry Pi specific installation instructions](https://docs.mopidy.com/en/latest/installation/raspberrypi/) back in August but sadly I only commited it to the develop branch so the online docs were not correctly updated. I have corrected that now so it should be visible. 

> 5. Ensure the system audio settings match the user audio settings:
`sudo ln -s ~/.asoundrc /etc/asound.conf`

I hope this extra step fixes your problem. If not, please open a new post on the [user forum](https://discourse.mopidy.com/c/mopidy/6) and provide system soundcard info such as the output from `aplay -l` and `aplay -L`.

**Comment by el97** [comment]
Thank you so much for replying! That seemed to fix the issue. Thanks!
