### ISSUE TITLE
Automatic restart

### ISSUE THREAD

**Issue by Hoerli1337** [mopidy/mopidy#1952]
Mopidy does not restart automatically on my Raspberry Pi with the default installation.
If you add these two lines to the service file, Mopidy will start on system boot without any problems:

```
Restart=on-failure
RestartSec=10
```

(/lib/systemd/system/mopidy.service)

Maybe you can still include them :)

**Comment by kingosticks** [comment]
Thanks. But I think we'd prefer to find out what problem there is on your system that requires a restart of Mopidy to fix. That's the kind of thing we'd prefer to do in the user forum.
