### ISSUE TITLE
Latest upgrade of mopidy broke youtube

### ISSUE THREAD

**Issue by mgrouch** [mopidy/mopidy#1955]
mopidy[814]: INFO     [MainThread] mopidy.ext Disabled extension youtube: (requests 2.21.0 (/usr/lib/python3/dist-packages), Requirement.parse('requests>=2.22'), {'ytmusicapi'})

Env: Raspberry Pi OS, arm64

**Comment by kingosticks** [comment]
Did you try upgrade your version of requests to the one you require? This is a Mopidy-YouTube issue.
