### ISSUE TITLE
Getting intial root directories for backends in mopidy.core.LibraryController does not work as described in the documentation.

### ISSUE THREAD

**Issue by pyjukebox** [mopidy/mopidy#1957]
**Describe the bug**

When trying to get the "_initial root directories_" with "mopidy.core.LibraryController" by using "None" as the URI as stated in the docs: "_To get the intial root directories for backends pass None as the URI._", I get a validation error.

I tried with uri:"null" and uri:"None" , uri:"file:None" and uri:"file:null". All with same errors, see below in "How to reproduce".

I got it working with `"uri":"file:root"` after inspecting mopidy's code here: https://github.com/mopidy/mopidy/blob/7037d58c4a483f35416f288148568bb8e3b72aef/mopidy/file/library.py#L44.

So this works:
 `curl -d '{"jsonrpc": "2.0", "id": 5, "method": "core.library.browse", "params":{"uri":"file:root"}}' -H 'Content-Type: application/json' http://192.168.178.64:6680/mopidy/rpc`
The expected result:
`{"jsonrpc": "2.0", "id": 5, "result": [{"__model__": "Ref", "uri": "file:///mnt", "name": "Mounts", "type": "directory"}]}`

It seems to me that due to `urllib.parse.urlparse(arg).scheme` in https://github.com/mopidy/mopidy/blob/7037d58c4a483f35416f288148568bb8e3b72aef/mopidy/internal/validation.py#L129

an url with value "null/None" will never work.

**How to reproduce**

with uri:"null"
`curl -d '{"jsonrpc": "2.0", "id": 5, "method": "core.library.browse", "params":{"uri":"null"}}' -H 'Content-Type: application/json' http://localhost/mopidy/rpc`
gives:
`{"jsonrpc": "2.0", "id": 5, "error": {"code": 0, "message": "Application error", "data": {"type": "ValidationError", "message": "Expected a valid URI, not 'null'", "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/mopidy/internal/jsonrpc.py\", line 131, in _handle_single_request\n    result = self._unwrap_result(result)\n  File \"/usr/lib/python3/dist-packages/mopidy/internal/jsonrpc.py\", line 228, in _unwrap_result\n    result = result.get()\n  File \"/usr/lib/python3/dist-packages/pykka/_threading.py\", line 45, in get\n    _compat.reraise(*self._data['exc_info'])\n  File \"/usr/lib/python3/dist-packages/pykka/_compat/__init__.py\", line 29, in reraise\n    raise value\n  File \"/usr/lib/python3/dist-packages/pykka/_actor.py\", line 193, in _actor_loop\n    response = self._handle_receive(envelope.message)\n  File \"/usr/lib/python3/dist-packages/pykka/_actor.py\", line 299, in _handle_receive\n    return callee(*message.args, **message.kwargs)\n  File \"/usr/lib/python3/dist-packages/mopidy/core/library.py\", line 92, in browse\n    validation.check_uri(uri)\n  File \"/usr/lib/python3/dist-packages/mopidy/internal/validation.py\", line 130, in check_uri\n    raise exceptions.ValidationError(msg.format(arg=arg))\nmopidy.exceptions.ValidationError: Expected a valid URI, not 'null'\n"}}}`

with uri:"None"
`curl -d '{"jsonrpc": "2.0", "id": 5, "method": "core.library.browse", "params":{"uri":"None"}}' -H 'Content-Type: application/json' http://localhost/mopidy/rpc`
gives:
`{"jsonrpc": "2.0", "id": 5, "error": {"code": 0, "message": "Application error", "data": {"type": "ValidationError", "message": "Expected a valid URI, not 'None'", "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/mopidy/internal/jsonrpc.py\", line 131, in _handle_single_request\n    result = self._unwrap_result(result)\n  File \"/usr/lib/python3/dist-packages/mopidy/internal/jsonrpc.py\", line 228, in _unwrap_result\n    result = result.get()\n  File \"/usr/lib/python3/dist-packages/pykka/_threading.py\", line 45, in get\n    _compat.reraise(*self._data['exc_info'])\n  File \"/usr/lib/python3/dist-packages/pykka/_compat/__init__.py\", line 29, in reraise\n    raise value\n  File \"/usr/lib/python3/dist-packages/pykka/_actor.py\", line 193, in _actor_loop\n    response = self._handle_receive(envelope.message)\n  File \"/usr/lib/python3/dist-packages/pykka/_actor.py\", line 299, in _handle_receive\n    return callee(*message.args, **message.kwargs)\n  File \"/usr/lib/python3/dist-packages/mopidy/core/library.py\", line 92, in browse\n    validation.check_uri(uri)\n  File \"/usr/lib/python3/dist-packages/mopidy/internal/validation.py\", line 130, in check_uri\n    raise exceptions.ValidationError(msg.format(arg=arg))\nmopidy.exceptions.ValidationError: Expected a valid URI, not 'None'\n"}}}`

**Expected behaviour**

I expect "_a list of mopidy.models.Ref objects for the directories and tracks at the given uri._".

**Environment**
Please complete the following information:
- OS: Dietpi (latest, based on debian buster)
- mopidy as service
- Your config :

```
[core]
cache_dir = /mnt/dietpi_userdata/mopidy/cache
config_dir = /etc/mopidy
data_dir = /mnt/dietpi_userdata/mopidy/data
max_tracklist_length = 10000
restore_state = false

[logging]
verbosity = 0
format = %(levelname)-8s [%(threadName)s] %(name)s %(message)s
color = false
config_file =

[audio]
mixer = software
mixer_volume =
output = autoaudiosink
buffer_time =

[proxy]
scheme =
hostname =
port =
username =
password =

[spotify]
enabled = true
username = <snip>
password = ********
client_id = <snip>
client_secret = ********
bitrate = 160
volume_normalization = true
private_session = false
timeout = 10
allow_cache = true
allow_network = true
allow_playlists = true
search_album_count = 20
search_artist_count = 10
search_track_count = 50
toplist_countries =

[spotify_web]
enabled = false  ; Extension disabled by user config.

[musicbox_webclient]
enabled = true
musicbox = false
websocket_host =
websocket_port =
on_track_click = PLAY_ALL

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600
password =
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist =
  listall
  listallinfo
default_playlist_scheme = m3u

[iris]
enabled = true
country = DE
locale = de_DE
spotify_authorization_url = https://jamesbarnsley.co.nz/iris/auth_spotify.php
lastfm_authorization_url = https://jamesbarnsley.co.nz/iris/auth_lastfm.php
genius_authorization_url = https://jamesbarnsley.co.nz/iris/auth_genius.php
data_dir = $XDG_DATA_DIR/iris

[alsamixer]
enabled = true
card = 0
control = Master
min_volume = 0
max_volume = 100
volume_scale = cubic

[file]
enabled = true
media_dirs =
  /mnt|Mounts
excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[http]
enabled = true
hostname = 192.168.178.64
port = 6680
zeroconf = Mopidy HTTP server on $hostname
allowed_origins =
  localhost
  192.168.178.64
csrf_protection = true
default_app = mopidy

[m3u]
enabled = true
base_dir =
default_encoding = latin-1
default_extension = .m3u8
playlists_dir = /mnt/dietpi_userdata/Music

[softwaremixer]
enabled = true

[stream]
enabled = true
protocols =
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist =
timeout = 5000

[local]
enabled = true
max_search_results = 100
media_dir = /mnt
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
included_file_extensions =
excluded_file_extensions =
  .cue
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
directories =
  Albums                  local:directory?type=album
  Artists                 local:directory?type=artist
  Composers               local:directory?type=artist&role=composer
  Genres                  local:directory?type=genre
  Performers              local:directory?type=artist&role=performer
  Release Years           local:directory?type=date&format=%25Y
  Tracks                  local:directory?type=track
  Last Week's Updates     local:directory?max-age=604800
  Last Month's Updates    local:directory?max-age=2592000
timeout = 10
use_artist_sortname = false
album_art_files =
  *.jpg
  *.jpeg
  *.png

```
- Software versions :
```
Executable: /usr/bin/mopidy
Platform: Linux-5.4.79-v7+-armv7l-with-debian-10.7
Python: CPython 3.7.3 from /usr/lib/python3.7
Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
Mopidy-MPD: 3.0.0 from /usr/local/lib/python3.7/dist-packages
  setuptools: 50.3.0 from /usr/local/lib/python3.7/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
  Pykka: 2.0.3 from /usr/lib/python3/dist-packages
Mopidy-Iris: 3.52.4 from /usr/local/lib/python3.7/dist-packages
  setuptools: 50.3.0 from /usr/local/lib/python3.7/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
  Pykka: 2.0.3 from /usr/lib/python3/dist-packages
Mopidy-ALSAMixer: 2.0.1 from /usr/local/lib/python3.7/dist-packages
  setuptools: 50.3.0 from /usr/local/lib/python3.7/dist-packages
  pyalsaaudio: 0.9.0 from /usr/local/lib/python3.7/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
  Pykka: 2.0.3 from /usr/lib/python3/dist-packages
Mopidy-Local: 3.2.0 from /usr/lib/python3/dist-packages
Mopidy-Spotify: 4.0.1 from /usr/local/lib/python3.7/dist-packages
  setuptools: 50.3.0 from /usr/local/lib/python3.7/dist-packages
  requests: 2.21.0 from /usr/lib/python3/dist-packages
  pyspotify: 2.1.3 from /usr/local/lib/python3.7/dist-packages
    cffi: 1.14.3 from /usr/local/lib/python3.7/dist-packages
      pycparser: 2.20 from /usr/local/lib/python3.7/dist-packages
    setuptools: 50.3.0 from /usr/local/lib/python3.7/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
  Pykka: 2.0.3 from /usr/lib/python3/dist-packages
Mopidy-Spotify-Web: 0.3.0 from /usr/local/lib/python3.7/dist-packages
  Pykka: 2.0.3 from /usr/lib/python3/dist-packages
  requests: 2.21.0 from /usr/lib/python3/dist-packages
  setuptools: 50.3.0 from /usr/local/lib/python3.7/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
  Mopidy-Spotify: 4.0.1 from /usr/local/lib/python3.7/dist-packages
    setuptools: 50.3.0 from /usr/local/lib/python3.7/dist-packages
    requests: 2.21.0 from /usr/lib/python3/dist-packages
    pyspotify: 2.1.3 from /usr/local/lib/python3.7/dist-packages
      cffi: 1.14.3 from /usr/local/lib/python3.7/dist-packages
        pycparser: 2.20 from /usr/local/lib/python3.7/dist-packages
      setuptools: 50.3.0 from /usr/local/lib/python3.7/dist-packages
    Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
    Pykka: 2.0.3 from /usr/lib/python3/dist-packages
  spotipy: 2.16.0 from /usr/local/lib/python3.7/dist-packages
    requests: 2.21.0 from /usr/lib/python3/dist-packages
    six: 1.12.0 from /usr/lib/python3/dist-packages
Mopidy-MusicBox-Webclient: 3.1.0 from /usr/local/lib/python3.7/dist-packages
  setuptools: 50.3.0 from /usr/local/lib/python3.7/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
  Pykka: 2.0.3 from /usr/lib/python3/dist-packages
GStreamer: 1.14.4.0 from /usr/lib/python3/dist-packages/gi
  Detailed information:
    Python wrapper: python-gi 3.30.4
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        pulsesink
        flump3dec
        mad

```

**Additional context**

It seems other people also had the same problem:
https://discourse.mopidy.com/t/newbee-question-uri-none-usage-in-browse-function/3024

**Comment by kingosticks** [comment]
The answer is in that forum post, the linked codebase also had an example.

> The docs are written for Python. The equivalent of Python’s None in Javascript is null. 

A string with value null (i.e. `"null"`) is not the same thing as the primitive value of null (i.e. `null`). 
 
```
curl -d '{"jsonrpc": "2.0", "id": 5, "method": "core.library.browse", "params":{"uri":null}}' -H 'Content-Type: application/json' http://192.168.178.64:6680/mopidy/rpc
```

**Comment by pyjukebox** [comment]
Lol, thank you. It works. I thought I had tried this as well.
