### ISSUE TITLE
Mopidy[520]: free(): invalid pointer

### ISSUE THREAD

**Issue by losiu97** [mopidy/mopidy#1975]
**Describe the bug**
I use mopidy with iris as frontend, mostly with spotify and youtube, and it stops working after some time. 

**How to reproduce**
I just run mopidy for some time (usually the bug appears after about 2 hours of listening), then the mopidy dies.
Here is what systemctl gives me:

pi@raspberrypi:~ $ systemctl status mopidy
● mopidy.service - Mopidy music server
   Loaded: loaded (/lib/systemd/system/mopidy.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Mon 2021-02-08 10:44:22 GMT; 22h ago
  Process: 514 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
  Process: 519 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
  Process: 520 ExecStart=/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf (code=killed, signal=ABRT)
 Main PID: 520 (code=killed, signal=ABRT)

Feb 08 10:16:04 raspberrypi mopidy[520]: INFO     [YouTubeBackend-3] mopidy_youtube Searching YouTube for query "sława przybylska"
Feb 08 10:16:04 raspberrypi mopidy[520]: INFO     [YouTubeBackend-3] mopidy_youtube session.get triggered: search
Feb 08 10:22:46 raspberrypi mopidy[520]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'artist': ['okudżawa']}"
Feb 08 10:22:46 raspberrypi mopidy[520]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'album': ['okudżawa']}"
Feb 08 10:22:46 raspberrypi mopidy[520]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'any': ['okudżawa']}"
Feb 08 10:22:46 raspberrypi mopidy[520]: INFO     [YouTubeBackend-3] mopidy_youtube Searching YouTube for query "okudżawa"
Feb 08 10:22:46 raspberrypi mopidy[520]: INFO     [YouTubeBackend-3] mopidy_youtube session.get triggered: search
Feb 08 10:44:22 raspberrypi mopidy[520]: free(): invalid pointer
Feb 08 10:44:22 raspberrypi systemd[1]: mopidy.service: Main process exited, code=killed, status=6/ABRT
Feb 08 10:44:22 raspberrypi systemd[1]: mopidy.service: Failed with result 'signal'.

**Expected behaviour**
Well, a fix

**Environment**

- Operating system: Raspbian GNU/Linux 10 (buster)
- Running as a service
- My Config:
`pi@raspberrypi:~ $ sudo mopidyctl config
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf config" as user mopidy
WARNING  [MainThread] mopidy.config Ignoring config section 'mpd' because no matching extension was found
[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy
max_tracklist_length = 10000
restore_state = false

[logging]
verbosity = 0
format = %(levelname)-8s [%(threadName)s] %(name)s %(message)s
color = false
config_file =

[audio]
mixer = software
mixer_volume = 40
output = alsasink device=hw:sndrpihifiberry
buffer_time = 

[proxy]
scheme = 
hostname = 
port = 
username = 
password = 

[youtube]
enabled = true
youtube_api_key = 
threads_max = 16
search_results = 15
playlist_max_videos = 20
api_enabled = false

[raspberry-gpio]
enabled = true
bcm0 = 
bcm1 = 
bcm2 = 
bcm3 = 
bcm4 = 
bcm5 = play_pause,active_low,250
bcm6 = volume_down,active_low,250
bcm7 = 
bcm8 = 
bcm9 = 
bcm10 = 
bcm11 = 
bcm12 = 
bcm13 = 
bcm14 = 
bcm15 = 
bcm16 = next,active_low,250
bcm17 = 
bcm18 = 
bcm19 = 
bcm20 = volume_up,active_low,250
bcm21 = 
bcm22 = 
bcm23 = 
bcm24 = volume_up,active_low,250
bcm25 = 
bcm26 = 
bcm27 = 

[pidi]
enabled = true
display = st7789

[local]
enabled = true
media_dir = /home/pi/hard_drive/shares/shares/shares/Muzyka/
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
included_file_extensions = 
excluded_file_extensions = 
  .cue
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
directories = 
  Albums                  local:directory?type=album
  Artists                 local:directory?type=artist
  Composers               local:directory?type=artist&role=composer
  Genres                  local:directory?type=genre
  Performers              local:directory?type=artist&role=performer
  Release Years           local:directory?type=date&format=%25Y
  Tracks                  local:directory?type=track
  Last Week's Updates     local:directory?max-age=604800
  Last Month's Updates    local:directory?max-age=2592000
timeout = 10
use_artist_sortname = false
album_art_files = 
  *.jpg
  *.jpeg
  *.png

[iris]
enabled = true
country = NZ
locale = en_NZ
spotify_authorization_url = https://jamesbarnsley.co.nz/iris/auth_spotify.php
lastfm_authorization_url = https://jamesbarnsley.co.nz/iris/auth_lastfm.php
genius_authorization_url = https://jamesbarnsley.co.nz/iris/auth_genius.php
data_dir = $XDG_DATA_DIR/iris

[file]
enabled = true
media_dirs = 
  $XDG_MUSIC_DIR|Music
  ~/|Home
excluded_file_extensions = 
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[http]
enabled = true
hostname = 0.0.0.0
port = 6680
zeroconf = Mopidy HTTP server on $hostname
allowed_origins = 
csrf_protection = true
default_app = mopidy

[m3u]
enabled = true
base_dir =
default_encoding = latin-1
default_extension = .m3u8
playlists_dir =

[softwaremixer]
enabled = true

[stream]
enabled = true
protocols = 
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist = 
timeout = 5000

[spotify]
enabled = true
username = konrad.lys1997@gmail.com
password = ********
client_id = 0bc89eaf-1bc9-4536-924d-83fb5d231234
client_secret = ********
bitrate = 320
volume_normalization = true
private_session = false
timeout = 10
allow_cache = true
allow_network = true
allow_playlists = true
search_album_count = 20
search_artist_count = 10
search_track_count = 50
toplist_countries =
`
- Software versions:
`pi@raspberrypi:~ $ sudo mopidyctl deps
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf deps" as user mopidy
WARNING  [MainThread] mopidy.config Ignoring config section 'mpd' because no matching extension was found
Executable: /usr/bin/mopidy
Platform: Linux-5.4.83+-armv6l-with-debian-10.7
Python: CPython 3.7.3 from /usr/lib/python3.7
Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
Mopidy-YouTube: 3.0 from /usr/local/lib/python3.7/dist-packages
  youtube-dl: 2020.3.8 from /usr/local/lib/python3.7/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
  Pykka: 2.0.3 from /usr/lib/python3/dist-packages
  requests: 2.21.0 from /usr/lib/python3/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  cachetools: 4.0.0 from /usr/local/lib/python3.7/dist-packages
  bs4: 0.0.1 from /usr/local/lib/python3.7/dist-packages
    beautifulsoup4: 4.8.2 from /usr/local/lib/python3.7/dist-packages
      soupsieve: 2.0 from /usr/local/lib/python3.7/dist-packages
mopidy-raspberry-gpio: 1.0.0 from /usr/local/lib/python3.7/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
  Pykka: 2.0.3 from /usr/lib/python3/dist-packages
Mopidy-Iris: 3.55.4 from /usr/local/lib/python3.7/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
  Pykka: 2.0.3 from /usr/lib/python3/dist-packages
mopidy-pidi: 1.0.0 from /usr/local/lib/python3.7/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
  Pykka: 2.0.3 from /usr/lib/python3/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  musicbrainzngs: 0.7.1 from /usr/local/lib/python3.7/dist-packages
  netifaces: 0.10.9 from /usr/local/lib/python3.7/dist-packages
Mopidy-Spotify: 4.1.0 from /usr/lib/python3/dist-packages
Mopidy-Local: 3.1.1 from /usr/local/lib/python3.7/dist-packages
  Pykka: 2.0.3 from /usr/lib/python3/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  uritools: 3.0.0 from /usr/local/lib/python3.7/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
GStreamer: 1.14.4.0 from /usr/lib/python3/dist-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.30.4
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mad`
- Pirate Audio DAC board (https://shop.pimoroni.com/products/pirate-audio-line-out)

**Comment by kingosticks** [comment]
This is most likely to be another pidi issue similar to what was reported [here](https://discourse.mopidy.com/t/mopidy-crashes-with-free-invalid-pointer/4466/2). It might even be the same one as I we didn't get an update from the original poster. 

As there, I’d suggest disabling the pirate audio plugin and verify the crashing stops. Then report the issue on the mopidy-pidi bug tracker. If it continues then please re-open this and provide a debug log.
