### ISSUE TITLE
Starting playback of a internet stream takes 4 seconds

### ISSUE THREAD

**Issue by 6i6i** [mopidy/mopidy#1977]
I am using Mopidy 3.55.4  running on X64 Linux. I have Iris as frontend.
When starting playback of an internet stream it takes about 4 seconds until something is really played.
I can reproduce it when adding f.ex. following stream url:

**http://ors-sn06.ors-shoutcast.at/oe3-q1a**

When I click play the time starts running until 4 seconds where I only hear about 500ms audio. After that it there is silence. Then after 4 seconds the time skips back to 0:01 and the audio is played.

See attached gif for a better error description.

Is there any way to make this faster?

![mopidy](https://user-images.githubusercontent.com/6044026/108377527-6a130880-7204-11eb-8fde-529cfed42dab.gif)

If I add the same in VLC it starts immediately to play.

**Comment by kingosticks** [comment]
Please post user questions in the forum.
