### ISSUE TITLE
Subsequent builds of mopidy pulls different `underscore.js` file.

### ISSUE THREAD

**Issue by Foxboron** [mopidy/mopidy#1981]
**Describe the bug**
I was rebuilding mopdiy in Arch Linux for a packaging change. Building the same source with the same version *should* result in the same files. But in this case the diff between the previous version `3.1.1-1` and `3.1.1-2` showed the following diff:

<pre>
==> Running checkpkg...
usr/share/doc/mopidy/html/_static/underscore-1.3.1.js	      |	usr/share/doc/mopidy/html/_static/underscore-1.12.0.js
</pre>

It's unclear to me what would be pulling this file, and why it wouldn't be the same across rebuilds.

**How to reproduce**
Wait a while and build mopidy. The `underscore-*.js` file might be a new version.

**Expected behaviour**
The same version of mopidy should always pull the same version of `underscore.js`.

**Environment**
Please complete the following information:
- Arch Linux
- Building mopidy
- N/A
- `3.1.1`
- N/A

**Additional context**
Build file changes resulting in the changed file
https://github.com/Foxboron/archlinux-pkgbuilds/commit/aba5b479a11aa355a2b7de45e955d6c60e3febce

**Comment by Foxboron** [comment]
I thought it broke reproducible builds but it doesn't. I can recreate the previous release with `underscore-1.3.1.js`. It's only present builds getting the newer `underscore-1.12.0.js`. Weird. Probably not an actual issue but still a bit weird.

I did however notice that newer builds of mopidy is pulling documentation references towards pykka v3.0 even if we build towards pykka v2. This does break reproducible builds.

**Comment by jodal** [comment]
The issue with `underscore-*.js` is probably due to different versions of Sphinx being used to build the docs.

The issue with linking to Pykka v3 instead of v2 docs is due to v3 recently being released and the connection between the docs sites being based on the URL of the Pykka docs. The Debian package patches out this link so that is is stable across package builds: https://salsa.debian.org/mopidy-team/mopidy/-/blob/debian/master/debian/patches/0002-Make-intersphinx-link-to-local-docs.patch

**Comment by Foxboron** [comment]
Ahh, then the `underscore-*.js` is not a reproducability issue. Which is great. I'll probably steal that debian patch for the Arch package. Thanks!

Fwiw, the systemd service can be solved with using `CacheDirectory=mopidy` instead of the `ExecStartPre` lines. But I'm a little bit unsure when it was introduced if you are supporting older Debian releases.
