### ISSUE TITLE
How to allow network connection to Mopidy in version >= 3.x?

### ISSUE THREAD

**Issue by gunwald** [mopidy/mopidy#1983]
I had the fairly old Mopidy version 2.2 from the Raspbian repro up and running for a wile and just recently updated to 3.1.1 using the Mopidy Debian sources. I had a minimal custom config just setting the music file directory and allowing network connection via http an for mpd for my local network.

Evidently a had to update my config file and came up with this:

```
[http]
hostname = ::

[file]
media_dirs =
    /home/user/Musik

[mpd]
hostname = ::
```
Starting up the service I noticed the message:

`Thread] mopidy.config Ignoring config section 'mpd' because no matching extension was found   `

And as a result I could of course not connect with any client that wasn't on the same machine as Mopidy.

In the doc I could not find any hint, what I might got wrong. To the contrary, my config is identical with an example given there under: https://docs.mopidy.com/en/latest/config/

I tried to completely purge Mopidy an reinstall it, just in case. But this didn't help at all.

So, is this a bug or am I an idiot?

**Comment by adamcik** [comment]
Mopidy-MPD was split out to it's own extension, was mentioned in the release notes if nothing else :-)

**Comment by kingosticks** [comment]
> if nothing else

Here too! https://mopidy.com/blog/2019/12/27/mopidy-3-faq/#whats-new-in-mopidy-30
