### ISSUE TITLE
Loading of some extensions causes Mopidy to crash

### ISSUE THREAD

**Issue by DavisNT** [mopidy/mopidy#1989]
**Describe the bug**
Some extensions can cause Mopidy 3.2 to fail to start. Example is https://github.com/xolox/mopidy-simple-webclient

**How to reproduce**
```
sudo pip3 install Mopidy-Simple-Webclient
sudo service mopidy restart
```

**Expected behaviour**
Mopidy starts without loading the extension.

**Environment**
Raspbian Buster.
Mopidy 3.2 installed via apt.

**Additional context**
Excerpt from syslog
```
Traceback (most recent call last):
  File "/usr/bin/mopidy", line 11, in <module>
    load_entry_point('Mopidy==3.2.0', 'console_scripts', 'mopidy')()
  File "/usr/lib/python3/dist-packages/mopidy/__main__.py", line 46, in main
    extensions_data = ext.load_extensions()
  File "/usr/lib/python3/dist-packages/mopidy/ext.py", line 262, in load_extensions
    "Loaded extension: %s %s", extension.dist_name, extension.version
AttributeError: 'Extension' object has no attribute 'dist_name'
```

**Comment by kingosticks** [comment]
That extension is very outdated, it's not python 3 and probably not compatible with Mopidy 3 is various ways. The list at https://mopidy.com/ext/ shows extensions known to be compatible.

**Comment by DavisNT** [comment]
@kingosticks Thank you! I know it. 

But is it correct behavior if Mopidy crashes without even showing extension name/path in the logs?

**Comment by kingosticks** [comment]
I think all bets are off when trying to use two things that are incompatible. What does it print with your fix?

**Comment by DavisNT** [comment]
With the fix the following error is logged:
```
ERROR    [MainThread] mopidy.ext Setup of extension from entry point simple-webclient failed, ignoring extension.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mopidy/ext.py", line 241, in load_extensions
    _ = extension.dist_name
AttributeError: 'Extension' object has no attribute 'dist_name'
```

Mopidy starts and problematic extension is not loaded/registered.

**Comment by djmattyg007** [comment]
I feel like this is a slippery slope with little value. If something hasn't been updated to work with newer versions of Mopidy, there's no telling how many small incompatibilities you might need to fix, even if the codebase that was written for python2 and never updated for python3 somehow magically works on python3 without any changes at all.

Even if we thought this was a good idea, the proposed patch is inadequate. If I was performing a general review/cleanup of the codebase and I came across those lines, I'd probably remove them. At the very least you should add some comments.

**Comment by DavisNT** [comment]
@djmattyg007 Good point about comment! I have added comment and accessing `ext_name` attribute (it is also used after the try block; no other attributes seem to be used in `load_extensions()` after the try block).

This patch does **not** increase compatibility with outdated extensions. The extension still **will not load** (I totally agree that problematic extensions should not load instead of loading and likely malfunctioning during use). However with this patch Mopidy starts and logs exception with name of problematic extension (instead of crashing during start without mentioning extension name in the logs - at least when using default logging settings).

I think whether this is a slippery slope depends on two design factors:
1. whether it is OK for Mopidy to be crashed by invalid/malfunctioning extensions;
2. whether names of problematic extensions should be logged with default logging settings.

**Comment by djmattyg007** [comment]
I don't really understand the problem with Mopidy crashing in a case like this. It makes the problem unambiguous and unavoidable. Something that fails fast as noisily aa possible is much better than something that fails silently and increases the debugging burden.

**Comment by jodal** [comment]
I agree that it could make sense to have Mopidy crash early if there were issues with any extension, assuming those issues are due to locally fixable problems and not e.g. transient network problems with a service the extension accesses during startup.

Given that we already have code to log any extension setup issues and continue starting Mopidy without the extension, I believe that it makes a lot of sense to make that code more robust and make sure that this error case also prints a usable log statement which includes the name of the crashing extension.

With the added comment, I'm :+1: to the change.
