### ISSUE TITLE
TypeError exception when playing track with unnamed artists

### ISSUE THREAD

**Issue by mgrouch** [mopidy/mopidy#1991]
```python
Jul 19 16:30:13 lysmarine sh[694]:     getattr(self, event)(**kwargs)
Jul 19 16:30:13 lysmarine sh[694]:   File "/usr/lib/python3/dist-packages/mopidy/core/actor.py", line 85, in stream_changed
Jul 19 16:30:13 lysmarine sh[694]:     self.playback._on_stream_changed(uri)
Jul 19 16:30:13 lysmarine sh[694]:   File "/usr/lib/python3/dist-packages/mopidy/core/playback.py", line 147, in _on_stream_ch
Jul 19 16:30:13 lysmarine sh[694]:     self._trigger_track_playback_started()
Jul 19 16:30:13 lysmarine sh[694]:   File "/usr/lib/python3/dist-packages/mopidy/core/playback.py", line 514, in _trigger_trac
Jul 19 16:30:13 lysmarine sh[694]:     self.core.history._add_track(tl_track.track)
Jul 19 16:30:13 lysmarine sh[694]:   File "/usr/lib/python3/dist-packages/mopidy/core/history.py", line 31, in _add_track
Jul 19 16:30:13 lysmarine sh[694]:     ", ".join(artist.name for artist in track.artists)
Jul 19 16:30:13 lysmarine sh[694]: TypeError: sequence item 0: expected str instance, NoneType found
```

also with recent version of mopidy
playlist containing youtube entries doesn't show up with track name, artist in musicbox

**Comment by aadityasinha-dotcom** [comment]
Hi! Can I work on this issue?

**Comment by kingosticks** [comment]
Yes please!

I would suggest the first step is to reproduce the exception by adding a test to https://github.com/mopidy/mopidy/blob/develop/tests/core/test_history.py that uses a Track with an Artist that does not have the name field set. And then fix the `HistoryController` so that new test passes. If you need any help please ask.

**Comment by aadityasinha-dotcom** [comment]
So I had to make a test class that uses **Track** with an **Artist** that does not have a name?

**Comment by aadityasinha-dotcom** [comment]
So I need to make a test class that uses `Track` with an `Artist` that does not have a name?

**Comment by kingosticks** [comment]
Yes, just add a simple new test case to what is already there. Then it'll be easy to verify the fix.

**Comment by aadityasinha-dotcom** [comment]
I have made a class named `TestWithoutName` in which I have put functions of `PlaybackHistoryTest`. I have just put the `Artist` name to None.

**Comment by kingosticks** [comment]
Are you still working on this @aadityasinha-dotcom ?

**Comment by Kunal-Attri** [comment]
Hi! Can I work on this issue?

**Comment by kingosticks** [comment]
Feel free

**Comment by Kunal-Attri** [comment]
So, I have added a test to https://github.com/mopidy/mopidy/blob/develop/tests/core/test_history.py that uses a track with an Artist with no name, and also modified HistoryController accordingly. How do I create a pull request for the specific files, to run the testCases?

**Comment by Kunal-Attri** [comment]
I have also created a pull request for the same from the fork i created and it's there in Pull Requests, needs maintainer's approval for first time contributors running workflows.

**Comment by Kunal-Attri** [comment]
#2011 pull request
