### ISSUE TITLE
mopidy as service comes up in wrong state 

### ISSUE THREAD

**Issue by mgrouch** [mopidy/mopidy#1995]
mopidy as service spawns too soon
if it can't access youtube or spotify at startup it can't play from them even later 
(until restart)

I had to workaround mopidy.service like this:

ExecStart=sh -c 'c=0; r=1; while [ $c -lt 20 -a $r -ne 0 ] ; do ping -c 1 -n -w 1 spotify.com; r=$?; c=`expr $c + 1`; sleep 5; done; /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf'

**Comment by djmattyg007** [comment]
Could you please run the following command, and paste the output?

```
systemctl cat mopidy.service
```

**Comment by kingosticks** [comment]
Please stop ignoring the issue template.

Configure your system to wait for the network before continuing to boot services that require a working network.

**Comment by mgrouch** [comment]
there might be no network when system comes up in my use case.
(on a boat). but when network becomes available I should be
able to use mopidy to play from on-line sources too.
