### ISSUE TITLE
The API limits results to 5000

### ISSUE THREAD

**Issue by ScuttleSE** [mopidy/mopidy#2002]
```
{
   "jsonrpc":"2.0",
   "id":1,
   "method":"core.library.search",
   "params":{
      "uris":[
         "local:"
      ],
      "query":{
         "uri":"Library/"
      }
   }
}
```

That query should return tens of thousands of results, I only get the first 5000. I have not found anything in the documentation that indicates that core.library.search or mopidy.backend.search limits one to the first 5000 results.

**Comment by kingosticks** [comment]
Might this be a limit of the local backend?

**Comment by ScuttleSE** [comment]
Haven't found a hardcoded limit there either, just that you _can_ have a limit on results

**Comment by ScuttleSE** [comment]
Actually, now that I rememeber it, there _was_ a limit in the local backend, but I changed that over a year ago in https://github.com/mopidy/mopidy-local/pull/49

**Comment by ScuttleSE** [comment]
Aaaand turns out I'm a bloody fool. I created a PR to be able to set the limit, then I complain when I hit the limit I set myself... Yes I had set the limit to 5000..
