### ISSUE TITLE
Apple Music via MusicKit

### ISSUE THREAD

**Issue by jaknz** [mopidy/mopidy#2019]
Apple have launched MusicKit JS as an API for linking to, controlling, and playing from Apple Music accounts. Is this enough functionality to build a plug-in? I'd be happy to contribute to this but don't have the knowledge to start it.

> Apple Music content can play directly in the browser. With MusicKit on the Web, users can stream songs, music videos, and radio from Apple Music on your website using MusicKit Web Components or a player you’ve customized using JavaScript.

https://developer.apple.com/musickit/
https://developer.apple.com/musickit/web/

**Comment by kingosticks** [comment]
No, unfortunately a javascript library like this (and Spotify's) can't be used.
