### ISSUE TITLE
Error installing with latest raspiOs (bullseye)

### ISSUE THREAD

**Issue by mgrouch** [mopidy/mopidy#2026]
E: The repository 'https://apt.mopidy.com bullseye Release' does not have a Release file.

Thanks

**Comment by jodal** [comment]
Please continue using the `buster` distribution from apt.mopidy.com, as described at https://docs.mopidy.com/en/latest/installation/debian/, even though you've upgraded to bullseye. As explained in the docs, `buster` refers to that the packages are built for Buster *or newer*, which includes Bullseye.
