### ISSUE TITLE
No sound running Mopidy/mpd as a Service

### ISSUE THREAD

**Issue by tianrking** [mopidy/mopidy#2031]
No sound running Mopidy/mpd as a Service

**Comment by tianrking** [comment]
ERROR    2021-12-05 23:23:07,629 [835227:HttpServer] tornado.application
  Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fe63017ee50>>, <Task finished name='Task-332' coro=<IrisCore.update_snapcast_meta() done, defined at /usr/local/lib/python3.9/dist-packages/mopidy_iris/core.py:1159> exception=KeyError('album')>)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.9/dist-packages/mopidy_iris/core.py", line 1177, in update_snapcast_meta
    meta["album"] = track["album"]
KeyError: 'album'
ERROR    2021-12-05 23:23:10,170 [835227:MainThread] mopidy.audio.gst
  GStreamer error: Could not connect to server

**Comment by kingosticks** [comment]
You've ignored the template.

**Comment by kingosticks** [comment]
And this is a bug for the Mopidy-Iris project, not here.

**Comment by kingosticks** [comment]
No response.
