### ISSUE TITLE
Mopidy is unable to connect to pulseaudio server

### ISSUE THREAD

**Issue by sseneca** [mopidy/mopidy#2035]
Posted on forum first but got no responses: https://discourse.mopidy.com/t/suddenly-getting-gstreamer-warning-failed-to-connect-connection-refused/5263

**Describe the bug**

I use Mopidy with mopidy-mpd and mopidy-jellyfin. This lets me stream music through an mpd client like ncmpcpp from my Jellyfin server.

The setup has been working great for well over a year until the Python 3.10 upgrade, where things have fallen apart. After I rebuilt `mopidy-mpd` and `mopidy-jellyfin` manually I can no longer get Mopidy to connect to my audio, with the following error message (I also passed in `GST_DEBUG=3` to get the first two additional lines):

```
0:00:37.258147435 11354 0x7fa3480512d0 WARN                   pulse pulsesink.c:614:gst_pulseringbuffer_open_device:<pulsesink0> error: Failed to connect: Timeout
0:00:37.258913699 11354 0x7fa3480512d0 ERROR                playbin gstplaybin2.c:5555:activate_group:<playbin0> failed to activate sinks
ERROR    2021-12-24 16:58:27,184 [11354:MainThread] mopidy.audio.gst
  GStreamer error: Failed to connect: Timeout
WARNING  2021-12-24 16:58:27,185 [11354:Audio-2 (_actor_loop)] mopidy.audio.actor
  Setting GStreamer state to GST_STATE_PLAYING failed
WARNING  2021-12-24 16:58:27,186 [11354:Core-7 (_actor_loop)] mopidy.core.tracklist
  Track is not playable: jellyfin:track:ecb4c9a12996e40aa20036c4a54d2f21
```

I’m on Parabola GNU/Linux-libre, which is very similar to Arch Linux. I use Pipewire and pipewire-pulse, with [this](https://github.com/mopidy/mopidy/issues/1974#issuecomment-797105715) configuration.

The thing that confuses me the most is that even when I comment out my custom settings for audio and use the default

```
[audio]
mixer = software
mixer_volume = 
output = autoaudiosink
buffer_time = 
```

I get the same `GStreamer warning: Failed to connect: Connection refused` warning (though ncmpcpp *does* queue the song, usually it just freezes). So I have no idea what’s going on.

Doing `sudo netstat -tunlp | rg 8888` does return what I’d expect:

```
tcp        0      0 127.0.0.1:8888          0.0.0.0:*               LISTEN      899/pipewire-pulse 
```

so the port _is_ open.

**How to reproduce**

- Start Mopidy as a system service
- Try to play a song in nmpcpp

**Expected behaviour**
It should play the song.

**Environment**
Please complete the following information:
- Operating system: Parabola GNU/Linux-libre (fully updated)
- Running Mopidy as a server
- Your config (output of `sudo mopidyctl config`): Note I get the same error even with the default options under `audio`. https://gist.github.com/sseneca/f14dd0933eafedaa4de972adb2431680
- Software versions (output of `sudo mopidyctl deps`): https://gist.github.com/sseneca/7344250ad43439e86a51df7ea30dd11e
- Any specific hardware (e.g. an exotic USB soundcard): No

**Comment by sseneca** [comment]
[From the discourse thread](https://discourse.mopidy.com/t/suddenly-getting-gstreamer-warning-failed-to-connect-connection-refused/5263), it looks like [this](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1863) issue with `wireplumber` was my issue, and wireplumber compiled from the latest commit fixes things.

**Comment by johnhamelink** [comment]
FYI

- The official arch linux `wireplumber` package now includes the fix @sseneca mentions above - no need to compile or use an AUR package anymore.
- If you are using `pipewire-media-session` as I was, this is actually not [recommended](https://gitlab.freedesktop.org/pipewire/media-session#pipewire-media-session), so you might want to take the opportunity to switch!

When I first saw this thread my first instinct was to use the `wireplumber-git` package on AUR, but it produced a broken configuration by default for me, so I thought it'd be helpful to make a note of this

**Comment by kingosticks** [comment]
Since Pipewire is getting more popular, if someone could draft a change to the docs we can add something. Else I don't think there's anything we can do here and I'll close this issue.
