### ISSUE TITLE
How to extract cover images from mopidy-spotiy?

### ISSUE THREAD

**Issue by chicco64** [mopidy/mopidy#2038]
Hi !
I would need to know if it is possible to extract, through a bash command, the cover image that mopidy-spotify displays through Mopidy-MusicBox-Webclient in jpg or bmp format, in a dedicated folder.
this for a possible use through Obs studio (visual radio project).
thank you

**Comment by kingosticks** [comment]
Please, use the forum for this kind of question rather than our bug tracker.
