### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by alamoudimoh** [mopidy/mopidy#2046]
Some people might argue that this is not an issue, but it is a serious issue 

There is not clear guidelines for beginners that shows us (beginners) how to do things?! And i believe that is why people don't really know mopidy.

It lacks the steps, for me it is like, hey guys i made a car, who can drive it? Only very experts drivers, thus u don't see it everywhere.

I want to use mopidy with YT Music and whole audio system. But really how, why the guidelines is somehow written assuming i know everything.

If i know everything, i wouldn't come here, i would have built my own

**Comment by kingosticks** [comment]
Thanks for the helpful insight from a beginner point of view. Please create a new topic at https://discourse.mopidy.com/ if you want to discuss this further.
