### ISSUE TITLE
Installation issue and discrepancy between pypi and debian repo

### ISSUE THREAD

**Issue by alexhalford** [mopidy/mopidy#2047]
I have tried following the installation instructions on debian bullseye, but I have hit a problem.
Installing from the debian package repository works as expected, by which I mean:
- Mopidy is installed
- `mopidyctl` is installed
- `systemctl enable mopidy.service` works
However, the version is only 3.1.1, which mopidy-mpd refuses to work with.

On the other hand, if I install via PyPi:
- Mopidy is installed, at the latest version (3.3.0)
- `mopidyctl` is **not** installed
- `systemctl enable mopidy.service` fails, as the unit file cannot be found.

This seems like a strange discrepancy. Am I doing something wrong?

**Comment by kingosticks** [comment]
You need to use our Mopidy apt repo, the contents of Debian's repo are, of course, old. See https://docs.mopidy.com/en/latest/installation/debian/#install-from-apt-mopidy-com

PyPI is the Python Package Index. It contains Python programs. It doesn't contain systemd files etc. This is quite normal.

Please ask for any further help on our forum at https://discourse.mopidy.com/ as this issue tracker is for bugs.
