### ISSUE TITLE
Pls add core event playlist_loaded

### ISSUE THREAD

**Issue by fmarzocca** [mopidy/mopidy#2050]
It would be nice to have a new core event:

**playlist_loaded(playlist)**

Called whenever playlist is loaded 

MAY be implemented by actor.

Parameters
**playlist (mopidy.models.Playlist)– the loaded playlist**

In this way, we can have the name of the currently loaded palylist

**Comment by kingosticks** [comment]
? Completed?

**Comment by fmarzocca** [comment]
No, sorry. I realized that the text is not clear so I need to rephrase it better...

What I think is really needed is an event which fires when a  **playlist is loaded in the tracklist (queue)**, which also returns the name of the playlists itself.

**Comment by kingosticks** [comment]
We'll leave it closed then. If someone wants to pick it back up again later, we'll reopen it. Your first request it possible, the second one will would require a lot more work as playlists are just groups of tracks. You cannot load a playlist into the tracklist, you can load a group of tracks.

**Comment by fmarzocca** [comment]
> You cannot load a playlist into the tracklist, you can load a group of tracks.

Yes, in fact since I understood this I decided to write a workaround. Thank you Nick
