### ISSUE TITLE
Support for a "forced refresh" option for playlists

### ISSUE THREAD

**Issue by BlackLight** [mopidy/mopidy#2062]
Since fetching playlists from a remote backend can be an expensive operation, several mopidy extensions (e.g. mopidy-spotify and mopidy-tidal) implement some form of caching as a trade-off.

mopidy-spotify loads playlist contents only at startup: it slows down mopidy's startup, but it makes sure that loading playlists later is snappy, even if that comes at the cost of losing playlist updates until the app is restarted.

mopidy-tidal, on the other hand, performs a "lazy initialization" - it loads the playlists from upstream only when `core.playlists.as_list` is called the first time. It can also be configured with a time-based setting for expiring the cached playlists, so users can tune it to find their own trade-off between playlists "freshness" and performance.

I think that things could be simplified a lot on the extensions side (and the user experience would also benefit from it) if the core could simply allow a client to pass something like a `force_refresh=True` flag to `core.playlists.as_list`, or a separate `core.playlists.refresh` method. It may break the mpd compatibility, but mpd AFAIK doesn't support the concept of playlists caching anyways.

Extensions that perform caching of playlists could then react separately on those requests to invalidate their caches, while other backends would simply ignore them.

Clients like Iris could then be used by users to manually trigger a refresh when they know that some playlists have been updated and they want to sync those changes. Right now Iris provides a "Refresh" button in the Playlists menu, but that simply calls `core.playlists.as_list`, which doesn't really have any effect on backends that perform caching.

**Comment by fmarzocca** [comment]
Agree!
(That's why in my [module](https://github.com/fmarzocca/Mopiqtt) I am using `core.playlists.refresh`)

**Comment by kingosticks** [comment]
What's missing from https://docs.mopidy.com/en/latest/api/core/#mopidy.core.PlaylistsController.refresh ?

**Comment by kingosticks** [comment]
Please re-open if my above comment misses the point of this issue.
