### ISSUE TITLE
Change the color of the icon

### ISSUE THREAD

**Issue by PritamSarbajna** [mopidy/mopidy#2065]
I think changing the color of the icons from #518cc6 to #211F1F would be more convenient

![Screenshot (250)](https://user-images.githubusercontent.com/90236635/205576902-61fff030-1256-4c56-9b28-c7c942b074c3.png)
![Screenshot (249)](https://user-images.githubusercontent.com/90236635/205576909-972172c8-1d32-4a8f-a63e-56c96e30304d.png)

> NOTE : You can assign this issue to me

**Comment by jodal** [comment]
It is not entirely clear, but I think you're referring to the GitHub buttons and their color. Also, you don't explain why you think the suggested change would be an improvement.

The buttons come from some other project/upstream source, so I find it valuable to keep them vanilla, to make 
them easier to update in the future.
