### ISSUE TITLE
Adding Mopidy Repo on Debian Bullseye 

### ISSUE THREAD

**Issue by ArkhamCookie** [mopidy/mopidy#2069]
In the [Debian/Ubuntu section of the docs](https://docs.mopidy.com/en/latest/installation/debian/#install-from-apt-mopidy-com), it says to add the archive's GPG key to `/usr/local/share/keyrings`, but the default place for keyrings on Debian (Bullseye) is `/usr/share/keyrings`.  I was wondering if I should add a note mentioning this to the docs.

It's a simple little fix:

### 1. Add the archive's GPG key:
```
sudo wget -q -O /usr/share/keyrings/mopidy-archive-keyrings.gpg https://apt.mopidy.com/mopidy.gpg`
```
### 2. Add the APT repo to your package sources:
```
printf "deb [signed-by=/usr/share/keyrings/mopidy-archive-keyring.gpg] https://apt.mopidy.com/ buster main contrib non-free\ndeb-src [signed-by=/usr/share/keyrings/mopidy-archive-keyring.gpg] https://apt.mopidy.com/ buster main contrib non-free" \
| sudo tee /etc/apt/sources.list.d/mopidy.list
```
### 3. Install Mopidy and all dependencies:
```
sudo apt update
sudo apt upgrade
```

**Comment by kingosticks** [comment]
Thanks. Maybe it should be in /etc/apt/keyrings. Posts on the internet mention all three paths, I personally don't care which but we might as well do what Debian recommends. Could you create a PR and I'll merge the fix?

**Comment by kingosticks** [comment]
I was looking at sorting this out and double-checking with the advice at https://wiki.debian.org/DebianRepository/UseThirdParty?action=show&redirect=RepositoryInstructions

> If future updates to the certificate will be managed by an apt/dpkg package as recommended below, then it SHOULD be downloaded into /usr/share/keyrings using the same filename that will be provided by the package. If it will be managed locally , it SHOULD be downloaded into /etc/apt/keyrings instead. 

We do not manage our certificate through apt/dpkg so that means ours belongs at /etc/apt/keyrings ?
