### ISSUE TITLE
Current version missing in apt repo

### ISSUE THREAD

**Issue by herrernst** [mopidy/mopidy#2072]
Hi,
according to GitHub releases the current verison of mopidy is 3.4.1: https://github.com/mopidy/mopidy/releases/tag/v3.4.1
But in the apt repo I only find 3.3, see https://apt.mopidy.com/dists/buster/main/binary-armhf/Packages
Is there any reason new releases are missing?
Thanks

**Comment by jodal** [comment]
I haven't packaged them yet. I'll try to get it done today!

**Comment by jodal** [comment]
I haven't forgotten, just ended up spending all free time buying and selling cars this week. #life
