### ISSUE TITLE
Mopidy freezed after choose TTS or Radio station

### ISSUE THREAD

**Issue by petrklic16** [mopidy/mopidy#2083]
Hi,

 i would like to ask you.
I have Odroid device with Home Assistant (newest version) and connected speaker over 3,5mm jack.
I've installed Mopidy and it's working fine, but...

 - it's not possible to udpate it (it's not main problem)
 - If i choose TTS or Radio from Media, Mopidy freezed...
I've created short video to describe my probelm :-)

[https://youtu.be/NipPb9csjQA](url)

Can you help me please?
And i would like to install spotify extension but i dont know how i can do it :-( in Home Assistant

Thank you so much

**Comment by kingosticks** [comment]
> i would like to ask you.

Sure, that's what the forum is for. Not here.
