### ISSUE TITLE
Playback breaks when changing track

### ISSUE THREAD

**Issue by miikkalaitinen** [mopidy/mopidy#2087]
I'm having a problem with changing the track after the first track has started playing usign ncmpcpp and mopidy mpd. Adding to tracks queue works and they play correctly, but changing track manually always fails (expect the first track after restart). 

I'm using:
-  GStreamer Core Library version 1.22.2
- Mopidy 3.4.1 (and bundled packages) running as a service 
- Mopidy-MPD 3.3.0
- Ubuntu 23.04 VM

I had a (somehow) working setup that i had setup in the start of April, but unfortunately I had to re-install my setup my server died. Being dump I didn't write the solution down so i have now idea what I did back then :D

Any help would be appreciated.

<details><summary>Debug Log</summary>
<p>

Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Request from [::ffff:127.0.0.1]:33824: addid "file:///home/rwbk/music/RWBK/Levyt/1997_Elomme_paivat_%28rwbkcd3%29/02-Sinfonia_nro_40%2C5_Saturnus.mp3"
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [FileBackend-3 (_actor_loop)] mopidy.file.library Looking up file URI: file:///home/rwbk/music/RWBK/Levyt/1997_Elomme_paivat_%28rwbkcd3%29/02-Sinfonia_nro_40%2C5_Saturnus.mp3
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Core-6 (_actor_loop)] mopidy.core.tracklist Triggering event: tracklist_changed()
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Core-6 (_actor_loop)] mopidy.listener Sending tracklist_changed to CoreListener: {}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdFrontend-7 (_actor_loop)] mopidy.listener Sending playlist to MpdSession: {}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Response to [::ffff:127.0.0.1]:33824:
Jun 08 13:59:07 musat mopidy[1924]:     Id: 2
Jun 08 13:59:07 musat mopidy[1924]:     OK
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Request from [::ffff:127.0.0.1]:33824: playid "2"
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got STATE_CHANGED bus message: old=GST_STATE_PLAYING new=GST_STATE_PAUSED pending=GST_STATE_READY
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Audio-2 (_actor_loop)] mopidy.audio.gst Changing state to GST_STATE_READY: result=GST_STATE_CHANGE_SUCCESS
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Audio-2 (_actor_loop)] mopidy.audio.actor Flags: 2
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [SoftwareMixer-1 (_actor_loop)] mopidy.mixer Mixer event: volume_changed(volume=50)
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [SoftwareMixer-1 (_actor_loop)] mopidy.listener Sending volume_changed to MixerListener: {'volume': 50}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got STATE_CHANGED bus message: old=GST_STATE_PAUSED new=GST_STATE_READY pending=GST_STATE_VOID_PENDING
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Audio-2 (_actor_loop)] mopidy.audio.gst Got source-setup signal: element=GstFileSrc
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Audio-2 (_actor_loop)] mopidy.audio.actor Running source-setup callback
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Audio-2 (_actor_loop)] mopidy.audio.gst Changing state to GST_STATE_PLAYING: result=GST_STATE_CHANGE_ASYNC
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Core-6 (_actor_loop)] mopidy.listener Sending volume_changed to CoreListener: {'volume': 50}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdFrontend-7 (_actor_loop)] mopidy.listener Sending mixer to MpdSession: {}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Response to [::ffff:127.0.0.1]:33824: OK
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Request from [::ffff:127.0.0.1]:33824: idle
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Response to [::ffff:127.0.0.1]:33824:
Jun 08 13:59:07 musat mopidy[1924]:     changed: playlist
Jun 08 13:59:07 musat mopidy[1924]:     changed: mixer
Jun 08 13:59:07 musat mopidy[1924]:     OK
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Request from [::ffff:127.0.0.1]:33824: noidle
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Request from [::ffff:127.0.0.1]:33824: status
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Audio-2 (_actor_loop)] mopidy.audio.actor Position query failed
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Response to [::ffff:127.0.0.1]:33824:
Jun 08 13:59:07 musat mopidy[1924]:     volume: 50
Jun 08 13:59:07 musat mopidy[1924]:     repeat: 0
Jun 08 13:59:07 musat mopidy[1924]:     random: 0
Jun 08 13:59:07 musat mopidy[1924]:     single: 0
Jun 08 13:59:07 musat mopidy[1924]:     consume: 0
Jun 08 13:59:07 musat mopidy[1924]:     playlist: 2
Jun 08 13:59:07 musat mopidy[1924]:     playlistlength: 2
Jun 08 13:59:07 musat mopidy[1924]:     xfade: 0
Jun 08 13:59:07 musat mopidy[1924]:     state: play
Jun 08 13:59:07 musat mopidy[1924]:     song: 0
Jun 08 13:59:07 musat mopidy[1924]:     songid: 1
Jun 08 13:59:07 musat mopidy[1924]:     nextsong: 1
Jun 08 13:59:07 musat mopidy[1924]:     nextsongid: 2
Jun 08 13:59:07 musat mopidy[1924]:     time: 0:273
Jun 08 13:59:07 musat mopidy[1924]:     elapsed: 0.000
Jun 08 13:59:07 musat mopidy[1924]:     bitrate: 0
Jun 08 13:59:07 musat mopidy[1924]:     OK
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Request from [::ffff:127.0.0.1]:33824: plchanges "1"
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Response to [::ffff:127.0.0.1]:33824:
Jun 08 13:59:07 musat mopidy[1924]:     file: file:///home/rwbk/music/RWBK/Levyt/1997_Elomme_paivat_%28rwbkcd3%29/01-Varasteleva_parturi.mp3
Jun 08 13:59:07 musat mopidy[1924]:     Time: 273
Jun 08 13:59:07 musat mopidy[1924]:     Title: 01-Varasteleva_parturi.mp3
Jun 08 13:59:07 musat mopidy[1924]:     Pos: 0
Jun 08 13:59:07 musat mopidy[1924]:     Id: 1
Jun 08 13:59:07 musat mopidy[1924]:     file: file:///home/rwbk/music/RWBK/Levyt/1997_Elomme_paivat_%28rwbkcd3%29/02-Sinfonia_nro_40%2C5_Saturnus.mp3
Jun 08 13:59:07 musat mopidy[1924]:     Time: 298
Jun 08 13:59:07 musat mopidy[1924]:     Title: 02-Sinfonia_nro_40,5_Saturnus.mp3
Jun 08 13:59:07 musat mopidy[1924]:     Pos: 1
Jun 08 13:59:07 musat mopidy[1924]:     Id: 2
Jun 08 13:59:07 musat mopidy[1924]:     OK
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Request from [::ffff:127.0.0.1]:33824: idle
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got STREAM_START bus message
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.actor Audio event: stream_changed(uri='file:///home/rwbk/music/RWBK/Levyt/1997_Elomme_paivat_%28rwbkcd3%29/02-Sinfonia_nro_40%2C5_Saturnus.mp3')
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.listener Sending stream_changed to AudioListener: {'uri': 'file:///home/rwbk/music/RWBK/Levyt/1997_Elomme_paivat_%28rwbkcd3%29/02-Sinfonia_nro_40%2C5_Saturnus.mp3'}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Core-6 (_actor_loop)] mopidy.core.playback Triggering track playback ended event
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Core-6 (_actor_loop)] mopidy.listener Sending track_playback_ended to CoreListener: {'tl_track': TlTrack(tlid=1, track=Track(length=273280, name='01-Varasteleva_parturi.mp3', uri='file:///home/rwbk/music/RWBK/Levyt/1997_Elomme_paivat_%28rwbkcd3%29/01-Varasteleva_parturi.mp3')), 'time_position': 69631}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Core-6 (_actor_loop)] mopidy.core.playback Changing state: playing -> playing
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Core-6 (_actor_loop)] mopidy.core.playback Triggering playback state change event
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Core-6 (_actor_loop)] mopidy.listener Sending playback_state_changed to CoreListener: {'old_state': 'playing', 'new_state': 'playing'}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Core-6 (_actor_loop)] mopidy.core.playback Triggering track playback started event
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Core-6 (_actor_loop)] mopidy.listener Sending track_playback_started to CoreListener: {'tl_track': TlTrack(tlid=2, track=Track(length=298110, name='02-Sinfonia_nro_40,5_Saturnus.mp3', uri='file:///home/rwbk/music/RWBK/Levyt/1997_Elomme_paivat_%28rwbkcd3%29/02-Sinfonia_nro_40%2C5_Saturnus.mp3'))}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdFrontend-7 (_actor_loop)] mopidy.listener Sending player to MpdSession: {}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Request from [::ffff:127.0.0.1]:33824: noidle
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Request from [::ffff:127.0.0.1]:33824: status
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Audio-2 (_actor_loop)] mopidy.audio.actor Position query failed
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Response to [::ffff:127.0.0.1]:33824:
Jun 08 13:59:07 musat mopidy[1924]:     volume: 50
Jun 08 13:59:07 musat mopidy[1924]:     repeat: 0
Jun 08 13:59:07 musat mopidy[1924]:     random: 0
Jun 08 13:59:07 musat mopidy[1924]:     single: 0
Jun 08 13:59:07 musat mopidy[1924]:     consume: 0
Jun 08 13:59:07 musat mopidy[1924]:     playlist: 2
Jun 08 13:59:07 musat mopidy[1924]:     playlistlength: 2
Jun 08 13:59:07 musat mopidy[1924]:     xfade: 0
Jun 08 13:59:07 musat mopidy[1924]:     state: play
Jun 08 13:59:07 musat mopidy[1924]:     song: 1
Jun 08 13:59:07 musat mopidy[1924]:     songid: 2
Jun 08 13:59:07 musat mopidy[1924]:     time: 0:298
Jun 08 13:59:07 musat mopidy[1924]:     elapsed: 0.000
Jun 08 13:59:07 musat mopidy[1924]:     bitrate: 0
Jun 08 13:59:07 musat mopidy[1924]:     OK
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Request from [::ffff:127.0.0.1]:33824: idle
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Dummy-9] mopidy.audio.gst Got SEGMENT pad event: rate=1.0 format=time start=0 stop=18446744073709551615 position=0
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Dummy-9] mopidy.audio.actor Audio event: position_changed(position=0)
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Dummy-9] mopidy.listener Sending position_changed to AudioListener: {'position': 0}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got TAG bus message: tags={'has-crc': [False], 'channel-mode': ['stereo'], 'audio-codec': ['MPEG-1 Layer 3 (MP3)']}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.actor Audio event: tags_changed(tags=['has-crc', 'channel-mode', 'audio-codec'])
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.listener Sending tags_changed to AudioListener: {'tags': ['has-crc', 'channel-mode', 'audio-codec']}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got TAG bus message: tags={'has-crc': [False], 'channel-mode': ['stereo'], 'audio-codec': ['MPEG-1 Layer 3 (MP3)']}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got TAG bus message: tags={'has-crc': [False], 'channel-mode': ['stereo'], 'audio-codec': ['MPEG-1 Layer 3 (MP3)']}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got STATE_CHANGED bus message: old=GST_STATE_READY new=GST_STATE_PAUSED pending=GST_STATE_PLAYING
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got ASYNC_DONE bus message.
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got TAG bus message: tags={'has-crc': [False], 'channel-mode': ['stereo'], 'audio-codec': ['MPEG-1 Layer 3 (MP3)']}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got TAG bus message: tags={'has-crc': [False], 'channel-mode': ['stereo'], 'audio-codec': ['MPEG-1 Layer 3 (MP3)']}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got TAG bus message: tags={'has-crc': [False], 'channel-mode': ['stereo'], 'audio-codec': ['MPEG-1 Layer 3 (MP3)']}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got TAG bus message: tags={'has-crc': [False], 'channel-mode': ['stereo'], 'audio-codec': ['MPEG-1 Layer 3 (MP3)']}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got TAG bus message: tags={'has-crc': [False], 'channel-mode': ['stereo'], 'audio-codec': ['MPEG-1 Layer 3 (MP3)']}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got TAG bus message: tags={'has-crc': [False], 'channel-mode': ['stereo'], 'audio-codec': ['MPEG-1 Layer 3 (MP3)']}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got TAG bus message: tags={'has-crc': [False], 'channel-mode': ['stereo'], 'audio-codec': ['MPEG-1 Layer 3 (MP3)']}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got TAG bus message: tags={'has-crc': [False], 'channel-mode': ['stereo'], 'audio-codec': ['MPEG-1 Layer 3 (MP3)'], 'minimum-bitrate': [192018], 'maximum-bitrate': [192018], 'bitrate': [192000]}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.actor Audio event: tags_changed(tags=['minimum-bitrate', 'maximum-bitrate', 'bitrate'])
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.listener Sending tags_changed to AudioListener: {'tags': ['minimum-bitrate', 'maximum-bitrate', 'bitrate']}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got TAG bus message: tags={'has-crc': [False], 'channel-mode': ['stereo'], 'audio-codec': ['MPEG-1 Layer 3 (MP3)'], 'minimum-bitrate': [191712], 'maximum-bitrate': [192018], 'bitrate': [192000]}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.actor Audio event: tags_changed(tags=['minimum-bitrate'])
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.listener Sending tags_changed to AudioListener: {'tags': ['minimum-bitrate']}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got STATE_CHANGED bus message: old=GST_STATE_PAUSED new=GST_STATE_PLAYING pending=GST_STATE_VOID_PENDING
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.actor Audio event: state_changed(old_state=playing, new_state=playing, target_state=None)
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.listener Sending state_changed to AudioListener: {'old_state': 'playing', 'new_state': 'playing', 'target_state': None}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Dummy-10] mopidy.audio.gst Got about-to-finish event.
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Dummy-10] mopidy.audio.actor Running about-to-finish callback.
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.gst Got EOS (end of stream) bus message.
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.audio.actor Audio event: reached_end_of_stream()
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MainThread] mopidy.listener Sending reached_end_of_stream to AudioListener: {}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Core-6 (_actor_loop)] mopidy.core.playback Changing state: playing -> stopped
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Core-6 (_actor_loop)] mopidy.core.playback Triggering playback state change event
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [Core-6 (_actor_loop)] mopidy.listener Sending playback_state_changed to CoreListener: {'old_state': 'playing', 'new_state': 'stopped'}
Jun 08 13:59:07 musat mopidy[1924]: DEBUG    [MpdFrontend-7 (_actor_loop)] mopidy.listener Sending player to MpdSession: {}
Jun 08 13:59:08 musat mopidy[1924]: DEBUG    [Core-6 (_actor_loop)] mopidy.core.playback Triggering track playback ended event
Jun 08 13:59:08 musat mopidy[1924]: DEBUG    [Core-6 (_actor_loop)] mopidy.listener Sending track_playback_ended to CoreListener: {'tl_track': TlTrack(tlid=2, track=Track(length=298110, name='02-Sinfonia_nro_40,5_Saturnus.mp3', uri='file:///home/rwbk/music/RWBK/Levyt/1997_Elomme_paivat_%28rwbkcd3%29/02-Sinfonia_nro_40%2C5_Saturnus.mp3')), 'time_position': 298109}
Jun 08 13:59:08 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Request from [::ffff:127.0.0.1]:33824: noidle
Jun 08 13:59:08 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Request from [::ffff:127.0.0.1]:33824: status
Jun 08 13:59:08 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Response to [::ffff:127.0.0.1]:33824:
Jun 08 13:59:08 musat mopidy[1924]:     volume: 50
Jun 08 13:59:08 musat mopidy[1924]:     repeat: 0
Jun 08 13:59:08 musat mopidy[1924]:     random: 0
Jun 08 13:59:08 musat mopidy[1924]:     single: 0
Jun 08 13:59:08 musat mopidy[1924]:     consume: 0
Jun 08 13:59:08 musat mopidy[1924]:     playlist: 2
Jun 08 13:59:08 musat mopidy[1924]:     playlistlength: 2
Jun 08 13:59:08 musat mopidy[1924]:     xfade: 0
Jun 08 13:59:08 musat mopidy[1924]:     state: stop
Jun 08 13:59:08 musat mopidy[1924]:     nextsong: 0
Jun 08 13:59:08 musat mopidy[1924]:     nextsongid: 1
Jun 08 13:59:08 musat mopidy[1924]:     OK
Jun 08 13:59:08 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.session Request from [::ffff:127.0.0.1]:33824: idle
Jun 08 13:59:48 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.network Client most likely disconnected.
Jun 08 13:59:48 musat mopidy[1924]: DEBUG    [MpdSession-8 (_actor_loop)] mopidy_mpd.network Already stopping: Actor is shutting down.
Jun 08 14:01:53 musat systemd[1]: mopidy.service: Main process exited, code=dumped, status=11/SEGV
Jun 08 14:01:53 musat systemd[1]: mopidy.service: Failed with result 'core-dump'.

</p>
</details> 

<details><summary>Config</summary>
<p>

[core]
cache_dir = $XDG_CACHE_DIR/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy
max_tracklist_length = 10000
restore_state = false

[logging]
verbosity = 2
format = %(levelname)-8s [%(threadName)s] %(name)s %(message)s
color = false
config_file = /etc/mopidy/logging.conf

[audio]
mixer = software
mixer_volume = 
output = alsasink
buffer_time = 

[proxy]
scheme = 
hostname = 
port = 
username = 
password = 

[file]
enabled = true
media_dirs = 
  /home/rwbk/music
excluded_file_extensions = 
  .html
  .htm
  .jpeg
  .jpg
  .log
  .nfo
  .png
  .txt
  .sid
  .bmp
  .m3u
  .gif
  .sfv
  .ini
  .db
  .torrent
  .zip
  .css
  .rar
  .mid
  .hvs
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[http]
enabled = false  ; Extension disabled by user config.

[m3u]
enabled = true
base_dir = /home/rwbk/music
default_encoding = latin-1
default_extension = .m3u8
playlists_dir = /var/lib/mopidy/playlists

[softwaremixer]
enabled = true

[stream]
enabled = true
protocols = 
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist = 
timeout = 5000

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6601
password = 
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist = 
  listall
  listallinfo
default_playlist_scheme = m3u

</p>
</details> 

<details><summary>Details</summary>
<p>

Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf deps" as user mopidy
INFO     [MainThread] mopidy.__main__ Starting Mopidy 3.4.1
DEBUG    [MainThread] mopidy.ext Loading entry point: file = mopidy.file:Extension
DEBUG    [MainThread] mopidy.ext Loaded extension: Mopidy-File 3.4.1
DEBUG    [MainThread] mopidy.ext Loading entry point: http = mopidy.http:Extension
DEBUG    [MainThread] mopidy.ext Loaded extension: Mopidy-HTTP 3.4.1
DEBUG    [MainThread] mopidy.ext Loading entry point: m3u = mopidy.m3u:Extension
DEBUG    [MainThread] mopidy.ext Loaded extension: Mopidy-M3U 3.4.1
DEBUG    [MainThread] mopidy.ext Loading entry point: softwaremixer = mopidy.softwaremixer:Extension
DEBUG    [MainThread] mopidy.ext Loaded extension: Mopidy-SoftwareMixer 3.4.1
DEBUG    [MainThread] mopidy.ext Loading entry point: stream = mopidy.stream:Extension
DEBUG    [MainThread] mopidy.ext Loaded extension: Mopidy-Stream 3.4.1
DEBUG    [MainThread] mopidy.ext Loading entry point: mpd = mopidy_mpd:Extension
DEBUG    [MainThread] mopidy.ext Loaded extension: Mopidy-MPD 3.3.0
DEBUG    [MainThread] mopidy.ext Discovered extensions: file, http, m3u, softwaremixer, stream, mpd
DEBUG    [MainThread] mopidy.config.keyring Fetching passwords from your keyring failed. Any passwords stored in the keyring will not be available. (org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11)
INFO     [MainThread] mopidy.config Loading config from builtin defaults
INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
INFO     [MainThread] mopidy.config Loading config from file:///etc/mopidy/mopidy.conf
INFO     [MainThread] mopidy.config Loading config from command line options
WARNING  [MainThread] mopidy.config Ignoring config section 'local' because no matching extension was found
WARNING  [MainThread] mopidy.config Ignoring config section 'ytmusic' because no matching extension was found
WARNING  [MainThread] mopidy.config Ignoring config section 'spotify' because no matching extension was found
ERROR    [MainThread] mopidy.internal.log Loading logging config '/etc/mopidy/logging.conf' failed. 'formatters'
DEBUG    [MainThread] mopidy.ext Validating extension: file
DEBUG    [MainThread] mopidy.ext Validating extension: http
DEBUG    [MainThread] mopidy.ext Validating extension: m3u
DEBUG    [MainThread] mopidy.ext Validating extension: softwaremixer
DEBUG    [MainThread] mopidy.ext Validating extension: stream
DEBUG    [MainThread] mopidy.ext Validating extension: mpd
INFO     [MainThread] mopidy.__main__ Enabled extensions: mpd, file, softwaremixer, stream, m3u
INFO     [MainThread] mopidy.__main__ Disabled extensions: http
Executable: /usr/bin/mopidy
Platform: Linux-6.2.0-20-generic-x86_64-with-glibc2.37
Python: CPython 3.11.2 from /usr/lib/python3.11
Mopidy: 3.4.1 from /usr/lib/python3/dist-packages
Mopidy-MPD: 3.3.0 from /usr/lib/python3/dist-packages
GStreamer: 1.22.2.0 from /usr/lib/python3/dist-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.44.1
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mad

</p>
</details>

**Comment by kingosticks** [comment]
We also had a 1.22 breakage in https://github.com/mopidy/mopidy/issues/2082 hmm

**Comment by miikkalaitinen** [comment]
Hi!

> (expect the first track after restart)

By this i meant that starting the first track after restarting mopidy service works fine. 

However:
- Play, Change
- Play, Pause, Change
- Play, Stop, Change
all break playback and require to restart to fix.

i had a look at #2082 before posting. 
> seems to work so far with gstreamer 1.22.2 and python 3.11
I also have gstreamer 1.22.2 and python 3.11

I can try downgrading to gstreamer 1.22.0 and see if that fixes the issue

**Comment by kingosticks** [comment]
Another thing to try would be to see if there's a problem with the duration GStreamer reports. Try comparing the output of these two commands:
1. ```python3 -m mopidy.audio.scan path_to_your_file```
2. ```gst-discoverer-1.0 path_to_your_file```

**Comment by miikkalaitinen** [comment]
Both seem to find the file and its duration correctly.

<details><summary>python3</summary>
<p>

uri                    file:///home/rwbk/music/RWBK/Konsertit/RWBK%2090v%20Musiikkitalo/7%20Woimailu.mp3
mime                   None
duration               677955
playable               True
seekable               True
tags
container-format       ['ID3 tag']
genre                  ['Other']
has-crc                [False]
channel-mode           ['stereo']
audio-codec            ['MPEG-1 Layer 3 (MP3)']
nominal-bitrate        [320000]
minimum-bitrate        [319725]
maximum-bitrate        [320031]
bitrate                [319990]

</p>
</details> 

<details><summary>gst-discover</summary>
<p>

Analyzing file:///home/rwbk/music/RWBK/Konsertit/RWBK%2090v%20Musiikkitalo/7%20Woimailu.mp3
Done discovering file:///home/rwbk/music/RWBK/Konsertit/RWBK%2090v%20Musiikkitalo/7%20Woimailu.mp3

Properties:
  Duration: 0:11:17.955925000
  Seekable: yes
  Live: no
  unknown #0: ID3 tag
    audio #1: MPEG-1 Layer 3 (MP3)
      Stream ID: 9863196db636dc8904acd137741fc3d49f905b048e92f65edd7a6d09cbc2e1a8
      Language: <unknown>
      Channels: 2 (front-left, front-right)
      Sample rate: 44100
      Depth: 16
      Bitrate: 320000
      Max bitrate: 0

</p>
</details> 

I also ran `dpkg -l | grep gstreamer` and got the following output

<details><summary>Details</summary>
<p>

**Comment by kingosticks** [comment]
There's usually only one version of a package like GStreamer in the Ubuntu repo so you either have to find a random third-party repo or build from source. I've personally never built it from source but it should be possible, maybe it's easier these days with their new build tooling. Sorry, I can't be much help with that.

If you do find a way of trying older/newer versions then I would jump to major versions.

**Comment by miikkalaitinen** [comment]
Hi!

I got it to work by changing from Ubuntu 23.04 to 22.04. 23.04 only seems to have gstreamer 1.22.2 atm but 22.04 has the newest 1.22.3! 

Thanks a lot for the help!

**Comment by kingosticks** [comment]
That's great it's working but are you sure Ubuntu 22.04 has v1.22.3?! [I can see it has v1.20.3](https://packages.ubuntu.com/jammy-updates/libgstreamer1.0-0), which would make more sense. I am very surprised there's an official Ubuntu repo providing the latest version of something.

**Comment by kingosticks** [comment]
Debian Bookworm is out soon (tomorrow?!) which has GST v1.22.0, I'll do some testing with that and 23.04 when I can.

**Comment by miikkalaitinen** [comment]
Hah! You're right :D I was only looking at the patch number. But it works now anyways! I'll try it out for a few weeks. The last installation I had had some problems with occasional crashing due to some invalid pointer errors which were propapbly coming from librespot, but we'll see how to goes this time. 

Thanks!

**Comment by adrhc** [comment]
so it seems the same as for https://github.com/mopidy/mopidy/issues/2082 and https://github.com/mopidy/mopidy/issues/2087; but this means mopidy is not working on Ubuntu 23.04
