### ISSUE TITLE
Backend.lookup should take a list of URIs

### ISSUE THREAD

**Issue by kingosticks** [mopidy/mopidy#2116]
Currently `Backend.lookup()` is called by `Core.LibraryController.lookup()` for each URI in turn. This prevents backends from potentially batching up the work. In some cases this wastes valuable API quota resources. We should make `lookup()` work like `get_images()` which already supports lists.

This will be a change to the `Backend` API so care will be needed to avoid breaking existing backends.

**Comment by rchatrath7** [comment]
Hi @kingosticks @jodal would I be able to be assigned to this? I think I have a PR that will be close for this.

**Comment by daniele-athome** [comment]
Any chance this will be backported to v3? If v3 is still maintained, that is.

**Comment by kingosticks** [comment]
We were not planning to do another v3 release.
