### ISSUE TITLE
Websocket error only when connecting to mopidy running as service

### ISSUE THREAD

**Issue by rpa144** [mopidy/mopidy#2125]
I am setting up Mopidy on RaspberryPI4B buster.
My music is on usb stick.
I have given 755 to all the directories and 644 to all the files on the stick to allow mopidy user to access the files.
I am using mopidy mobile client installed on android tablet (fire)
I have made identical config changes in both the mopidy.conf files (for Pi user and the for service user)
Mopidy config and sudo mopidyctl config both show file and local enabled true and no errors on config.
I installed mopidy following all the directions from mopidy.com and not other tool/internet pages.
When I run mopidy in Pi's context using mopidy command, the mobile client app runs perfectly, lists all the music and  when I click on track, it plays it.
When I run mopidy as a service using sudo service mopidy start.. this is where problem comes.
Mopidy mobile client connects to server and is able to explore all the media. But when I click on any track to play (or click anywhere any other tab, menu etc) it gives me websocket closed ignore/retry error box.
If I stop the service and run mopidy as Pi, it works ok. the error happens only when I am running mopidy as a service.

**How to reproduce**
Looks like mopidy service user is not able to open the websockets using standard install for buster.

**Environment**
Please complete the following information:
- Operating system raspbian based on debian buster
- [Running Mopidy](https://docs.mopidy.com/en/latest/running/) as a service or in the terminal? as a service
- 
- Your config (output of `sudo mopidyctl config`)
- `
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf config" as user mopidy
[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy
max_tracklist_length = 10000
restore_state = false

[logging]
verbosity = 0
format = %(levelname)-8s [%(threadName)s] %(name)s %(message)s
color = false
config_file =

[audio]
mixer = software
mixer_volume =
output = autoaudiosink
buffer_time =

[proxy]
scheme =
hostname =
port =
username =
password =

[file]
enabled = true
media_dirs =
  /media/pi/xxxx-xxxx/Music
excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .db
  .nfo
  .pdf
  .png
  .txt
  .zip
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[http]
enabled = true
hostname = 0.0.0.0
port = 6680
zeroconf = Mopidy HTTP server on $hostname
allowed_origins =
csrf_protection = true
default_app = mopidy

[m3u]
enabled = true
base_dir =
default_encoding = latin-1
default_extension = .m3u8
playlists_dir =

[softwaremixer]
enabled = true

[stream]
enabled = true
protocols =
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist =
timeout = 5000

[local]
enabled = true
max_search_results = 100
media_dir = /media/pi/xxxx-xxxx/Music
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
included_file_extensions =
excluded_file_extensions =
  .cue
  .directory
  .html
  .jpeg
  .jpg
  .db
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
directories =
  Albums                  local:directory?type=album
  Artists                 local:directory?type=artist
  Composers               local:directory?type=artist&role=composer
  Genres                  local:directory?type=genre
  Performers              local:directory?type=artist&role=performer
  Release Years           local:directory?type=date&format=%25Y
  Tracks                  local:directory?type=track
  Last Week's Updates     local:directory?max-age=604800
  Last Month's Updates    local:directory?max-age=2592000
timeout = 10
use_artist_sortname = false
album_art_files =
  *.jpg
  *.jpeg
  *.png
'
- Software versions (output of `sudo mopidyctl deps`)
- 
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.co                                                                                                             nf deps" as user mopidy
Executable: /usr/bin/mopidy
Platform: Linux-5.10.103-v7l+-armv7l-with-debian-10.13
Python: CPython 3.7.3 from /usr/lib/python3.7
Mopidy: 3.4.1 from /usr/lib/python3/dist-packages
Mopidy-Iris: 3.68.0 from /usr/local/lib/python3.7/dist-packages
  Mopidy: 3.4.1 from /usr/lib/python3/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  Pykka: 2.0.3 from /usr/lib/python3/dist-packages
Mopidy-Local: 3.2.1 from /usr/lib/python3/dist-packages
GStreamer: 1.14.4.0 from /usr/lib/python3/dist-packages/gi
  Detailed information:
    Python wrapper: python-gi 3.30.4
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mad

- Any specific hardware (e.g. an exotic USB soundcard) USB data stick.

**Additional context**
Add any other context about the problem here. If appropriate, upload an [appropriately verbose](https://docs.mopidy.com/en/latest/troubleshooting/#debug-logging) log file showing the bug.

**Comment by kingosticks** [comment]
If everything works up until trying to start playback then this is a playback issue and the websocket is likely fine. Also note there are many, many fully working installs of Mopidy on RPI OS out there.

This sounds like a system permission issue and not a Mopidy bug (we'd much prefer these were posted in the forum).

Please turn on debug level logging, restart Mopidy, reproduce the problem, and provide that log.

**Comment by rpa144** [comment]
Thanks for chiming in and a deep heartfelt thank you to you and everyone actively contributing to this community.

Fixed the issue by adding user mopidy to a bunch of other groups besides the  video group mentioned in the install docs. (followed https://discourse.mopidy.com/t/solved-no-audio-as-service-but-sudo-u-mopidy-works-dietpi/3134/3) I am pretty sure all those groups are not required. however it fixed the websockets issue!!!

Ideally though standard install should have configured required user groups for user mopidy ( I am thinking netdev or www-data. will try to recreate error by removing those).
I am running absolute vanilla version of everything. (mopidy is the only thing installed on my RPI4b. and it was weird seeing that websockets error happened only when running as service)

You can close the bug. I will ask follow up issues in the forum.
once again, thank you for being so super about helping everyone.
