### ISSUE TITLE
mopidy is crashing on play (coredump)

### ISSUE THREAD

**Issue by solsticedhiver** [mopidy/mopidy#2147]
On archlinux arm (arvm7h) on rpi3b, with mopidy 3.4.1-3, gstreamer 1.22.9-2, and using an USB audio (basic) card (Unitek Y-247A ?), mopidy is crashing when trying to play either local file (mp3, mp4) or a radio stream.
kernel 6.6.14-1-rpi

Even with verbose log, I can't find anything in mopidy.log, or in my system log.

Sometimes, it does not crash, in 1 in 10 times. But that s very rare.
Sometimes, there is that infamous bug:
```
OverflowError: Python int too large to convert to C long
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mopidy/audio/actor.py", line 212, in on_message
    elif msg.type == Gst.MessageType.BUFFERING:
         ^^^^^^^^
SystemError: <built-in method get_value of gi.FieldInfo object at 0xb4293ef0> returned a result with an exception set
```
But that is only for radio stream and not local files...

**Comment by kingosticks** [comment]
If it's also with local files then it's likely not the C long buffering problem.

What is arvm7h? Please provide the info we ask for in bug reports. There's also GST_DEBUG (see Mopidy docs) to generate verbose logs. Logs are useful to us, even if not to you.

**Comment by solsticedhiver** [comment]
armv7l in fact.

log of `GST_DEBUG=5 GST_DEBUG_NO_COLOR=1 mopidy -v 2>&1|tee -p mopidy.log`
* setting volume to 50%, go to broswe, files, click on an mp3 (local file)
[mopidy.log.gz](https://github.com/mopidy/mopidy/files/14168449/mopidy.log.gz)

**Comment by kingosticks** [comment]
Is it possible to collect the core dump? It's interesting that it is maybe tag related,

**Comment by solsticedhiver** [comment]
[mopidy-9139.dump.gz](https://github.com/mopidy/mopidy/files/14169126/mopidy-9139.dump.gz)
```
$ coredumpctl info 9139
           PID: 9139 (mopidy)
           UID: 1000 (cassini)
           GID: 1000 (cassini)
        Signal: 11 (SEGV)
     Timestamp: Mon 2024-02-05 17:25:00 CET (1h 2min ago)
  Command Line: /usr/bin/python /usr/bin/mopidy -v
    Executable: /usr/bin/python3.11
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (cassini)
       Boot ID: 63b1301097c640e4bd817b4802813fb9
    Machine ID: 6d8db8504b2b4c3b9dcde2b88ebae33f
      Hostname: daphnis
       Storage: /var/lib/systemd/coredump/core.mopidy.1000.63b1301097c640e4bd817b4802813fb9.9139.1707150300000000.zst (present)
  Size on Disk: 9.0M
       Message: Process 9139 (mopidy) of user 1000 dumped core.
                
                Stack trace of thread 9241:
                #0  0x00000000b5dc4136 n/a (n/a + 0x0)
                ELF object binary architecture: ARM
```

**Comment by kingosticks** [comment]
I don't have an arm machine to hand to load that dump. If you could provide the relevant backtrace with debug symbols that would help.

**Comment by kingosticks** [comment]
Please try upgrading your version of liborc to  0.4.37, this might be the same issue as https://gitlab.freedesktop.org/gstreamer/orc/-/issues/64

**Comment by kingosticks** [comment]
ok, thanks for the report.

**Comment by kingosticks** [comment]
FYI that was some other

> I tried to rebuild gstreamer; it failed
> 
> ```
> gstreamer/subprojects/gst-plugins-bad/ext/neon/meson.build:1:11: ERROR: Dependency lookup for neon with method 'pkgconfig' failed: Invalid version, need 'neon' ['<= 0.32.99'] found '0.33.0'.
> ```
> 
> I am giving up. Using now mpd and mympd.

FYI that was [due to some other bug](https://gitlab.archlinux.org/archlinux/packaging/packages/gstreamer/-/issues/3) (now supposedly fixed)

**Comment by solsticedhiver** [comment]
yeah. just minutes after my previous message, I found that page too, and used the fix on antoher try at rebuilding gstreamer, but it failed later on in the build process nonetheless...

**Comment by kingosticks** [comment]
urgh, well again, thanks for reporting none the less.

**Comment by solsticedhiver** [comment]
with a new gstreamer 1.22.10 package released on archlinuxarm, it seems to work better now....

**Comment by kingosticks** [comment]
Yes, thanks to @blacklight (#2148) who chased it up with the gstreamer team.
