### ISSUE TITLE
Problem to add radio uri's (http) to tracklist

### ISSUE THREAD

**Issue by TCke83** [mopidy/mopidy#2163]
After upgrading to the 4.x release of mopidy i'm unable to add http stream uri's to the tracklist.

`DEBUG    2024-07-07 10:59:47,352 [2556:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.116.182: '{"id":8,"jsonrpc":"2.0","method":"core.tracklist.add","params":{"uris":["http://icecast.vrtcdn.be/mnm_hits-high.mp3"]}}'
DEBUG    2024-07-07 10:59:47,354 [2556:HttpServer] mopidy.http.handlers
  Sent WebSocket message to 192.168.116.182: '{"jsonrpc": "2.0", "id": 8, "result": []}'
`

I've looked in the api documentation, but it seems to me the request is correct. I've read some api's have changed but this one seems to match the request i sent t oadde the track.

Anyone has an idea why this request doesn't work anymore? It used to work with the pre 4.x version.

**Comment by TCke83** [comment]
Is this a feature that doesn't work yet on the 4.x version? Or is the reason it doesn't work something else?

**Comment by kingosticks** [comment]
I can't think of a reason why this would have changed, it should work as before. Can you share a verbose log showing this?

**Comment by TCke83** [comment]
I've tried this again, it works now, don't really know why. Maybe a supportive library was missing. But i'm going to close the issue.

**Comment by TCke83** [comment]
@kingosticks keep up the good work, love this project!
