### ISSUE TITLE
Add a DLNA media server (DMS) backend

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#230]
This issue concerns Mopidy getting and playing music stored on a DLNA media server (DMS), e.g. a NAS somewhere on the local network.

This issues _does not_ concern Mopidy being a DLNA media server (DMS) itself, exposing it's library to other DLNA compatible devices. For that, see #52.

**Comment by hoschi** [comment]
:+1: for DLNA Media Server

**Comment by jodal** [comment]
https://github.com/tkem/mopidy-dleyna lets Mopidy play music from DLNA servers, like a NAS.
