### ISSUE TITLE
Add init script

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#266]
The init script should:
- run Mopidy in the background as a daemon
- run Mopidy as its own user

**Comment by fradeve** [comment]
I'm using this: https://gist.github.com/Freso/7434553
and unfortunately on my Arch it is not working, don't know why.

**Comment by morfeokmg** [comment]
> systemd start script (arch and others)
> 
> Create
> `$ nano /etc/systemd/system/mopidy.service`
> 
> ```
> [Unit]
> Description=Mopidy        
> After=network.target
> 
> [Service]
> ExecStart=/usr/bin/mopidy --config=/etc/mopidy.conf
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> Enable
> `$ systemctl enable /etc/systemd/system/mopidy.service`

I need to change too, i use fedora 30, but i use the SELinux, and mopidy doesn't have security rules to use the system. 
In fact, is more "easy" change the user to mpd than generate all kind of rules of SELinux.
In my case, i need use an external disk to play my music, but i need change several options 
I try, by example:(grants as 777)
` semanage fcontext -a -t mpd_data_t '/var/lib/mopidy/music/ArchivosWAV(/.*)?'`
` restorecon -R -v /var/lib/mopidy/music/ArchivosWAV`

and mopidy can't read the /dev/sdb1 mount in /mnt/MUSIC and linked to /var/lib/mopidy/music/ArchivosWAV

other point is that user mopidy doesn't have grants as this kind of directories:
```
setsebool -P mpd_enable_homedirs 1
setsebool -P use_fusefs_home_dirs 1
```
then, is more easy change to mpd user than make all the different rules to mopidy.
