### ISSUE TITLE
Add possibility to start multiple instances of mopidy on the same computer

### ISSUE THREAD

**Issue by SoundTentacle** [mopidy/mopidy#329]
It would be nice to be able to start multiple instances of mopidy.
Every instance get its own settings.py-file which you has to specify as start parameter

**Comment by thegreatmichael** [comment]
how do we launch multiple instances? it looks like you're saying i should do something on the command line. looking at https://docs.mopidy.com/en/latest/config/ it doesn't look like there's a relevant setting (e.g. `port`)
