### ISSUE TITLE
Create Grooveshark backend

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#340]
http://developers.grooveshark.com/docs/public_api/v3/

**Comment by camilonova** [comment]
Here you go:

https://github.com/camilonova/mopidy-grooveshark

**Comment by txomon** [comment]
Are you using official API?

**Comment by camilonova** [comment]
I'm using this https://github.com/koehlma/pygrooveshark

**Comment by txomon** [comment]
Oh ok =)

**Comment by camilonova** [comment]
I could not find any other python library, did you know any?

**Comment by txomon** [comment]
Nope, not at least a working one. I started to do my own, but didn't have
time :/

Anyway, AFAIK, the only way to support broadcasts (the feature I am
interested in, is using unofficial API

**Comment by camilonova** [comment]
Agree, I tried to do it on my own but I failed. I asked for help: https://github.com/koehlma/pygrooveshark/issues/24

Seems the author can do it: https://github.com/koehlma/pygrooveshark/issues/5#issuecomment-24640316

I am very interested in broadcast support too.

**Comment by txomon** [comment]
Well, he said he hadn't done it yet. Maybe contributing to that would be
the way to go,.. instead of creating our own.

BTW, I would add pygrooveshark as a dependency rather than copying it in
the repo.

**Comment by camilonova** [comment]
Too big for raspberry https://github.com/koehlma/pygrooveshark/issues/22
