### ISSUE TITLE
Squeezebox support

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#357]
See http://wiki.slimdevices.com/index.php/SLIMP3_client_protocol and https://github.com/winjer/squeal as starting points. Note that we could also have mopidy output to a squeezebox if we just have icecast or http streaming working, as these devices are essentially just told what stream to play.

Mainly put in as a placeholder for the idea as I don't really intend to spend any time on this idea as I believe mopidy + webinterface + android is likely to be a better solution.

**Comment by alexxtasi** [comment]
Hi @adamcik 
I know it's been a long time.... ;-) 
But I am interested in using mopidy (RPi installation) and also connect my old squeezbox to it, so mopidy streams to my squeezbox.

Is this possible and in which way?
Or this issue is closed because there is no way to it ?

regards
