### ISSUE TITLE
Multi unit synchronous audio

### ISSUE THREAD

**Issue by lydhig** [mopidy/mopidy#408]
I would like to use several (in my case Raspberry Pi with Pi Musicbox) in my house. I would like to have all these units play the same stream synchronously. This means that I could play the same Spotify music in all house with one Spotify account. To make this all  audiobuffer in all units has to be synchronized with each other.

The expensive audiosystem Sonos has this killer feature.

**Comment by sashahilton00** [comment]
Just reopening this thread as there appears to be a solution that could be easily bundled with mopidy and would make a killer feature:https://github.com/badaix/snapcast is a separate service that accepts any audio piped into <code>/tmp/snapfifo</code> and then broadcasts it in sync to any clients that are listening for it. It doesn't enable individual music on a per room basis, but it does enable synced multi-room audio, and would be a good place to start if thinking about multi session audio streaming, though managing multiple streams isn't possible with a single instance of mpd/mopidy yet I think... perhaps mopidy could later add functionality to manage multiple mpd instances, then multi session streaming would be possible...

**Comment by SeanDS** [comment]
Ah, that's very exciting! It looks like there are even instructions for Mopidy. Thanks for the update.

**Comment by linuxguy123** [comment]
I'm very interested in this as well.   I'm willing to write some code or test.

**Comment by sashahilton00** [comment]
It would be great. Sadly I just put it on here for informational purposes, and am far too busy to be contributing anything significant. Works well when testing though :)
