### ISSUE TITLE
Add more powerful search capabilities

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#45]
Currently, the search capabilities in the local backend is quite naive and simplistic. It would be nice to have more powerful search capabilities, maybe using an existing search solution.

An existing search solutions that seems interesting is [Whoosh](http://whoosh.ca/) which is a pure Python search engine, available under the Apache 2 license, both from PyPI and as a Debian package.

**Comment by adamcik** [comment]
This is no longer relevant due to #1003 unless we want to move the issue to a new external repo?
