### ISSUE TITLE
Support crossfading between tracks

### ISSUE THREAD

**Issue by Florian95** [mopidy/mopidy#450]
Hi,

Add the crossfade value in configuration file to a general crossfader between tracks changes.

Regardsm

**Comment by Dzordzu** [comment]
Maybe use modified version of the [gst-plugin-base/crossfade](https://github.com/GStreamer/gst-plugins-base/blob/master/tests/examples/compositor/crossfade.c)

**Comment by Hoerli1337** [comment]
Hi!
Wanted to ask if there is any progress here in the meantime.
Would also find it enormously cool if the playback of individual songs would be seamless or a suitable transition could be created.
This not only for Spotify but also for other playback source such as local or YouTube (Music).
