### ISSUE TITLE
Scanner doesn't like m4a files either ...

### ISSUE THREAD

**Issue by iw65ihg** [mopidy/mopidy#455]
I tried to create the tag_cache file with mopidy-scan. For all m4a (created by iTunes) I get the warning: WARNING  Failed file:///media/store/iTunesMusic/ZZ%20Top/La%20Futura/10%20Have%2                                                                         0A%20Little%20Mercy.m4a: Your GStreamer installation is missing a plug-in.
Looks like a similar issue as #275.
I'm on Mopidy 0.14.1.

**Comment by nshung** [comment]
I get the same error on mac. My "gst-inspect-0.10 | grep aac" output looks like:

typefindfunctions: audio/aac: aac, adts, adif, loas
audioparsers:  aacparse: AAC audio stream parser

How do I install "gstreamer0.10-ffmpeg" on mac? Brew says there is no such thing. I have already installed ffmpeg though.

**Comment by jodal** [comment]
The GStreamer 0.10 formulas are in the alternative `homebrew-versions` repository, as they have been replaced by GStreamer 1.x in the main Homebrew repository.

To install it from the alternative repository, either run:

```
brew tap homebrew/homebrew-versions
brew install gst-ffmpeg010
```

Or:

```
brew install homebrew/homebrew-versions/gst-ffmpeg010
```

I think it's also possible to get AAC support through `gst-plugins-bad010` if you install it with `faad2` support:

```
brew install homebrew/homebrew-versions/gst-plugins-bad010 --with-faad2
```

Our `mopidy/mopidy/mopidy` formula installs `gst-plugins-bad010` with this argument by default: https://github.com/mopidy/homebrew-mopidy/blob/master/mopidy.rb
