### ISSUE TITLE
WiMP / Tidal support

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#48]
It would be nice to have support for the Norwegian music streaming service, [WiMP](http://www.wimp.no/). They currently have no public API or library, unlike Spotify, but according to [tweets](http://twitter.com/wimp/status/8975885632) from their official Twitter account they do have private APIs that it is possible to gain access to.

I guess they won't like their private APIs to be used in an open source project, but maybe we could get access and develop the backend as closed source, only to publish it once they make their API public?

**Comment by tincanfury** [comment]
I take it no one has worked to getting TIDAL support yet? There is a fully working KODI add-on already created and working, so their API works, and people have figured it out. If I can get mopidy to work in openwrt I can try and take a crack at it with my zero-to-nil programming abilities...

**Comment by mones88** [comment]
if you are still interested in Tidal integration I've written a plugin... 
It is my first attempt at writing python code and mopidy plugin so feel free to improve it if needed!!
The plugin uses tamland's api to interact with Tidal, thank you @tamland 
[Repo here](https://github.com/mones88/mopidy-tidal)

**Comment by landroni** [comment]
Since there is apparently an API available, shouldn't this request be reopened?

**Comment by jodal** [comment]
What @tkem said, and it the extension already exists: https://github.com/mones88/mopidy-tidal

**Comment by landroni** [comment]
Oh, thank you, I wasn't aware of this. 

I actually had a similar request for Qobuz support... Is there an extension for this as well? Should I open a separate ticket for this?

**Comment by kingosticks** [comment]
In general, there is point opening new issues for extensions you'd like to see as there is nothing actionable in Mopidy. The APIs exist, someone just needs to come along and make use of them.

**Comment by tkem** [comment]
@landroni: Such questions should better be placed on Mopidy's discussion forum: https://discuss.mopidy.com/.
Even we don't know all extensions that exist out there, or are in development..

**Comment by shawaj** [comment]
Will Mopidy-tidal become an official plugin? If my company wanted to help contribute to mopidy development of Qobuz plugin what is best way to do that?

**Comment by tkem** [comment]
@shawaj: Please post general questions to http://discuss.mopidy.org.
@jodal: Should we lock conversations on this issue (and maybe other extensions related core issues, too?)

**Comment by shawaj** [comment]
@tkem - the questions aren't general questions. They relate to this thread. Can you not just answer here? Or maybe via email

**Comment by tkem** [comment]
@shawaj: This thread was closed, because this is not a Mopidy core issue. Tidal-specific questions should be placed on mopidy-tidal's issue tracker, where people involved with Mopidy-Tidal will see it. As for Qobuz, there's already a thread here: https://discuss.mopidy.com/t/qobuz-backend-plugin-for-mopidy/1145

**Comment by shawaj** [comment]
Ok sorry, didn't mean to annoy you or anything but just wanted to know if
this would be pulled into mopidy as an official plugin or not?

What makes the difference between an unofficial plugin and am officially
supported one under the mopidy repos?

Thanks again

**Comment by tkem** [comment]
@shawaj: No offense meant, we're just trying to keep people from commenting on closed issues that nobody will look at any more ;-)
Posting on discuss.mopidy.com might also attract the attention of "third-party" extension developers which are not members of the mopidy org.
Extensions in the mopidy repos are generally maintained by Mopidy's core developers. Sometimes extensions which have been abandoned by their original maintainers are also moved here (look for "Maintainer Wanted" signs). Whether this makes them more "official" than others I don't know.

**Comment by shawaj** [comment]
Cool :-) thanks so much.

Do you accept contributions from developers employed by companies just to
do this?

As we're looking to put a full time developer on supporting existing open
source projects and creating new ones in the SBC and audio space
(predominantly to support projects we're working on - by way of full
transparency)... and possibly more devs as our company expands (we're a
hardware company and we rely on a lot of open source software so keen to
give back!)

Mopidy/PiMusicBox is one we love and use every day and are building
products around so want to help grow it - for us and for everyone :-)

**Comment by tkem** [comment]
I don't think there'll be any objections to contribution from people who get actually paid for working on Mopidy, but I guesz @jodal and/or @adamcik should have the final word on that.
However, as I anticipated, this discussion *should* be continued on discuss.mopidy.org!!!
