### ISSUE TITLE
Documentation for running as a service on OSX

### ISSUE THREAD

**Issue by terlar** [mopidy/mopidy#488]
I didn't find this information anywhere. Where would I put documentation on how to make mopidy run as a service on OSX?

`~/Library/LaunchAgents/cx.mopidy.plist`

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>cx.mopidy</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/bin/mopidy</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PYTHONPATH</key>
    <string>/usr/local/lib/python2.7/site-packages</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>WorkingDirectory</key>
  <string>/usr/local</string>
</dict>
</plist>
```

**Comment by vdesabou** [comment]
FYI, the link http://www.benjaminguillet.com/blog/2013/08/16/launch-mopidy-at-login-on-os-x/ is now 404

**Comment by jodal** [comment]
Someone already filed a bug about the link being broken, so the
instructions were recently included in the Mopidy docs.

See
https://docs.mopidy.com/en/latest/installation/osx/#running-mopidy-automatically-on-login
