### ISSUE TITLE
Icecast streaming stopping on next track

### ISSUE THREAD

**Issue by MrFly** [mopidy/mopidy#492]
Hi,

I'm using current mopidy 0.14.2 with Ubuntu 12.04 to stream from spotify via shout2send to my local icecast2 server (controlled by mpd). Everytime the track changes (maybe manual via any mpd client or automatically after end of first track) the stream is dead. That means, that any clients on the icecast server gets dropped.

Is there any chance to fix this behaviour, maybe with something like a "between-tracks-silent-buffer"??

Thank you very much.

**Comment by allquixotic** [comment]
This seems like it's implemented now. I'm able to listen to multiple songs without "refreshing" the stream with the develop version in git.

**Comment by adamcik** [comment]
This should indeed be fixed in develop with gapless, last known ways to break this is with prev/next. But there is an other bug to track that. And if you pause, but the pause one we aren't going to fix.

**Comment by gerroon** [comment]
Is this fixed or not?  I am having similar issues, I can get the stream and the fallback playing but i cant play next or another track, generally the players complain (mpg123, ffplay etc) and quit when trying to advance

**Comment by brodly** [comment]
also curious if this is fixed? Currently using the fallback stream workaround, but it doesn't seem to work that well. Pause works, but next stops the stream.

**Comment by JaskaRoman** [comment]
I'm currently using the fallback track workaround, which seems to work, as long as the next track is from the same source (e.g. Spotify, YouTube). Otherwise, the client playback stops and needs a refresh. Is there anything I can try to get this working?
