### ISSUE TITLE
Support local tracks in spotify playlists

### ISSUE THREAD

**Issue by kemurphy** [mopidy/mopidy#519]
If a spotify playlist contains a local track (spotify:local URI), mopidy should search the other backends for a matching track (the URI provides album, artist, track name, and duration).  @jodal thinks this would require refactoring core.  It would at least require a way to avoid deadlock if we wanted to do what the spotify desktop client does and search spotify for a matching track.  Searching other backends for matching tracks currently doesn't cause problems if the backends list is made available where it needs to be.

**Comment by adamcik** [comment]
I think this is one of the issues we've mostly decided to give up on. Closing and if someone disagrees reopen.
