### ISSUE TITLE
Make backend.playlists.lookup() return list of track URIs

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#527]
The lookup of tracks is currently only done against the local backend, so other URI types be it http or file won't work even if the stream backend can handle them.

We have to options so solve this:

1. Simply add a ``Track(uri=uri)`` for cases where lookup fails and it's not a local uri.
2. Update the API between core and backends to only return playlist tracks uris, which implies core needing to look them all up afterwards.

First option is obviously the least intrusive, the second is in my opinion the correct one.

**Comment by jodal** [comment]
Option 2 and #704 is part of the Core API v1.0 plans. Closing this issue, as this is tracked elsewhere.
