### ISSUE TITLE
RAOP audio output

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#58]
If Mopidy supported [RAOP](http://en.wikipedia.org/wiki/Remote_Audio_Output_Protocol) audio streaming, we could stream audio to Apple's [AirPort Express](http://www.apple.com/airportexpress/).

**Comment by nmatthews** [comment]
Sorry to revive a four year old comment, but I found this thread and wanted to try the link Adam posted at https://github.com/adamcik/mopidy/tree/feature/roap-support, but that link appears dead. If you could recreate the patch or give me a suggestion as to how to do so I'd be grateful and would test.
