### ISSUE TITLE
Write journal files in json library.

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#651]
For each flush from the local library, then json backend should write out all the tracks since last flush making it possible to pickup where we left off.

**Comment by adamcik** [comment]
```
with gzip.open('/tmp/library.jsonl.gz', 'wb') as fp:
    json.dump({'version': 1.0}, fp)
    for track in library['tracks']:
        fp.write('\n')                                        
        json.dump(track, fp, cls=ModelJSONEncoder)

with gzip.open('/tmp/library.jsonl.gz', 'rb') as fp:
    header = json.loads(fp.readline())
    for line in fp.readlines():
        print json.loads(line, object_hook=model_json_decoder)
```

might be a viable alternative for this. Idea from http://jsonlines.org/

**Comment by dz0ny** [comment]
You could also shard libraries based on artist or path...

**Comment by adamcik** [comment]
http://blog.gocept.com/2013/07/15/reliable-file-updates-with-python/ might also be a nice reference.

**Comment by jodal** [comment]
Ref #1003, we're planning to discontinue the JSON backend and replace it with Mopidy-Local-SQLite. Thus, I'm closing this.
