### ISSUE TITLE
Improve IPv6 handling for windows

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#664]
> Done! Another improvement might be to return false in https://github.com/abarisain/mopidy/blob/window/mopidy/utils/network.py#L22 if hasattr(socket, 'IPPROTO_IPV6') && sys.platform != 'win32' or move what is in if has_ipv6: in another function, and try on this.

> The motivation would be that if this fails, mopidy will not crash like it used to, but will only listen on IPV6, which can look like it is not listening at all until you try connecting using IPV6. That's what happened to me before I added the "else", and it took me hours to figure this out.

**Comment by jodal** [comment]
In the two years that has passed, I haven't heard about anyone else trying to run Mopidy on Windows. I think this is more noise than useful to keep open. Closing.
