### ISSUE TITLE
Add missing MPD playlist commands

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#669]
- [x] playlistadd
- [x] playlistclear
- [x] playlistdelete
- [x] playlistmove
- [x] rename
- [x] rm
- [x] save
- [ ] playlistfind
- [ ] playlistsearch

**Comment by IvanMalison** [comment]
@adamcik Is there an official source of documentation for the mpd protocol? I cant seem to find anything mentioning playlistsearch...

**Comment by trygveaa** [comment]
http://www.musicpd.org/doc/protocol/queue.html

**Comment by jodal** [comment]
We need to crosscheck this todo list against #1187, #1308 and #1322.

**Comment by jodal** [comment]
I crosschecked and it seems all commands mentioned here have been implemented by the above PRs, except `playlistfind` and `playlistsearch` which operates on the current playlist, not the stored playlists.

**Comment by adamcik** [comment]
Should we look at if playlistfind/search need to be added for the next release?

**Comment by jodal** [comment]
I'm not sure I understand what the criteria for deciding if we need to add these two commands for 1.2 would be?

**Comment by adamcik** [comment]
What MPD protocol version we are claiming.

**Comment by jodal** [comment]
The two commands are new in MPD 0.13, so strictly speeking we've been missing them for all the six years Mopidy has existed.

**Comment by adamcik** [comment]
Whoops, so we should at least have not implemented stubs then for 1.2/2.0 I guess

**Comment by jodal** [comment]
We have that already, it seems.

**Comment by jodal** [comment]
We've added all mentioned missing playlist commands in develop. The two remaining are not playlist commands, but tracklist commands. We do have empty placeholders for those, and don't need open issues for them, like we don't have open issues for all the other commands we've never implemented. Closing.
