### ISSUE TITLE
Change track.last_modified to be milliseconds since Unix epoch

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#678]
To be consistent with `playlist.last_modified`.

**Comment by adamcik** [comment]
We could probably just go ahead and do this, only think I suspect actually cares about this value is the local scanner.

**Comment by tkem** [comment]
@adamcik: Mopidy-Local-SQLite uses `track.last_modified` for its "Last Week's Updates" virtual directory, so changing the resolution to milliseconds would break this.
That being said, sure that's easy to fix in Mopidy-Local-SQLite, and consistency might be more important.
