### ISSUE TITLE
Return valid db_update date/time in MPD stats response

### ISSUE THREAD

**Issue by CDrummond** [mopidy/mopidy#686]
I'm the author of Cantata, a Qt4/5 MPD client. To populate the music listings I use the listallinfo command - which is now supported by Mopidy as of 0.18. Cantata caches the music listing, to save calling listallinfo at each start-up. To ensure the cache is valid, Cantata stores MPD's db_update date/time in its cache file - and compares this with that returned by a stats call.

Currently, Mopidy returns 0 for all values in the stats response. Could mopdiy not return the date/time of the local backend's tag cache instead?

(I'm ok with leaving the other fields as all 0 - as this is currently how Cantata detects that it is connected to Mopidy :-) )

**Comment by adamcik** [comment]
Since the MPD stats don't really make sense in Mopidy, and we just merged #990 which blacklists `listall` and `listallinfo` info I don't think there is anything that can be done with this bug. So going ahead and closing it.
