### ISSUE TITLE
Warn if module is configured but not installed

### ISSUE THREAD

**Issue by schinken** [mopidy/mopidy#694]
Throw a warning if a module e.g. "spotify" is configured but not installed. 

I migrated my mopidy config recently but forgot to install mopidy-spotify which resulted in no errors but in a not working mopidy spotify connection. 

It would be nice if there would be an warning for "spotify module configured but not installed/found"

**Comment by jodal** [comment]
Fixed by #1002 

Seems like your "fixes: #nnn" syntax isn't what GitHub expects, ref https://help.github.com/articles/closing-issues-via-commit-messages/.
