### ISSUE TITLE
Add more type checks to core API

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#700]
Example of problem we currently have: Web clients can easily get strings into the tracklist by calling `mopidy.tracklist.add('foo')`, where 'foo' is handled as a list of tracks, adding 'f', 'o', and 'o' to the tracklist. Obviously this fails and crashes Mopidy when someone try to use the strings as `Track` objects.

We should probably do a lot more `isinstance()` checks where we expect Mopidy models, so we can fail earlier and ease debugging.

**Comment by adamcik** [comment]
I've done a quick experiment adding:

- `isinstance` checks for models and uris
- bounds checks for numbers
- coercing to bools where applicable

Result has been that I've only broken one test that tries to do a negative seek for some reason.

Based on my quick experience I'm suggesting the following:

1. `isisntance` type checking for all models
2. bounds checking for numbers where reasonable
3. coercing of booleans such as tracklist options which get stored
4. `is_valid_uri` checking for all URIs
5. `is_valid_query` checking / normalization for all queries, criteria etc.
6. `is_valid_state` check for `set_state`

This should cover most of the APIs in core that can be called with arguments.

**Comment by jodal** [comment]
This sounds like a good plan. Make sure to raise `ValueError` and `TypeError` as appropriate, and not simply `AssertionError`.

**Comment by adamcik** [comment]
Haven't I already done most of this?

**Comment by jodal** [comment]
Yes, you have.
