### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by woutervanwijk** [mopidy/mopidy#716]
On the Raspberry Pi, CPU usage of mopidy 0.18 is quite a lot more than 0.15/0.16 when playing music. It goes up to 98%, and this causes the music to stutter (mostly when a new file is being played). Sometimes mopidy gets unstable, maybe this has to do with it too. I also observe higher usage on Ubuntu and got reports from other users about this too.
This btw mostly happens after a while, not immediately after mopidy is started.

**Comment by mwild1** [comment]
I'm using ethernet and have high CPU usage, sometimes causing playback to stutter and then 'pause' for minutes at a time.

$ cat /sys/bus/cpu/devices/cpu0/cpufreq/cpuinfo_cur_freq
800000
root@MusicBox:~# cat /sys/bus/cpu/devices/cpu0/cpufreq/scaling_governor
performance
root@MusicBox:~# cat /sys/bus/cpu/devices/cpu0/cpufreq/scaling_available_governors
conservative ondemand userspace powersave performance 

root@MusicBox:~# cat /etc/issue 
MusicBox 0.5.3

/boot/config.txt: https://matthewwild.co.uk/uploads/musicbox_config.txt

Is there anyway I can easily figure out what (inside mopidy) is causing the CPU usage? It's definitely something specific.

**Comment by adamcik** [comment]
You could try looking into python profiling to figure out what is using CPU.

As for this issue in general, at this point it has trailed off into something rather unspecific and isn't tracking any bug we can expect to fix in mopidy as such. In response to this I'm closing the bug and asking that any further discussion of this general issue be moved to https://discuss.mopidy.com/ and if specific bugs emerge that new issues be opened.

**Comment by kingosticks** [comment]
I think it's fair to pin the original problem on a combination of the
specific musicbox-webclient implementation and performance issues, when
using a Spotify cache which I think is tracked elsewhere.

**Comment by allo-** [comment]
Same problem. USB-Audio (so no cpu audio via the rpi port), mopidy, spotify plugin, ethernet (no wifi) and only mpd-connection. Spotify library brings disconnects, 1-2 failed reconnects until the client is able to connect again. When spotify is playing it works okay, until switching songs or browsing the spotify library or similiar.
