### ISSUE TITLE
Scanner hangs with AVI file

### ISSUE THREAD

**Issue by xezpeleta** [mopidy/mopidy#726]
Hi,

If you run **mopidy local scan** command and you have any AVI file in your media directory, the process will hang with no error message.

Therefore, it would be interesting to include .avi/.AVI files in default exclude section (mopidy.conf).

Thanks!

**Comment by adamcik** [comment]
Think I finally ran into something similar enough to maybe have found a fix for this. In my case GStreamer for some reason decided a valid MP3 might be a h264 file. And for added fun the the h264 parser then went into and endless loop trying to handle the MP3 data... There is of course a GStreamer bug for part the endless loop part already, but against 0.10 which is no longer maintained.

On the bright side I decided to try and just reject `video/*` during decoding, and it makes us skip the bad parses and move on to identifying my test file as an actual MP3 and the scan is progressing.

I'll try and get a PR in with the minor change needed. And with some luck this also resolves this issue.

**Comment by adamcik** [comment]
My previous comment was actually for my attempt at fixing what turned out to be an other instance of #797. But this got me testing the scanner on a larger corpus, and I've just made the scanner handle videos just fine. So there will be a PR fixing this shortly :-)

**Comment by adamcik** [comment]
I think #1124 fixed this. Closing this now, and if I'm wrong feel free to reopen.
