### ISSUE TITLE
mopidy

### ISSUE THREAD

**Issue by fauconnier** [mopidy/mopidy#728]
Hi,

It could be interesting to create a pipeline output to pifm. That would allow to listen to Spotify on all my radio fm. This should not be too difficult (no?).

The link of documentation of pifm : http://www.icrobotics.co.uk/wiki/index.php/Turning_the_Raspberry_Pi_Into_an_FM_Transmitter

Update:

I've just noticed that a tutorial exists :
http://www.dobreprogramy.pl/okokok/Malinowa-stacja-radiowa,51313.html

If you don't read Polish, try GoogleTranslate.

**Comment by frollic** [comment]
Bumping this - there's a fork of pifm that adds RDS functionality to the broadcast, pifmrds.

Would be cool/great if it was possible to broadcast the name of the song played
along with the music. 
Is there a chance of adding an exec trigger every time the song/artist changes (also with 
web radio), to update the RDS info sent out ?

thanks
