### ISSUE TITLE
Support for Amazon Music

### ISSUE THREAD

**Issue by Launch201** [mopidy/mopidy#743]
Feature request for support for Amazon Music

**Comment by DerDom** [comment]
Hey, thanks for your work on mopidy. 

I would love to have Amazon Cloud Player support for my Pi Musicbox. Is there anything I can do to support that extension?  (I am not a developer, so I am probably not able to do it myself) 

How much work would it be to add cloudplaya (https://github.com/chipx86/cloudplaya) or any other existing extension to mopidy? Or is it possible to use the Amazon Cloud Drive API (https://developer.amazon.com/public/apis/experience/cloud-drive)?

**Comment by DerDom** [comment]
Nuvola Player 2.5 also supports Amazon Cloud Player. http://nuvolaplayer.fenryxo.cz/releases/2.5.html
Is it possible to learn from their Service Integration? http://nuvolaplayer.fenryxo.cz/services.html

**Comment by Jaffa** [comment]
I've started work on a Python library that supports Amazon Music/Prime Music: https://github.com/Jaffa/amazon-music.

Looking at [Extension development](https://docs.mopidy.com/en/latest/extensiondev/) and the [Backend API](https://docs.mopidy.com/en/latest/api/backend/#backend-api), it should be relatively straightforward.

**Comment by kingosticks** [comment]
Nice one. Is your project python3 *only*?

**Comment by Jaffa** [comment]
Good question. Some of the imports will definitely be different with Python
2, but apart from that I'm not sure.

If Python 2's required for Mopidy, I'll check it in both.

**Comment by Jaffa** [comment]
As of [687dc85](https://github.com/Jaffa/amazon-music/commit/687dc85bf447369fc60de04e7367dfc059aefaf4), it supports Python 2 - and will continue to do so.

**Comment by abhiambadkar** [comment]
Would love to have this extension. How is it going? Do you need help? I am a developer as well.

**Comment by Jaffa** [comment]
@abhiambadkar - thanks for the offer! Help's appreciated with the underlying `AmazonMusic` library; or you could start on the Mopidy extension using it. There's a TODO for the former in Github, and it could certainly do with someone other than me testing it!

**Comment by s-martin** [comment]
Has anybody been working on an extension for Amazon Music lately?
@Jaffa, I've seen your code, does this still work?

**Comment by cjsmith87** [comment]
Hi @Jaffa , I am looking for something that would allow me to use Amazon Prime Music with Mopidy in a similar way to their spotify extension. Is this code still working?
