### ISSUE TITLE
Is it possible to use a non-default card for alsa hardware mixer ?

### ISSUE THREAD

**Issue by mihaipora** [mopidy/mopidy#745]
I have an USB sound card which I don't want to make default in the system and use it only for music playback.
Audio output works fine with

```
[Audio]
output = alsasink device=hw:2,0
```

The problem is that by default alsamixer tries to use card 0, not card 2.
Is there a way to pass card number to mixer from mopidy conf ?

From command line, if I want to choose the USB mixer I need to type:

`amixer -c 2`

Setting the volume with amixer looks like:

`amixer -c 2 sset PCM <value>`

**Comment by wowcut** [comment]
This should definitely go into the documentation, preferably into a quick start guide. This is very basic information and I had to search much too long for it.
