### ISSUE TITLE
Frequent segfaults at song switch

### ISSUE THREAD

**Issue by FruitieX** [mopidy/mopidy#782]
I'm running mopidy 0.18.3 on Arch Linux x86_64, and get pretty frequent segfaulting during a song switch. I'm using ncmpcpp 0.5.10 to control mopidy, and playing local music files (mp3, flac, both seem to crash). System is up to date with latest packages available as of now (e.g. gstreamer0.10 0.10.36-4, python2 2.7.8-1).

Audio is played through a local pulseaudio server, though it is running as another user but it accepts TCP connections on localhost, so I run mopidy with:

PULSE_SERVER=localhost mopidy -vvv

However I've tested without this and mopidy also crashes then, and I've also tested to disconnect the mpd client right after I've started playback, but still mopidy will crash occasionally at song switch.

Here's the output I get right before the crash:

```
DEBUG    2014-07-15 14:36:42,073 [27564:MainThread] mopidy.listener
  Sending state_changed to AudioListener: {'old_state': u'playing', 'new_state': u'playing'}
DEBUG    2014-07-15 14:42:27,193 [27564:MainThread] mopidy.audio.actor
  Triggering reached_end_of_stream event
DEBUG    2014-07-15 14:42:27,193 [27564:MainThread] mopidy.listener
  Sending reached_end_of_stream to AudioListener: {}
[1]    27564 segmentation fault  mopidy -vvv
```

Any help to debug this further is appreciated (I'd happily pour some hours into it myself, but don't know where to start!), sorry if I didn't provide enough information!

**Comment by aereaux** [comment]
Hello, I am experiencing what appears to be the same issue as this one.  Mopidy segfaults when switching tracks sometimes.  I tried installing glib2-unstable as mentioned in this thread, but the issue persists.  When I use gdb, it says:

    Program received signal SIGSEGV, Segmentation fault.
    0x00007f5e56cae4d5 in g_mutex_lock () from /usr/lib/libglib-2.0.so.0

**Comment by jodal** [comment]
@aereaux This looks like something similar but different. Can you open a new issue?
