### ISSUE TITLE
Add per logger colors?

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#808]
Idea is to be able to switch color for say `mopidy.audio` to make debugging simpler  when working on a component. I've been doing this indirectly by sprinkling some code with warning log statements to get the same effect.

Instead we could either add a ``logcolor/mopidy.audio=ORANGE`` type setting, or the one I prefer ``loglevels/mopidy.audio=DEBUG/BLUE`` or something like that.

**Comment by jodal** [comment]
Fixed by #1005
