### ISSUE TITLE
Tracks without albums cannot have images

### ISSUE THREAD

**Issue by tkem** [mopidy/mopidy#838]
Some tracks do not belong to an album ("singletons", as beets calls them), but may well have images attached to them. Technically -- from a MusicBrainz point of view -- they still belong to a release (a.k.a. an album in Mopidy's terms), but not everybody relies on MusicBraint to tag their collection. Therefore, it may be desirable to also provide an `images` property to `mopidy.models.Track`.

Note that extensions might also like to provide *artist* images from external sources, e.g. to show up in search results, but that's a different story...

**Comment by jodal** [comment]
Fixed by PR #981.
