### ISSUE TITLE
Add symlink support in scanning

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#858]
This is currently disabled on purpose, but we should consider adding support for enabling following links.

**Comment by morgoth** [comment]
I cannot make symlinks to work - is it supported now?

**Comment by jodal** [comment]
The issue is closed, but the milestone is v0.20, which isn't released yet. The change is in the "develop" branch.

**Comment by morgoth** [comment]
Thanks for quick response.
To continue annoying questionnaire ;-) - when do you plan to release 0.20?

**Comment by jodal** [comment]
"Real soon now" :-)

**Comment by ikogan** [comment]
I'm currently running 2.0.0 and I can't seem to get the following setup to work:

```
pi@echo:/var/lib/mopidy/media $ ls -lah
total 8.0K
drwxr-xr-x  3 mopidy audio 4.0K Feb 15 18:49 .
drwxr-xr-x 10 mopidy audio 4.0K Feb  4 21:07 ..
drwxr-xr-x  3 root   root     0 Feb 16 20:20 Network
lrwxrwxrwx  1 root   root    17 Feb 15 18:49 USB -> /var/run/usbmount
pi@echo:/var/lib/mopidy/media $
```

```
pi@echo:/var/lib/mopidy/media $ ls -lah USB/
total 0
drwxr-xr-x  2 root root  60 Feb 16 20:20 .
drwxr-xr-x 20 root root 800 Feb 16 20:20 ..
lrwxrwxrwx  1 root root  11 Feb 16 20:20 SanDisk_Ultra_Fit_1 -> /media/usb0
pi@echo:/var/lib/mopidy/media $
```

I don't see the `USB` directory at all when I browse local files.

**Comment by kingosticks** [comment]
Please, in future post usage question at http://discuss.mopidy.com rather than resurrect 12 month old closed issues here.  

When you do so, please include the full output of `mopidy deps` and `mopidy config`. Please take particular note to include the value for the relevant config setting: https://docs.mopidy.com/en/latest/ext/local/#confval-local/scan_follow_symlinks

**Comment by ikogan** [comment]
Apologies, I'll give that a shot.
