### ISSUE TITLE
Set default webclient

### ISSUE THREAD

**Issue by woutervanwijk** [mopidy/mopidy#860]
It would be nice if the user could choose a default webclient in the mopidy http-extensions webpage, so that this webclient would be shown instead of the mopidy page if you browse to the webserver after choosing the default.

**Comment by jcass77** [comment]
Using ```static_dir``` is not really practical at the moment due to the clashes that can occur as described in the referenced issue above - not sure if there is a quick and easy fix for that?

**Comment by tkem** [comment]
I think the general use case (as I understand it) would better be served by running a (small) separate Web server on port 80 that simply redirects to the respective Mopidy client on port 6680. Thus, "normal" users won't even have to deal with port numbers, and admins/"power users" would still be able to access all installed clients via port 6680.

**Comment by dz0ny** [comment]
Or just use avahi and set SRV RR for example each webclient would advertise itself with hostname.webclient_name server can the use HOST header to do its magic :)

**Comment by adamcik** [comment]
Closing this as enough of us seem to be slightly in favor of just having a minimal proxy in front of Mopidy to handle this type of thing.

**Comment by halloamt** [comment]
This works for me with nginx

`
        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                #       try_files $uri $uri/ /index.html;
                # Uncomment to enable naxsi on this location
                # include /etc/nginx/naxsi.rules

                #rewrite "^i.$" /moped/ break;

                proxy_pass http://localhost:8080/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

                rewrite /mopidy/(.*) /mopidy/$1 break;
                rewrite /(.*) /moped/$1 break;
                proxy_redirect off;
        }
`
