### ISSUE TITLE
Start "deprecating" internal core APIs

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#870]
Certain parts of core are basically internal only APIs that we have leaked out. Changing these on a whim without 1.0 isn't reasonable, but as part of preparing for that change all the function we consider internal should be clearly marked as such in the docs.

Another way to look at this is that I want us to clearly define what parts of core we still consider fair game for frontends to call. Some cases which we have already discussed in the 1.0 core design doc are no brainers, while other methods like say `history.add` are more grey areas as IMO no frontend should be calling them, all changes to that state should be from events from backend and audio systems.

**Comment by jodal** [comment]
In #969 I've now documented all the getters/setters, making it possible to make one half "internal". I found one such candidate, `playback.set_current_tl_track()`, which is used heavily in tests.

**Comment by adamcik** [comment]
Should we also have removed `core.playback.set_state`? Though now this will have to wait for a 2.x

**Comment by jodal** [comment]
My first guess is that it should be deprecated, yes. Are there other open issues left in the core API?

**Comment by adamcik** [comment]
Not that I noticed when going through, that is unless you count a bunch of the tracklist operations that are there for doing "atomic" changes instead of fetch-modify-replace.

**Comment by adamcik** [comment]
Oh and all the places we take `query=None, **kwargs`` should probably deprecate `kwargs` use.

**Comment by adamcik** [comment]
Most of the big parts of this have been done, don't think we need a tracking bug for the ongoing work in this area.
