### ISSUE TITLE
Spotify Playlists listed as [loading] when added by external client

### ISSUE THREAD

**Issue by fatg3erman** [mopidy/mopidy#885]
Not certain if this is in mopidy core or mopidy-spotify so I'll try here first.

With mopidy running, if I use the official Spotify client to create a new playlist, mopidy detects that I have done so but when I query mopidy for the list of playlists (either through the HTTP or MPD interfaces) the new playlist is listed with a name of

[loading]  spotify:user:(etc etc)

Also, doing a search with no parameters on the spotify: domain (which usually returns all tracks in all playlists - very useful that) does not return the tracks from the new playlist.

Restarting mopidy resolves both problems.

**Comment by jodal** [comment]
There's no current workaround, but this is fixed in the upcoming Mopidy-Spotify 2, which is soon to be released.
