### ISSUE TITLE
"http://www.benjaminguillet.com/blog/2013/08/16/launch-mopidy-at-login-on-os-x/" no longer exists

### ISSUE THREAD

**Issue by gjtorikian** [mopidy/mopidy#887]
This link no longer exists. A lot of resources point to it as a place for learning how to automatically start Mopidy on OS X. 

Not even the Wayback Machine or Google's cache contains it anymore. :cry:

**Comment by jodal** [comment]
Included in the docs at https://docs.mopidy.com/en/develop/installation/osx/#running-mopidy-automatically-on-login
