### ISSUE TITLE
Your GStreamer installation is missing a plug-in. (OS X 10.10)

### ISSUE THREAD

**Issue by ghost** [mopidy/mopidy#888]
A bit new to this. I have installed mopidy 0.19.4 with homebrew. mopidy local scan fails with the following warning:

WARNING  Failed local:track:Evelyn%20Kaufman%20jokes.m4a: Your GStreamer installation is missing a plug-in.

https://gist.github.com/brillbrill/22e5b59af68d529dee4e

any advice very welcome

**Comment by claman** [comment]
I ran the uninstall and reinstall like you suggested:

    brew uninstall gst-plugins-bad010 mopidy
    brew install mopidy/mopidy/mopidy

During the install, this message came up:

    Error: The `brew link` step did not complete successfully
    The formula built, but is not symlinked into /usr/local
    Could not symlink share/glib-2.0/schemas/gschemas.compiled
    Target /usr/local/share/glib-2.0/schemas/gschemas.compiled
    is a symlink belonging to gsettings-desktop-schemas. You can unlink it:
      brew unlink gsettings-desktop-schemas
    
    To force the link and overwrite all conflicting files:
      brew link --overwrite gst-plugins-bad010
    
    To list all files that would be deleted:
      brew link --overwrite --dry-run gst-plugins-bad010
    
    Possible conflicting files are:
    /usr/local/share/glib-2.0/schemas/gschemas.compiled -> /usr/local/Cellar/gsettings-desktop-schemas/3.14.0/share/glib-2.0/schemas/gschemas.compiled

Should I unlink/overwrite the file?

**Comment by jodal** [comment]
I've tried both:

```
brew link --overwrite gst-plugins-bad010
```

and:

```
brew link --overwrite gsettings-desktop-schemas
```

...on two different systems. No issues so far. So yes, I believe overwriting this file is quite safe.

**Comment by claman** [comment]
Ok, thanks! That seems to have solved this issue. Of course, now I'm running into another one. Ah well.
