### ISSUE TITLE
GStreamer grabs alsa device exclusively

### ISSUE THREAD

**Issue by cartel0x27** [mopidy/mopidy#889]
I'm trying to use mopidy with alsa and dmix, in order to have mopidy and shairport share a single sound card.

My asound.conf is pretty standard:

```
pcm.!default {
    type plug
    slave.pcm "dmixer"
}
pcm.dsp0 {
    type plug
    slave.pcm "dmixer"
}
pcm.dmixer {
    type dmix
    ipc_key 1020
    slave {
        pcm "hw:1,0"
     }
     bindings {
        0 0
        1 1
     }
}
ctl.mixer0 {
    type hw
    slave.pcm "dmixer"
}
```

and i have alsa selected in mopidy.conf

```
[audio]
#mixer=software
output=alsasink
```

as well as with shairport

```
/usr/local/bin/shairport.pl -a livingroom --ao_driver alsa -d
```

I know gstreamer can access the device correctly because

```
gst-launch-0.10 audiotestsrc ! audioresample ! alsasink
```

while playing music in shairport, works.

but as soon as i play music with mopidy i get:

```
$ gst-launch-0.10 audiotestsrc ! audioresample ! alsasink
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstAlsaSink:alsasink0: Could not open audio device for playback.
Additional debug info:
gstalsasink.c(694): gst_alsasink_open (): /GstPipeline:pipeline0/GstAlsaSink:alsasink0:
Playback open error on device 'default': Permission denied
Setting pipeline to NULL ...
Freeing pipeline ...
```

mopidy appears to be exclusively accessing the PCM device.
when i run the gstreamer test above, and start mopidy, i get the extremely useful error message:

```
2014-11-09 10:48:57,936 ERROR [18691:MainThread] mopidy.audio.actor: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure. Debug message: gstplaysink.c(1899): gen_audio_chain (): /GstPlayBin2:playbin20/GstPlaySink:playsink0
```

no sound plays over the top of the test tone, when it should.

**Comment by startmat** [comment]
check this for an complete asound.cfg with dmix with access for all users:

https://www.redhat.com/archives/rhl-list/2007-November/msg05220.html

This one is working for me in my rapi with an usb.audio stick:
vi /etc/asound.conf

pcm.!default {
        type plug
        slave.pcm "dmixer"
        ttable.0.1 1
        ttable.1.0 1
}

pcm.dmixer  {
        type dmix
        ipc_key 1024
        ipc_key_add_uid false
        ipc_perm 0666                       # mixing for all users
        slave {
                pcm "hw:1,0"
                period_time 0
                period_size 1024
                buffer_size 4096
                rate 44100
        }
        bindings {
                0 0
                1 1
        }
}

ctl.dmixer {
        type hw
        card 0
}
