### ISSUE TITLE
Playback progress goes too fast

### ISSUE THREAD

**Issue by oncletom** [mopidy/mopidy#898]
Hello!

Thanks for this great project. It helped us much during a hackathon to build a local radio :-)

At the moment we play WAV files but when I connect with ncmpcpp from my laptop to the pi, although the sound is totally fine, the elapsed time goes too fast, usually between 2 and 3 seconds every second.

![mopidy-playback](https://cloud.githubusercontent.com/assets/138627/5290085/bfe6a6b6-7b3b-11e4-92ad-adebbb238485.gif)

I encounter this issue on two Raspberry Pi, an A+ and B+.

Any idea?

```
[audio]
#mixer = software
mixer_volume = 100
output = alsasink

[alsamixer]
#enabled = true
#card = 0
#control = Master

[softwaremixer]
#enabled = true
```

**Comment by adamcik** [comment]
I've never been able to reproduce this. So going ahead and closing this. If it is still a problem in `develop` please let us know and we'll try and take an other look.
