### ISSUE TITLE
MPD status: None is not 0

### ISSUE THREAD

**Issue by avuton** [mopidy/mopidy#899]
Hello,

We've been getting a few crash reports in [MPDroid](http://github.com/abarisain/dmix) where the MPD status response for some things (notably, bitrate) returns a string literal 'None' rather than 0. This is *definitely* not protocol, and I can see it's not a default response for mopidy. Is there any chance this is a bug (old or new) making it through the server response? The reason I ask is I see 'None' next to bitrate in the models.py, I'm thinking it has snuck through to the protocol one time or another.

Thanks!

**Comment by adamcik** [comment]
Is there anything we can/should do for this in mopidy, or should we just close this?
