### ISSUE TITLE
MPdroid ver 1.07 add streams error

### ISSUE THREAD

**Issue by kibuy** [mopidy/mopidy#900]
Hi

I try to add stream in MPDroid 1.07 but it's not saved, in started mopidy in debug mode and i see this errror, bug/not implemented function or do i need to install extension for this ?

mopidy version is the latest, v0.19.4 

```
DEBUG    2014-12-07 16:48:54,153 [13731:MpdSession-14] mopidy.mpd.session
  Request from [::ffff:192.168.0.75]:38884: playlistadd "[Radio Streams]" "http://http-live.sr.se/p1-mp3-192#Sveriges radio P1"
DEBUG    2014-12-07 16:48:54,156 [13731:MpdSession-14] mopidy.mpd.session
  Response to [::ffff:192.168.0.75]:38884: ACK [0@0] {playlistadd} Not implemented
```

**Comment by adamcik** [comment]
Don't think there is anything more we can do specifically for this issue on the Mopidy side. So closing this in favor of other issues for adding the missing playlist support.
