### ISSUE TITLE
Documentation outlining "installation from source" is just using pip

### ISSUE THREAD

**Issue by timmyomahony** [mopidy/mopidy#903]
The documentation here: 

https://docs.mopidy.com/en/latest/installation/source/

for installing mopidy from source isn't actually outlining how to install it from source. 

> 4. Install the latest release of Mopidy: `sudo pip install -U mopidy`

Instead, you need to clone the repo and install via python:
    
    apt-get install git
    git clone https://github.com/mopidy/mopidy.git
    cd mopidy
    python setup.py install

**Comment by Lixxia** [comment]
When I was reading the It was not clear to me either. Typically install from source directions are for those looking to work with the source code (in my experience). 

At the very least I think it would be nice to have a redirect to the Contributing section. Alternatively the Install from Source page could have a section for pip and a section for git. I’d be happy to make these changes, but I’d like some input first.

**Comment by adamcik** [comment]
Happy to merge such a change improving the documentation :-)

**Comment by jodal** [comment]
Clarified by PR #959
