### ISSUE TITLE
Add option to rescan all files

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#910]
There should be a setting to recheck all files instead of only having the clear option.

**Comment by RonaldZ** [comment]
Would you mind clarifying what you're looking for a bit? Are you looking for something that would clear and then re-scan your files, or something else?

**Comment by adamcik** [comment]
Essentially I was thinking something along the lines of having a `--force` option in the scan which would make it ignore the the mtime check and always refresh the files.

**Comment by RonaldZ** [comment]
Gotcha, a scan that will refresh files regardless of whether they have been modified. I'll start digging into it.

**Comment by adamcik** [comment]
87ea3c9 fixed this, thanks Ronald :-)
