### ISSUE TITLE
list <artist / album etc.> iterates over all local tracks

### ISSUE THREAD

**Issue by joemarshall** [mopidy/mopidy#913]
If you call mopidy with a 'list albums' or 'list artists' command, how it is handled is:
1) List all tracks in the database that fit the query.
2) Add the the artist for each track into a set
3) return the set

How it should work:
1) List all the artists/albums in the database (that fit whatever extra query is applied), possibly via browse URIs or something.

This causes a bug in the sqlite backend, because that backend sanity checks the general 'search' command and limits it to 100 results, and also means that listing artists / albums etc. is *very* slow if you have even a vaguely large local database. I imagine it also massively slows down the various search things in spotify/google music etc, because presumably if you search for artist it has to return all the tracks by that artist first?

This is not obvious in musicbox, because it doesn't use the list command at all, but breaks most clients (MPDroid, NCMPCPP both support browsing by artist or album). 

Description of the sqlite backend bug caused by this here:
https://discuss.mopidy.com/t/browse-artists-albums-only-shows-a-small-number-of-artists/435/3
https://github.com/tkem/mopidy-local-sqlite/issues/45

Example of the underlying code that needs fixing:

in mopidy/mpd/music_db.py:

        def _list_artist(context, query):
            artists = set()
            results = context.core.library.find_exact(**query).get()
            for track in _get_tracks(results):
                for artist in track.artists:
                    if artist.name:
                        artists.add(('Artist', artist.name))
            return artists

**Comment by adamcik** [comment]
We just merged #1022 which adds a new API for getting these distinct values. Internally the JSON backend still does the same stupid thing, but at least now mopidy-local-sqlite can do a sane distinct query.

In other words I'm considering this solved, as I've opened #1019 to try and hunt down other places relying to "blank" searches to get all the tracks and do stuff with them.
