### ISSUE TITLE
Local json library ignores "limit" and "offset" search parameters

### ISSUE THREAD

**Issue by tkem** [mopidy/mopidy#917]
AFAICS, the local `json` library doesn't handle `limit` and `offset` when searching: https://github.com/mopidy/mopidy/blob/develop/mopidy/local/json.py#L160
This seems to be the reason that the `json` and `sqlite` libraries behave differently with regard to MPD's `list artist`, `list album`, etc. commands, which caused bug reports for Mopidy-Local-SQLite, which handles this correctly, I think: tkem/mopidy-local-sqlite#45.
I suggest fixing this in the `json` library, so users may no longer believe this to be an SQLite-related issue.

**Comment by ali** [comment]
cc @adamcik 

Three options I'm considering:
1. Remove the limit and offset parameters. Is there a reason to limit or offset the results? Why is pagination a concern? (re: https://github.com/mopidy/mopidy/pull/949#issuecomment-74946621)
2. Make the limit and offset parameters optional (default to None, can be an int).
3. Find a way to use pagination from [local.library's search functions][local.library].

I'm uncertain about both option 3 and paginating local libraries, especially if these parameters are unused.

[local.library]: https://github.com/mopidy/mopidy/blob/develop/mopidy/local/library.py#L44

**Comment by adamcik** [comment]
Fixed by #947 now that #1022 has been merged. There is still no way to do pagination though, which should be a new issue IMO.
