### ISSUE TITLE
Local libraries don't list albums in search

### ISSUE THREAD

**Issue by joemarshall** [mopidy/mopidy#920]
The way the local libraries are written, they only return tracks, so a search for an album in e.g. musicbox webclient returns just tracks.

**Comment by tkem** [comment]
Probably depends on mopidy#840

**Comment by joemarshall** [comment]
It relates to something mentioned in that, in that the current local backend doesn't support lookup of albums or artists, which means that searchresults with them in aren't so useful.

The existingsqlite backend does support lookup of albums and artists in the browse structure, but the search function in that has no way of returning albums and artists. 

If the local backend a)returns albums and artists for search results, and b)returns lookup-able URIs to them, then it works great in clients such as musicbox web client - I implemented this, amongst other things in the pull request below, and it works great (although I can see the PR might need some messing before it is good enough to merge)
https://github.com/mopidy/mopidy/pull/921

One gotcha is that the popular musicbox webclient has what I think is a bug with quoting of URIs when you click on an album name.
https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/issues/62

**Comment by adamcik** [comment]
Given the plans to do #1003 I doubt we will bother fixing this in the JSON backend. Though if someone adds this to the json search results in a reasonable way, we would consider merging it despite the plan to move local out of the main project.
