### ISSUE TITLE
Cannot validate soundcloud or spotify

### ISSUE THREAD

**Issue by Snorlock** [mopidy/mopidy#932]
I have set this is my config, real values instead of the token and username and password.

[soundcloud]
#enabled = true
#explore_songs = 25
#auth_token = token

[spotify]
#enabled = true
#username = username 
#password = password
#bitrate = 160

But i still get this when i start mopidy

INFO     2015-01-06 09:38:08,022 [18512:MainThread] mopidy.__main__
  Enabled extensions: local, mpd, softwaremixer, http, stream
INFO     2015-01-06 09:38:08,022 [18512:MainThread] mopidy.__main__
  Disabled extensions: spotify, soundcloud
WARNING  2015-01-06 09:38:08,022 [18512:MainThread] mopidy.__main__
  Found soundcloud configuration errors, the extension has been automatically disabled:
WARNING  2015-01-06 09:38:08,023 [18512:MainThread] mopidy.__main__
    soundcloud/auth_token must be set.
WARNING  2015-01-06 09:38:08,023 [18512:MainThread] mopidy.__main__
  Found spotify configuration errors, the extension has been automatically disabled:
WARNING  2015-01-06 09:38:08,023 [18512:MainThread] mopidy.__main__
    spotify/username must be set.
WARNING  2015-01-06 09:38:08,023 [18512:MainThread] mopidy.__main__
    spotify/password must be set.
WARNING  2015-01-06 09:38:08,023 [18512:MainThread] mopidy.__main__
  Please fix the extension configuration errors or disable the extensions to silence these messages.

Do i put something wrong in the config or why is this happening?

**Comment by kingosticks** [comment]
Lines starting with the hash character are comments are are ignored.

**Comment by Snorlock** [comment]
Lol, i thought so but since all was i wanted to ask first

**Comment by kingosticks** [comment]
No problem. There should be example configs in the documentation and the
github readmes for each extension. If you do have any other question please
post them on discuss rather than here as this is primarily for bugs etc.
