### ISSUE TITLE
Use a "global" playlist mapping in MPD dispatch code

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#934]
https://discuss.mopidy.com/t/mpc-clients-are-slow-to-connect-to-git-version-of-mopidy/518 has some of the backstory. But the short version is that redoing this mapping for users with many spotify playlists is costly (and can lead to inconsistencies).

So we should be caching this or just moving it up to the server level instead of doing this once per session / connection.

**Comment by jodal** [comment]
Fixed by PR #968
