### ISSUE TITLE
Feature Request: audio/mixer = none

### ISSUE THREAD

**Issue by reneanda** [mopidy/mopidy#936]
Would it be possible to add a "none" option to the audio/mixer configuration?
I miss the behavior from MPD, where you can set mixer_type to "none" and get fixed volume at 100%.
http://www.musicpd.org/doc/user/config_audio_outputs.html

Thank you.

**Comment by adamcik** [comment]
I *think* just leaving mixer blank will get you this result, but it probably wouldn't hurt to have an explicit setting `none` which does the same.

**Comment by reneanda** [comment]
Leaving it blank gives the following:
`WARNING  Found fatal audio configuration errors:`
`WARNING    audio/mixer must be set.`
`ERROR    Please fix fatal configuration errors, exiting...`

If I comment audio/mixer out Mopidy defaults to SoftwareMixer. Disabling the SoftwareMixer extension does not work.

**Comment by jodal** [comment]
@ZenithDK I removed some code in #983, that should make it easier to add support for the mixer actor being `None`.

**Comment by herrernst** [comment]
I also would like to have that. Thank you!

**Comment by ZenithDK** [comment]
I've implemented this now, but I feel like this needs some testcases, but not sure how to go about that.
Any hints?
