### ISSUE TITLE
Deleting local playlist does not delete corresponding M3U file

### ISSUE THREAD

**Issue by tkem** [mopidy/mopidy#937]
Calling `LocalPlaylistsProvider.delete(uri)` in Mopidy 0.19.5 effectively removes the playlist only from `self._playlists`, but does not delete the underlying M3U file. Therefore, the playlist will re-appear after a restart or a `PlaylistsController.refresh()`.

Looking into `local/playlists.py`, there seems to be an issue with the mapping of file names to URIs. For example, the file `radio.m3u` in my playlists directory will be assigned the URI `local:playlist:radio`, i.e. without extension, but AFAICS the extension will not be re-added by `LocalPlaylistsProvider._m3u_uri_to_path()`, so `LocalPlaylistsProvider._delete_m3u()` will silently(!) fail.

I guess this does not only affect deletion of playlists, but probably other playlist API functions that need to access the underlying M3U files, too.

Regarding local playlist URIs, I also noted that the file "Radio Österreich.m3u" is given the URI 'local:playlist:Radio \xd6sterreich', which is not properly percent-encoded. So, may I suggest refactoring the whole URI-related stuff in `local/playlists.py`, maybe reusing or adapting some of the URI encoding/decoding functions already used for local tracks ;-)

**Comment by tkem** [comment]
Update: As somewhat expected, when trying to save an existing playlist with another `playlist.name`, I get
```
[Errno 2] No such file or directory: u'/home/tkemmer/.local/share/mopidy/local/playlists/radio'
```
for M3U file "radio.m3u".

**Comment by tkem** [comment]
Since nobody else seems to be working on this, I started looking into this myself:
https://github.com/tkem/mopidy/tree/fix/937
So you can label this as as "2 - working", I guess ;-)

**Comment by jodal** [comment]
I invited you to join the team, so you can assign yourself and update the labels :-)

**Comment by tkem** [comment]
Hey, thanks... I feel flattered ;-)
