### ISSUE TITLE
Pleer.com extension

### ISSUE THREAD

**Issue by programLyrique** [mopidy/mopidy#941]
[pleer.com](pleer.com) is a mp3 streaming service.

It has an API http://pleer.com/ru/api

I guess it should be developed as an extension rather than provided directly with *mopidy*...

**Comment by adamcik** [comment]
https://discuss.mopidy.com/t/supporting-new-streaming-services-and-other-music-sources/22 has some notes for adding support for new services. Per our usual policy I'm closing this bug as we won't be adding it in mopidy itself, but it can still be found under the Extension wishlist label with other suggested services.
