### ISSUE TITLE
Add support for stream titles in MPD protocol

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#944]
Turns out MPD metadata tags already support having a radio station title and a current track:

```
Title: Leggo Beast - Skanked
Name: Groove Salad: a nicely chilled plate of ambient beats and grooves. [SomaFM]
```

we need to add some way of supporting this in mopidy. This might require model changes on our side to better handle streams and possibly other things that cant be nicely shoehorned into our track models.

**Comment by adamcik** [comment]
One option could be to change the just added ``current_metadata_track`` to ``stream_metadata`` and only populate it with metadata from audio. Then when providing status in the MPD frontend we can consider the track metadata as the `name` and add the `title` from the stream if it is different from the name.

**Comment by adamcik** [comment]
Also we should probably do this _before_ a 0.20 release.

**Comment by adamcik** [comment]
And relevant for #270

**Comment by AlexandrePTJ** [comment]
Naming `current_metadata_track` to `stream_metadata` will be more precise indeed.
However I did not find the MPD's protocol key which can store `Name`. There is `Track` but I am not sure.

**Comment by adamcik** [comment]
I've never seen any mention of this in the protocol docs (I might have missed it of course), but if you fire up an MPD an play an icecast stream you will see the behavior.
