### ISSUE TITLE
Support for GoogleCast

### ISSUE THREAD

**Issue by DerDom** [mopidy/mopidy#948]
Would it be possible to stream from my Android device to mopidy via GoogleCast? So that my raspberry pi acts like a Chromecast stick?

https://developers.google.com/cast/

**Comment by kingosticks** [comment]
This sort of question would be better suited to https://discuss.mopidy.com/

**Comment by DerDom** [comment]
Thanks, just posted it there: https://discuss.mopidy.com/t/support-for-googlecast-chromecast/556

**Comment by DerDom** [comment]
It this something for the "extension wishlist"?
