### ISSUE TITLE
Connect to websocket via HTTPS if appropriate

### ISSUE THREAD

**Issue by andrenarchy** [mopidy/mopidy#950]
**Problem:** if the page is loaded via HTTPS (e.g. with a reverse proxy in front of mopidy), the default websocket url is `ws://...` and the browser refuses to connect to an unsafe endpoint.

**Expected behavior:** the script should detect whether it is loaded via HTTP or HTTPS and switch to `wss://...` if appropriate.

I'll prepare a PR in a minute.

**Comment by dz0ny** [comment]
You can simply use :// instead of ws:// this more applies to
http-frontend authors. But would be nice for core debug page too.

**Comment by andrenarchy** [comment]
The correct syntax for the protocol-relative URL would be `//...` (without colon), see http://tools.ietf.org/html/rfc3986#section-4.2.

This works nicely for HTTP/HTTPS in all browsers (see [here](http://stackoverflow.com/questions/4831741/can-i-change-all-my-http-links-to-just)) but it doesn't work with websockets since `https://` is a different protocol than `wss://` (at least it looks like that for the browser). ;) See also [here](http://lucumr.pocoo.org/2012/9/24/websockets-101/) in the section *Websocket URLs*.

So we'll have to switch by hand.
