### ISSUE TITLE
Return playlist results from search

### ISSUE THREAD

**Issue by IvanMalison** [mopidy/mopidy#955]
Is there a reason that this is not currently possible? Is it because the mpd protocol does not support this feature?

**Comment by IvanMalison** [comment]
Ahh. I just found https://github.com/mopidy/mopidy/issues/669 . It seems that playlist search is supported by mpd. Is there a reason that it has not, as of yet, been implemented?

**Comment by trygveaa** [comment]
playlistsearch is for searching for songs in the current playlist, i.e. the queue that is playing.

I don't think the MPD protocol supports searching for anything other than songs. It might be able to add support for returning playlists as fake songs as it is done with artists and albums.

However I don't know if the backends allow you to search through playlist (e.g. I don't think Spotify it's able to).

**Comment by IvanMalison** [comment]
@trygveaa I'm actually writing a backend that I want to return playlists as search results from. The backend provides nothing but playlists that are generated from various queries to the last.fm API. The playlists are actually generated as they are requested, and it would be impractical to generate them ahead of time simply because there would be far to many of them. I want to do things like provide a playlist of top tracks for an artist, or top tracks for an arbitrary user.

I was able to make a playlist that streams from other backends by providing uris, but when I tried to make fake albums that appear as search results, I was unable to stream any of the tracks in the tracklist. I haven't gone digging into the mopidy core code yet, but I imagine that there is some issue with supplying uris that dont come from the same backend in albums? Do you have any idea what the issue might be off the top of your head?

**Comment by adamcik** [comment]
Have you looked at https://github.com/mopidy/mopidy/issues/620 and the google doc linked in the issue? It covers a lot of our previous thoughts on how we want to support this use case.

As for returning URIs for other backends that is no problem at all. Mopidy will just pass the URI around without knowing or caring about what it really is most of the time. So as long as some installed backend can handle it you are good.

**Comment by jodal** [comment]
I think the combination of #523 for returning playlists in the `SearchResult` model and #620 for dynamic playlists should cover this issue. Closing.
