### ISSUE TITLE
Add sleep timer

### ISSUE THREAD

**Issue by teq0** [mopidy/mopidy#956]
I've added a sleep timer function to core, I'd like some feedback before I submit it - https://github.com/teq0/mopidy/commit/d28715fb8492fc14d6f82172945392f24c41a0db

I initially added it as an extension, but it's such a basic function that it felt like some UIs might like to have it built in as a first class feature, adding to core means it's instantly available via the JSON-RPC API.

I've added sleeptimer.py to mopidy/core, which provides the following public methods:

start(self, duration) - duration is a float for the number of seconds before sleeping
cancel(self) - kills the sleep timer if it is running
get_state(self) - returns the current state of the sleep timer i.e. running (True or False), duration, seconds left

It generates the following events:

sleeptimer_started - params = seconds_left, duration
sleeptimer_cancelled - no params
sleeptimer_tick - sent every 0.5 seconds (ish) to allow UI to show countdown, params = seconds_left
sleeptimer_expired - when playback is stopped, no params

I've also forked Mopidy-Musicbox-Webclient and added a simple UI - https://github.com/teq0/Mopidy-MusicBox-Webclient/commit/d5b6649fee91932cf9b018ac3f253cc1ec266d3b

**Comment by adamcik** [comment]
What use cases in the UI do you want to use this for? Would be nice to get some examples to get a better idea if this warrants being added to core or not.

Other thing is that I would likely just use the event loop (http://www.pygtk.org/pygtk2reference/gobject-functions.html#function-gobject--timeout-add) for the server side part of this. And any other event loop we switch to will have support for a similar timer.

**Comment by teq0** [comment]
Well main use case is being able to listen to music, such as Spotify playlists or radio, and have it turn off automatically, such as when you are listening to music to go to sleep to. Pretty much all music and podcast software has this, or, in the case of mobile software, can respond to the OS built in sleep timer (as in iOS and Spotify). 

In many cases where the timer is built-in there is a UI that displays the status (active or not) and a countdown of the amount of time left before it stops playback, so it's pretty tightly integrated into the UI for the playback controls.

Here's the simple UI change I did for the Musicbox webclient:

![image](https://cloud.githubusercontent.com/assets/6080717/6102485/76e1e6d0-b08b-11e4-9b93-bbcbf43307ad.png)

I'll change it to use gobject.timeout.add rather than starting a separate thread, that's a better solution.

**Comment by michaellunzer** [comment]
This looks awesome!

**Comment by teq0** [comment]
OK, so somebody is interested. I'll go ahead and write some tests and submit a PR.

**Comment by teq0** [comment]
I'm having a bit trouble writing decent tests for this, can someone point me in the right direction? Fairly ordinary tests work fine, but the timer handler function (the one added using gobject.timeout_add()) doesn't seem to get called so I can't test most of the functionality.

I'm testing the main functionality by stating the sleeptimer, then sleeping using thread.sleep(), then checking that the right events have fired and that playback has stopped etc. The initial event is fired, before it adds the timeout, but the code triggered by the timeout doesn't run (it works fine when not in test mode).

It seems like maybe I can't use thread.sleep() to wait because that makes the whole thread sleep? How do people normally test stuff that is run using gobject.timeout_add()?

**Comment by ZenithDK** [comment]
I'm guessing Mock? You can use this to fake the calls to the function and not have to do sleep - which is probably what is causing the problem.
I am new to Mock as well, so can't give you that many pointers besides try looking at the existing testcases that use Mock and look up tutorials and howtos online.

**Comment by jodal** [comment]
The reason the callbacks isn't triggered is probably because the GLib event loop isn't running in the tests. That said, I agree with @ZenithDK that the proper solution is to use `mock` to test so that you don't need to use `thread.sleep()` in the tests. We want test suites to be fast, and sleeping is the easiest way to make them really slow.

**Comment by teq0** [comment]
I copied the code from __main__.py to initialise the event loop (dbus) but that didn't seem to help. 

I think what @ZenithDK is saying is that I should mock out gobject.timeout_add() and just call the timer function directly in a tight loop. I'll try that, but that approach isn't really testing much of the functionality, which is time-dependent (there's time calculations etc). It's also not going to uncover any quirks of how my code might interact with the gobject event loop etc.

But maybe that's OK for unit tests.

**Comment by fheil** [comment]
Hello,

I'm highly interested in this feature. I've >10 years of linux experience and I doublechecked the modifications I did according to this patch. It doesn't work for me. I see the UI elements (after disabling the hidden settings in the index.html).

I have a PI B model with Mopidy 0.19.5 running. My index.html is located in /opt/webclient.  sleeptimer.js is below this directory in the ./js directory. 

The core modifications I did were done in /usr/local/lib/python2.7/dist-packages/mopidy/core/ and in /usr/local/lib/python2.7/dist-packages/mopidy/http.

Please help me to get this awesome feature to work. 

Thanks to all
