### ISSUE TITLE
Support mixcloud

### ISSUE THREAD

**Issue by PanderMusubi** [mopidy/mopidy#957]
Can mixcloud please be supported?

**Comment by kingosticks** [comment]
Doesn't look like it: http://www.mixcloud.com/developers/#audio-streams

**Comment by PanderMusubi** [comment]
That is strange. With an API you can still track who is listening.

**Comment by PanderMusubi** [comment]
There are ways now, see http://kodi.wiki/view/Add-on:MixCloud and https://discuss.mopidy.com/t/integrate-mixcloud-through-soundtomp3/338

**Comment by unusualcomputers** [comment]
I did more or less that https://github.com/unusualcomputers/unusualcomputers/blob/master/code/mopidy/mopidymixcloud/README.rst and it works, have a go
