### ISSUE TITLE
Reduce scope of backends playback

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#960]
This takes over the #766 idea "Remove seek from backend API and use gstreamer only?" - But more importantly 90+ percent of backends I've looked at only implement `change_track` to translate the track to an other uri than the one actually there. We should make this simpler for them and reduce what they actually need to implement.

**Comment by jcass77** [comment]
Is this issue still valid? We've got ```translate_uri``` at the moment, if that is what was being referred to.

Or are there other scope reductions that are being considered as well?

**Comment by jodal** [comment]
Agree, sounds like this might be considered as fixed now. What do you think, @adamcik?

**Comment by adamcik** [comment]
Sounds reasonable, the part I still care about now is #398.
