### ISSUE TITLE
Replace GStreamer for playlist parsing

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#961]
@adamcik will replace this text with details

**Comment by jodal** [comment]
Duplicate of #671.

**Comment by hadess** [comment]
totem-pl-parser? Or did you mean some other type of playlists?

https://developer.gnome.org/totem-pl-parser/stable/TotemPlParser.html

**Comment by adamcik** [comment]
Yes eventually, for the short term this was just about getting rid of the crazy custom elements I added.
