### ISSUE TITLE
A polite request to backend developers from a client developer

### ISSUE THREAD

**Issue by fatg3erman** [mopidy/mopidy#966]
This is something that has been niggling at me for a while as a client developer so I thought I'd raise it for discussion.

It would be very helpful from my point of view if backend extensions used a unique URI scheme for all their playlists, tracks, albums, and artist models.

Currently we have some backends that support a 'backend-name:' URI scheme in some places but then  (1) use an 'http:' URI scheme for tracks added to the current tracklist, or (2) even use 'http:' for all track URIs.

As a client developer this causes me a headache. Although we like to be entirely backend-transparent it's actually nice, from a presenting-things-to-the-user perspective, to know which source the music is coming from. It permits a client to use some sensible default icons, for example. And often we might want to handle streaming radio differently from 'normal' tracks and if backends are using 'http:' for 'normal' tracks it becomes increasingly difficult to do this nicely.

So I thought I'd raise this for discussion and see what people who understand how mopidy works think. I'm assuming it's pretty easy for a backend to use a 'mybackend:' URI scheme but actually pass all playback responsibility to the stream backend?

**Comment by adamcik** [comment]
http://goo.gl/TOzY8L which was just revised earlier this week actually already addresses this issue. We are suggesting adding a `source` field to all models. The idea behind this is giving frontends, and other mopidy components and idea of where a track is from without needing to understand the URIs in use.

So for instance `mopidy-spotify-tunigo` would set source `spotify`, as would `mopidy-spotify`. And say `mopidy-dirble` would either be `dirble`, or perhaps even `webradio`. In the case where a backend doesn't explicitly set this we will default to using the short backend name.

Of course this won't help at all if you are using the MPD frontend, but it should hopefully make this much easier for the HTTP clients.

**Comment by fatg3erman** [comment]
Super! Yeah that addresses my issue exactly. I'd suggest that, from my point of view at least, 'webradio' is probably more useful than 'dirble' - something generic to identify an endless streaming service would be terrific.

True it won't help mpd clients, but certainly as far as I'm concerned if you're using mopidy you ought to be using an HTTP client just because... it's better.

**Comment by kingosticks** [comment]
The `core->get_backends` dict could provide you with a higher level 'webradio' category. But classifying things so coarsely might break down when you get a backend providing both on-demand tracks as well as infinite radio-like streams.  I think if you wanted higher level categories you might prefer it on a per-track basis rather than per-backend. Which sort of ties in with some better way of handling podcasts and streams, as per the TODO in the API document.

**Comment by fatg3erman** [comment]
That's a good point. I haven't checked, for example, the tunein API but some API providers almost insist on clients displaying some kind of branding when their stations are being played. Rompr currently does this (by checking the URI scheme) for tunein, dirble, radio-de, and bassdrive. 

OTOH not having some generic 'webradio' category means that when a new radio-backend is created it won't get handled by the client as a web radio - unless it uses an http: URI scheme. Bassdrive includes a stream and several on-demand items so for that I even have to check the actual format of the URI, which is going to be prone to future breakage,

So perhaps as well as "source", some way of determining whether the thing is actually a stream would be useful. Surely the backend itself would know this and be able to fill in the fields appropriately?

**Comment by adamcik** [comment]
Knowing if things are a stream or not without having to guess based on the audio stream would indeed be extremely useful in core. Things like pause still need special handling for streams / live audio, and there is also the case about about resuming / retrying on network errors for streams, which we of course don't want for local tracks for instance.

**Comment by adamcik** [comment]
Chances are we care about the both the source, i.e. which streaming service, directory service etc and the type. Where type is more radio stream, podcast etc. And we are probably best of not trying have have single thing cover both distinctions.

**Comment by adamcik** [comment]
Closing this as I just created #1108 to track the adding of a source field for this use.
