### ISSUE TITLE
Support for notifying extensions about suspend/resume

### ISSUE THREAD

**Issue by ZenithDK** [mopidy/mopidy#970]
I am working on an extension for my amplifier, and a common use case right now is that I suspend my HTPC with mopidy running, and then manually power off the receiver.
Once the HTPC resumes I have to power on the receiver again as mopidy does not know about the suspend/resume.

Would it be possible for mopidy to be notified about the suspend and resume, and propagate this to the extensions so they may take action?
I would like my extension to power off the receiver when suspending, and power it on when resuming.

**Comment by adamcik** [comment]
Does this really need to be in mopidy? Couldn't you just have a tiny program along the lines of what you created in #1016 which tells the receiver to turn off? Or is the problem that only one program can have the serial open at once at you mopidy extension has already claimed it?

**Comment by ZenithDK** [comment]
Only one process can open the serial at a time, but I am reworking my amplifier extension to handle multiple clients so this should be fairly trivial to integrate into that setup.

This is definitely feature creep :-) But webclients can use this show that the server is shutting down/suspending - but no, not something that needs to be in mopidy.

**Comment by adamcik** [comment]
Ok, considering this out of scope for now and closing.
