### ISSUE TITLE
Adding Folders to Playlist

### ISSUE THREAD

**Issue by s-hell** [mopidy/mopidy#991]
Didn't found an issue for that. So:

It isn't possible to add a whole folder to the playlist. You can only add single files. I tried with ncmpcpp via mpd.

**Comment by trygveaa** [comment]
Do you mean it isn't possible because you don't know how, or because it doesn't work?

How varies from client to client, in ncmpcpp you do it by pressing space when the folder is selected.

If you get an error, what is it?

**Comment by jodal** [comment]
Ping? :-)

**Comment by s-hell** [comment]
Ah , sorry, forgot this issue.
Adding a folder with space works. Using a normal mpd you can add folder in ncmpcpp by pressing a
This doesn't work with mopidy.

**Comment by adamcik** [comment]
Which `ncmpcpp` version is this?

**Comment by jodal** [comment]
Half a year with no response.

**Comment by vincentDcmps** [comment]
HiI have same issue when I used ncmpcpp to add a folder to tracklist with 'a' shortcut when I press 'space' this work I have test on two backend mpd-subidy and file
