### ISSUE TITLE
Gstreamer is missing a plugin .mp3 developing on OSX(10.10)

### ISSUE THREAD

**Issue by beachamc** [mopidy/mopidy#993]
When I run mopidy local scan I get the following error message for all of my .mp3 files.

Your GStreamer installation is missing a plug-in.

The scan works for .m4a files and I've installed gst-plugins-bad010.

I am running OSX Yosemite and am running the program with ```python setup.py develop
``` and then ```mopidy```.

**Comment by kingosticks** [comment]
A Google search gives me this which looks pretty relevant (but I've no idea
what brew is) https://github.com/mopidy/mopidy/issues/787

**Comment by beachamc** [comment]
The only issue with this is that I am not installing mopidy through homebrew and I am not sure how to manually include mad.

**Comment by jodal** [comment]
Yeah, all the `'with-x'` lines in https://github.com/mopidy/homebrew-mopidy/blob/master/mopidy.rb translate to `--with-x` on the command line, if you don't want to use Homebrew to install Mopidy itself.

That said, if trying to get a Mopidy development environment up and running on OS X, I'd still use `brew install mopidy/mopidy/mopidy` first to install Mopidy globally on your system, as that will fix all dependencies, and then create a virtualenv where I install Mopidy from Git contained in the virtualenv and do all actual development.
