### ISSUE TITLE
Add support for contributing on OSX

### ISSUE THREAD

**Issue by beachamc** [mopidy/mopidy#994]
The documentation does not provide clear instruction for contributing on OSX. Specifically, the installing dependencies listed on [this](https://docs.mopidy.com/en/latest/installation/source/) page of GStreamer. I would be more than happy to add documentation for contributing on OSX.

**Comment by adamcik** [comment]
@jodal should this have been closed with #1009, or is there still something to improve here?

**Comment by jodal** [comment]
I think there's a bit to improve on the contribution page, so I'll keep this upon until I've fixed that.
