### ISSUE TITLE
No event triggered when playlists are deleted

### ISSUE THREAD

**Issue by tkem** [mopidy/mopidy#996]
When calling `PlaylistsController.create()` or `PlaylistsController.save()`, a `playst_changed` event is sent, containing the respective playlist. No such event is sent when calling `PlaylistsController.delete()`, which may also be of interest to clients.

I don't think a `playlist_changed` event should be used here, since there is no longer any playlist to pass, and this may break existing clients. `playlists_loaded` is also not an option, since that means something completely different. So maybe a new `playlist_deleted` event might make sense, which just carries the URI of the deleted playlist.

Note that for an 1.0 API, it might also make sense to pass only the playlist URI with `playlist_changed` to avoid sending large models around.

**Comment by dbrgn** [comment]
I'll give this a stab :)
